import type { Question } from "@/types/question";

export const QUESTIONS: Question[] = [
  {
    id: "diag-psat89-rw-1",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The scientist’s explanation of black holes was so _______ that even elementary school students could follow along, asking thoughtful questions throughout the presentation.",
    options: ["confusing", "accessible", "lengthy", "technical"],
    correctAnswer: "B",
    explanation: `'Accessible' means easy to understand — students could follow along and ask questions. ✓`,
    explanations: { "A": "If students followed along, the explanation wasn’t confusing.", "B": `'Accessible' means easy to understand — students could follow along and ask questions. ✓`, "C": "Length isn’t the key quality; clarity is.", "D": `'Technical' would make it harder to follow, not easier.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-2",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "After the flooding damaged dozens of homes, the community came together with remarkable _______, organizing food drives, shelter, and cleanup crews within hours.",
    options: ["hesitation", "confusion", "efficiency", "reluctance"],
    correctAnswer: "C",
    explanation: `Organizing food, shelter, and cleanup 'within hours' shows remarkable efficiency. ✓`,
    explanations: { "A": `'Within hours' shows speed, not hesitation.`, "B": "They organized multiple efforts successfully — not confused.", "C": `Organizing food, shelter, and cleanup 'within hours' shows remarkable efficiency. ✓`, "D": "Coming together willingly shows the opposite of reluctance." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-3",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The two paintings looked nearly identical to casual observers, but an art expert could _______ subtle differences in brushstroke technique and color mixing.",
    options: ["ignore", "create", "detect", "eliminate"],
    correctAnswer: "C",
    explanation: `'Detect' means to discover or notice — the expert can spot what casual observers miss. ✓`,
    explanations: { "A": "An expert wouldn’t ignore differences — they’d notice them.", "B": "The expert isn’t creating the differences; they already exist.", "C": `'Detect' means to discover or notice — the expert can spot what casual observers miss. ✓`, "D": "The expert can’t eliminate differences that are already in the paintings." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-4",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The hiking trail was clearly _______ on the map, with a bold red line showing every turn and rest stop along the 12-mile route.",
    options: ["hidden", "marked", "dangerous", "shortened"],
    correctAnswer: "B",
    explanation: `'Marked' means indicated or shown — the trail is clearly displayed with a bold line. ✓`,
    explanations: { "A": `A 'bold red line' showing every turn is the opposite of hidden.`, "B": `'Marked' means indicated or shown — the trail is clearly displayed with a bold line. ✓`, "C": "The map shows the route; nothing suggests danger.", "D": "Nothing suggests the trail was shortened." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-5",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The new student was _______ at first, rarely speaking in class or joining group activities, but by the end of the semester she had become one of the most active participants.",
    options: ["reserved", "popular", "demanding", "dishonest"],
    correctAnswer: "A",
    explanation: `'Reserved' means quiet and holding back — matches 'rarely speaking' and contrasts with later becoming active. ✓`,
    explanations: { "A": `'Reserved' means quiet and holding back — matches 'rarely speaking' and contrasts with later becoming active. ✓`, "B": `Being popular contradicts 'rarely joining group activities.'`, "C": "Nothing suggests she was demanding.", "D": "Shyness isn’t dishonesty." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-6",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The mayor promised to make the city’s budget more _______, publishing all spending records online so that any resident could review how tax dollars were being used.",
    options: ["complicated", "expensive", "transparent", "restrictive"],
    correctAnswer: "C",
    explanation: `'Transparent' means open and visible — publishing records for public review. ✓`,
    explanations: { "A": "Publishing records for anyone to review makes things clearer, not more complicated.", "B": "Transparency is about openness, not cost.", "C": `'Transparent' means open and visible — publishing records for public review. ✓`, "D": "Making records available is the opposite of restrictive." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-7",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: `What is the main purpose of the last sentence ('A single sea otter... warm')?`,
    passage: "Sea otters spend most of their lives in the ocean, eating, sleeping, and even giving birth in the water. They are one of the few animals that use tools — they place rocks on their stomachs while floating on their backs and use them to crack open shellfish. A single sea otter can eat up to 25% of its body weight in food each day, which is necessary because, unlike most marine mammals, sea otters have no layer of blubber to keep them warm.",
    options: ["To argue that sea otters eat too much food.", "To explain why sea otters need to consume so much food.", "To compare sea otters to all other marine mammals.", "To describe what types of food sea otters prefer."],
    correctAnswer: "B",
    explanation: "The sentence connects high food intake (25% of body weight) to the reason: no blubber for warmth, so they need energy from food. ✓",
    explanations: { "A": "The passage doesn’t judge their eating as excessive.", "B": "The sentence connects high food intake (25% of body weight) to the reason: no blubber for warmth, so they need energy from food. ✓", "C": "It mentions one difference (no blubber), not a full comparison.", "D": "Food types aren’t discussed in that sentence." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-8",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Cross-Text Connections",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How does Mr. Davis’s approach (Text 2) differ from Ms. Torres’s (Text 1)?",
    passage: "<strong>Text 1</strong><br>School librarian Ms. Torres believes that students learn best when they choose their own reading material. She allows students to select any book that interests them, arguing that the freedom to choose builds a lifelong love of reading.<br><br><strong>Text 2</strong><br>English teacher Mr. Davis values student choice but believes some structure is necessary. He provides a curated list of 20 age-appropriate books and lets students pick from the list. This way, he says, students still have choice but are guided toward books that will challenge and develop their reading skills.",
    options: ["Mr. Davis opposes student choice entirely.", "Mr. Davis limits choice to a curated selection to ensure appropriate challenge.", "Mr. Davis believes reading is not important for students.", "Mr. Davis allows students to read anything, including comic books."],
    correctAnswer: "B",
    explanation: "Torres: any book. Davis: choice from 20 curated books. He limits choice but doesn’t eliminate it. ✓",
    explanations: { "A": `He 'values student choice' — doesn’t oppose it.`, "B": "Torres: any book. Davis: choice from 20 curated books. He limits choice but doesn’t eliminate it. ✓", "C": "He clearly cares about reading skills.", "D": `He limits choice to a list, not 'anything.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-9",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the main idea of the text?",
    passage: "Fireflies produce light through a chemical reaction in their abdomens. The enzyme luciferase combines with a molecule called luciferin in the presence of oxygen, producing a glow with almost no heat. This ‘cold light’ is remarkably efficient — nearly 100% of the energy is emitted as light, compared to about 10% for a traditional incandescent light bulb.",
    options: ["Fireflies are more useful than light bulbs.", "Fireflies produce light through an extremely efficient chemical process.", "The enzyme luciferase was discovered recently.", "Fireflies live in warm climates."],
    correctAnswer: "B",
    explanation: "The passage explains the chemical process and highlights its efficiency (nearly 100% vs. 10%). ✓",
    explanations: { "A": "No usefulness comparison is made.", "B": "The passage explains the chemical process and highlights its efficiency (nearly 100% vs. 10%). ✓", "C": "No discovery timeline is mentioned.", "D": "Habitat isn’t discussed." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-10",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "According to the text, what made Petra’s survival in the desert possible?",
    passage: "The ancient city of Petra, carved directly into red sandstone cliffs in modern-day Jordan, was the capital of the Nabataean kingdom around 300 BCE. Despite being located in a desert, the Nabataeans engineered an elaborate system of dams, cisterns, and water channels that could collect and store enough rainwater to support a population of 20,000 people.",
    options: ["Its location near a major river.", "Trade relationships with neighboring countries.", "An engineered water collection and storage system.", "A climate that was cooler than surrounding areas."],
    correctAnswer: "C",
    explanation: `'Dams, cisterns, and water channels' that collected and stored rainwater supported 20,000 people. ✓`,
    explanations: { "A": "No river is mentioned — it’s in a desert.", "B": "Trade isn’t discussed.", "C": `'Dams, cisterns, and water channels' that collected and stored rainwater supported 20,000 people. ✓`, "D": "Climate differences aren’t mentioned." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-11",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The text mainly emphasizes which point about crows?",
    passage: "Scientists studying crows have discovered that the birds can recognize individual human faces and remember whether a specific person has been friendly or threatening. In experiments, crows scolded researchers who had previously captured them, even years later, while ignoring researchers who had only fed them. Even more remarkably, crows that had never personally encountered the ‘threatening’ researcher also learned to scold that person, suggesting the information was communicated between birds.",
    options: ["Crows are the most intelligent birds in the world.", "Crows can recognize faces, remember experiences, and share threat information with other crows.", "Scientists should not capture crows for research.", "Crows prefer to eat food provided by humans."],
    correctAnswer: "B",
    explanation: "Face recognition + long-term memory + social communication of threats — all three are described. ✓",
    explanations: { "A": `'Most intelligent' is never claimed.`, "B": "Face recognition + long-term memory + social communication of threats — all three are described. ✓", "C": "No ethical argument about research is made.", "D": "Food preference isn’t the point." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-12",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which additional finding would most directly support Dr. Chen’s claim about the economic importance of reefs?",
    passage: "Marine biologist Dr. Lisa Chen claims that coral reefs are essential to coastal communities not just for ecological reasons but for economic ones as well. She points to research showing that healthy reefs protect shorelines from storm damage, reducing wave energy by up to 97%.",
    options: ["Coral reefs are home to thousands of species of fish.", "A study found that communities near healthy reefs spend 80% less on coastal storm repairs than communities without reef protection.", "Ocean temperatures have risen by 1.5 degrees over the past century.", "Some coral species can live for hundreds of years."],
    correctAnswer: "B",
    explanation: "Spending 80% less on repairs directly ties reef health to economic savings. ✓",
    explanations: { "A": "Species diversity is ecological, not economic.", "B": "Spending 80% less on repairs directly ties reef health to economic savings. ✓", "C": "Temperature change doesn’t address economic value.", "D": "Coral lifespan isn’t about economics." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-13",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the type of evidence Wright uses?",
    passage: "Historian James Wright argues that the construction of the transcontinental railroad in the 1860s did more to unify the United States than any political event of that era. He notes that before the railroad, a journey from New York to California took six months by wagon. After its completion in 1869, the same trip took just seven days.",
    options: ["A personal anecdote about riding the railroad.", "A comparison of travel times before and after the railroad to show its impact.", "A survey of Americans’ opinions about the railroad.", "A list of all the cities connected by the railroad."],
    correctAnswer: "B",
    explanation: "Six months vs. seven days — a before/after comparison demonstrates the transformative effect. ✓",
    explanations: { "A": "No personal story is told.", "B": "Six months vs. seven days — a before/after comparison demonstrates the transformative effect. ✓", "C": "No survey or opinions are cited.", "D": "No list of cities." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-14",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to support the claim that art clubs have become increasingly popular?",
    passage: "A school tracked student participation in after-school clubs over four years.",
    options: ["In 2023, sports clubs had 210 members.", "Art club membership grew from 45 to 120 students between 2020 and 2023, the largest increase of any club category.", "Science clubs had fewer members than sports clubs in every year.", "Total club participation increased from 300 to 450 over the period."],
    correctAnswer: "B",
    explanation: "Art clubs tripled (45 to 120), the largest growth, directly supporting the claim. ✓",
    explanations: { "A": "Sports data doesn’t address art club popularity.", "B": "Art clubs tripled (45 to 120), the largest growth, directly supporting the claim. ✓", "C": "Science vs. sports doesn’t address art.", "D": "Total participation doesn’t isolate art clubs." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-15",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to identify a seasonal pattern?",
    passage: "A local farm tracked monthly egg production from its flock of 50 chickens.",
    options: ["The farm produced 1,200 eggs in March.", "January had the lowest production at 800 eggs.", "Production peaked in spring and summer months (March–August) and declined in fall and winter, suggesting a seasonal pattern linked to daylight hours.", "The farm has 50 chickens."],
    correctAnswer: "C",
    explanation: "Connecting higher production in spring/summer to lower production in fall/winter identifies a seasonal cycle. ✓",
    explanations: { "A": "A single data point isn’t a pattern.", "B": "One low point doesn’t establish a pattern.", "C": "Connecting higher production in spring/summer to lower production in fall/winter identifies a seasonal cycle. ✓", "D": "Flock size doesn’t describe a pattern." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-16",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "For decades, scientists believed that taste buds on the tongue were organized into distinct zones — sweet at the tip, sour on the sides, bitter at the back. This ‘tongue map’ appeared in textbooks worldwide. However, careful experiments have shown that all areas of the tongue can detect all five basic tastes (sweet, sour, salty, bitter, and umami), though sensitivity varies slightly by region. ________",
    options: ["Therefore, the tongue map is an accurate and useful tool for teaching about taste.", "The persistence of the tongue map in textbooks illustrates how widely repeated misinformation can become accepted as fact.", "Scientists should stop studying how taste works.", "This means that humans cannot actually distinguish between different flavors."],
    correctAnswer: "B",
    explanation: "A debunked idea persisting in textbooks = misinformation becoming accepted through repetition. ✓",
    explanations: { "A": "The experiments disproved the tongue map; it’s not accurate.", "B": "A debunked idea persisting in textbooks = misinformation becoming accepted through repetition. ✓", "C": "Nothing suggests stopping research.", "D": "Disproving the map doesn’t mean people can’t taste flavors." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-17",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Bats are often feared as carriers of disease, and many people consider them pests. _______, bats play a vital role in ecosystems by pollinating plants, dispersing seeds, and consuming enormous quantities of insects.",
    options: ["Similarly", "In reality", "As a result", "For instance"],
    correctAnswer: "B",
    explanation: `'In reality' contrasts the negative perception with the positive truth. ✓`,
    explanations: { "A": "The second sentence contrasts the fear, not supports it.", "B": `'In reality' contrasts the negative perception with the positive truth. ✓`, "C": "Their ecological role isn’t a result of being feared.", "D": "The ecological role isn’t an example of being feared." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-18",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The school’s new recycling program reduced paper waste by 40% in its first year. _______, the cafeteria switched to compostable trays, cutting plastic waste by an additional 25%.",
    options: ["However", "In addition", "Instead", "Nevertheless"],
    correctAnswer: "B",
    explanation: "Both are positive environmental steps — one adds to the other. ✓",
    explanations: { "A": "The cafeteria change doesn’t contradict the recycling success.", "B": "Both are positive environmental steps — one adds to the other. ✓", "C": `'Instead' means replacement, but both programs exist.`, "D": `'Nevertheless' implies contrast, but both are successes.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-19",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Elephants are known for their exceptional memories, which help them remember water sources during droughts and recognize family members after years apart. _______, this strong memory means elephants can also hold grudges, avoiding humans or places where they experienced harm.",
    options: ["On the other hand", "For this reason", "In contrast", "However"],
    correctAnswer: "D",
    explanation: "Shifts from positive aspects of memory to a more complex consequence. ✓",
    explanations: { "A": `'On the other hand' is too neutral; 'however' better signals the shift from positive to potentially negative.`, "B": `Holding grudges isn’t a 'reason' for good memory; it’s a consequence with a different tone.`, "C": "Not truly contrasting two different subjects.", "D": "Shifts from positive aspects of memory to a more complex consequence. ✓" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-20",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about recycling for a school newspaper and wants to encourage classmates to participate.",
    options: ["Recycling was first practiced in ancient civilizations thousands of years ago.", "The school currently recycles less than 30% of its waste, but studies show that schools with active student participation reach 70% or higher — meaning our small daily choices could more than double our recycling rate.", "Aluminum cans are the most commonly recycled item in the United States.", "The recycling bin is located next to the cafeteria."],
    correctAnswer: "B",
    explanation: "Shows the gap (30%) and the achievable goal (70%) with student participation — motivating and specific. ✓",
    explanations: { "A": "Historical trivia doesn’t encourage current participation.", "B": "Shows the gap (30%) and the achievable goal (70%) with student participation — motivating and specific. ✓", "C": "National facts about aluminum don’t encourage classmates directly.", "D": "Location info is practical but not motivating." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-21",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about guide dogs and wants to emphasize the extensive training they undergo.",
    options: ["Guide dogs are usually Labrador Retrievers or German Shepherds.", "Guide dog programs exist in over 30 countries worldwide.", "Guide dogs undergo nearly two years of specialized training, beginning with basic obedience as puppies and advancing to complex skills like navigating traffic, avoiding overhead obstacles, and making independent safety decisions.", "People with visual impairments may also use white canes for navigation."],
    correctAnswer: "C",
    explanation: "Two years, progression from basic to complex skills, specific examples — emphasizes extensive training. ✓",
    explanations: { "A": "Breed information, not training.", "B": "Global reach, not training details.", "C": "Two years, progression from basic to complex skills, specific examples — emphasizes extensive training. ✓", "D": "Alternative navigation tools, not about guide dog training." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-22",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the benefits of school gardens and wants to highlight academic connections.",
    options: ["School gardens have become more popular in the past decade.", "Gardening can be a relaxing hobby for people of all ages.", "Students who participate in school garden programs show improved performance in science by applying concepts like photosynthesis and ecosystems hands-on, and in math through measuring plot areas and tracking plant growth data.", "Some schools grow tomatoes, peppers, and herbs in their gardens."],
    correctAnswer: "C",
    explanation: "Connects gardening to specific academic subjects (science, math) with concrete examples. ✓",
    explanations: { "A": "Popularity trend, not academic benefit.", "B": "General hobby benefit, not academic.", "C": "Connects gardening to specific academic subjects (science, math) with concrete examples. ✓", "D": "Crop types don’t demonstrate academic connections." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-23",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The science fair projects were impressive this _______ several students built working robots, and one group even launched a small weather balloon.",
    options: ["year", "year;", "year,", "year—"],
    correctAnswer: "B",
    explanation: "Semicolon correctly joins two related independent clauses. ✓",
    explanations: { "A": "No punctuation creates a run-on sentence.", "B": "Semicolon correctly joins two related independent clauses. ✓", "C": "Comma splice — two independent clauses can’t be joined by just a comma.", "D": "A dash could work informally but semicolon is standard here." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-24",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Although the weather forecast predicted _______ the outdoor concert went ahead as planned and drew a record crowd.",
    options: ["rain", "rain;", "rain,", "rain."],
    correctAnswer: "C",
    explanation: `Comma correctly follows the introductory 'Although' clause. ✓`,
    explanations: { "A": "No punctuation between a subordinate clause and main clause.", "B": "Semicolon can’t separate a dependent from an independent clause.", "C": `Comma correctly follows the introductory 'Although' clause. ✓`, "D": `Period creates a fragment ('Although the weather...' can’t stand alone).` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-25",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The museum’s newest exhibit features artifacts from ancient _______ including pottery, tools, and jewelry dating back over 3,000 years.",
    options: ["Egypt;", "Egypt", "Egypt,", "Egypt."],
    correctAnswer: "C",
    explanation: `Comma before the participial phrase 'including pottery...' is standard. ✓`,
    explanations: { "A": `Semicolon is too strong — 'including...' is a phrase, not an independent clause.`, "B": "No punctuation before the participial phrase makes the sentence hard to read.", "C": `Comma before the participial phrase 'including pottery...' is standard. ✓`, "D": "Period creates a fragment." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-26",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The team of researchers _______ working late every night to finish the experiment before the deadline.",
    options: ["were", "was", "are", "have"],
    correctAnswer: "B",
    explanation: `'Team' is singular; 'was' agrees. Past tense matches 'working late.' ✓`,
    explanations: { "A": `'Team' is a collective noun treated as singular.`, "B": `'Team' is singular; 'was' agrees. Past tense matches 'working late.' ✓`, "C": `'Are' is present tense but context ('before the deadline') implies past.`, "D": `'Have' doesn’t pair with 'working' in this structure.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-27",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Neither the principal nor the teachers _______ aware of the schedule change until Monday morning.",
    options: ["was", "is", "were", "has been"],
    correctAnswer: "C",
    explanation: `'Teachers' (nearest subject) is plural, so 'were' agrees. Past tense fits 'until Monday morning.' ✓`,
    explanations: { "A": `With 'neither...nor,' verb agrees with the nearer subject: 'teachers' is plural.`, "B": `'Is' is singular present — wrong number and tense.`, "C": `'Teachers' (nearest subject) is plural, so 'were' agrees. Past tense fits 'until Monday morning.' ✓`, "D": `'Has been' is singular.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-28",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The old bridge had been _______ over the years by harsh weather and heavy traffic, and engineers warned that it could no longer safely support large vehicles.",
    options: ["improved", "constructed", "weakened", "decorated"],
    correctAnswer: "C",
    explanation: `Harsh weather and heavy traffic damage structures over time; 'weakened' fits the safety warning. ✓`,
    explanations: { "A": "If improved, it would still be safe.", "B": `'Constructed' doesn’t fit — bridges are constructed once, not repeatedly by weather.`, "C": `Harsh weather and heavy traffic damage structures over time; 'weakened' fits the safety warning. ✓`, "D": "Weather doesn’t decorate a bridge." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-29",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The teacher praised the student’s essay for its _______ argument, noting that each paragraph built logically on the one before it and led naturally to a strong conclusion.",
    options: ["disorganized", "brief", "coherent", "repetitive"],
    correctAnswer: "C",
    explanation: `'Coherent' means logically connected and consistent — paragraphs building logically on each other. ✓`,
    explanations: { "A": `'Logically built' and 'led naturally' describe the opposite of disorganized.`, "B": "The praise is about structure, not length.", "C": `'Coherent' means logically connected and consistent — paragraphs building logically on each other. ✓`, "D": "Building logically isn’t the same as repeating." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-30",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "When the star basketball player was injured during the championship game, the team’s chances of winning seemed to _______ significantly, and the mood in the arena shifted from excitement to concern.",
    options: ["improve", "diminish", "stabilize", "multiply"],
    correctAnswer: "B",
    explanation: `'Diminish' means to decrease — losing a key player reduces winning chances. ✓`,
    explanations: { "A": "Losing a star player wouldn’t improve chances.", "B": `'Diminish' means to decrease — losing a key player reduces winning chances. ✓`, "C": `'Stabilize' means to remain steady, but the mood shifted.`, "D": "Chances wouldn’t multiply after losing a player." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-31",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Rather than addressing the criticism directly, the politician chose to _______ the question by talking about an unrelated topic, hoping the audience would forget what had been asked.",
    options: ["answer", "deflect", "repeat", "simplify"],
    correctAnswer: "B",
    explanation: `'Deflect' means to redirect away from — talking about something unrelated to avoid the question. ✓`,
    explanations: { "A": `'Addressing directly' is what was NOT done.`, "B": `'Deflect' means to redirect away from — talking about something unrelated to avoid the question. ✓`, "C": "The question wasn’t repeated; it was avoided.", "D": "The question wasn’t simplified; it was dodged." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-32",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The documentary provided a _______ look at life in the deep ocean, showing creatures and environments that most people have never seen or even imagined.",
    options: ["rare", "boring", "brief", "common"],
    correctAnswer: "A",
    explanation: `'Creatures most people have never seen' makes this a rare glimpse into an unseen world. ✓`,
    explanations: { "A": `'Creatures most people have never seen' makes this a rare glimpse into an unseen world. ✓`, "B": "Showing never-before-seen creatures would likely be fascinating, not boring.", "C": "Nothing suggests the documentary was brief.", "D": `'Common' contradicts 'never seen or imagined.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-33",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the structure of the text?",
    passage: "Many people think of deserts as lifeless wastelands, but the Sonoran Desert in the American Southwest is actually home to over 2,000 plant species, 350 bird species, and 60 species of mammals. Far from being empty, it supports one of the most diverse ecosystems of any desert on Earth.",
    options: ["It presents a common misconception and then corrects it with evidence.", "It compares two different deserts.", "It argues that deserts should be protected by law.", "It lists the dangers of living in a desert environment."],
    correctAnswer: "A",
    explanation: "Misconception (deserts = lifeless) then correction (2,000+ plants, 350 birds, 60 mammals). ✓",
    explanations: { "A": "Misconception (deserts = lifeless) then correction (2,000+ plants, 350 birds, 60 mammals). ✓", "B": "Only the Sonoran Desert is discussed.", "C": "No legal argument is made.", "D": "No dangers are mentioned." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-34",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which additional finding would most directly support Dr. Park’s argument?",
    passage: "Veterinarian Dr. Amy Park argues that regular exercise is just as important for pets as it is for humans. She notes that dogs who receive at least 30 minutes of daily exercise have significantly fewer behavioral problems, including less destructive chewing and less excessive barking.",
    options: ["Dogs are the most popular pet in the United States.", "A study found that regularly exercised dogs had 40% fewer visits to the vet for stress-related conditions compared to sedentary dogs.", "Some dog breeds require more grooming than others.", "Dog food sales have increased over the past decade."],
    correctAnswer: "B",
    explanation: "Fewer vet visits due to exercise directly supports the health importance argument. ✓",
    explanations: { "A": "Popularity doesn’t support exercise benefits.", "B": "Fewer vet visits due to exercise directly supports the health importance argument. ✓", "C": "Grooming is unrelated to exercise.", "D": "Food sales don’t address exercise." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-35",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly weaken Johnson’s argument?",
    passage: "Chef Marcus Johnson believes that cooking should be taught in every middle school, arguing that it develops life skills, encourages healthier eating, and builds confidence. He started a program in three local schools where students prepare one meal per week using fresh ingredients.",
    options: ["A survey found that students in the program enjoyed cooking more than before.", "A study of similar programs found no measurable improvement in students’ eating habits, confidence levels, or practical life skills after two years of participation.", "Some schools lack the budget for cooking equipment.", "Johnson’s restaurants have received positive reviews."],
    correctAnswer: "B",
    explanation: "No improvement in the three claimed benefits directly contradicts his argument. ✓",
    explanations: { "A": "Enjoying cooking supports, not weakens, his argument.", "B": "No improvement in the three claimed benefits directly contradicts his argument. ✓", "C": "Budget challenges are practical barriers but don’t disprove the benefits.", "D": "Restaurant reviews are irrelevant to school cooking programs." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-36",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to describe a significant shift in commuting behavior?",
    passage: "A city tracked how residents commute to work over a five-year period.",
    options: ["In 2018, 65% of residents drove alone to work.", "Public transit use remained stable at around 15% throughout the period.", "The percentage of residents working from home tripled from 5% to 15% between 2018 and 2023, while driving alone dropped from 65% to 50%, suggesting remote work has significantly changed commuting patterns.", "Biking to work remained at 5% in both years."],
    correctAnswer: "C",
    explanation: "Identifies two major changes (remote work tripling, driving declining) and connects them to a broader pattern. ✓",
    explanations: { "A": "Single data point, not a shift.", "B": "Stability isn’t a shift.", "C": "Identifies two major changes (remote work tripling, driving declining) and connects them to a broader pattern. ✓", "D": "No change means no shift." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-37",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "The passenger pigeon was once the most abundant bird in North America, with flocks so large they darkened the sky for hours as they passed overhead. By 1914, the species was completely extinct. Unregulated hunting and habitat destruction had eliminated billions of birds in less than a century. ________",
    options: ["Passenger pigeons were related to modern-day rock doves.", "The rapid extinction of such an abundant species demonstrated that even seemingly inexhaustible populations can be destroyed without conservation protections.", "Scientists have successfully brought back other extinct species through cloning.", "Bird watching has become an increasingly popular hobby."],
    correctAnswer: "B",
    explanation: `From 'most abundant' to extinct in <100 years — proves no population is safe without protections. ✓`,
    explanations: { "A": "Taxonomy doesn’t follow from the extinction narrative.", "B": `From 'most abundant' to extinct in <100 years — proves no population is safe without protections. ✓`, "C": "Cloning isn’t discussed in the passage.", "D": "Bird watching is unrelated." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-38",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "In a study of classroom learning, researchers found that students who took handwritten notes scored significantly higher on conceptual questions than students who typed notes on laptops. The researchers suggested that because handwriting is slower, it forces students to process and summarize information rather than transcribing lectures word for word. ________",
    options: ["This suggests that the physical act of handwriting, by requiring more cognitive effort, may lead to deeper understanding of material.", "Therefore, all schools should immediately ban laptops from classrooms.", "The study proves that technology has no place in education.", "Students who type notes are less intelligent than those who write by hand."],
    correctAnswer: "A",
    explanation: "Connects slower handwriting to deeper processing to better understanding — a logical conclusion. ✓",
    explanations: { "A": "Connects slower handwriting to deeper processing to better understanding — a logical conclusion. ✓", "B": `'Immediately ban' is too extreme for one study.`, "C": "One study about note-taking doesn’t prove technology has no place.", "D": "The study is about the method, not intelligence." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-39",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The first attempt to climb the mountain ended in failure when a sudden blizzard forced the team to turn back at 22,000 feet. _______, the team regrouped, resupplied, and made a successful summit attempt three weeks later.",
    options: ["Similarly", "As a result", "Undeterred", "Meanwhile"],
    correctAnswer: "C",
    explanation: `'Undeterred' means not discouraged — they tried again despite failure. ✓`,
    explanations: { "A": "The second attempt isn’t similar to the failure.", "B": "Success wasn’t a direct result of the failure.", "C": `'Undeterred' means not discouraged — they tried again despite failure. ✓`, "D": `'Meanwhile' implies simultaneous events, but these are sequential.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-40",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Honeybees are responsible for pollinating approximately one-third of the food crops consumed in the United States. _______, the decline in bee populations due to pesticide use and habitat loss has raised serious concerns among agricultural scientists.",
    options: ["In other words", "Consequently", "On the other hand", "For example"],
    correctAnswer: "B",
    explanation: "Because bees are so important, their decline has consequences — cause and effect. ✓",
    explanations: { "A": "The concern is a consequence, not a restatement.", "B": "Because bees are so important, their decline has consequences — cause and effect. ✓", "C": "No contrast between the two ideas.", "D": "The decline isn’t an example of pollination." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-41",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The new park was designed to be accessible to visitors of all abilities, with paved walking paths, wheelchair ramps, and sensory gardens. _______, the playground equipment was chosen specifically to accommodate children with physical disabilities.",
    options: ["However", "In contrast", "Likewise", "Nevertheless"],
    correctAnswer: "C",
    explanation: `'Likewise' shows the playground shares the same accessibility goal as the paths and ramps. ✓`,
    explanations: { "A": "The playground supports the same goal, not contradicts it.", "B": "No contrast between accessibility features.", "C": `'Likewise' shows the playground shares the same accessibility goal as the paths and ramps. ✓`, "D": `'Nevertheless' implies something surprising, but this is consistent.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-42",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about sleep and academic performance and wants to present a persuasive argument for later school start times.",
    options: ["The average teenager needs 8–10 hours of sleep per night.", "Some schools start as early as 7:00 AM.", "Schools that shifted start times from 7:30 to 8:30 AM saw attendance improve by 12% and average GPAs rise by 0.2 points, suggesting that even one extra hour of sleep can measurably improve academic outcomes.", "Many teenagers stay up late using their phones."],
    correctAnswer: "C",
    explanation: "Specific evidence (12% attendance, 0.2 GPA) from schools that made the change = persuasive. ✓",
    explanations: { "A": "General sleep need isn’t a persuasive argument for later starts.", "B": "Current start time alone doesn’t argue for change.", "C": "Specific evidence (12% attendance, 0.2 GPA) from schools that made the change = persuasive. ✓", "D": "Device use is a separate issue from school policy." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-43",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the Great Pacific Garbage Patch and wants to convey its scale to readers.",
    options: ["Plastic pollution is a global environmental problem.", "The Great Pacific Garbage Patch covers an estimated 1.6 million square kilometers — an area roughly twice the size of Texas — and contains approximately 80,000 tons of plastic debris, making it the largest accumulation of ocean plastic in the world.", "Ocean currents move in circular patterns called gyres.", "Volunteers participate in beach cleanups every year."],
    correctAnswer: "B",
    explanation: "Area (1.6M km²), comparison (twice Texas), weight (80,000 tons), and superlative (largest) all convey scale. ✓",
    explanations: { "A": "Too general; doesn’t convey specific scale.", "B": "Area (1.6M km²), comparison (twice Texas), weight (80,000 tons), and superlative (largest) all convey scale. ✓", "C": "How gyres work doesn’t convey the patch’s size.", "D": "Cleanups are response, not scale." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-44",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the importance of public libraries and wants to emphasize their role beyond lending books.",
    options: ["The first public library in the United States was established in 1833.", "Modern public libraries serve as community hubs offering free internet access, job training workshops, language classes, and safe after-school spaces for children — services that particularly benefit low-income residents who may lack these resources elsewhere.", "Libraries contain both fiction and nonfiction books.", "Many libraries use the Dewey Decimal System to organize materials."],
    correctAnswer: "B",
    explanation: "Internet, job training, language classes, after-school spaces — all services beyond lending books, with equity angle. ✓",
    explanations: { "A": "History, not current role beyond books.", "B": "Internet, job training, language classes, after-school spaces — all services beyond lending books, with equity angle. ✓", "C": "Describing book types is about lending books.", "D": "Organization systems are about books, not beyond-book services." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-45",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The school’s drama club performed three shows over the _______ each one drew a larger audience than the last.",
    options: ["weekend,", "weekend;", "weekend", "weekend and"],
    correctAnswer: "B",
    explanation: "Semicolon correctly joins two related independent clauses. ✓",
    explanations: { "A": "Comma splice — two independent clauses need more than a comma.", "B": "Semicolon correctly joins two related independent clauses. ✓", "C": "No punctuation creates a run-on.", "D": `'And' works but needs a comma before it: 'weekend, and each one...'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-46",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The park’s most popular trail, which runs along the _______ is closed for maintenance until April.",
    options: ["river,", "river;", "river", "river."],
    correctAnswer: "A",
    explanation: `Comma closes the nonrestrictive clause 'which runs along the river' before the main clause continues. ✓`,
    explanations: { "A": `Comma closes the nonrestrictive clause 'which runs along the river' before the main clause continues. ✓`, "B": "Semicolon can’t close a nonrestrictive clause.", "C": "No punctuation between the clause and main verb.", "D": "Period creates a fragment." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-47",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Before the invention of the printing _______ books had to be copied entirely by hand, a process that could take months for a single volume.",
    options: ["press", "press;", "press,", "press."],
    correctAnswer: "C",
    explanation: `Comma correctly separates the introductory 'Before...' clause from the main clause. ✓`,
    explanations: { "A": "No punctuation after an introductory adverbial clause.", "B": "Semicolon can’t follow a subordinate clause.", "C": `Comma correctly separates the introductory 'Before...' clause from the main clause. ✓`, "D": "Period creates a fragment." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-48",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Every student in the class _______ required to complete a science project before the end of the semester.",
    options: ["are", "is", "were", "have been"],
    correctAnswer: "B",
    explanation: `'Every student' is always singular — 'is' agrees. ✓`,
    explanations: { "A": `'Every' is singular; 'are' is plural.`, "B": `'Every student' is always singular — 'is' agrees. ✓`, "C": `'Were' is plural past tense.`, "D": `'Have been' is plural.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-49",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The dogs at the shelter, including a golden retriever and two beagles, _______ already been vaccinated before being made available for adoption.",
    options: ["has", "have", "is", "was"],
    correctAnswer: "B",
    explanation: `'Dogs' is plural; 'have' agrees. The parenthetical 'including...' doesn’t change the subject. ✓`,
    explanations: { "A": `Subject is 'dogs' (plural), not 'retriever.'`, "B": `'Dogs' is plural; 'have' agrees. The parenthetical 'including...' doesn’t change the subject. ✓`, "C": `'Is' is singular present.`, "D": `'Was' is singular past.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-50",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "By the time the guests _______, the host had already set the table and prepared all the food.",
    options: ["arrive", "will arrive", "arrived", "had arrived"],
    correctAnswer: "C",
    explanation: `Simple past 'arrived' works with 'had already set' (past perfect) — the setting happened before the arrival. ✓`,
    explanations: { "A": `Present tense doesn’t match past context ('had set').`, "B": "Future tense contradicts past context.", "C": `Simple past 'arrived' works with 'had already set' (past perfect) — the setting happened before the arrival. ✓`, "D": "Both actions can’t be past perfect; one must be simple past." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-51",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The artist _______ paintings hang in the National Gallery won the prestigious award for the third time.",
    options: ["who’s", "whose", "whom", "which"],
    correctAnswer: "B",
    explanation: `'Whose' shows possession: the artist’s paintings. ✓`,
    explanations: { "A": `'Who’s' = 'who is' — doesn’t fit.`, "B": `'Whose' shows possession: the artist’s paintings. ✓`, "C": `'Whom' is an object pronoun, not possessive.`, "D": `'Which' doesn’t show possession.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-52",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The choir practiced every day after school, and _______ hard work paid off when they won first place at the state competition.",
    options: ["they’re", "there", "their", "its"],
    correctAnswer: "C",
    explanation: `'Their' is the possessive pronoun for the choir members. ✓`,
    explanations: { "A": `'They’re' = 'they are' — doesn’t fit before 'hard work.'`, "B": `'There' is a location word, not possessive.`, "C": `'Their' is the possessive pronoun for the choir members. ✓`, "D": `'Its' could work if referring to the choir as a unit, but 'their' is more natural with the plural ‘they’ implied.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-53",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The package that _______ ordered last week finally arrived this morning, three days later than expected.",
    options: ["I had", "I have", "me", "myself had"],
    correctAnswer: "A",
    explanation: `'Had ordered' is past perfect, correctly showing the order preceded the arrival. ✓`,
    explanations: { "A": `'Had ordered' is past perfect, correctly showing the order preceded the arrival. ✓`, "B": `'Have ordered' is present perfect, but the arrival was this morning (past).`, "C": `'Me' can’t be a subject.`, "D": `'Myself' is reflexive and can’t serve as the subject here.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-rw-54",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Running along the forest trail early in the _______ the jogger spotted a family of deer near the stream.",
    options: ["morning", "morning;", "morning,", "morning."],
    correctAnswer: "C",
    explanation: "Comma correctly separates the introductory participial phrase from the main clause. ✓",
    explanations: { "A": "No punctuation after the participial phrase creates a run-on.", "B": "Semicolon can’t separate a participial phrase from its main clause.", "C": "Comma correctly separates the introductory participial phrase from the main clause. ✓", "D": "Period creates a fragment." },
    tags: ["diagnostic"],
  }
];
