// Colon usage — 60 questions (20 per test type)

const FORMAT = "Which choice completes the text so that it conforms to the conventions of Standard English?";

const sat = [
  {
    stem: `${FORMAT}\n\nThe committee narrowed its decision to two finalists ______ Dr. Okafor and Dr. Santos.`,
    options: ["finalists:", "finalists,", "finalists;", "finalists, namely,"],
    correct: 0,
    explanation: "The left side is a complete sentence ('The committee narrowed its decision to two finalists'); the right side introduces the list. Use a colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe three ingredients in a classic vinaigrette ______ oil, vinegar, and salt.`,
    options: ["are", "are:", "are —", "are;"],
    correct: 0,
    explanation: "'The three ingredients in a classic vinaigrette are' is NOT a complete sentence — it's a fragment waiting for its complement. No colon can be used after a fragment.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nHer favorite subjects have always been the same ______ history, art, and literature.`,
    options: ["same:", "same,", "same;", "same, which are"],
    correct: 0,
    explanation: "'Her favorite subjects have always been the same' is a complete sentence; the colon introduces the list.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe contract named three witnesses ______ the notary, the attorney, and the bookkeeper.`,
    options: ["witnesses:", "witnesses,", "witnesses;", "witnesses, including"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe proposal received three ______ Dr. Hayashi, Ms. Patel, and Mr. Kim.`,
    options: ["endorsements:", "endorsements,", "endorsements;", "endorsements are from"],
    correct: 0,
    explanation: "Complete sentence + list = colon. Be careful with 'received three' — 'The proposal received three endorsements' is a full sentence.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe senator spoke about ______ education, health care, and infrastructure.`,
    options: ["several issues:", "several issues,", "several issues;", "several issues that include,"],
    correct: 0,
    explanation: "'The senator spoke about several issues' is a complete sentence; the colon introduces the list.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe new employees ______ Elena, Marcus, and Priya.`,
    options: ["are", "are:", "are —", "are;"],
    correct: 0,
    explanation: "'The new employees are' is NOT a complete sentence. No colon after a fragment.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe reviewer gave the film the highest possible praise ______ she called it the best picture of the decade.`,
    options: ["praise:", "praise,", "praise;", "praise, and she"],
    correct: 0,
    explanation: "Complete sentence on the left introducing an explanation on the right — colon is correct.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nEvery good debate requires three things ______ evidence, clear reasoning, and a willingness to listen.`,
    options: ["things:", "things,", "things;", "things, and"],
    correct: 0,
    explanation: "Complete sentence + introduced list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe bakery specializes in ______ croissants, tarts, and macarons.`,
    options: ["French pastries:", "French pastries,", "French pastries;", "French pastries like"],
    correct: 0,
    explanation: "'The bakery specializes in French pastries' is a complete sentence; colon introduces the list.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe scientists have three main tools ______ a microscope, a spectrometer, and a centrifuge.`,
    options: ["tools:", "tools,", "tools;", "tools which are"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe job requires a candidate with ______ strong writing skills, attention to detail, and the ability to meet deadlines.`,
    options: ["three qualities:", "three qualities,", "three qualities;", "three qualities, including,"],
    correct: 0,
    explanation: "'The job requires a candidate with three qualities' is a full sentence; colon introduces the list.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe museum's most famous pieces include ______ a Rembrandt, a Vermeer, and a Monet.`,
    options: ["the following:", "the following,", "the following;", "the following, such as"],
    correct: 0,
    explanation: "'The museum's most famous pieces include the following' is a complete sentence; colon introduces the list.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe research focused on ______ Albania, Romania, and Bulgaria.`,
    options: ["three countries:", "three countries,", "three countries;", "three countries of: "],
    correct: 0,
    explanation: "'The research focused on three countries' is a complete sentence; colon introduces the list.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nHer verdict on the performance was ______ the acting was superb, but the script was weak.`,
    options: ["clear:", "clear,", "clear;", "clear, and"],
    correct: 0,
    explanation: "'Her verdict on the performance was clear' is a complete sentence; colon introduces the explanation.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe campers need ______ sleeping bags, a tent, and a cooking stove.`,
    options: ["three things:", "three things,", "three things;", "three things, namely,"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe artist is famous for her ______ bold lines, vivid colors, and imaginative subjects.`,
    options: ["signature style:", "signature style,", "signature style;", "signature style, for example"],
    correct: 0,
    explanation: "'The artist is famous for her signature style' is a complete sentence; colon introduces the explanation.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe town has three historic landmarks ______ the old courthouse, the stone bridge, and the first public library.`,
    options: ["landmarks:", "landmarks,", "landmarks;", "landmarks, and they are"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe message from the coach was simple ______ work hard and trust your teammates.`,
    options: ["simple:", "simple,", "simple;", "simple, that being"],
    correct: 0,
    explanation: "'The message from the coach was simple' is a complete sentence; colon introduces the explanation.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe box contained ______ a compass, a map, and a small flashlight.`,
    options: ["three useful items:", "three useful items,", "three useful items;", "three useful items, such as"],
    correct: 0,
    explanation: "'The box contained three useful items' is a complete sentence; colon introduces the list.",
    difficulty: "M",
  },
];

const nmsqt = [
  {
    stem: `${FORMAT}\n\nThe school offers three languages ______ Spanish, Mandarin, and French.`,
    options: ["languages:", "languages,", "languages;", "languages, namely,"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe main ingredients in gazpacho ______ tomatoes, cucumbers, and bell peppers.`,
    options: ["are", "are:", "are —", "are;"],
    correct: 0,
    explanation: "'The main ingredients in gazpacho are' is NOT a complete sentence. No colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe lecture covered four topics ______ mitosis, meiosis, DNA replication, and protein synthesis.`,
    options: ["topics:", "topics,", "topics;", "topics, which are"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe conference attendees ______ professors, graduate students, and industry professionals.`,
    options: ["included:", "included,", "included;", "were including"],
    correct: 0,
    explanation: "'The conference attendees included' is NOT a complete sentence. No colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nHer reasoning was straightforward ______ the project was over budget and behind schedule.`,
    options: ["straightforward:", "straightforward,", "straightforward;", "straightforward because"],
    correct: 0,
    explanation: "'Her reasoning was straightforward' is a complete sentence; colon introduces the explanation.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe gift basket held three items ______ a jar of honey, a box of tea, and a small candle.`,
    options: ["items:", "items,", "items;", "items, and they were"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe three largest cities in the country ______ São Paulo, Rio de Janeiro, and Salvador.`,
    options: ["are", "are:", "are —", "are;"],
    correct: 0,
    explanation: "'The three largest cities in the country are' is NOT a complete sentence.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe verdict was clear ______ the design was innovative and the execution was flawless.`,
    options: ["clear:", "clear,", "clear;", "clear, as"],
    correct: 0,
    explanation: "Complete sentence + explanation = colon.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe classroom needs three supplies ______ whiteboard markers, printer paper, and sticky notes.`,
    options: ["supplies:", "supplies,", "supplies;", "supplies, which are"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe town is known for ______ the lake, the old mill, and the annual harvest festival.`,
    options: ["three attractions:", "three attractions,", "three attractions;", "three attractions, and they are"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe coach has three rules for the team ______ show up on time, give full effort, and support each other.`,
    options: ["team:", "team,", "team;", "team, which include"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe four winners ______ Marisol, Kenji, Fatima, and Thabo.`,
    options: ["were", "were:", "were —", "were;"],
    correct: 0,
    explanation: "'The four winners were' is NOT a complete sentence.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe festival featured ______ jazz, folk, and classical.`,
    options: ["three music genres:", "three music genres,", "three music genres;", "three music genres, including"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe three candidates on the ballot ______ a teacher, a farmer, and a retired soldier.`,
    options: ["were", "were:", "were —", "were;"],
    correct: 0,
    explanation: "'The three candidates on the ballot were' is NOT a complete sentence.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe playwright drew from three sources ______ family history, local legends, and a few of her own dreams.`,
    options: ["sources:", "sources,", "sources;", "sources, such as"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe hike had three challenging sections ______ the steep ridge, the river crossing, and the final ascent.`,
    options: ["sections:", "sections,", "sections;", "sections, and they included"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe committee agreed on ______ start with a survey, publish a report, and hold a community meeting.`,
    options: ["three next steps:", "three next steps,", "three next steps;", "three next steps, to"],
    correct: 0,
    explanation: "'The committee agreed on three next steps' is a complete sentence; colon introduces the list.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe museum's collection features ______ Rodin, Brancusi, and Giacometti.`,
    options: ["three sculptors:", "three sculptors,", "three sculptors;", "three sculptors, namely,"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe professor's advice was simple ______ read widely, write often, and revise carefully.`,
    options: ["simple:", "simple,", "simple;", "simple, and it was"],
    correct: 0,
    explanation: "Complete sentence + explanation = colon.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe backpack contained ______ a notebook, a pencil case, and a water bottle.`,
    options: ["three essentials:", "three essentials,", "three essentials;", "three essentials, including"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
];

const psat89 = [
  {
    stem: `${FORMAT}\n\nThe club meets on three days each week ______ Monday, Wednesday, and Friday.`,
    options: ["week:", "week,", "week;", "week, and they are"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe three main ingredients ______ flour, sugar, and butter.`,
    options: ["are", "are:", "are —", "are;"],
    correct: 0,
    explanation: "'The three main ingredients are' is NOT a complete sentence.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe playlist has three new ______ pop, rock, and jazz.`,
    options: ["songs in three styles:", "songs in three styles,", "songs in three styles;", "songs in three styles, which are"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe team members ______ Alex, Bri, and Carlos.`,
    options: ["are", "are:", "are —", "are;"],
    correct: 0,
    explanation: "'The team members are' is NOT a complete sentence.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nHer answer was straightforward ______ she had already decided to take the job.`,
    options: ["straightforward:", "straightforward,", "straightforward;", "straightforward, because"],
    correct: 0,
    explanation: "Complete sentence + explanation = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe lunchbox contained ______ a sandwich, an apple, and a juice box.`,
    options: ["three items:", "three items,", "three items;", "three items, and"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe five players on the court ______ two guards, two forwards, and a center.`,
    options: ["were", "were:", "were —", "were;"],
    correct: 0,
    explanation: "'The five players on the court were' is NOT a complete sentence.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nHer reasoning was clear ______ the bus was late, so they had to walk.`,
    options: ["clear:", "clear,", "clear;", "clear, since"],
    correct: 0,
    explanation: "Complete sentence + explanation = colon.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe bedroom needs three things ______ a new lamp, a rug, and curtains.`,
    options: ["things:", "things,", "things;", "things, that are"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe park is known for ______ old trees, a quiet pond, and winding trails.`,
    options: ["three features:", "three features,", "three features;", "three features, namely,"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe coach gave the team three rules ______ listen, practice, and respect each other.`,
    options: ["rules:", "rules,", "rules;", "rules, which are"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe four members of the band ______ Jamie, Kim, Lou, and Mario.`,
    options: ["are", "are:", "are —", "are;"],
    correct: 0,
    explanation: "'The four members of the band are' is NOT a complete sentence.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe festival offered ______ blues, hip-hop, and folk.`,
    options: ["three genres:", "three genres,", "three genres;", "three genres, like"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe three exchange students ______ Ana, Bo, and Chidi.`,
    options: ["are", "are:", "are —", "are;"],
    correct: 0,
    explanation: "'The three exchange students are' is NOT a complete sentence.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe recipe has three ______ whisk the eggs, fold in the flour, and bake for twenty minutes.`,
    options: ["steps:", "steps,", "steps;", "steps, beginning with"],
    correct: 0,
    explanation: "'The recipe has three steps' is a complete sentence; colon introduces the steps.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe hike had three difficult sections ______ a steep climb, a rope bridge, and a muddy descent.`,
    options: ["sections:", "sections,", "sections;", "sections, such as"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nShe agreed to ______ clean the garage, mow the lawn, and wash the car.`,
    options: ["three chores:", "three chores,", "three chores;", "three chores, including"],
    correct: 0,
    explanation: "'She agreed to three chores' is a complete sentence; colon introduces the list.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe school honored three students ______ Jonah, Priya, and Tasha.`,
    options: ["students:", "students,", "students;", "students, who were"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nHer rule for weekends was simple ______ finish homework first, then have fun.`,
    options: ["simple:", "simple,", "simple;", "simple, being that she would"],
    correct: 0,
    explanation: "Complete sentence + explanation = colon.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe fridge held ______ milk, cheese, and butter.`,
    options: ["three dairy items:", "three dairy items,", "three dairy items;", "three dairy items, namely,"],
    correct: 0,
    explanation: "Complete sentence + list = colon.",
    difficulty: "M",
  },
];

export default {
  skill: "colon_usage",
  skillLabel: "Colon usage",
  domain: "Standard English Conventions",
  section: "rw",
  batches: {
    "sat-rw": sat,
    "nmsqt-rw": nmsqt,
    "psat89-rw": psat89,
  },
};
