// Comma usage — 60 questions (20 per test type)

const FORMAT = "Which choice completes the text so that it conforms to the conventions of Standard English?";

const sat = [
  {
    stem: `${FORMAT}\n\n______ the hiking group reached the summit just before sunrise.`,
    options: [
      "After a long night of climbing,",
      "After a long night of climbing",
      "After, a long night of climbing,",
      "After a long, night of climbing",
    ],
    correct: 0,
    explanation: "An introductory phrase needs exactly one comma at the end, right before the main clause.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe novelist Zadie Smith ______ is one of the most celebrated writers of her generation.`,
    options: [
      ", whose first book 'White Teeth' was published in 2000,",
      "whose first book 'White Teeth' was published in 2000",
      "whose first book, 'White Teeth', was published in 2000",
      "whose first book 'White Teeth' was published in 2000,",
    ],
    correct: 0,
    explanation: "The clause about her first book is nonrestrictive (Smith is already identified by name). Set it off with commas on BOTH sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe store ______ and a full selection of craft supplies.`,
    options: [
      "sells yarn, knitting needles,",
      "sells yarn knitting needles",
      "sells yarn, knitting needles",
      "sells, yarn, knitting needles",
    ],
    correct: 0,
    explanation: "A series of three items needs a comma between each — Oxford comma included before 'and.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ the engineers inspected every bridge in the county.`,
    options: [
      "Following the earthquake,",
      "Following the earthquake",
      "Following, the earthquake,",
      "Following the, earthquake,",
    ],
    correct: 0,
    explanation: "Intro phrase needs one comma at the end.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nMy oldest cousin ______ will be visiting us next week.`,
    options: [
      ", who lives in Atlanta,",
      "who lives in Atlanta",
      ", who lives in Atlanta",
      "who lives in Atlanta,",
    ],
    correct: 0,
    explanation: "Nonrestrictive clause describing 'my oldest cousin' — use commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe recipe calls for ______ and a teaspoon of salt.`,
    options: [
      "two cups of flour, three eggs, a cup of milk,",
      "two cups of flour three eggs a cup of milk",
      "two cups of flour, three eggs a cup of milk,",
      "two cups, of flour, three eggs, a cup of milk",
    ],
    correct: 0,
    explanation: "Four-item list needs commas between each item and before the 'and' (Oxford comma).",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe architect ______ has designed libraries in three countries.`,
    options: [
      ", who is originally from Mexico City,",
      "who is originally from Mexico City",
      "who is originally from Mexico City,",
      ", who is originally from Mexico City",
    ],
    correct: 0,
    explanation: "Nonrestrictive 'who' clause about a specific architect — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ the team decided to play on.`,
    options: [
      "Although it was raining heavily,",
      "Although it was raining heavily",
      "Although, it was raining heavily,",
      "Although it, was raining heavily,",
    ],
    correct: 0,
    explanation: "Introductory dependent clause needs one comma at the end.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nHis latest novel ______ has received wide acclaim.`,
    options: [
      ", a story about three siblings,",
      "a story about three siblings",
      ", a story about three siblings",
      "a story about three siblings,",
    ],
    correct: 0,
    explanation: "'A story about three siblings' is a nonrestrictive appositive describing 'his latest novel.' Use commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe volunteers distributed ______ and warm blankets.`,
    options: [
      "food, bottled water,",
      "food bottled water",
      "food bottled water,",
      "food, bottled, water,",
    ],
    correct: 0,
    explanation: "Three-item list with Oxford comma before 'and.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ the audience rose to its feet and applauded.`,
    options: [
      "When the soloist finished her piece,",
      "When the soloist finished her piece",
      "When, the soloist finished her piece,",
      "When the soloist, finished her piece,",
    ],
    correct: 0,
    explanation: "Introductory dependent clause → one comma at the end.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe artist's most famous painting ______ hangs in a small museum in Boston.`,
    options: [
      ", completed in 1925,",
      "completed in 1925",
      ", completed in 1925",
      "completed in 1925,",
    ],
    correct: 0,
    explanation: "Nonrestrictive descriptive phrase — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe restaurant is famous for ______ and its homemade pasta.`,
    options: [
      "its cozy atmosphere, attentive service,",
      "its cozy atmosphere attentive service",
      "its cozy atmosphere, attentive service",
      "its, cozy atmosphere, attentive service,",
    ],
    correct: 0,
    explanation: "Three-item list with Oxford comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ the committee voted to postpone the decision.`,
    options: [
      "After hours of discussion,",
      "After hours of discussion",
      "After, hours of discussion,",
      "After hours, of discussion,",
    ],
    correct: 0,
    explanation: "Introductory phrase → one closing comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe governor's office ______ released a statement on Tuesday morning.`,
    options: [
      ", responding to widespread criticism,",
      "responding to widespread criticism",
      "responding to widespread criticism,",
      ", responding to widespread criticism",
    ],
    correct: 0,
    explanation: "Nonrestrictive participial phrase — commas on both sides.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe gallery showcases ______ and mixed-media installations.`,
    options: [
      "paintings, sculptures, photographs,",
      "paintings sculptures photographs",
      "paintings, sculptures photographs,",
      "paintings, sculptures, photographs",
    ],
    correct: 0,
    explanation: "Four-item series needs commas between items and an Oxford comma before 'and.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ the airline issued new boarding guidelines.`,
    options: [
      "In response to the delays,",
      "In response to the delays",
      "In, response to the delays,",
      "In response, to the delays,",
    ],
    correct: 0,
    explanation: "Intro phrase → one closing comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe historian Barbara Tuchman ______ is best known for her books on the First World War.`,
    options: [
      ", a Pulitzer Prize winner,",
      "a Pulitzer Prize winner",
      ", a Pulitzer Prize winner",
      "a Pulitzer Prize winner,",
    ],
    correct: 0,
    explanation: "Nonrestrictive appositive naming Tuchman's credential — commas on both sides.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe recipe requires ______ and two cups of fresh basil.`,
    options: [
      "olive oil, garlic, salt,",
      "olive oil garlic salt",
      "olive oil, garlic, salt",
      "olive, oil, garlic, salt,",
    ],
    correct: 0,
    explanation: "Four-item list with Oxford comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ the students gathered in the library for tutoring.`,
    options: [
      "On Thursdays,",
      "On Thursdays",
      "On, Thursdays,",
      "On Thursdays ,",
    ],
    correct: 0,
    explanation: "A short introductory prepositional phrase gets a comma at the end.",
    difficulty: "F",
  },
];

const nmsqt = [
  {
    stem: `${FORMAT}\n\n______ the new library opened to the public.`,
    options: [
      "After many years of planning and construction,",
      "After many years of planning and construction",
      "After, many years of planning and construction,",
      "After many, years of planning and construction,",
    ],
    correct: 0,
    explanation: "Intro phrase → one comma at the end.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe physicist Marie Curie ______ remains an icon of scientific achievement.`,
    options: [
      ", the first woman to win a Nobel Prize,",
      "the first woman to win a Nobel Prize",
      ", the first woman to win a Nobel Prize",
      "the first woman to win a Nobel Prize,",
    ],
    correct: 0,
    explanation: "Nonrestrictive appositive — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe soup recipe uses ______ and freshly chopped parsley.`,
    options: [
      "tomatoes, onions, garlic,",
      "tomatoes onions garlic",
      "tomatoes, onions, garlic",
      "tomatoes onions, garlic,",
    ],
    correct: 0,
    explanation: "Four-item series with Oxford comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ the students waited patiently for the bus.`,
    options: [
      "Despite the cold weather,",
      "Despite the cold weather",
      "Despite, the cold weather,",
      "Despite the, cold weather,",
    ],
    correct: 0,
    explanation: "Intro phrase → one comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe poet Langston Hughes ______ published 'The Weary Blues' in 1926.`,
    options: [
      ", a central figure of the Harlem Renaissance,",
      "a central figure of the Harlem Renaissance",
      ", a central figure of the Harlem Renaissance",
      "a central figure of the Harlem Renaissance,",
    ],
    correct: 0,
    explanation: "Nonrestrictive appositive — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe backpack contained ______ and a reusable water bottle.`,
    options: [
      "a notebook, three pens, a calculator,",
      "a notebook three pens a calculator",
      "a notebook, three pens, a calculator",
      "a notebook, three, pens, a calculator,",
    ],
    correct: 0,
    explanation: "Four-item list with Oxford comma.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe oldest building in town ______ is being restored this year.`,
    options: [
      ", a former schoolhouse built in 1870,",
      "a former schoolhouse built in 1870",
      ", a former schoolhouse built in 1870",
      "a former schoolhouse built in 1870,",
    ],
    correct: 0,
    explanation: "Nonrestrictive appositive — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ the engineers worked through the night.`,
    options: [
      "Knowing that the bridge had to reopen by morning,",
      "Knowing that the bridge had to reopen by morning",
      "Knowing, that the bridge had to reopen by morning,",
      "Knowing that, the bridge had to reopen by morning,",
    ],
    correct: 0,
    explanation: "Intro participial phrase → one comma at the end.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe painting ______ hangs above the fireplace.`,
    options: [
      ", which was a gift from her grandmother,",
      "which was a gift from her grandmother",
      ", which was a gift from her grandmother",
      "which was a gift from her grandmother,",
    ],
    correct: 0,
    explanation: "Nonrestrictive 'which' clause — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe musician performed ______ and a brand-new composition.`,
    options: [
      "two classical pieces, a folk song, an original ballad,",
      "two classical pieces a folk song an original ballad",
      "two classical pieces, a folk song, an original ballad",
      "two, classical pieces, a folk song, an original ballad,",
    ],
    correct: 0,
    explanation: "Four-item list with Oxford comma.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ the travelers booked a hotel near the train station.`,
    options: [
      "To save money,",
      "To save money",
      "To, save money,",
      "To save, money,",
    ],
    correct: 0,
    explanation: "Intro infinitive phrase → one closing comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe documentary ______ won several awards.`,
    options: [
      ", filmed entirely in black and white,",
      "filmed entirely in black and white",
      ", filmed entirely in black and white",
      "filmed entirely in black and white,",
    ],
    correct: 0,
    explanation: "Nonrestrictive participial phrase — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe market is known for ______ and its locally roasted coffee.`,
    options: [
      "its fresh produce, friendly vendors, handmade bread,",
      "its fresh produce friendly vendors handmade bread",
      "its fresh produce, friendly vendors, handmade bread",
      "its fresh produce, friendly, vendors, handmade, bread,",
    ],
    correct: 0,
    explanation: "Four-item series with Oxford comma.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ the team finalized its strategy for the championship.`,
    options: [
      "After reviewing hours of game footage,",
      "After reviewing hours of game footage",
      "After, reviewing hours of game footage,",
      "After reviewing, hours of game footage,",
    ],
    correct: 0,
    explanation: "Intro phrase → one comma at the end.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe city's oldest theater ______ will be demolished next month.`,
    options: [
      ", closed for renovations since last spring,",
      "closed for renovations since last spring",
      "closed for renovations since last spring,",
      ", closed for renovations since last spring",
    ],
    correct: 0,
    explanation: "Nonrestrictive participial phrase — commas on both sides.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe exhibit included ______ and several restored photographs.`,
    options: [
      "ancient pottery, carved bone tools, iron weapons,",
      "ancient pottery carved bone tools iron weapons",
      "ancient pottery, carved bone tools, iron weapons",
      "ancient pottery, carved, bone tools, iron, weapons,",
    ],
    correct: 0,
    explanation: "Four-item series with Oxford comma.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ the company announced a new product line.`,
    options: [
      "Following the success of its last launch,",
      "Following the success of its last launch",
      "Following, the success of its last launch,",
      "Following the, success of its last launch,",
    ],
    correct: 0,
    explanation: "Intro phrase → one comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe composer Aaron Copland ______ wrote some of the most distinctly American music of the 20th century.`,
    options: [
      ", born in Brooklyn in 1900,",
      "born in Brooklyn in 1900",
      ", born in Brooklyn in 1900",
      "born in Brooklyn in 1900,",
    ],
    correct: 0,
    explanation: "Nonrestrictive participial phrase — commas on both sides.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe kitchen needs ______ and a new refrigerator.`,
    options: [
      "fresh paint, new cabinets, better lighting,",
      "fresh paint new cabinets better lighting",
      "fresh paint, new cabinets, better lighting",
      "fresh, paint, new, cabinets, better, lighting,",
    ],
    correct: 0,
    explanation: "Four-item series with Oxford comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ the volunteers finished painting the mural.`,
    options: [
      "By early evening,",
      "By early evening",
      "By, early evening,",
      "By early, evening,",
    ],
    correct: 0,
    explanation: "Intro phrase → one comma.",
    difficulty: "F",
  },
];

const psat89 = [
  {
    stem: `${FORMAT}\n\n______ the class visited the history museum.`,
    options: [
      "On Friday morning,",
      "On Friday morning",
      "On, Friday morning,",
      "On Friday, morning,",
    ],
    correct: 0,
    explanation: "Intro phrase → one closing comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nMy uncle ______ is teaching me how to play guitar.`,
    options: [
      ", who lives in New Orleans,",
      "who lives in New Orleans",
      ", who lives in New Orleans",
      "who lives in New Orleans,",
    ],
    correct: 0,
    explanation: "Nonrestrictive 'who' clause about a specific uncle — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nFor breakfast, Sara had ______ and orange juice.`,
    options: [
      "toast, scrambled eggs,",
      "toast scrambled eggs",
      "toast, scrambled eggs",
      "toast, scrambled, eggs,",
    ],
    correct: 0,
    explanation: "Three-item series with Oxford comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ the soccer team kept practicing.`,
    options: [
      "Even after the rain started,",
      "Even after the rain started",
      "Even, after the rain started,",
      "Even after, the rain started,",
    ],
    correct: 0,
    explanation: "Intro phrase → one comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe author J. K. Rowling ______ wrote the Harry Potter series.`,
    options: [
      ", a former English teacher,",
      "a former English teacher",
      ", a former English teacher",
      "a former English teacher,",
    ],
    correct: 0,
    explanation: "Nonrestrictive appositive — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe backpack held ______ and a bag of trail mix.`,
    options: [
      "a water bottle, a flashlight, a map,",
      "a water bottle a flashlight a map",
      "a water bottle, a flashlight, a map",
      "a water, bottle, a flashlight, a map,",
    ],
    correct: 0,
    explanation: "Four-item list with Oxford comma.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe oldest tree in the park ______ is over 300 years old.`,
    options: [
      ", a massive oak near the entrance,",
      "a massive oak near the entrance",
      ", a massive oak near the entrance",
      "a massive oak near the entrance,",
    ],
    correct: 0,
    explanation: "Nonrestrictive appositive — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ the volunteers set up the tables.`,
    options: [
      "Before the guests arrived,",
      "Before the guests arrived",
      "Before, the guests arrived,",
      "Before the, guests arrived,",
    ],
    correct: 0,
    explanation: "Intro clause → one comma at the end.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe book ______ won several children's literature awards.`,
    options: [
      ", which was illustrated by the author's sister,",
      "which was illustrated by the author's sister",
      ", which was illustrated by the author's sister",
      "which was illustrated by the author's sister,",
    ],
    correct: 0,
    explanation: "Nonrestrictive 'which' clause — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe store sells ______ and handmade soaps.`,
    options: [
      "candles, incense, essential oils,",
      "candles incense essential oils",
      "candles, incense, essential oils",
      "candles, incense, essential, oils,",
    ],
    correct: 0,
    explanation: "Four-item series with Oxford comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ Luis studied hard for his exam.`,
    options: [
      "Throughout the weekend,",
      "Throughout the weekend",
      "Throughout, the weekend,",
      "Throughout the, weekend,",
    ],
    correct: 0,
    explanation: "Intro phrase → one comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe documentary ______ aired on public television last month.`,
    options: [
      ", filmed over two years in the Arctic,",
      "filmed over two years in the Arctic",
      ", filmed over two years in the Arctic",
      "filmed over two years in the Arctic,",
    ],
    correct: 0,
    explanation: "Nonrestrictive participial phrase — commas on both sides.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe new restaurant is known for ______ and its friendly staff.`,
    options: [
      "its warm atmosphere, fresh ingredients, generous portions,",
      "its warm atmosphere fresh ingredients generous portions",
      "its warm atmosphere, fresh ingredients, generous portions",
      "its, warm atmosphere, fresh ingredients, generous portions,",
    ],
    correct: 0,
    explanation: "Four-item series with Oxford comma.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ the bakery runs out of croissants.`,
    options: [
      "Most Saturday mornings,",
      "Most Saturday mornings",
      "Most, Saturday mornings,",
      "Most Saturday, mornings,",
    ],
    correct: 0,
    explanation: "Intro phrase → one comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe old schoolhouse ______ is being converted into a museum.`,
    options: [
      ", built in 1890 and closed in 1975,",
      "built in 1890 and closed in 1975",
      "built in 1890 and closed in 1975,",
      ", built in 1890 and closed in 1975",
    ],
    correct: 0,
    explanation: "Nonrestrictive participial phrase — commas on both sides.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe art supply box had ______ and a pack of colored markers.`,
    options: [
      "pencils, erasers, a sharpener,",
      "pencils erasers a sharpener",
      "pencils, erasers, a sharpener",
      "pencils, erasers, a, sharpener,",
    ],
    correct: 0,
    explanation: "Four-item list with Oxford comma.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ the club gathered for its first meeting of the year.`,
    options: [
      "Eager to get started,",
      "Eager to get started",
      "Eager, to get started,",
      "Eager to, get started,",
    ],
    correct: 0,
    explanation: "Intro participial phrase → one comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe conductor Leonard Bernstein ______ led the New York Philharmonic for over a decade.`,
    options: [
      ", an American composer and pianist,",
      "an American composer and pianist",
      ", an American composer and pianist",
      "an American composer and pianist,",
    ],
    correct: 0,
    explanation: "Nonrestrictive appositive — commas on both sides.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe recipe requires ______ and a dash of black pepper.`,
    options: [
      "olive oil, lemon juice, garlic, sea salt,",
      "olive oil lemon juice garlic sea salt",
      "olive oil, lemon juice, garlic, sea salt",
      "olive, oil, lemon, juice, garlic, sea, salt,",
    ],
    correct: 0,
    explanation: "Five-item list with Oxford comma.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ the marathon runners crossed the finish line.`,
    options: [
      "Just before sunset,",
      "Just before sunset",
      "Just, before sunset,",
      "Just before, sunset,",
    ],
    correct: 0,
    explanation: "Intro phrase → one comma.",
    difficulty: "F",
  },
];

export default {
  skill: "comma_usage",
  skillLabel: "Comma usage",
  domain: "Standard English Conventions",
  section: "rw",
  batches: {
    "sat-rw": sat,
    "nmsqt-rw": nmsqt,
    "psat89-rw": psat89,
  },
};
