// Expected value — 60 questions (20 per test type)

const sat = [
  {
    stem: "A spinner has three equal sections labeled $1$, $3$, and $5$. What is the expected value of one spin?",
    options: ["$3$", "$9$", "$5$", "$1$"],
    correct: 0,
    explanation: "Equal sections → plain average: $\\frac{1+3+5}{3} = 3$.",
    difficulty: "F",
  },
  {
    stem: "A fair six-sided die is rolled. What is the expected value of the outcome?",
    options: ["$3.5$", "$3$", "$4$", "$6$"],
    correct: 0,
    explanation: "$\\frac{1+2+3+4+5+6}{6} = \\frac{21}{6} = 3.5$.",
    difficulty: "F",
  },
  {
    stem: "A coin is flipped. Heads pays $\\$10$; tails pays $\\$0$. What is the expected payout?",
    options: ["$\\$5$", "$\\$10$", "$\\$0$", "$\\$2.50$"],
    correct: 0,
    explanation: "$10 \\cdot \\frac{1}{2} + 0 \\cdot \\frac{1}{2} = 5$.",
    difficulty: "F",
  },
  {
    stem: "A spinner has four equal sections with point values $2$, $4$, $6$, and $8$. What is the expected value of one spin?",
    options: ["$5$", "$20$", "$4$", "$6$"],
    correct: 0,
    explanation: "$\\frac{2+4+6+8}{4} = 5$.",
    difficulty: "F",
  },
  {
    stem: "A random variable $X$ takes the value $10$ with probability $0.2$ and the value $0$ with probability $0.8$. Find $E(X)$.",
    options: ["$2$", "$10$", "$8$", "$5$"],
    correct: 0,
    explanation: "$E(X) = 10 \\cdot 0.2 + 0 \\cdot 0.8 = 2$.",
    difficulty: "F",
  },
  {
    stem: "A game costs $\\$3$ to play. You win $\\$12$ with probability $\\frac{1}{4}$ and nothing otherwise. What is the expected profit per play?",
    options: ["$\\$0$", "$\\$3$", "$-\\$3$", "$\\$9$"],
    correct: 0,
    explanation: "Win profit: $12 - 3 = 9$. Lose profit: $-3$. $E = 9 \\cdot \\frac{1}{4} + (-3) \\cdot \\frac{3}{4} = 2.25 - 2.25 = 0$. A fair game.",
    difficulty: "M",
  },
  {
    stem: "A fundraiser sells $200$ raffle tickets for $\\$5$ each. One ticket wins a $\\$400$ prize. What is the expected profit for a person who buys one ticket?",
    options: ["$-\\$3$", "$-\\$5$", "$\\$2$", "$-\\$1$"],
    correct: 0,
    explanation: "Win: $400 - 5 = 395$, probability $\\frac{1}{200}$. Lose: $-5$, probability $\\frac{199}{200}$. $E = \\frac{395}{200} - \\frac{995}{200} = -\\frac{600}{200} = -3$.",
    difficulty: "M",
  },
  {
    stem: "A random variable has the distribution: $P(X=0)=0.5$, $P(X=2)=0.3$, $P(X=5)=0.2$. Find $E(X)$.",
    options: ["$1.6$", "$2.33$", "$3.5$", "$1$"],
    correct: 0,
    explanation: "$E = 0(0.5) + 2(0.3) + 5(0.2) = 0 + 0.6 + 1 = 1.6$.",
    difficulty: "M",
  },
  {
    stem: "A bag contains $3$ red balls, $2$ blue balls, and $5$ green balls. Red balls are worth $10$ points, blue are $5$, green are $0$. One ball is drawn at random. What is the expected point value?",
    options: ["$4$", "$5$", "$7.5$", "$3$"],
    correct: 0,
    explanation: "$10 \\cdot \\frac{3}{10} + 5 \\cdot \\frac{2}{10} + 0 \\cdot \\frac{5}{10} = 3 + 1 + 0 = 4$.",
    difficulty: "M",
  },
  {
    stem: "A quiz has $10$ multiple-choice questions, each with $4$ options. A student guesses every question. What is the expected number of correct answers?",
    options: ["$2.5$", "$10$", "$4$", "$0.25$"],
    correct: 0,
    explanation: "Per question: probability $\\frac{1}{4}$, expected correct $= 0.25$. Over $10$ questions: $10 \\cdot 0.25 = 2.5$.",
    difficulty: "M",
  },
  {
    stem: "A single fair die is rolled. You win the number of dollars that shows (so rolling a $4$ wins $\\$4$). What is the expected dollar amount?",
    options: ["$\\$3.50$", "$\\$3$", "$\\$6$", "$\\$4$"],
    correct: 0,
    explanation: "Expected value of a die roll is $3.5$, so expected dollars is $\\$3.50$.",
    difficulty: "M",
  },
  {
    stem: "An insurance policy pays out $\\$1000$ with probability $0.01$ and nothing otherwise. What is the expected payout?",
    options: ["$\\$10$", "$\\$100$", "$\\$1000$", "$\\$1$"],
    correct: 0,
    explanation: "$1000 \\cdot 0.01 + 0 \\cdot 0.99 = 10$.",
    difficulty: "M",
  },
  {
    stem: "A spinner has a $20\\%$ chance of landing on red, $30\\%$ chance of blue, and $50\\%$ chance of green. Red pays $\\$5$, blue pays $\\$10$, green pays $\\$0$. What is the expected payout?",
    options: ["$\\$4$", "$\\$5$", "$\\$15$", "$\\$8$"],
    correct: 0,
    explanation: "$5(0.2) + 10(0.3) + 0(0.5) = 1 + 3 + 0 = 4$.",
    difficulty: "M",
  },
  {
    stem: "A carnival game costs $\\$2$ to play. You win $\\$5$ with probability $\\frac{1}{3}$, nothing otherwise. What is the expected profit per game?",
    options: ["$-\\$\\frac{1}{3}$", "$\\$1$", "$-\\$2$", "$\\$0$"],
    correct: 0,
    explanation: "$E = (5-2) \\cdot \\frac{1}{3} + (-2) \\cdot \\frac{2}{3} = 1 - \\frac{4}{3} = -\\frac{1}{3}$.",
    difficulty: "C",
  },
  {
    stem: "A box contains $10$ cards: $4$ win $\\$3$ each, $6$ win $\\$0$. You draw one card. What is the expected payout?",
    options: ["$\\$1.20$", "$\\$3$", "$\\$1.50$", "$\\$0$"],
    correct: 0,
    explanation: "$3 \\cdot \\frac{4}{10} + 0 \\cdot \\frac{6}{10} = 1.20$.",
    difficulty: "M",
  },
  {
    stem: "A game has three outcomes: win $\\$8$ with probability $0.25$, win $\\$2$ with probability $0.25$, win $\\$0$ with probability $0.5$. What is the expected winnings?",
    options: ["$\\$2.50$", "$\\$5$", "$\\$10$", "$\\$3.33$"],
    correct: 0,
    explanation: "$8(0.25) + 2(0.25) + 0(0.5) = 2 + 0.5 + 0 = 2.50$.",
    difficulty: "M",
  },
  {
    stem: "A random variable $X$ has $P(X=-2)=0.4$ and $P(X=3)=0.6$. Find $E(X)$.",
    options: ["$1$", "$0.5$", "$0.2$", "$2.5$"],
    correct: 0,
    explanation: "$E(X) = -2(0.4) + 3(0.6) = -0.8 + 1.8 = 1$.",
    difficulty: "M",
  },
  {
    stem: "A charity is deciding between two games. Game A has expected profit $\\$2$ per play; Game B has expected profit $\\$5$ per play. If they plan to run $100$ plays, which game is expected to raise more money, and by how much?",
    options: ["Game B, by $\\$300$", "Game A, by $\\$300$", "Game B, by $\\$500$", "They are equal"],
    correct: 0,
    explanation: "Game B per play: $\\$5$; Game A: $\\$2$. Difference per play: $\\$3$. Over $100$ plays: $\\$300$ more for Game B.",
    difficulty: "C",
  },
  {
    stem: "A dart game: hitting the bullseye ($10\\%$ chance) scores $50$ points, hitting the inner ring ($30\\%$ chance) scores $20$ points, and missing ($60\\%$ chance) scores $0$. Expected score per throw?",
    options: ["$11$", "$23.3$", "$14$", "$70$"],
    correct: 0,
    explanation: "$50(0.1) + 20(0.3) + 0(0.6) = 5 + 6 + 0 = 11$.",
    difficulty: "C",
  },
  {
    stem: "A lottery ticket costs $\\$2$. There is a $\\frac{1}{1000}$ chance of winning $\\$1500$, a $\\frac{1}{100}$ chance of winning $\\$10$, and otherwise no win. What is the expected profit per ticket?",
    options: ["$-\\$0.40$", "$\\$1.50$", "$-\\$2$", "$\\$0$"],
    correct: 0,
    explanation: "$E(\\text{winnings}) = 1500 \\cdot 0.001 + 10 \\cdot 0.01 + 0 \\cdot 0.989 = 1.50 + 0.10 = 1.60$. Profit $= 1.60 - 2 = -0.40$.",
    difficulty: "C",
  },
];

const nmsqt = [
  {
    stem: "A spinner has three equal sections labeled $2$, $4$, and $6$. What is the expected value of one spin?",
    options: ["$4$", "$12$", "$6$", "$2$"],
    correct: 0,
    explanation: "Equal sections → average: $\\frac{2+4+6}{3} = 4$.",
    difficulty: "F",
  },
  {
    stem: "A fair four-sided die has faces labeled $1$, $2$, $3$, $4$. What is the expected value of one roll?",
    options: ["$2.5$", "$2$", "$3$", "$4$"],
    correct: 0,
    explanation: "$\\frac{1+2+3+4}{4} = 2.5$.",
    difficulty: "F",
  },
  {
    stem: "A coin toss pays $\\$6$ for heads and $\\$2$ for tails. What is the expected payout?",
    options: ["$\\$4$", "$\\$6$", "$\\$2$", "$\\$8$"],
    correct: 0,
    explanation: "$6 \\cdot \\frac{1}{2} + 2 \\cdot \\frac{1}{2} = 4$.",
    difficulty: "F",
  },
  {
    stem: "A spinner has four equal sections worth $5$, $10$, $15$, and $20$ points. What is the expected value per spin?",
    options: ["$12.5$", "$50$", "$15$", "$10$"],
    correct: 0,
    explanation: "$\\frac{5+10+15+20}{4} = 12.5$.",
    difficulty: "F",
  },
  {
    stem: "A random variable equals $20$ with probability $0.1$ and $0$ with probability $0.9$. Find its expected value.",
    options: ["$2$", "$20$", "$0.9$", "$10$"],
    correct: 0,
    explanation: "$E = 20(0.1) + 0(0.9) = 2$.",
    difficulty: "F",
  },
  {
    stem: "A game costs $\\$4$ to play. You win $\\$20$ with probability $\\frac{1}{5}$ and nothing otherwise. What is the expected profit?",
    options: ["$\\$0$", "$\\$4$", "$-\\$4$", "$\\$16$"],
    correct: 0,
    explanation: "Win profit: $20 - 4 = 16$. Lose profit: $-4$. $E = 16 \\cdot \\frac{1}{5} + (-4) \\cdot \\frac{4}{5} = 3.2 - 3.2 = 0$. Fair game.",
    difficulty: "M",
  },
  {
    stem: "A school club sells $100$ raffle tickets for $\\$3$ each. One ticket wins a $\\$150$ prize. What is the expected profit for a person who buys one ticket?",
    options: ["$-\\$1.50$", "$\\$1.50$", "$-\\$3$", "$-\\$0.50$"],
    correct: 0,
    explanation: "Win: $150 - 3 = 147$, $P = \\frac{1}{100}$. Lose: $-3$, $P = \\frac{99}{100}$. $E = \\frac{147}{100} - \\frac{297}{100} = -\\frac{150}{100} = -1.50$.",
    difficulty: "M",
  },
  {
    stem: "A distribution: $P(X=1)=0.4$, $P(X=3)=0.4$, $P(X=5)=0.2$. Find $E(X)$.",
    options: ["$2.6$", "$3$", "$2.33$", "$1.5$"],
    correct: 0,
    explanation: "$E = 1(0.4) + 3(0.4) + 5(0.2) = 0.4 + 1.2 + 1.0 = 2.6$.",
    difficulty: "M",
  },
  {
    stem: "A jar contains $5$ white marbles, $3$ black, and $2$ gold. Pulling a white scores $0$, black scores $5$, gold scores $20$. Expected score per pull?",
    options: ["$5.5$", "$8.33$", "$25$", "$2.5$"],
    correct: 0,
    explanation: "$0 \\cdot \\frac{5}{10} + 5 \\cdot \\frac{3}{10} + 20 \\cdot \\frac{2}{10} = 0 + 1.5 + 4 = 5.5$.",
    difficulty: "M",
  },
  {
    stem: "A quiz has $8$ true/false questions. A student guesses on every one. What is the expected number of correct answers?",
    options: ["$4$", "$2$", "$8$", "$1$"],
    correct: 0,
    explanation: "Each question: probability $0.5$ of correct. $8 \\times 0.5 = 4$.",
    difficulty: "M",
  },
  {
    stem: "A roulette-style game: the ball lands on each of $20$ colors with equal probability. Color $\\#1$ pays $\\$20$; all others pay $\\$0$. Expected payout?",
    options: ["$\\$1$", "$\\$20$", "$\\$0$", "$\\$0.05$"],
    correct: 0,
    explanation: "$20 \\cdot \\frac{1}{20} + 0 \\cdot \\frac{19}{20} = 1$.",
    difficulty: "M",
  },
  {
    stem: "An insurance company estimates that claims of $\\$5000$ will occur with probability $0.02$. What is the expected claim per policy?",
    options: ["$\\$100$", "$\\$5000$", "$\\$50$", "$\\$10$"],
    correct: 0,
    explanation: "$5000 \\cdot 0.02 = 100$.",
    difficulty: "M",
  },
  {
    stem: "A game pays $\\$15$ with probability $0.2$, $\\$5$ with probability $0.5$, and $\\$0$ with probability $0.3$. Expected payout?",
    options: ["$\\$5.50$", "$\\$6.67$", "$\\$20$", "$\\$10$"],
    correct: 0,
    explanation: "$15(0.2) + 5(0.5) + 0(0.3) = 3 + 2.5 + 0 = 5.50$.",
    difficulty: "M",
  },
  {
    stem: "A booth game costs $\\$1$. You win $\\$4$ with probability $\\frac{1}{4}$, otherwise nothing. Expected profit per play?",
    options: ["$\\$0$", "$\\$1$", "$-\\$1$", "$\\$3$"],
    correct: 0,
    explanation: "Win profit $3$, lose profit $-1$. $E = 3 \\cdot \\frac{1}{4} + (-1) \\cdot \\frac{3}{4} = 0.75 - 0.75 = 0$. Fair.",
    difficulty: "C",
  },
  {
    stem: "A deck of $20$ cards contains $5$ win-$\\$6$ cards and $15$ win-$\\$0$ cards. You draw one. Expected payout?",
    options: ["$\\$1.50$", "$\\$3$", "$\\$6$", "$\\$30$"],
    correct: 0,
    explanation: "$6 \\cdot \\frac{5}{20} + 0 \\cdot \\frac{15}{20} = 1.50$.",
    difficulty: "M",
  },
  {
    stem: "A game: win $\\$12$ with probability $0.25$, win $\\$4$ with probability $0.25$, win $\\$0$ with probability $0.5$. Expected winnings?",
    options: ["$\\$4$", "$\\$8$", "$\\$16$", "$\\$5.33$"],
    correct: 0,
    explanation: "$12(0.25) + 4(0.25) + 0(0.5) = 3 + 1 + 0 = 4$.",
    difficulty: "M",
  },
  {
    stem: "$X$ takes values $-1$ and $4$ with probabilities $0.6$ and $0.4$. Find $E(X)$.",
    options: ["$1$", "$1.5$", "$0$", "$3$"],
    correct: 0,
    explanation: "$E(X) = -1(0.6) + 4(0.4) = -0.6 + 1.6 = 1$.",
    difficulty: "M",
  },
  {
    stem: "A charity runs two games. Game A earns $\\$3$ per play on average; Game B earns $\\$7$ per play. Over $50$ plays, how much more does Game B earn than Game A?",
    options: ["$\\$200$", "$\\$50$", "$\\$100$", "$\\$400$"],
    correct: 0,
    explanation: "Difference per play: $\\$4$. Over $50$: $50 \\times 4 = \\$200$.",
    difficulty: "C",
  },
  {
    stem: "A puzzle game: $15\\%$ chance of scoring $40$, $25\\%$ chance of scoring $20$, $60\\%$ chance of scoring $0$. Expected score?",
    options: ["$11$", "$20$", "$60$", "$9$"],
    correct: 0,
    explanation: "$40(0.15) + 20(0.25) + 0(0.60) = 6 + 5 + 0 = 11$.",
    difficulty: "C",
  },
  {
    stem: "A ticket costs $\\$3$. There is a $\\frac{1}{500}$ chance of winning $\\$500$ and a $\\frac{1}{50}$ chance of winning $\\$20$. Otherwise no prize. Expected profit per ticket?",
    options: ["$-\\$1.60$", "$\\$0$", "$-\\$3$", "$\\$1.40$"],
    correct: 0,
    explanation: "$E(\\text{winnings}) = 500 \\cdot \\frac{1}{500} + 20 \\cdot \\frac{1}{50} + 0 = 1 + 0.40 = 1.40$. Profit $= 1.40 - 3 = -1.60$.",
    difficulty: "C",
  },
];

const psat89 = [
  {
    stem: "A spinner has three equal sections labeled $3$, $6$, and $9$. What is the expected value of one spin?",
    options: ["$6$", "$18$", "$9$", "$3$"],
    correct: 0,
    explanation: "Equal sections → average: $\\frac{3+6+9}{3} = 6$.",
    difficulty: "F",
  },
  {
    stem: "A fair coin is flipped. Heads scores $4$ points, tails scores $2$ points. Expected score per flip?",
    options: ["$3$", "$4$", "$2$", "$6$"],
    correct: 0,
    explanation: "$\\frac{4+2}{2} = 3$.",
    difficulty: "F",
  },
  {
    stem: "A standard six-sided die is rolled. What is the expected value?",
    options: ["$3.5$", "$3$", "$4$", "$6$"],
    correct: 0,
    explanation: "$\\frac{1+2+3+4+5+6}{6} = 3.5$.",
    difficulty: "F",
  },
  {
    stem: "A spinner has four equal sections worth $1$, $2$, $3$, and $4$ points. What is the expected value per spin?",
    options: ["$2.5$", "$10$", "$3$", "$2$"],
    correct: 0,
    explanation: "$\\frac{1+2+3+4}{4} = 2.5$.",
    difficulty: "F",
  },
  {
    stem: "$X$ equals $15$ with probability $0.2$ and $0$ with probability $0.8$. Find $E(X)$.",
    options: ["$3$", "$15$", "$7.5$", "$0.8$"],
    correct: 0,
    explanation: "$E = 15(0.2) + 0(0.8) = 3$.",
    difficulty: "F",
  },
  {
    stem: "A game costs $\\$2$. You win $\\$8$ with probability $\\frac{1}{4}$, nothing otherwise. Expected profit?",
    options: ["$\\$0$", "$\\$2$", "$-\\$2$", "$\\$6$"],
    correct: 0,
    explanation: "Win profit $6$, lose profit $-2$. $E = 6 \\cdot \\frac{1}{4} + (-2) \\cdot \\frac{3}{4} = 1.5 - 1.5 = 0$.",
    difficulty: "M",
  },
  {
    stem: "A club sells $50$ raffle tickets for $\\$4$ each. The single prize is $\\$100$. Expected profit per ticket?",
    options: ["$-\\$2$", "$\\$2$", "$-\\$4$", "$\\$0$"],
    correct: 0,
    explanation: "Win: $100 - 4 = 96$, $P = \\frac{1}{50}$. Lose: $-4$, $P = \\frac{49}{50}$. $E = \\frac{96}{50} - \\frac{196}{50} = -\\frac{100}{50} = -2$.",
    difficulty: "M",
  },
  {
    stem: "Distribution: $P(X=0)=0.6$, $P(X=4)=0.3$, $P(X=10)=0.1$. Find $E(X)$.",
    options: ["$2.2$", "$4.67$", "$14$", "$1.2$"],
    correct: 0,
    explanation: "$0(0.6) + 4(0.3) + 10(0.1) = 0 + 1.2 + 1.0 = 2.2$.",
    difficulty: "M",
  },
  {
    stem: "A bag has $4$ red, $3$ blue, and $3$ green marbles. Red scores $2$, blue scores $4$, green scores $6$. Expected score per draw?",
    options: ["$3.8$", "$4$", "$12$", "$3$"],
    correct: 0,
    explanation: "$2 \\cdot \\frac{4}{10} + 4 \\cdot \\frac{3}{10} + 6 \\cdot \\frac{3}{10} = 0.8 + 1.2 + 1.8 = 3.8$.",
    difficulty: "M",
  },
  {
    stem: "A quiz has $5$ multiple-choice questions, each with $4$ options. A student guesses randomly. Expected number correct?",
    options: ["$1.25$", "$5$", "$4$", "$2.5$"],
    correct: 0,
    explanation: "Per question: $\\frac{1}{4}$ chance. Over $5$: $5 \\cdot 0.25 = 1.25$.",
    difficulty: "M",
  },
  {
    stem: "A lucky draw: $1$ winning ticket out of $10$ pays $\\$50$, the rest pay $\\$0$. Expected payout per draw?",
    options: ["$\\$5$", "$\\$50$", "$\\$0$", "$\\$10$"],
    correct: 0,
    explanation: "$50 \\cdot \\frac{1}{10} + 0 \\cdot \\frac{9}{10} = 5$.",
    difficulty: "M",
  },
  {
    stem: "An insurance policy pays $\\$800$ with probability $0.05$ and nothing otherwise. Expected payout?",
    options: ["$\\$40$", "$\\$800$", "$\\$160$", "$\\$4$"],
    correct: 0,
    explanation: "$800 \\cdot 0.05 = 40$.",
    difficulty: "M",
  },
  {
    stem: "A game pays $\\$10$ with probability $0.3$, $\\$2$ with probability $0.5$, and $\\$0$ with probability $0.2$. Expected payout?",
    options: ["$\\$4$", "$\\$6$", "$\\$12$", "$\\$4.50$"],
    correct: 0,
    explanation: "$10(0.3) + 2(0.5) + 0(0.2) = 3 + 1 + 0 = 4$.",
    difficulty: "M",
  },
  {
    stem: "A ring toss costs $\\$1$. You win $\\$5$ with probability $\\frac{1}{5}$, otherwise nothing. Expected profit per play?",
    options: ["$\\$0$", "$\\$1$", "$-\\$1$", "$\\$4$"],
    correct: 0,
    explanation: "Win profit $4$, lose profit $-1$. $E = 4 \\cdot \\frac{1}{5} + (-1) \\cdot \\frac{4}{5} = 0.8 - 0.8 = 0$.",
    difficulty: "C",
  },
  {
    stem: "A box contains $20$ cards. $4$ win $\\$5$ each; the rest win $\\$0$. Expected payout per card drawn?",
    options: ["$\\$1$", "$\\$5$", "$\\$0.25$", "$\\$20$"],
    correct: 0,
    explanation: "$5 \\cdot \\frac{4}{20} + 0 \\cdot \\frac{16}{20} = 1$.",
    difficulty: "M",
  },
  {
    stem: "A game: win $\\$6$ with probability $0.5$, win $\\$2$ with probability $0.25$, win $\\$0$ with probability $0.25$. Expected winnings?",
    options: ["$\\$3.50$", "$\\$8$", "$\\$2.67$", "$\\$4$"],
    correct: 0,
    explanation: "$6(0.5) + 2(0.25) + 0(0.25) = 3 + 0.5 + 0 = 3.50$.",
    difficulty: "M",
  },
  {
    stem: "$X$ takes values $-3$ and $5$ with probabilities $0.7$ and $0.3$. Find $E(X)$.",
    options: ["$-0.6$", "$1$", "$2$", "$-3$"],
    correct: 0,
    explanation: "$-3(0.7) + 5(0.3) = -2.1 + 1.5 = -0.6$.",
    difficulty: "M",
  },
  {
    stem: "A charity is choosing between Game A (expected profit $\\$1$ per play) and Game B (expected profit $\\$4$ per play). Over $80$ plays, how much more will Game B earn?",
    options: ["$\\$240$", "$\\$80$", "$\\$320$", "$\\$160$"],
    correct: 0,
    explanation: "Difference per play: $\\$3$. Over $80$: $80 \\times 3 = \\$240$.",
    difficulty: "C",
  },
  {
    stem: "A puzzle rewards $30$ points $25\\%$ of the time, $10$ points $50\\%$ of the time, and $0$ points $25\\%$ of the time. Expected score?",
    options: ["$12.5$", "$13.33$", "$40$", "$8$"],
    correct: 0,
    explanation: "$30(0.25) + 10(0.5) + 0(0.25) = 7.5 + 5 + 0 = 12.5$.",
    difficulty: "C",
  },
  {
    stem: "A lottery ticket costs $\\$1$. There is a $\\frac{1}{200}$ chance of winning $\\$100$ and a $\\frac{1}{20}$ chance of winning $\\$5$. Otherwise nothing. Expected profit per ticket?",
    options: ["$-\\$0.25$", "$\\$0.75$", "$-\\$1$", "$\\$0$"],
    correct: 0,
    explanation: "$E(\\text{winnings}) = 100 \\cdot \\frac{1}{200} + 5 \\cdot \\frac{1}{20} = 0.50 + 0.25 = 0.75$. Profit $= 0.75 - 1 = -0.25$.",
    difficulty: "C",
  },
];

export default {
  skill: "expected_value",
  skillLabel: "Expected value",
  domain: "Problem Solving & Data",
  section: "math",
  batches: {
    "sat-math": sat,
    "nmsqt-math": nmsqt,
    "psat89-math": psat89,
  },
};
