// Organization — 60 questions (20 per test type)
// Each question gives a short paragraph with numbered sentences and asks
// where a new sentence belongs OR which order produces a logical paragraph.
// Objectively correct: follows pronoun/antecedent and transition-signal rules.

const sat = [
  {
    stem: "A student has drafted four sentences and wants to arrange them into a logical paragraph:\n[1] The team found that the new catalyst reduced reaction time by 40%.\n[2] However, independent labs have not yet replicated the result.\n[3] A research group at Delft University announced a breakthrough in solar cell efficiency last year.\n[4] Until replication occurs, most chemists are treating the announcement with cautious interest.\nWhich order produces the most logical paragraph?",
    options: [
      "3, 1, 2, 4",
      "1, 3, 2, 4",
      "3, 2, 1, 4",
      "2, 3, 1, 4",
    ],
    correct: 0,
    explanation: "Sentence 3 introduces the topic with no earlier reference. Sentence 1 describes the team's specific finding, so it follows 3. Sentence 2 uses 'However' to contrast the finding, so it follows 1. Sentence 4 wraps up the caution, so it comes last.",
    difficulty: "M",
  },
  {
    stem: "Where should the following sentence be added to the paragraph below?\n'As a result, the technology is still considered experimental.'\n[1] Solid-state batteries promise longer life and better safety than current lithium-ion cells. [2] Several prototypes have achieved over 2,000 charge cycles in laboratory conditions. [3] However, the manufacturing process is currently too slow for mass production, and material costs remain high. [4] Automakers and electronics companies are watching the field closely.",
    options: [
      "After sentence 3",
      "After sentence 1",
      "After sentence 2",
      "After sentence 4",
    ],
    correct: 0,
    explanation: "'As a result' needs a cause to appear immediately before it. Sentence 3 lists the causes (slow manufacturing, high costs), so the new sentence goes right after it.",
    difficulty: "M",
  },
  {
    stem: "Four sentences need to be ordered:\n[1] In fact, their singing changes based on which groups they live with.\n[2] Humpback whales produce long, complex songs that can last up to thirty minutes.\n[3] These observations suggest humpback songs may be a form of cultural transmission.\n[4] Researchers studying whale populations around Australia noticed patterns that spread through the group over time.\nWhich order produces the most logical paragraph?",
    options: [
      "2, 4, 1, 3",
      "2, 1, 4, 3",
      "4, 2, 1, 3",
      "2, 3, 4, 1",
    ],
    correct: 0,
    explanation: "Sentence 2 is the topic sentence — introduces whale songs. Sentence 4 introduces the researchers and their observation. Sentence 1 ('In fact') elaborates on how singing changes. Sentence 3 draws the conclusion.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'Its design, inspired by traditional Japanese joinery, has won awards for energy efficiency.'\n[1] Architect Mei Lin is best known for her commercial buildings in downtown Chicago. [2] Her latest project is a small library in a residential neighborhood. [3] The library opened to the public last spring. [4] Visitors have praised its warm, natural interior.",
    options: [
      "After sentence 2",
      "After sentence 1",
      "After sentence 3",
      "After sentence 4",
    ],
    correct: 0,
    explanation: "'Its design' refers to the library mentioned in sentence 2. The new sentence must come after 2 and before 3 (which then continues with when the library opened).",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] This realization led city officials to expand the number of dedicated bus lanes the following year.\n[2] For years, commuters in Bogotá had complained about gridlock on the main avenues.\n[3] A 2007 study showed that buses traveled 40% faster when they had their own lanes.\n[4] The result has been shorter commute times and higher ridership across the network.",
    options: [
      "2, 3, 1, 4",
      "3, 1, 2, 4",
      "2, 1, 3, 4",
      "1, 2, 3, 4",
    ],
    correct: 0,
    explanation: "Sentence 2 sets up the problem (gridlock). Sentence 3 presents the study finding. Sentence 1 ('This realization') responds to the finding. Sentence 4 describes the result.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'Despite this success, the method remains controversial among classical musicians.'\n[1] A new teaching method encourages children to compose their own melodies before learning to read music. [2] Students who use the method tend to perform better on both sight-reading and improvisation tests. [3] Traditionalists argue that children should master notation first, to avoid bad habits.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 3",
      "After sentence 1",
    ],
    correct: 0,
    explanation: "'Despite this success' refers to the success in sentence 2. The new sentence should follow 2 and lead into 3, which explains the controversy.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] She eventually found a position as a staff photographer at a national newspaper.\n[2] Maria Acevedo grew up in a small town in New Mexico with little access to formal art education.\n[3] Her photographs have since been exhibited in museums around the world.\n[4] Still, she taught herself photography using a camera her grandfather had given her.",
    options: [
      "2, 4, 1, 3",
      "2, 1, 4, 3",
      "4, 2, 1, 3",
      "1, 2, 4, 3",
    ],
    correct: 0,
    explanation: "Sentence 2 is the topic opener. Sentence 4 ('Still') contrasts her lack of education with her self-teaching. Sentence 1 describes her first job. Sentence 3 describes her later success.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'By contrast, the northern site showed very few such tools.'\n[1] Archaeologists excavated two sites in the same river valley last summer. [2] The southern site produced hundreds of stone tools from what appears to be a workshop. [3] This difference surprised the team, since the sites were less than a mile apart.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 3",
      "After sentence 1",
    ],
    correct: 0,
    explanation: "'By contrast' needs the first side of the contrast immediately before it. Sentence 2 describes the southern site; the new sentence describes the northern one. Then sentence 3 comments on the difference.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] Unfortunately, the heavy use has caused visible wear on the trail surface.\n[2] Park managers have proposed a timed-entry system to reduce the crowding.\n[3] The popular Redrock Canyon trail sees more than five thousand visitors on weekends.\n[4] That popularity has helped the local economy but created challenges for preservation.",
    options: [
      "3, 4, 1, 2",
      "3, 1, 4, 2",
      "4, 3, 1, 2",
      "3, 2, 4, 1",
    ],
    correct: 0,
    explanation: "Sentence 3 is the topic opener (the trail and its popularity). Sentence 4 explains both benefits and challenges. Sentence 1 ('Unfortunately') adds to the challenges. Sentence 2 is the proposed response.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'These birds can recognize individual human faces even years later.'\n[1] Researchers at the University of Washington have been studying crows since 2006. [2] They have found that crows display complex social behaviors, including grief and problem-solving. [3] This ability has forced scientists to rethink how bird memory works. [4] Crows, it turns out, are among the most intelligent animals in the bird world.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 3",
      "After sentence 4",
    ],
    correct: 0,
    explanation: "Sentence 3 ('This ability') needs the ability to be described in the sentence immediately before. The new sentence names the ability (face recognition), so it goes between 2 and 3.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] Olive oil was one of the most valuable commodities in the ancient Mediterranean.\n[2] Some were shipped as far as Britain and the Black Sea.\n[3] Archaeologists have uncovered storage jars that once held thousands of gallons.\n[4] Its value came from its role in food, medicine, and religious ceremonies.",
    options: [
      "1, 4, 3, 2",
      "1, 3, 2, 4",
      "4, 1, 3, 2",
      "1, 2, 3, 4",
    ],
    correct: 0,
    explanation: "Sentence 1 is the topic. Sentence 4 explains why it was valuable. Sentence 3 introduces the archaeology. Sentence 2 ('Some') refers to the jars in 3 and describes their range.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'For this reason, many farmers have begun planting cover crops between main crops.'\n[1] Soil erosion is a long-standing problem for farms in the region. [2] Cover crops protect the soil from wind and rain when fields would otherwise be bare. [3] Early adopters report improved soil health and higher yields in the following season.",
    options: [
      "Before sentence 2",
      "Before sentence 1",
      "After sentence 2",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'For this reason' needs the reason immediately before. Sentence 1 describes erosion as the reason. The new sentence introduces the response, and sentence 2 then explains how cover crops help.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] These tiny devices can measure air quality, temperature, and humidity in real time.\n[2] As sensor prices fall, the networks are expanding rapidly in cities worldwide.\n[3] Low-cost environmental sensors are changing how cities monitor pollution.\n[4] The resulting data helps planners target interventions where they are needed most.",
    options: [
      "3, 1, 4, 2",
      "3, 4, 1, 2",
      "1, 3, 2, 4",
      "3, 2, 1, 4",
    ],
    correct: 0,
    explanation: "Sentence 3 is the topic. Sentence 1 ('These tiny devices') describes what they do. Sentence 4 talks about the resulting data. Sentence 2 describes the expansion.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'However, the benefits disappear if the garden is not maintained.'\n[1] Community gardens have been shown to improve neighborhood morale. [2] They also provide fresh produce in areas with few grocery stores. [3] Neglected gardens quickly become overgrown eyesores that frustrate residents.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'However' contrasts the benefits listed in sentences 1-2 with the caveat. Sentence 3 then describes the neglected-garden consequence.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] The result is a lighter, stronger material that can withstand higher temperatures.\n[2] Engineers at MIT have developed a new ceramic composite.\n[3] Their breakthrough involves combining two materials that were previously thought incompatible.\n[4] Such a combination may enable next-generation jet engines.",
    options: [
      "2, 3, 1, 4",
      "2, 1, 3, 4",
      "3, 2, 1, 4",
      "2, 4, 3, 1",
    ],
    correct: 0,
    explanation: "Sentence 2 introduces the topic. Sentence 3 describes the breakthrough. Sentence 1 describes the result of that breakthrough. Sentence 4 names the application.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'To address this, the museum has installed temperature-controlled display cases throughout the exhibit.'\n[1] Ancient textiles are extremely sensitive to changes in humidity and temperature. [2] Even brief exposures can cause fading and fiber damage. [3] Visitors have praised the new setup and the richer detail it reveals.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'To address this' needs 'this' to be a problem already described. Sentences 1 and 2 describe the sensitivity. Sentence 3 ('Visitors have praised the new setup') needs the new setup to be introduced — which the new sentence does.",
    difficulty: "C",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] At first, the program served only ten children.\n[2] Now, two decades later, it enrolls more than eight hundred students every summer.\n[3] What began as a small tutoring group in 2004 has grown into a major citywide initiative.\n[4] Its founder, retired teacher Elena Moss, says the growth still surprises her.",
    options: [
      "3, 1, 2, 4",
      "1, 3, 2, 4",
      "3, 4, 1, 2",
      "4, 3, 1, 2",
    ],
    correct: 0,
    explanation: "Sentence 3 is the topic. Sentence 1 ('At first') is the beginning. Sentence 2 ('Now') is the present. Sentence 4 is the founder's reflection.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'These results have been independently confirmed by two other research groups.'\n[1] A team at Johns Hopkins reported that a new antibiotic reduced infections in hospital patients. [2] The antibiotic works by targeting bacterial cell walls in a previously unknown way. [3] Pharmaceutical companies are now racing to begin clinical trials at scale.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'These results' refers to the reported results in sentence 1. But sentence 2 describes the mechanism, which is part of the result set. Putting the new sentence after 2 (confirming the full picture) leads naturally into sentence 3 (companies racing for trials).",
    difficulty: "C",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] Those earlier models assumed the population would grow slowly for decades.\n[2] New census data tells a very different story.\n[3] City planners have long relied on demographic projections that are now outdated.\n[4] Planners are scrambling to update their long-range plans to reflect the change.",
    options: [
      "3, 1, 2, 4",
      "1, 3, 2, 4",
      "2, 3, 1, 4",
      "3, 2, 1, 4",
    ],
    correct: 0,
    explanation: "Sentence 3 is the topic opener. Sentence 1 ('Those earlier models') refers to the projections in 3. Sentence 2 introduces the new data. Sentence 4 is the response.",
    difficulty: "C",
  },
  {
    stem: "Where should this sentence go?\n'Consequently, the museum has expanded its volunteer training program.'\n[1] The small natural history museum has seen a surge in visitors over the past two years. [2] Much of the increase comes from school groups that require extra staffing. [3] Volunteers now lead most of the educational programming on weekdays.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'Consequently' needs the cause immediately before. Sentence 2 describes the increased staffing need. Sentence 3 then describes the volunteer-led programming — the result.",
    difficulty: "C",
  },
];

const nmsqt = [
  {
    stem: "Which order produces the most logical paragraph?\n[1] The discovery has already changed how paleontologists think about early bird flight.\n[2] A team in China unearthed the fossils near a riverbed in 2019.\n[3] Fossils of a previously unknown winged reptile were announced last month.\n[4] They spent three years analyzing the wing structure before publishing.",
    options: [
      "3, 2, 4, 1",
      "3, 1, 2, 4",
      "2, 3, 4, 1",
      "3, 4, 2, 1",
    ],
    correct: 0,
    explanation: "Sentence 3 is the topic. Sentence 2 describes the discovery. Sentence 4 describes the analysis. Sentence 1 is the impact.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'Because of this, the city is planning to install more cooling stations near transit stops.'\n[1] Summer heat waves have become more frequent in the metropolitan area. [2] Public health officials have documented a sharp rise in heat-related hospital visits. [3] The stations will offer free water and shaded seating for commuters.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'Because of this' needs the cause (the rise in visits) immediately before. Sentence 2 is that cause; the new sentence introduces the plan; sentence 3 describes what the plan provides.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] The new method uses sound waves to detect cracks invisible to the naked eye.\n[2] Researchers in Germany have developed a faster way to inspect bridges.\n[3] Early trials found hidden damage in two aging structures that had recently passed visual inspection.\n[4] Their findings could change how infrastructure is maintained worldwide.",
    options: [
      "2, 1, 3, 4",
      "1, 2, 3, 4",
      "2, 3, 1, 4",
      "2, 4, 1, 3",
    ],
    correct: 0,
    explanation: "Sentence 2 is the topic. Sentence 1 ('The new method') describes how it works. Sentence 3 describes the early trials. Sentence 4 is the broader impact.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'This limitation is one reason scientists are looking for alternative pollinators.'\n[1] Honeybees remain the most widely used crop pollinator in North America. [2] Colony collapse has reduced bee populations sharply over the past fifteen years. [3] Mason bees and leafcutter bees are among the most promising candidates.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'This limitation' refers to colony collapse in sentence 2. The new sentence bridges to sentence 3, which names the alternatives.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] By winter, the school had become the largest Latin grammar school in the colony.\n[2] John Harvard opened a small classroom in Cambridge in 1636.\n[3] His students at first numbered only nine.\n[4] Growth was slow but steady through the spring and summer of the following year.",
    options: [
      "2, 3, 4, 1",
      "3, 2, 4, 1",
      "2, 4, 1, 3",
      "2, 3, 1, 4",
    ],
    correct: 0,
    explanation: "Sentence 2 is the founding. Sentence 3 is the initial size. Sentence 4 is the growth. Sentence 1 is the endpoint.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'In response, librarians have begun rotating the oldest items into climate-controlled storage.'\n[1] The state archives contain documents dating back to the 1790s. [2] Humidity fluctuations in the main reading room have been damaging the oldest paper. [3] Researchers can still request access through an appointment system.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'In response' needs the problem (humidity damage) right before. The new sentence slots between 2 and 3.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] Despite the setback, the team returned the following year with better equipment.\n[2] In 2011, a research expedition set out to map part of the Greenland ice sheet.\n[3] Their first attempt was cut short by unexpectedly severe weather.\n[4] This time they were able to complete most of the survey before the season ended.",
    options: [
      "2, 3, 1, 4",
      "2, 1, 3, 4",
      "3, 2, 1, 4",
      "2, 4, 3, 1",
    ],
    correct: 0,
    explanation: "Sentence 2 is the opener. Sentence 3 is the setback. Sentence 1 ('Despite the setback') describes the return. Sentence 4 is the successful second attempt.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'These characteristics make the species especially vulnerable to habitat loss.'\n[1] The California condor is one of the largest flying birds in North America. [2] Condors mate for life and produce only one chick every two years. [3] Conservationists have raised chicks in captivity since the 1980s to boost the population.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'These characteristics' refers to the slow reproduction in sentence 2. The new sentence explains why conservation (in sentence 3) is needed.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] That project became the country's first large-scale wind farm.\n[2] Engineer Maria Costa had spent years designing efficient turbines.\n[3] In 1998, she got her chance to build one at scale.\n[4] Today, over a quarter of the nation's electricity comes from wind.",
    options: [
      "2, 3, 1, 4",
      "2, 1, 3, 4",
      "3, 2, 1, 4",
      "2, 4, 3, 1",
    ],
    correct: 0,
    explanation: "Sentence 2 is the opener. Sentence 3 is her opportunity. Sentence 1 ('That project') is the result. Sentence 4 is the long-term outcome.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'As a result, the festival has expanded to three weekends this year.'\n[1] The town's annual jazz festival has grown steadily since it began in 2010. [2] Ticket sales doubled between 2019 and 2022. [3] Organizers have already booked headliners for next summer.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'As a result' needs the growing ticket sales (sentence 2) as its cause.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] The paintings depict daily life in a fishing village that no longer exists.\n[2] Historians have used them to reconstruct clothing, tools, and even food from that era.\n[3] Art restorers discovered the paintings behind a crumbling wall.\n[4] Each painting measures less than a foot across but is extraordinarily detailed.",
    options: [
      "3, 1, 4, 2",
      "3, 4, 1, 2",
      "1, 3, 4, 2",
      "3, 2, 1, 4",
    ],
    correct: 0,
    explanation: "Sentence 3 is the discovery. Sentence 1 ('The paintings') describes their subject. Sentence 4 describes their size and detail. Sentence 2 describes the historians' use.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'For that reason, the company is now publishing its full recipes online.'\n[1] A popular snack brand built its reputation on secret ingredients. [2] Recent health concerns have led customers to ask for more transparency. [3] Industry analysts say the move will likely attract new customers.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'For that reason' needs the demand for transparency (sentence 2) as its cause.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] Once inside, the robot's camera can inspect parts that humans cannot safely reach.\n[2] A newly developed inspection robot is small enough to crawl through pipes.\n[3] Nuclear plants have begun using the technology to check reactor cooling systems.\n[4] Its findings are already helping plant operators schedule maintenance more efficiently.",
    options: [
      "2, 1, 3, 4",
      "2, 3, 1, 4",
      "1, 2, 3, 4",
      "2, 4, 1, 3",
    ],
    correct: 0,
    explanation: "Sentence 2 is the topic. Sentence 1 describes what the robot does. Sentence 3 is the application. Sentence 4 is the result.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'However, not every species benefits equally from the return of the wolves.'\n[1] When wolves were reintroduced to Yellowstone in 1995, elk populations began to fall. [2] This allowed willows and aspens to recover along riverbanks. [3] Beavers have especially benefited from the restored vegetation.",
    options: [
      "After sentence 3",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 2",
    ],
    correct: 0,
    explanation: "'However' signals a contrast with the benefits described in sentences 2-3. The new sentence should go after 3 to pivot away from the benefits.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] In the end, most of the gold was recovered and returned to the museum.\n[2] In 1987, thieves broke into a small history museum in Cairo.\n[3] Investigators tracked them across three countries before making arrests.\n[4] They took several ancient coins and a gold pendant before fleeing.",
    options: [
      "2, 4, 3, 1",
      "2, 3, 4, 1",
      "4, 2, 3, 1",
      "2, 1, 4, 3",
    ],
    correct: 0,
    explanation: "Sentence 2 is the break-in. Sentence 4 describes what was stolen. Sentence 3 is the investigation. Sentence 1 is the resolution.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'To meet the demand, local farms have increased planting by 30% this year.'\n[1] Interest in locally grown produce has risen sharply in the region. [2] Farmers' markets now operate in nearly every town. [3] Some markets have had to add a second day each week to handle the crowds.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'To meet the demand' refers to the demand described in sentences 1-2. The new sentence fits after 2 (where the demand has been established) and leads into 3 (the handling of crowds).",
    difficulty: "C",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] The bakery's original recipes, written by the founder in 1920, hang framed on the back wall.\n[2] The Santos family has run a bakery in the same neighborhood for four generations.\n[3] Today, the great-grandchildren of the founder still use those recipes every day.\n[4] Customers say they can taste the continuity in every loaf.",
    options: [
      "2, 1, 3, 4",
      "1, 2, 3, 4",
      "2, 3, 1, 4",
      "2, 4, 1, 3",
    ],
    correct: 0,
    explanation: "Sentence 2 is the opener. Sentence 1 ('The bakery's original recipes') describes what's on the wall. Sentence 3 describes current use. Sentence 4 is the customer view.",
    difficulty: "C",
  },
  {
    stem: "Where should this sentence go?\n'This change has prompted the museum to hire two additional security staff.'\n[1] Visitor numbers at the Brooklyn Art Museum have risen steadily for three years. [2] The new exhibit on modern photography drew record crowds last month. [3] Long lines have become a feature of weekend afternoons.",
    options: [
      "After sentence 3",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 2",
    ],
    correct: 0,
    explanation: "'This change' refers to the growing crowds described through sentence 3. Putting the hiring after sentence 3 makes the cause-effect clearest.",
    difficulty: "C",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] At first, the device could only recognize five words.\n[2] A research team began work on a speech-recognition system in 1980.\n[3] Today, their successors power smart speakers in millions of homes.\n[4] Over the next thirty years, the technology improved steadily in both speed and accuracy.",
    options: [
      "2, 1, 4, 3",
      "2, 4, 1, 3",
      "1, 2, 4, 3",
      "2, 3, 1, 4",
    ],
    correct: 0,
    explanation: "Sentence 2 is the start. Sentence 1 ('At first') is the early capability. Sentence 4 is the gradual improvement. Sentence 3 is the present state.",
    difficulty: "C",
  },
  {
    stem: "Where should this sentence go?\n'As a result, the town now draws birdwatchers from several states each spring.'\n[1] The small town of Riverton was once best known for its dairy farms. [2] Conservation work in the 1990s restored wetlands just outside of town. [3] Over a hundred bird species now nest or stop over in the restored habitat.",
    options: [
      "After sentence 3",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 2",
    ],
    correct: 0,
    explanation: "'As a result' needs the cause (the bird species) immediately before. Sentence 3 describes the species; the new sentence describes the resulting birdwatchers.",
    difficulty: "C",
  },
];

const psat89 = [
  {
    stem: "Which order produces the most logical paragraph?\n[1] The recipe has been handed down through five generations.\n[2] Every summer, Mia's family bakes a blueberry pie for the neighborhood picnic.\n[3] Mia says the crust is the most important part.\n[4] It originally came from her great-great-grandmother, who learned it from a neighbor.",
    options: [
      "2, 1, 4, 3",
      "1, 2, 4, 3",
      "2, 3, 1, 4",
      "3, 2, 1, 4",
    ],
    correct: 0,
    explanation: "Sentence 2 is the topic. Sentence 1 ('The recipe') describes its history. Sentence 4 gives its origin. Sentence 3 is Mia's personal comment.",
    difficulty: "F",
  },
  {
    stem: "Where should this sentence go?\n'Because of the wet spring, the team is expecting a large harvest.'\n[1] Apple orchards cover the hills east of town. [2] Most of the trees were planted over a decade ago. [3] Visitors can pick apples from early September through late October.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "The new sentence introduces an expected harvest that logically precedes sentence 3 (when visitors pick). It's specific to growing conditions, so it fits after the background in sentence 2.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] Still, she plans to try the course again next spring.\n[2] Leslie took a beginner's pottery class last summer.\n[3] Her first few attempts collapsed on the wheel.\n[4] She enjoyed the class enough that she bought her own clay to practice at home.",
    options: [
      "2, 3, 4, 1",
      "2, 4, 3, 1",
      "3, 2, 4, 1",
      "2, 1, 3, 4",
    ],
    correct: 0,
    explanation: "Sentence 2 is the opener. Sentence 3 describes the early struggles. Sentence 4 shows her enthusiasm. Sentence 1 ('Still') adds the plan to continue.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'However, many classic books were never made available as e-books.'\n[1] Digital reading has become popular over the past decade. [2] Many readers now prefer tablets or e-readers to physical books. [3] Libraries have had to keep physical copies of these older titles.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'However' contrasts the popularity of digital reading (1-2) with the gap in older titles. Sentence 3 then explains the library response.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] The new bike lane stretches from the park to the library.\n[2] City officials cut the ribbon on the project last Friday.\n[3] Commuters and families have already started using it on weekends.\n[4] Plans are now underway to extend the lane south toward the river.",
    options: [
      "2, 1, 3, 4",
      "1, 2, 3, 4",
      "2, 4, 1, 3",
      "2, 3, 1, 4",
    ],
    correct: 0,
    explanation: "Sentence 2 is the opener. Sentence 1 ('The new bike lane') describes it. Sentence 3 is current use. Sentence 4 is the next step.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'For this reason, the town is considering an after-school program at the community center.'\n[1] Many parents in town work long hours. [2] Children often wait at home alone until a parent returns. [3] The program would offer supervised homework time and snacks.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'For this reason' needs the problem (children alone after school) immediately before. Sentence 3 then describes what the program offers.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] These jars are often used to store pickles and jams.\n[2] Glass canning jars have a long history in American kitchens.\n[3] The Mason jar, patented in 1858, is still the most common style today.\n[4] Modern versions come with sealed lids that let food last for years.",
    options: [
      "2, 3, 1, 4",
      "2, 1, 3, 4",
      "3, 2, 4, 1",
      "2, 4, 1, 3",
    ],
    correct: 0,
    explanation: "Sentence 2 is the topic. Sentence 3 introduces the Mason jar. Sentence 1 ('These jars') describes use. Sentence 4 describes modern versions.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'As a result, the club now meets every other Saturday morning.'\n[1] The neighborhood birdwatching club was founded in 2021. [2] Attendance grew so quickly that members could barely fit in the original meeting space. [3] Members now rotate between two parks to accommodate everyone.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'As a result' needs the growing attendance (sentence 2) as its cause. The new sentence bridges 2 and 3.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] On his first morning, he learned to greet customers in both English and Spanish.\n[2] Diego started his summer job at the grocery store in June.\n[3] By August, he was training new hires himself.\n[4] He quickly moved from bagging groceries to running a register.",
    options: [
      "2, 1, 4, 3",
      "2, 3, 4, 1",
      "1, 2, 4, 3",
      "2, 4, 3, 1",
    ],
    correct: 0,
    explanation: "Sentence 2 is the start. Sentence 1 is the first day. Sentence 4 is his progression. Sentence 3 is the culmination.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'This caused the science fair to be rescheduled for the following Monday.'\n[1] A strong thunderstorm rolled through town on Friday afternoon. [2] The power went out for more than four hours at the middle school. [3] Students finished their projects at home over the weekend.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'This' refers to the power outage in sentence 2. The new sentence bridges 2 and 3.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] The pair of otters spent most of the morning wrestling in the shallow water.\n[2] A family visited the aquarium last weekend.\n[3] The children especially enjoyed the otter exhibit.\n[4] By the time the family left, both kids were asking to come back.",
    options: [
      "2, 3, 1, 4",
      "2, 1, 3, 4",
      "3, 2, 1, 4",
      "2, 4, 3, 1",
    ],
    correct: 0,
    explanation: "Sentence 2 is the opener. Sentence 3 is the children's favorite. Sentence 1 ('The pair of otters') describes what they saw. Sentence 4 is the conclusion.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'This has prompted volunteers to organize weekend cleanup events.'\n[1] The community park has become a popular gathering spot on weekends. [2] Unfortunately, litter has become a growing problem there. [3] So far, volunteers have filled dozens of bags at each cleanup.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'This' refers to the litter problem in sentence 2. The new sentence then leads into sentence 3's description of the cleanups.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] Her paintings now hang in two local galleries.\n[2] Samantha has loved drawing since she was a young child.\n[3] In high school, she discovered oil painting during an art class.\n[4] She says she is finally painting the landscapes she dreamed of as a kid.",
    options: [
      "2, 3, 1, 4",
      "2, 1, 3, 4",
      "3, 2, 1, 4",
      "2, 4, 3, 1",
    ],
    correct: 0,
    explanation: "Sentence 2 is the opener. Sentence 3 is the discovery. Sentence 1 is the present. Sentence 4 is her reflection.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'To address this, the school has installed new LED lights in every classroom.'\n[1] The aging fluorescent lights at Lincoln Middle School were expensive to run. [2] Teachers also complained that the bulbs flickered and buzzed throughout the day. [3] Early reports say the new lights are much quieter and brighter.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'To address this' needs the complaints (sentence 2) immediately before. Sentence 3 then reports the result.",
    difficulty: "M",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] His first time riding the subway alone was nerve-wracking.\n[2] When Jayden moved to the city, he had never used public transit before.\n[3] Now he rides the train to school and work every day without a second thought.\n[4] Over the next few weeks, he learned which lines to take and when to transfer.",
    options: [
      "2, 1, 4, 3",
      "2, 4, 3, 1",
      "1, 2, 4, 3",
      "2, 3, 1, 4",
    ],
    correct: 0,
    explanation: "Sentence 2 is the opener. Sentence 1 is his first experience. Sentence 4 is the learning period. Sentence 3 is his current routine.",
    difficulty: "M",
  },
  {
    stem: "Where should this sentence go?\n'For that reason, the team has begun tracking the water level weekly.'\n[1] The small pond at the nature preserve supports dozens of frog and fish species. [2] Recent dry summers have lowered the water level significantly. [3] The weekly measurements will help rangers respond quickly if the pond drops further.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'For that reason' needs the cause (falling water level in sentence 2). The new sentence bridges 2 and 3.",
    difficulty: "C",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] Some of the posters are more than fifty years old.\n[2] The old movie theater downtown has a collection of vintage posters lining the lobby.\n[3] Visitors often stop to take photos of the rarest ones.\n[4] The theater's owner says the collection has become part of the experience.",
    options: [
      "2, 1, 3, 4",
      "1, 2, 3, 4",
      "2, 3, 1, 4",
      "2, 4, 1, 3",
    ],
    correct: 0,
    explanation: "Sentence 2 is the topic. Sentence 1 ('Some of the posters') describes their age. Sentence 3 is visitor behavior. Sentence 4 is the owner's reflection.",
    difficulty: "C",
  },
  {
    stem: "Where should this sentence go?\n'Consequently, the store has added an online ordering system to speed up pickups.'\n[1] A popular deli downtown has seen its lunch crowds grow each month. [2] Customers often waited in line for twenty minutes or more to place an order. [3] Early users of the online system say their pickup times have been cut in half.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'Consequently' needs the long wait (sentence 2) as its cause. The new sentence bridges 2 and 3.",
    difficulty: "C",
  },
  {
    stem: "Which order produces the most logical paragraph?\n[1] At first, the dog was too shy to approach strangers.\n[2] The Martinez family adopted a rescue dog last winter.\n[3] Today, she greets every visitor with a wagging tail.\n[4] Patient training and daily walks slowly built her confidence.",
    options: [
      "2, 1, 4, 3",
      "2, 4, 1, 3",
      "1, 2, 4, 3",
      "2, 3, 1, 4",
    ],
    correct: 0,
    explanation: "Sentence 2 is the opener. Sentence 1 ('At first') is the initial state. Sentence 4 is the training. Sentence 3 is the result.",
    difficulty: "C",
  },
  {
    stem: "Where should this sentence go?\n'Because of this growing interest, a second beekeeping class has been added.'\n[1] The city offers free classes on urban gardening each spring. [2] This year's surprise hit has been the class on keeping backyard bees. [3] The new session will meet on Thursday evenings starting in May.",
    options: [
      "After sentence 2",
      "Before sentence 1",
      "After sentence 1",
      "After sentence 3",
    ],
    correct: 0,
    explanation: "'Because of this growing interest' needs 'this interest' defined immediately before — the surprise hit described in sentence 2. Sentence 3 then gives details about the added session.",
    difficulty: "C",
  },
];

export default {
  skill: "organization",
  skillLabel: "Organization and logical flow",
  domain: "Expression of Ideas",
  section: "rw",
  batches: {
    "sat-rw": sat,
    "nmsqt-rw": nmsqt,
    "psat89-rw": psat89,
  },
};
