// Parallelism — 60 questions (20 per test type)

const FORMAT = "Which choice completes the text so that it conforms to the conventions of Standard English?";

const sat = [
  {
    stem: `${FORMAT}\n\nTo prepare for the marathon, Daniel trained four days a week, kept a strict diet, and ______`,
    options: ["slept eight hours each night.", "was getting enough sleep.", "sleeping was important to him.", "sleep was a priority."],
    correct: 0,
    explanation: "The list is past-tense verb phrases ('trained,' 'kept'). The third item has to match: 'slept eight hours each night.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe professor advised her students not only to attend every lecture but also ______`,
    options: ["to take detailed notes.", "that they should take detailed notes.", "they needed to take detailed notes.", "taking detailed notes."],
    correct: 0,
    explanation: "'Not only X but also Y' needs parallel forms. 'To attend' is an infinitive, so 'to take detailed notes' must also be an infinitive.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nShe enjoys hiking in the mountains, swimming in the lake, and ______`,
    options: ["biking along the river trail.", "to bike along the river trail.", "she bikes along the river trail.", "biked along the river trail."],
    correct: 0,
    explanation: "The list is gerunds ('hiking,' 'swimming'). Match with 'biking.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe coach praised the team for their effort, their communication, and ______`,
    options: ["their teamwork.", "how well they worked together.", "that they worked as a team.", "working as a team."],
    correct: 0,
    explanation: "The list is noun phrases with 'their' ('their effort,' 'their communication'). Match with 'their teamwork.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe new policy will increase funding for libraries, reduce class sizes, and ______`,
    options: ["improve teacher training.", "teacher training will be improved.", "improving teacher training.", "to improve teacher training."],
    correct: 0,
    explanation: "The list is base-verb phrases ('increase,' 'reduce'). Match: 'improve teacher training.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nWriting in the morning is more productive for me than ______`,
    options: ["writing at night.", "to write at night.", "I write at night.", "writing during the night hours."],
    correct: 0,
    explanation: "Compare a gerund ('writing in the morning') with a gerund ('writing at night').",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nMy grandmother was both a talented musician and ______`,
    options: ["a dedicated teacher.", "taught many students.", "teaching her grandchildren.", "she taught history."],
    correct: 0,
    explanation: "'Both X and Y' must be parallel. 'A talented musician' is a noun phrase; match with 'a dedicated teacher.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe architect's new building is striking for its bold lines, its dramatic lighting, and ______`,
    options: ["its unusual materials.", "using unusual materials.", "it uses unusual materials.", "unusual materials being used."],
    correct: 0,
    explanation: "The list is 'its X, its Y, and its Z.' Match the pattern.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNeither the cost of the repairs nor ______ discouraged the homeowners from restoring the old barn.`,
    options: ["the difficulty of the work", "working hard at the project", "that the work was difficult", "to work on the project"],
    correct: 0,
    explanation: "'Neither X nor Y' needs parallel forms. 'The cost of the repairs' is a noun phrase; match with 'the difficulty of the work.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nA good presentation requires preparing your material carefully, practicing your delivery, and ______`,
    options: ["engaging with your audience.", "to engage with your audience.", "that you engage with your audience.", "engagement with the audience."],
    correct: 0,
    explanation: "The list is gerunds. Match 'engaging.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe vacation was relaxing not only because of the beautiful scenery but also ______`,
    options: ["because of the friendly people.", "friendly people were there.", "the people were friendly.", "of how friendly the people were."],
    correct: 0,
    explanation: "'Not only because of X but also because of Y.' Match: 'because of the friendly people.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe job requires strong writing skills, attention to detail, and ______`,
    options: ["the ability to work independently.", "being able to work independently.", "that you can work independently.", "working on your own."],
    correct: 0,
    explanation: "The list is noun phrases. Match 'the ability to work independently.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nHe preferred to read rather than ______`,
    options: ["to watch television.", "watching television.", "television viewing.", "he watched television."],
    correct: 0,
    explanation: "'Rather than' with 'to read' (infinitive) needs an infinitive on the other side: 'to watch television.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe new employee is hardworking, detail-oriented, and ______`,
    options: ["enthusiastic.", "shows enthusiasm.", "has enthusiasm.", "enthusiasm is evident."],
    correct: 0,
    explanation: "The list is adjectives ('hardworking,' 'detail-oriented'). Match: adjective 'enthusiastic.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nEither the principal or ______ will attend the parent meeting.`,
    options: ["one of the teachers", "teachers will be there", "will a teacher go", "they are going to send a teacher"],
    correct: 0,
    explanation: "'Either X or Y' must be parallel. 'The principal' is a noun phrase; match with 'one of the teachers.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe students learned how to formulate a hypothesis, how to design an experiment, and ______`,
    options: ["how to analyze the results.", "analyzing the results.", "that they should analyze the results.", "the analysis of results."],
    correct: 0,
    explanation: "The list is 'how to X' phrases. Match: 'how to analyze the results.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe chef is known for using local ingredients, creating unusual flavor combinations, and ______`,
    options: ["presenting dishes beautifully.", "beautiful presentation.", "beautifully presents her dishes.", "to present dishes beautifully."],
    correct: 0,
    explanation: "The list is gerund phrases ('using,' 'creating'). Match: 'presenting.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe tour guide spoke about the history of the building, explained its architectural features, and ______`,
    options: ["answered visitors' questions.", "visitors had questions answered.", "answering visitors' questions.", "the questions were answered."],
    correct: 0,
    explanation: "The list is past-tense verb phrases. Match: 'answered visitors' questions.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe author's novels are known for ______ than for their intricate plots.`,
    options: ["their vivid characters more", "their vivid characters more so", "the vividness of their characters more", "having more vivid characters"],
    correct: 0,
    explanation: "'For X more than for Y' requires parallel 'for' phrases. 'For their vivid characters more... than for their intricate plots.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe workshop covered how to write a résumé, how to prepare for interviews, and ______`,
    options: ["how to negotiate a salary.", "negotiating a salary.", "salary negotiation.", "that you should negotiate a salary."],
    correct: 0,
    explanation: "The list is 'how to X' phrases. Match: 'how to negotiate a salary.'",
    difficulty: "M",
  },
];

const nmsqt = [
  {
    stem: `${FORMAT}\n\nDuring the summer, the children spent their time swimming, biking, and ______`,
    options: ["playing in the park.", "to play in the park.", "they played in the park.", "the park was their play area."],
    correct: 0,
    explanation: "The list is gerunds. Match: 'playing in the park.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe program aims both to teach coding basics and ______`,
    options: ["to introduce students to real-world applications.", "introducing students to real-world applications.", "students are introduced to real-world applications.", "real-world applications will be introduced."],
    correct: 0,
    explanation: "'Both X and Y' must be parallel. 'To teach' (infinitive) → 'to introduce' (infinitive).",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nShe packed warm clothes, waterproof boots, and ______`,
    options: ["a sturdy backpack.", "brought a sturdy backpack.", "she took a sturdy backpack.", "a backpack she could count on."],
    correct: 0,
    explanation: "The list is noun phrases. Match: 'a sturdy backpack.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe committee commended the volunteers for their generosity, their dedication, and ______`,
    options: ["their patience.", "being patient.", "how patient they were.", "they were patient."],
    correct: 0,
    explanation: "The list is 'their X' noun phrases. Match: 'their patience.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe new law will expand health care, raise the minimum wage, and ______`,
    options: ["protect voting rights.", "voting rights will be protected.", "protecting voting rights.", "to protect voting rights."],
    correct: 0,
    explanation: "The list is base-verb phrases. Match: 'protect voting rights.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nLearning a new language in a classroom is more difficult for some students than ______`,
    options: ["learning one from everyday conversation.", "to learn one from everyday conversation.", "learning from everyday conversations is for them.", "everyday conversations."],
    correct: 0,
    explanation: "Compare a gerund ('learning') with a gerund ('learning').",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nHer older brother is both an accomplished pianist and ______`,
    options: ["a skilled carpenter.", "he builds things as well.", "works as a carpenter.", "carpentry is his other trade."],
    correct: 0,
    explanation: "'Both X and Y' needs parallel noun phrases. 'An accomplished pianist' → 'a skilled carpenter.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe report praised the city's improved transit, its cleaner air, and ______`,
    options: ["its lower crime rates.", "crime rates that are lower.", "because crime rates have fallen.", "falling crime rates."],
    correct: 0,
    explanation: "The list is 'its X' phrases. Match: 'its lower crime rates.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNeither the cost of the materials nor ______ kept the carpenter from finishing the project.`,
    options: ["the complexity of the design", "designing it was complex", "because the design was complex", "a complex design"],
    correct: 0,
    explanation: "'Neither X nor Y' needs parallel noun phrases. 'The cost of the materials' → 'the complexity of the design.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nSuccessful gardening requires watering regularly, checking for pests, and ______`,
    options: ["pruning overgrown branches.", "to prune overgrown branches.", "that you prune overgrown branches.", "overgrown branches need pruning."],
    correct: 0,
    explanation: "The list is gerund phrases. Match: 'pruning.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe students protested not only because of the tuition hike but also ______`,
    options: ["because of the cuts to financial aid.", "financial aid was cut.", "cuts were made to financial aid.", "of how the financial aid was cut."],
    correct: 0,
    explanation: "'Not only because of X but also because of Y.' Match: 'because of the cuts to financial aid.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe teacher values creative thinking, hard work, and ______`,
    options: ["honest effort.", "being honest.", "students who are honest.", "to be honest."],
    correct: 0,
    explanation: "The list is noun phrases. Match: 'honest effort.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nShe would rather hike through the forest than ______`,
    options: ["bike along the highway.", "biking along the highway.", "to bike along the highway.", "she bikes on the highway."],
    correct: 0,
    explanation: "'Rather ... than' with base-verb 'hike' needs base-verb on the other side: 'bike.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe new coach is patient, encouraging, and ______`,
    options: ["knowledgeable.", "has knowledge.", "she knows a lot.", "knowing a great deal."],
    correct: 0,
    explanation: "List is adjectives. Match: 'knowledgeable.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nEither my mother or ______ will pick me up from the airport.`,
    options: ["my older sister", "my older sister is going to come", "will my sister get me", "they will send my sister"],
    correct: 0,
    explanation: "'Either X or Y.' 'My mother' is a noun phrase; match with 'my older sister.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe class learned how to identify primary sources, how to evaluate bias, and ______`,
    options: ["how to cite them correctly.", "citing them correctly.", "the correct citation method.", "that they should cite correctly."],
    correct: 0,
    explanation: "List is 'how to X.' Match: 'how to cite them correctly.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe chef demonstrated slicing vegetables, searing the meat, and ______`,
    options: ["plating the dish.", "to plate the dish.", "the dish being plated.", "that the dish should be plated."],
    correct: 0,
    explanation: "List is gerund phrases. Match: 'plating.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe guide described the park's wildlife, explained its history, and ______`,
    options: ["pointed out notable trees.", "notable trees were pointed out.", "pointing out notable trees.", "the notable trees."],
    correct: 0,
    explanation: "List is past-tense verb phrases. Match: 'pointed out notable trees.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe filmmaker is celebrated ______ than for her innovative storytelling.`,
    options: ["more for her visual style", "more so for her visual style", "for her visual style more", "for the visual style she has more"],
    correct: 0,
    explanation: "'More for X than for Y.' The correct phrasing is 'more for her visual style than for her innovative storytelling.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe course covered how to conduct interviews, how to take field notes, and ______`,
    options: ["how to write up findings.", "the writing up of findings.", "findings to be written up.", "writing up of the findings."],
    correct: 0,
    explanation: "List is 'how to X.' Match: 'how to write up findings.'",
    difficulty: "M",
  },
];

const psat89 = [
  {
    stem: `${FORMAT}\n\nOn weekends, Mia likes reading, painting, and ______`,
    options: ["walking in the park.", "to walk in the park.", "she walks in the park.", "walks in the park."],
    correct: 0,
    explanation: "List is gerunds. Match: 'walking in the park.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe plan is both to raise money and ______`,
    options: ["to raise awareness.", "raising awareness.", "awareness needs to be raised.", "for awareness to be raised."],
    correct: 0,
    explanation: "'Both X and Y' parallel: 'to raise money' / 'to raise awareness.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe kit contained bandages, scissors, and ______`,
    options: ["antiseptic wipes.", "antiseptic wipes were in it too.", "it had antiseptic wipes.", "the antiseptic wipes that were inside."],
    correct: 0,
    explanation: "List is noun phrases. Match: 'antiseptic wipes.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe principal thanked the volunteers for their time, their effort, and ______`,
    options: ["their enthusiasm.", "being enthusiastic.", "that they were enthusiastic.", "how they were enthusiastic."],
    correct: 0,
    explanation: "List is 'their X.' Match: 'their enthusiasm.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe proposal will build new schools, repair old roads, and ______`,
    options: ["add more parks.", "more parks will be added.", "adding more parks.", "to add more parks."],
    correct: 0,
    explanation: "List is base-verb phrases. Match: 'add more parks.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nTraveling by train is easier for some people than ______`,
    options: ["driving a car.", "to drive a car.", "by driving a car.", "that they drive a car."],
    correct: 0,
    explanation: "Compare gerund 'traveling' with gerund 'driving.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nMy uncle is both a gardener and ______`,
    options: ["a handyman.", "can fix things.", "fixes things around the house.", "good at fixing things."],
    correct: 0,
    explanation: "'Both X and Y' parallel: 'a gardener' / 'a handyman.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe brochure described the park's hiking trails, its picnic areas, and ______`,
    options: ["its camping grounds.", "where to camp.", "camping was allowed.", "a place to go camping."],
    correct: 0,
    explanation: "List is 'its X.' Match: 'its camping grounds.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNeither the cost of the uniform nor ______ kept Juan from joining the team.`,
    options: ["the long practice hours", "that practice was long", "practicing for long hours", "having to practice for long hours"],
    correct: 0,
    explanation: "'Neither X nor Y' parallel: 'the cost of the uniform' / 'the long practice hours.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nLearning to drive requires practicing regularly, staying calm, and ______`,
    options: ["following the rules of the road.", "to follow the rules of the road.", "that you follow the rules.", "the rules of the road being followed."],
    correct: 0,
    explanation: "List is gerund phrases. Match: 'following.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe students were excited not only because of the trip but also ______`,
    options: ["because of the free meals.", "free meals were included.", "since free meals came with it.", "meals that were free."],
    correct: 0,
    explanation: "'Not only because of X but also because of Y.' Match: 'because of the free meals.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe summer job required strength, patience, and ______`,
    options: ["attention to detail.", "being attentive.", "that you paid attention.", "paying careful attention."],
    correct: 0,
    explanation: "List is noun phrases. Match: 'attention to detail.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nHe prefers to walk to school rather than ______`,
    options: ["to ride the bus.", "riding the bus.", "he rides the bus.", "the bus ride."],
    correct: 0,
    explanation: "'Rather than' with 'to walk' (infinitive) needs 'to ride' (infinitive).",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe kitten is small, curious, and ______`,
    options: ["playful.", "likes to play.", "it loves playing.", "playing a lot."],
    correct: 0,
    explanation: "List is adjectives. Match: 'playful.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nEither Mr. Patel or ______ will lead the tour tomorrow.`,
    options: ["Ms. Jensen", "Ms. Jensen will lead", "will Ms. Jensen lead", "the one leading will be Ms. Jensen"],
    correct: 0,
    explanation: "'Either X or Y' needs parallel noun phrases: 'Mr. Patel' / 'Ms. Jensen.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe students learned how to solve equations, how to graph functions, and ______`,
    options: ["how to interpret results.", "interpreting results.", "that interpretation is key.", "results that they interpret."],
    correct: 0,
    explanation: "List is 'how to X.' Match: 'how to interpret results.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe musician is known for writing catchy tunes, singing with emotion, and ______`,
    options: ["playing multiple instruments.", "she plays multiple instruments.", "to play multiple instruments.", "multiple instruments are played."],
    correct: 0,
    explanation: "List is gerund phrases. Match: 'playing multiple instruments.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe ranger pointed out the deer, described the river, and ______`,
    options: ["warned us about bears.", "bears were a danger.", "warning us about bears.", "the bear warning."],
    correct: 0,
    explanation: "List is past-tense verb phrases. Match: 'warned us about bears.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe artist is celebrated more for her use of color than ______`,
    options: ["for her choice of subjects.", "her choice of subjects.", "because of her subjects.", "how she chose subjects."],
    correct: 0,
    explanation: "'More for X than for Y.' Match: 'for her choice of subjects.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe class covered how to write a summary, how to outline an essay, and ______`,
    options: ["how to revise a draft.", "revising a draft.", "draft revision.", "how you can revise a draft."],
    correct: 0,
    explanation: "List is 'how to X.' Match: 'how to revise a draft.'",
    difficulty: "M",
  },
];

export default {
  skill: "parallelism",
  skillLabel: "Parallel structure",
  domain: "Standard English Conventions",
  section: "rw",
  batches: {
    "sat-rw": sat,
    "nmsqt-rw": nmsqt,
    "psat89-rw": psat89,
  },
};
