// Point of view — 60 questions (20 per test type)
// Each question gives a short passage or quoted description, then asks
// the student to pick the option that most accurately names the speaker's
// stance. Objectively correct answers.

const sat = [
  {
    stem: "A science journalist describes a new vaccine as 'promising' but adds that 'long-term data is still being collected and early enthusiasm should be tempered until results are replicated.' Which best describes the journalist's point of view?",
    options: [
      "Cautiously optimistic — interested in the technology but unwilling to draw firm conclusions yet.",
      "Entirely enthusiastic, with no reservations.",
      "Openly hostile toward the vaccine.",
      "Neutral, with no evaluative stance.",
    ],
    correct: 0,
    explanation: "'Promising' is positive; 'tempered' signals caution. The writer is cautiously optimistic.",
    difficulty: "F",
  },
  {
    stem: "Professor Alvarez calls a colleague's proposal 'creative in its framing but unworkable in practice due to unrealistic cost estimates.' Which best describes Alvarez's point of view toward the proposal?",
    options: [
      "Appreciative of the design but doubtful of its feasibility.",
      "Fully supportive of both the design and the implementation plan.",
      "Entirely dismissive of the proposal.",
      "Neutral, without evaluating it.",
    ],
    correct: 0,
    explanation: "'Creative in framing' is praise; 'unworkable in practice' is criticism of feasibility. Mixed: admires design, doubts feasibility.",
    difficulty: "M",
  },
  {
    stem: "A historian writes that an old theory of revolution 'has been repeatedly shown to rest on misread evidence and should be abandoned by serious scholars.' Which best describes the historian's point of view?",
    options: [
      "Firmly dismissive of the theory.",
      "Cautious but mostly supportive.",
      "Neutral and analytical.",
      "Fully enthusiastic about the theory.",
    ],
    correct: 0,
    explanation: "'Misread evidence' and 'should be abandoned' are strong rejections. The stance is firmly dismissive.",
    difficulty: "M",
  },
  {
    stem: "A critic calls a new novel 'ambitious but ultimately weighed down by its own length and the author's reluctance to cut a single subplot.' Which best describes the critic's point of view?",
    options: [
      "Respectful of the novel's ambition but disappointed by its execution.",
      "Enthusiastic praise.",
      "Outright dismissal.",
      "Neutral, neither praise nor criticism.",
    ],
    correct: 0,
    explanation: "'Ambitious' is positive; 'weighed down' and 'reluctance to cut' are negative criticism of craft. Mixed: admires intent, disappointed in execution.",
    difficulty: "M",
  },
  {
    stem: "An economist says the tax reform 'will likely generate growth in the short term, but its long-term effects on inequality remain deeply concerning.' Which best describes the economist's point of view?",
    options: [
      "Partly supportive and partly worried — positive short-term, negative long-term.",
      "Entirely supportive.",
      "Entirely opposed.",
      "Indifferent to the reform.",
    ],
    correct: 0,
    explanation: "'Generate growth' is positive short-term; 'deeply concerning' is negative long-term. Mixed stance.",
    difficulty: "M",
  },
  {
    stem: "A teacher writes that a new curriculum 'accomplishes its stated goals and is a clear improvement over the previous edition, though the teacher's guide could use more examples.' Which best describes her point of view?",
    options: [
      "Strongly positive overall, with a minor criticism.",
      "Mostly negative.",
      "Strictly neutral.",
      "Entirely dismissive.",
    ],
    correct: 0,
    explanation: "'Clear improvement' is strong praise; 'could use more examples' is a small criticism. Mostly positive with a minor concern.",
    difficulty: "M",
  },
  {
    stem: "A researcher notes that the field 'has made enormous progress in the last decade' but warns that 'replication rates remain troubling and more rigorous standards are needed.' Which best describes her point of view?",
    options: [
      "Encouraged by the progress but worried about the rigor of the evidence.",
      "Entirely enthusiastic.",
      "Entirely pessimistic.",
      "Neutral and detached.",
    ],
    correct: 0,
    explanation: "'Enormous progress' is positive; 'troubling' and 'more rigorous standards needed' are critical. Mixed stance.",
    difficulty: "M",
  },
  {
    stem: "A reviewer describes a concert as 'technically flawless but emotionally flat — every note was in place, yet none of them seemed to matter.' Which best describes the reviewer's point of view?",
    options: [
      "Impressed by the technique but disappointed by the lack of feeling.",
      "Unreservedly enthusiastic.",
      "Completely dismissive of the performance.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Technically flawless' is positive; 'emotionally flat' is negative. Split along technique vs. feeling.",
    difficulty: "M",
  },
  {
    stem: "A biologist calls a rival team's data 'intriguing and clearly worth following up on, though the sample size is too small for firm conclusions.' Which best describes her point of view?",
    options: [
      "Intrigued by the finding but hesitant about drawing conclusions from the current data.",
      "Fully confident in the finding.",
      "Completely dismissive of the rival team's work.",
      "Neutral and uninterested.",
    ],
    correct: 0,
    explanation: "'Intriguing and worth following up' is positive; 'sample size too small for firm conclusions' hedges.",
    difficulty: "M",
  },
  {
    stem: "A diplomat says the treaty 'marks an important step forward' but cautions that 'any celebration would be premature until signatory nations follow through on their commitments.' Which best describes her point of view?",
    options: [
      "Encouraged by the step but cautious about declaring success.",
      "Entirely confident.",
      "Entirely skeptical.",
      "Indifferent.",
    ],
    correct: 0,
    explanation: "'Important step forward' is positive; 'premature' and 'until ... follow through' hedge. Encouraged but cautious.",
    difficulty: "M",
  },
  {
    stem: "A coach tells the press that her team 'played with heart' but also that 'we made too many avoidable mistakes that cost us the game.' Which best describes the coach's point of view?",
    options: [
      "Proud of her team's effort but critical of its execution.",
      "Uniformly proud.",
      "Uniformly disappointed.",
      "Indifferent to the outcome.",
    ],
    correct: 0,
    explanation: "'Played with heart' is positive; 'avoidable mistakes' is critical. Mixed stance — proud of effort, critical of execution.",
    difficulty: "F",
  },
  {
    stem: "A film critic describes a new documentary as 'beautifully shot, carefully researched, and one of the most important films of the year.' Which best describes her point of view?",
    options: [
      "Strongly positive across the board.",
      "Mostly negative.",
      "Neutral.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "Every evaluative phrase is positive. No reservations.",
    difficulty: "F",
  },
  {
    stem: "A journalist writes that the company's earnings report 'exceeded expectations and should please shareholders,' but adds that the company 'still faces significant legal exposure from ongoing lawsuits.' Which best describes the journalist's point of view?",
    options: [
      "Positive on the earnings but warning of risks.",
      "Entirely positive.",
      "Entirely negative.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Exceeded expectations' is positive; 'significant legal exposure' is a warning. Mixed.",
    difficulty: "M",
  },
  {
    stem: "A historian calls a new biography 'well-researched and engagingly written — by far the best single-volume treatment of its subject.' Which best describes her point of view?",
    options: [
      "Strongly positive, with no reservations.",
      "Mostly critical.",
      "Neutral.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "Every phrase is unambiguous praise.",
    difficulty: "F",
  },
  {
    stem: "An art critic calls a new exhibit 'loud, crowded, and deeply confused about what it wants to say.' Which best describes her point of view?",
    options: [
      "Firmly negative toward the exhibit.",
      "Mildly positive.",
      "Ambivalent.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Loud,' 'crowded,' and 'deeply confused' are all critical. Firmly negative.",
    difficulty: "M",
  },
  {
    stem: "An engineer writes that a proposed bridge design is 'elegant in concept but impractical at the scale the city needs; the materials alone would exceed the budget three times over.' Which best describes her point of view?",
    options: [
      "Admiring of the concept but rejecting the design as impractical.",
      "Entirely supportive.",
      "Entirely dismissive of both concept and execution.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Elegant in concept' is praise; 'impractical' and 'three times over' are strong rejection of feasibility.",
    difficulty: "C",
  },
  {
    stem: "A teacher writes that her students 'made remarkable progress in reading' but 'continue to struggle with written expression.' Which best describes her point of view?",
    options: [
      "Encouraged by progress in one area while acknowledging ongoing struggles in another.",
      "Entirely pleased with their progress.",
      "Entirely frustrated by the lack of progress.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Remarkable progress' is praise for reading; 'continue to struggle' is a concern for writing.",
    difficulty: "M",
  },
  {
    stem: "A reporter writes that the new policy 'addresses a genuine problem' but warns that 'the implementation plan may prove impossible to execute within the proposed timeline.' Which best describes the reporter's point of view?",
    options: [
      "Supportive of the goal but doubtful about how it will be carried out.",
      "Fully behind the policy.",
      "Entirely opposed to the policy.",
      "Indifferent.",
    ],
    correct: 0,
    explanation: "'Genuine problem' is positive about the goal; 'impossible to execute' is skeptical about implementation.",
    difficulty: "C",
  },
  {
    stem: "An astronomer describes a rival claim as 'exciting if confirmed, but based on a single, unreplicated observation and therefore not yet reliable.' Which best describes her point of view?",
    options: [
      "Intrigued but not yet convinced.",
      "Fully persuaded.",
      "Fully dismissive.",
      "Completely indifferent.",
    ],
    correct: 0,
    explanation: "'Exciting if confirmed' signals interest; 'not yet reliable' signals withheld judgment.",
    difficulty: "M",
  },
  {
    stem: "A chef calls a new ingredient 'versatile and surprisingly affordable' and says she 'plans to incorporate it into several menu items.' Which best describes the chef's point of view?",
    options: [
      "Enthusiastic and practical — she likes the ingredient and intends to use it.",
      "Hesitant and uncertain.",
      "Entirely dismissive.",
      "Neutral and detached.",
    ],
    correct: 0,
    explanation: "Every phrase is positive, and her stated plan confirms the enthusiasm.",
    difficulty: "F",
  },
];

const nmsqt = [
  {
    stem: "A reporter describes a new law as 'a step in the right direction' but adds that 'enforcement will determine whether it actually changes anything.' Which best describes the reporter's point of view?",
    options: [
      "Cautiously supportive — positive about the intent, uncertain about the outcome.",
      "Unreservedly supportive.",
      "Firmly opposed.",
      "Completely neutral.",
    ],
    correct: 0,
    explanation: "'Step in the right direction' is positive; 'will determine' is hedged about outcomes.",
    difficulty: "F",
  },
  {
    stem: "Dr. Kim describes a drug trial as 'promising in its early results but insufficient in its sample size to justify immediate approval.' Which best describes Kim's point of view?",
    options: [
      "Intrigued by the early results but unwilling to endorse approval yet.",
      "Fully supportive of immediate approval.",
      "Fully dismissive of the trial.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Promising' is positive; 'insufficient ... to justify immediate approval' hedges.",
    difficulty: "M",
  },
  {
    stem: "A critic calls an old economic theory 'long discredited and no longer worth serious consideration.' Which best describes the critic's point of view?",
    options: [
      "Firmly dismissive.",
      "Cautiously supportive.",
      "Neutral.",
      "Enthusiastic.",
    ],
    correct: 0,
    explanation: "'Discredited' and 'no longer worth serious consideration' are strong rejections.",
    difficulty: "M",
  },
  {
    stem: "A reviewer says a new album is 'ambitious in scope but inconsistent in execution, with a few memorable tracks and several that feel unfinished.' Which best describes her point of view?",
    options: [
      "Mixed — she admires the ambition but is disappointed by the inconsistency.",
      "Uniformly praising.",
      "Entirely negative.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Ambitious in scope' is praise; 'inconsistent' and 'unfinished' are critical.",
    difficulty: "M",
  },
  {
    stem: "A business analyst says the merger 'will increase efficiency in the short term' but 'raises serious concerns about market concentration over the next decade.' Which best describes the analyst's point of view?",
    options: [
      "Short-term positive, long-term concerned.",
      "Entirely supportive.",
      "Entirely opposed.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Increase efficiency' is positive; 'serious concerns' is negative.",
    difficulty: "M",
  },
  {
    stem: "A librarian describes a new cataloging system as 'a clear improvement over the previous one' though 'staff will need weeks of training to use it effectively.' Which best describes her point of view?",
    options: [
      "Positive about the system but realistic about the transition cost.",
      "Entirely critical.",
      "Entirely enthusiastic without reservations.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Clear improvement' is positive; 'weeks of training' is a realistic caveat.",
    difficulty: "M",
  },
  {
    stem: "A scientist notes that recent climate models are 'more accurate than anything we had ten years ago' but 'still struggle with regional precipitation.' Which best describes her point of view?",
    options: [
      "Impressed by the progress but aware of remaining limitations.",
      "Entirely confident in the models.",
      "Entirely skeptical of the models.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'More accurate' is praise; 'still struggle' is a limitation.",
    difficulty: "M",
  },
  {
    stem: "A reviewer writes that a play was 'beautifully acted by an exceptional cast' but 'undermined by a script that went nowhere.' Which best describes the reviewer's point of view?",
    options: [
      "Praises the acting but criticizes the script.",
      "Uniformly positive.",
      "Uniformly negative.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "Split praise: positive for acting, negative for script.",
    difficulty: "M",
  },
  {
    stem: "A geologist calls a rival's findings 'thought-provoking but built on assumptions that remain untested.' Which best describes her point of view?",
    options: [
      "Intrigued but not yet persuaded.",
      "Fully persuaded.",
      "Fully hostile.",
      "Indifferent.",
    ],
    correct: 0,
    explanation: "'Thought-provoking' is positive; 'untested assumptions' is a concern that stops short of persuasion.",
    difficulty: "M",
  },
  {
    stem: "A minister describes the summit as 'a genuine achievement in diplomacy' but warns that 'implementation will be extraordinarily difficult.' Which best describes the minister's point of view?",
    options: [
      "Pleased with the diplomatic achievement but realistic about the difficulty ahead.",
      "Uniformly triumphant.",
      "Uniformly defeated.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Genuine achievement' is praise; 'extraordinarily difficult' is a warning.",
    difficulty: "M",
  },
  {
    stem: "A parent writes that the new school schedule 'has worked well for her family' but adds that 'other families in the community have reported real struggles.' Which best describes the parent's point of view?",
    options: [
      "Personally satisfied but aware that others have had different experiences.",
      "Uniformly enthusiastic.",
      "Uniformly dissatisfied.",
      "Indifferent.",
    ],
    correct: 0,
    explanation: "'Worked well for her family' is positive; 'real struggles' for others is a concern.",
    difficulty: "F",
  },
  {
    stem: "A food critic describes a restaurant as 'excellent in every respect — from the service to the dessert menu.' Which best describes her point of view?",
    options: [
      "Strongly positive with no reservations.",
      "Mildly critical.",
      "Neutral.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "'Excellent in every respect' is unambiguous praise.",
    difficulty: "F",
  },
  {
    stem: "A journalist writes that the city's transit plan 'addresses the most pressing bottlenecks' but cautions that 'funding shortfalls could delay the plan by several years.' Which best describes the journalist's point of view?",
    options: [
      "Supportive of the plan but concerned about funding.",
      "Entirely behind the plan.",
      "Entirely opposed.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Addresses the most pressing bottlenecks' is positive; 'funding shortfalls' is a concern.",
    difficulty: "M",
  },
  {
    stem: "A historian calls a new museum exhibit 'the most thorough and well-curated treatment of its subject she has ever seen.' Which best describes her point of view?",
    options: [
      "Strongly admiring.",
      "Mildly critical.",
      "Neutral.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "'Most thorough and well-curated' and 'ever seen' are strong praise.",
    difficulty: "F",
  },
  {
    stem: "A theater critic calls a new production 'busy, cluttered, and missing any clear point of view of its own.' Which best describes her stance?",
    options: [
      "Firmly negative.",
      "Mildly positive.",
      "Ambivalent.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "Every phrase is a criticism.",
    difficulty: "M",
  },
  {
    stem: "An architect calls a proposed skyscraper 'elegant on paper but impractical for the neighborhood — the site simply can't absorb the extra traffic.' Which best describes her point of view?",
    options: [
      "Appreciative of the aesthetic vision but dismissive of the practical fit.",
      "Entirely supportive.",
      "Entirely dismissive of both vision and fit.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Elegant on paper' is praise; 'impractical' and 'can't absorb' are rejection of feasibility.",
    difficulty: "C",
  },
  {
    stem: "A manager writes that her team 'has delivered impressive results this quarter' but 'continues to struggle with meeting weekly deadlines.' Which best describes her point of view?",
    options: [
      "Proud of big-picture results while concerned about ongoing deadline issues.",
      "Entirely proud.",
      "Entirely frustrated.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Impressive results' is praise; 'continues to struggle' is a concern.",
    difficulty: "M",
  },
  {
    stem: "A columnist writes that the tax plan 'targets a real inequity in the system' but 'may cause unintended harm to small businesses.' Which best describes his point of view?",
    options: [
      "Supportive of the goal but worried about unintended consequences.",
      "Entirely behind the plan.",
      "Entirely against it.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Real inequity' is positive about the goal; 'unintended harm' is a concern.",
    difficulty: "C",
  },
  {
    stem: "A physicist describes a rival team's paper as 'fascinating if correct, but resting on a measurement that could not be repeated in subsequent work.' Which best describes her point of view?",
    options: [
      "Interested but skeptical, pending replication.",
      "Fully convinced.",
      "Fully dismissive.",
      "Indifferent.",
    ],
    correct: 0,
    explanation: "'Fascinating if correct' is conditional interest; 'could not be repeated' is a serious doubt.",
    difficulty: "M",
  },
  {
    stem: "A gardener describes a new heirloom tomato as 'flavorful, productive, and easy to grow — my favorite of the season.' Which best describes her point of view?",
    options: [
      "Wholeheartedly enthusiastic.",
      "Mildly critical.",
      "Neutral.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "Every phrase is positive. Strong enthusiasm.",
    difficulty: "F",
  },
];

const psat89 = [
  {
    stem: "A reporter describes a new recycling program as 'a good start' but notes that 'only about half of residents have actually begun using it.' Which best describes the reporter's point of view?",
    options: [
      "Positive about the program's intent but aware of limited adoption.",
      "Entirely supportive.",
      "Entirely opposed.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Good start' is praise; 'only about half' is a concern about adoption.",
    difficulty: "F",
  },
  {
    stem: "A teacher describes a new textbook as 'clearly written and well-organized, though the practice problems are too few.' Which best describes her point of view?",
    options: [
      "Mostly positive with one specific complaint.",
      "Mostly negative.",
      "Neutral.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "'Clearly written' and 'well-organized' are praise; 'too few' is a minor complaint.",
    difficulty: "M",
  },
  {
    stem: "A historian describes an older interpretation as 'no longer tenable in light of recent discoveries.' Which best describes the historian's point of view?",
    options: [
      "Firmly dismissive of the older interpretation.",
      "Cautiously supportive of it.",
      "Neutral.",
      "Enthusiastic about it.",
    ],
    correct: 0,
    explanation: "'No longer tenable' is strong rejection.",
    difficulty: "M",
  },
  {
    stem: "A music reviewer calls a new album 'inventive and fresh in places, but hampered by several songs that drag.' Which best describes the reviewer's point of view?",
    options: [
      "Mixed — praises some tracks and criticizes others.",
      "Uniformly enthusiastic.",
      "Uniformly dismissive.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Inventive and fresh' is praise; 'hampered' and 'drag' are criticism.",
    difficulty: "M",
  },
  {
    stem: "A city planner says a new parking garage 'solves the immediate need for downtown parking' but 'encourages more car traffic than the area can sustain.' Which best describes her point of view?",
    options: [
      "Sees short-term value but worries about long-term consequences.",
      "Entirely supportive.",
      "Entirely opposed.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Solves immediate need' is positive; 'more traffic than area can sustain' is negative.",
    difficulty: "M",
  },
  {
    stem: "A student describes a summer program as 'one of the most rewarding experiences I've had' though 'the dorm rooms were uncomfortable.' Which best describes her point of view?",
    options: [
      "Strongly positive overall with a minor complaint.",
      "Mostly negative.",
      "Neutral.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "'Most rewarding' is strong praise; 'dorm rooms uncomfortable' is minor.",
    difficulty: "F",
  },
  {
    stem: "A scientist calls a new technique 'a valuable addition to the lab's toolkit' that 'still needs refinement before it can replace older methods.' Which best describes her point of view?",
    options: [
      "Sees value but also room for improvement.",
      "Fully satisfied with the technique as is.",
      "Entirely dismissive.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Valuable addition' is praise; 'still needs refinement' is a caveat.",
    difficulty: "M",
  },
  {
    stem: "A reviewer says a restaurant 'has atmosphere and attentive service' but 'the food is forgettable.' Which best describes the reviewer's point of view?",
    options: [
      "Praises atmosphere and service while criticizing the food.",
      "Uniformly positive.",
      "Uniformly negative.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "Split: positive for atmosphere/service, negative for food.",
    difficulty: "M",
  },
  {
    stem: "A researcher describes a recent claim as 'worth pursuing but not yet supported by enough replications to consider established.' Which best describes her stance?",
    options: [
      "Interested but not yet convinced.",
      "Fully convinced.",
      "Fully dismissive.",
      "Indifferent.",
    ],
    correct: 0,
    explanation: "'Worth pursuing' is positive; 'not yet supported' hedges.",
    difficulty: "M",
  },
  {
    stem: "A mayor describes the new housing policy as 'a long-overdue response to a real crisis' but acknowledges that 'implementation will be contentious.' Which best describes the mayor's point of view?",
    options: [
      "Strongly in favor but expecting difficult politics.",
      "Entirely confident and untroubled.",
      "Entirely opposed.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Long-overdue response' is strong support; 'contentious' is a realistic concern.",
    difficulty: "M",
  },
  {
    stem: "A parent writes that the new daycare 'has excellent staff' but 'is too expensive for most families in the neighborhood.' Which best describes her point of view?",
    options: [
      "Praises the staff but criticizes the cost.",
      "Uniformly positive.",
      "Uniformly negative.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "Split: positive on staff, negative on affordability.",
    difficulty: "F",
  },
  {
    stem: "A food critic describes a bakery as 'a rare place where every item is made with care and sold at a fair price.' Which best describes her point of view?",
    options: [
      "Strongly positive without reservation.",
      "Mildly critical.",
      "Neutral.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "'Rare,' 'care,' and 'fair price' are all positive.",
    difficulty: "F",
  },
  {
    stem: "A coach writes that her player 'has improved dramatically in ball-handling' but 'needs to work on defensive positioning.' Which best describes her point of view?",
    options: [
      "Pleased with progress in one area while urging improvement in another.",
      "Entirely pleased.",
      "Entirely dissatisfied.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Improved dramatically' is praise; 'needs to work on' is an area for growth.",
    difficulty: "M",
  },
  {
    stem: "A historian writes that a new archival discovery 'will force scholars to reconsider the accepted timeline of the event.' Which best describes her point of view?",
    options: [
      "Regards the discovery as significant and likely to change the field.",
      "Dismisses the discovery.",
      "Neutral and uninterested.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "'Will force scholars to reconsider' treats the discovery as significant.",
    difficulty: "M",
  },
  {
    stem: "An art critic describes a new exhibit as 'loud, distracted, and never committed to a single idea.' Which best describes her stance?",
    options: [
      "Firmly negative.",
      "Mildly positive.",
      "Neutral.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "'Loud,' 'distracted,' and 'never committed' are all criticism.",
    difficulty: "M",
  },
  {
    stem: "An urban planner calls a proposed highway expansion 'well-intended but likely to worsen the congestion it was designed to relieve.' Which best describes her point of view?",
    options: [
      "Acknowledges the intent but predicts the opposite of the desired outcome.",
      "Entirely supportive.",
      "Entirely dismissive of the intent.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Well-intended' is charitable; 'worsen the congestion' is a critical prediction.",
    difficulty: "C",
  },
  {
    stem: "A manager writes that her team 'has done outstanding work this quarter' but 'struggled with clear internal communication.' Which best describes her point of view?",
    options: [
      "Proud of the work while concerned about communication.",
      "Uniformly proud.",
      "Uniformly disappointed.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Outstanding work' is praise; 'struggled' is a criticism about communication.",
    difficulty: "M",
  },
  {
    stem: "A journalist describes a new safety regulation as 'sensible in intent' but 'poorly drafted in ways that may create loopholes.' Which best describes the journalist's point of view?",
    options: [
      "Supportive of the goal but critical of the drafting.",
      "Fully supportive.",
      "Fully opposed.",
      "Neutral.",
    ],
    correct: 0,
    explanation: "'Sensible in intent' is positive; 'poorly drafted' is a criticism of execution.",
    difficulty: "C",
  },
  {
    stem: "A biologist describes a rival's data as 'suggestive but too noisy to justify strong conclusions.' Which best describes her point of view?",
    options: [
      "Open to the possibility but unconvinced by the current data.",
      "Fully convinced.",
      "Fully dismissive.",
      "Indifferent.",
    ],
    correct: 0,
    explanation: "'Suggestive' is interested; 'too noisy' is unconvinced.",
    difficulty: "M",
  },
  {
    stem: "A gardener calls a new fertilizer 'effective, affordable, and easy to use — the best she has tried in years.' Which best describes her point of view?",
    options: [
      "Wholeheartedly enthusiastic.",
      "Mildly critical.",
      "Neutral.",
      "Ambivalent.",
    ],
    correct: 0,
    explanation: "Every phrase is positive. Strong enthusiasm.",
    difficulty: "F",
  },
];

export default {
  skill: "point_of_view",
  skillLabel: "Point of view",
  domain: "Craft & Structure",
  section: "rw",
  batches: {
    "sat-rw": sat,
    "nmsqt-rw": nmsqt,
    "psat89-rw": psat89,
  },
};
