// Possessives and contractions — 60 questions (20 per test type)

const FORMAT = "Which choice completes the text so that it conforms to the conventions of Standard English?";

const sat = [
  {
    stem: `${FORMAT}\n\nThe panel praised the three ______ research on coral reef restoration.`,
    options: ["biologists'", "biologist's", "biologists", "biologists's"],
    correct: 0,
    explanation: "There are three biologists (plural), and the research belongs to them. Plural ending in -s, possessive → apostrophe after the s.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe committee will announce ______ decision on Monday.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "Collective noun 'committee' is singular. Use possessive 'its' (no apostrophe). 'It's' means 'it is.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ raining again, which means the game will probably be postponed.`,
    options: ["It's", "Its", "Their", "There's"],
    correct: 0,
    explanation: "'It's raining' = 'It is raining.' Use the contraction 'It's' with an apostrophe.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe ______ new gymnasium was completed last summer.`,
    options: ["children's", "childrens'", "childrens", "children"],
    correct: 0,
    explanation: "'Children' is already plural, so add 's — 'children's.' 'Childrens'' is never correct.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nI don't know ______ going to win the election next week.`,
    options: ["who's", "whose", "whos", "who"],
    correct: 0,
    explanation: "'Who is going to win' → contraction 'who's' with apostrophe.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe author ______ novel won the prize last year will be speaking tomorrow.`,
    options: ["whose", "who's", "that's", "its"],
    correct: 0,
    explanation: "Possessive 'whose' — the novel belongs to the author. 'Who's' means 'who is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe two ______ reports were praised for their thoroughness and clarity.`,
    options: ["students'", "student's", "students", "students's"],
    correct: 0,
    explanation: "Two students (plural), reports belong to them — apostrophe after the s.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe dog wagged ______ tail as soon as it saw the familiar face.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "The dog is singular, and the tail belongs to it. Possessive 'its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe company announced ______ plans to open two new offices next year.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "Collective noun 'company' is singular. Possessive 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe ______ locker room is being renovated next month.`,
    options: ["women's", "womens'", "womens", "women"],
    correct: 0,
    explanation: "'Women' is already plural, so add 's — 'women's.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ turn is it to present the project results?`,
    options: ["Whose", "Who's", "Whos", "Whoever's"],
    correct: 0,
    explanation: "Possessive 'whose' — the turn belongs to someone.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nBy the end of the semester, the ______ progress had improved significantly.`,
    options: ["students'", "student's", "students", "students's"],
    correct: 0,
    explanation: "Multiple students, plural possessive — 'students'.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe cat knocked ______ bowl off the counter for the second time today.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "The cat is singular; the bowl belongs to it. 'Its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe ______ rights movement gained momentum in the mid-20th century.`,
    options: ["women's", "womens'", "womans", "woman's"],
    correct: 0,
    explanation: "'Women' is already plural; add 's for possessive.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ a long way from home, so she felt homesick at first.`,
    options: ["It's", "Its", "Their", "They're"],
    correct: 0,
    explanation: "'It's a long way' = 'It is a long way.' Contraction with apostrophe.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe twins showed off ______ new bicycles to the neighbors.`,
    options: ["their", "they're", "there", "its"],
    correct: 0,
    explanation: "'Their' is the plural possessive belonging to the twins. 'They're' means 'they are'; 'there' is a place.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe ______ bookshelves are organized by genre and author.`,
    options: ["library's", "libraries'", "libraries's", "libraries"],
    correct: 0,
    explanation: "A single library, singular possessive — 'library's.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe ______ voices blended beautifully during the final chorus.`,
    options: ["choir's", "choirs'", "choir", "choir is"],
    correct: 0,
    explanation: "One choir (singular), voices belong to it. Singular possessive 'choir's.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ been a long time since we've seen each other.`,
    options: ["It's", "Its", "It", "Itss"],
    correct: 0,
    explanation: "'It's been' = 'It has been.' Contraction with apostrophe.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe ______ toys were scattered across the living room floor.`,
    options: ["children's", "childrens'", "childrens", "children"],
    correct: 0,
    explanation: "Irregular plural 'children' + 's for possessive.",
    difficulty: "M",
  },
];

const nmsqt = [
  {
    stem: `${FORMAT}\n\nThe scientists' data ______ groundbreaking, but the conclusions still need peer review.`,
    options: ["is", "it's", "its", "being"],
    correct: 0,
    explanation: "This isn't a possessive question — it's a verb agreement. On SAT, 'data' can be singular: 'is.' (For this item, the possessive is already in place on 'scientists'.') This question tests whether you recognize the possessive form is already correct in the stem.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe ______ garden has won awards for three years in a row.`,
    options: ["neighbors'", "neighbor's", "neighbors", "neighbors's"],
    correct: 0,
    explanation: "Multiple neighbors (collective), plural ending in -s, possessive — 'neighbors'.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe corporation defended ______ decision in a press release this morning.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "Collective noun 'corporation' is singular. Use possessive 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ going to be a close game tonight between the two rivals.`,
    options: ["It's", "Its", "Their", "They're"],
    correct: 0,
    explanation: "'It's going to be' = 'It is going to be.' Contraction.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe ______ soccer uniforms arrived in time for the first game.`,
    options: ["men's", "mens'", "mens", "man's"],
    correct: 0,
    explanation: "'Men' is already plural; add 's.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ name is on the top of the list this month?`,
    options: ["Whose", "Who's", "Whos", "Whom's"],
    correct: 0,
    explanation: "Possessive 'whose' — the name belongs to someone.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe architect ______ office designed the new library.`,
    options: ["whose", "who's", "whoms", "its"],
    correct: 0,
    explanation: "Possessive 'whose' — the office belongs to the architect.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe four ______ reports were submitted in a single folder.`,
    options: ["researchers'", "researcher's", "researchers", "researchers's"],
    correct: 0,
    explanation: "Four researchers (plural), possessive — 'researchers'.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe bird built ______ nest in the lowest branches of the oak.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "The bird is singular; nest belongs to it. 'Its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe museum announced ______ newest acquisition on Friday.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "Singular noun 'museum.' Possessive 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe ______ dressing room is on the second floor of the building.`,
    options: ["children's", "childrens'", "childrens", "children"],
    correct: 0,
    explanation: "'Children' is already plural; add 's.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ turn is it to walk the dog this evening?`,
    options: ["Whose", "Who's", "Whos", "Whom"],
    correct: 0,
    explanation: "Possessive 'whose.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nBy the end of the season, the ______ record was the best in the league.`,
    options: ["team's", "teams'", "teams", "teams's"],
    correct: 0,
    explanation: "Singular 'team' possessive — 'team's.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe fox darted into ______ den just as the storm broke.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "The fox is singular; the den belongs to it. 'Its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe ______ tennis tournament is held every July.`,
    options: ["women's", "womens'", "womans'", "woman's"],
    correct: 0,
    explanation: "'Women' already plural + 's.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ my turn to choose the restaurant tonight.`,
    options: ["It's", "Its", "Their", "There"],
    correct: 0,
    explanation: "'It's' = 'It is.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe sisters kept ______ promises to each other throughout the school year.`,
    options: ["their", "they're", "there", "its"],
    correct: 0,
    explanation: "'Their' — plural possessive belonging to the sisters.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe ______ hours were extended through the summer.`,
    options: ["gallery's", "galleries'", "gallerys", "galleries's"],
    correct: 0,
    explanation: "Singular 'gallery' possessive — 'gallery's.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe ______ opening performance received a standing ovation.`,
    options: ["orchestra's", "orchestras'", "orchestras", "orchestra is"],
    correct: 0,
    explanation: "Singular 'orchestra' possessive — 'orchestra's.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ too late to call the dentist, so we'll try tomorrow.`,
    options: ["It's", "Its", "Their", "They're"],
    correct: 0,
    explanation: "'It's too late' = 'It is too late.'",
    difficulty: "F",
  },
];

const psat89 = [
  {
    stem: `${FORMAT}\n\nThe ______ backpacks were lined up along the hallway wall.`,
    options: ["students'", "student's", "students", "students's"],
    correct: 0,
    explanation: "Multiple students, plural possessive — 'students'.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe hamster ran on ______ wheel almost all night long.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "One hamster, singular possessive — 'its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\n______ been weeks since we last visited the beach.`,
    options: ["It's", "Its", "Their", "There's"],
    correct: 0,
    explanation: "'It's been' = 'It has been.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe ______ toys were donated to the local shelter.`,
    options: ["children's", "childrens'", "childrens", "children"],
    correct: 0,
    explanation: "'Children' is already plural; add 's.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ going to be the next class president?`,
    options: ["Who's", "Whose", "Whos", "Whom's"],
    correct: 0,
    explanation: "'Who is going to be' — contraction 'who's.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe musician ______ guitar was stolen has offered a reward.`,
    options: ["whose", "who's", "whom's", "its"],
    correct: 0,
    explanation: "Possessive 'whose' — the guitar belongs to the musician.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe three ______ lunchboxes were all the same color.`,
    options: ["twins'", "twin's", "twins", "twins's"],
    correct: 0,
    explanation: "Three twins (plural), possessive — 'twins'.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe squirrel buried ______ acorns all over the yard.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "One squirrel, singular possessive — 'its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe school announced ______ plans to host a career fair in May.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "Singular 'school' → 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe ______ running team has won the district three years in a row.`,
    options: ["men's", "mens'", "mans", "man's"],
    correct: 0,
    explanation: "'Men' is already plural; add 's.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ pencil is this on the floor?`,
    options: ["Whose", "Who's", "Whos", "Whom"],
    correct: 0,
    explanation: "Possessive 'whose.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nBy Friday, the ______ playoff record was undefeated.`,
    options: ["team's", "teams'", "teams", "teams's"],
    correct: 0,
    explanation: "Singular 'team' possessive — 'team's.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe bear returned to ______ cave at the end of the hibernation season.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "Singular 'bear' possessive — 'its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe ______ basketball team is playing its final game tonight.`,
    options: ["women's", "womens'", "womans", "woman's"],
    correct: 0,
    explanation: "'Women' already plural + 's.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ supposed to be sunny tomorrow.`,
    options: ["It's", "Its", "Their", "There"],
    correct: 0,
    explanation: "'It's' = 'It is.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe brothers wore ______ matching sweaters for the family photo.`,
    options: ["their", "they're", "there", "its"],
    correct: 0,
    explanation: "'Their' — plural possessive belonging to the brothers.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe ______ mascot is a golden retriever named Buddy.`,
    options: ["club's", "clubs'", "clubs", "clubs's"],
    correct: 0,
    explanation: "Singular 'club' possessive — 'club's.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe ______ final performance brought the crowd to its feet.`,
    options: ["band's", "bands'", "bands", "band is"],
    correct: 0,
    explanation: "Singular 'band' possessive — 'band's.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\n______ getting late, so we should head home.`,
    options: ["It's", "Its", "Their", "They're"],
    correct: 0,
    explanation: "'It's getting late' = 'It is getting late.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe dance troupe premiered ______ newest routine on Saturday.`,
    options: ["its", "it's", "their", "they're"],
    correct: 0,
    explanation: "Singular collective 'troupe' → 'its.'",
    difficulty: "M",
  },
];

export default {
  skill: "possessives",
  skillLabel: "Possessives and contractions",
  domain: "Standard English Conventions",
  section: "rw",
  batches: {
    "sat-rw": sat,
    "nmsqt-rw": nmsqt,
    "psat89-rw": psat89,
  },
};
