// Pronoun clarity and agreement — 60 questions (20 per test type)

const FORMAT = "Which choice completes the text so that it conforms to the conventions of Standard English?";

const sat = [
  {
    stem: `${FORMAT}\n\nThe debate team, which has won every tournament for three years, ______ next competition is in Chicago.`,
    options: ["its", "their", "there", "them"],
    correct: 0,
    explanation: "Collective noun 'team' is singular, so the possessive is 'its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nEach student should bring ______ own laptop to the coding workshop.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Each' is singular, so the pronoun must be singular: 'his or her.' On the SAT, avoid singular 'their.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe committee announced ______ decision to delay the vote by a week.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'committee' is singular. Use 'its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nNeither of the boys finished ______ homework before the movie started.`,
    options: ["his", "their", "its", "there"],
    correct: 0,
    explanation: "'Neither' is singular. Since both are boys, 'his' is the matching singular.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe jury delivered ______ verdict after twelve hours of deliberation.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "'Jury' is a collective noun acting as a unit: singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe researchers published ______ findings in a peer-reviewed journal.`,
    options: ["their", "its", "there", "his or her"],
    correct: 0,
    explanation: "'Researchers' is plural. Use 'their.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nWhen Marcus met with his advisor, ______ went over the course schedule carefully.`,
    options: ["the two of them", "he", "they", "she"],
    correct: 0,
    explanation: "The ambiguous original would be 'he' or 'they' — but 'he' is ambiguous (Marcus or advisor?). 'The two of them' is unambiguous.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nEvery one of the applicants submitted ______ portfolio on time.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Every one' is singular. Use 'his or her.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe company announced ______ intention to expand into three new markets next year.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'company' is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe students turned in ______ essays before leaving for the weekend.`,
    options: ["their", "its", "his or her", "there"],
    correct: 0,
    explanation: "'Students' is plural. Use 'their.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nAfter the scientist reviewed the data, ______ realized a mistake had been made in the calibration.`,
    options: ["she", "they", "it", "one"],
    correct: 0,
    explanation: "The antecedent is 'the scientist' (singular, and known to be female in this sentence). Use 'she.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEach of the volunteers brought ______ own lunch to the cleanup event.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Each' is singular. Use 'his or her.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe family sold ______ house and moved across the country last summer.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'family' acting as a unit is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNone of the attendees forgot ______ umbrella, even though the forecast had predicted rain.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'None' with 'umbrella' (singular, one per person) and 'each attendee' reading → singular 'his or her' on the SAT.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nWhen teachers give feedback, ______ should focus on specific improvements rather than vague praise.`,
    options: ["they", "he or she", "it", "one"],
    correct: 0,
    explanation: "The antecedent 'teachers' is plural. Use 'they.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe audience showed ______ appreciation with a long standing ovation.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'audience' is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nBoth of the candidates presented ______ positions clearly during the debate.`,
    options: ["their", "his or her", "its", "there"],
    correct: 0,
    explanation: "'Both' is plural. Use 'their.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEverybody in the class remembered to bring ______ textbook to the exam review.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Everybody' is singular. On the SAT, use 'his or her.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe band released ______ first album last spring.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'band' acting as a unit is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nAnybody who wants to join the club must first submit ______ name to the secretary.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Anybody' is singular. Use 'his or her.'",
    difficulty: "C",
  },
];

const nmsqt = [
  {
    stem: `${FORMAT}\n\nThe school board released ______ annual report last Friday.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'school board' is singular. Use 'its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nEach of the dancers practiced ______ routine for an hour before the show.`,
    options: ["her", "their", "its", "his or her"],
    correct: 0,
    explanation: "'Each' is singular. The sentence suggests the dancers are women in this context; 'her' fits. Alternately 'his or her' would also be acceptable, but 'her' is simpler and unambiguous.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe orchestra finished ______ rehearsal right before the doors opened.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'orchestra' is singular. Use 'its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nNeither of the sisters brought ______ phone to the concert.`,
    options: ["her", "their", "its", "his or her"],
    correct: 0,
    explanation: "'Neither' is singular; both are sisters, so 'her.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe herd of sheep moved slowly across the valley toward ______ usual grazing area.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'herd' is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe reporters packed up ______ notebooks when the press conference ended.`,
    options: ["their", "its", "his or her", "there"],
    correct: 0,
    explanation: "'Reporters' is plural. Use 'their.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nWhen Lin spoke with the librarian, ______ looked up the book in the catalog.`,
    options: ["the librarian", "she", "they", "one"],
    correct: 0,
    explanation: "'She' would be ambiguous (Lin or librarian?). Naming 'the librarian' removes the ambiguity.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nEvery one of the drivers had ______ vehicle inspected before the race.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Every one' is singular. Use 'his or her.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe corporation defended ______ decision to close the factory in a public statement.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'corporation' is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe hikers returned to ______ cabin after the sudden storm passed.`,
    options: ["their", "its", "his or her", "there"],
    correct: 0,
    explanation: "'Hikers' is plural. Use 'their.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nAfter the doctor examined the patient, ______ ordered additional blood tests.`,
    options: ["the doctor", "he", "they", "one"],
    correct: 0,
    explanation: "'He' would be ambiguous. 'The doctor' is unambiguous.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEach of the students was responsible for ______ own materials.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Each' is singular. Use 'his or her.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe family kept ______ routine simple during the move.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'family' is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNone of the volunteers forgot ______ assigned task at the soup kitchen.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'None' with 'assigned task' (one per volunteer) → singular 'his or her.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nWhen journalists write investigative pieces, ______ often consult multiple independent sources.`,
    options: ["they", "he or she", "it", "one"],
    correct: 0,
    explanation: "'Journalists' is plural. Use 'they.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe audience rose to ______ feet as the final chord faded.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'audience' is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nBoth of the musicians tuned ______ instruments before the show.`,
    options: ["their", "his or her", "its", "there"],
    correct: 0,
    explanation: "'Both' is plural. Use 'their.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nSomebody left ______ umbrella by the front door.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Somebody' is singular. On the SAT, use 'his or her.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe choir performed ______ holiday concert at the community center.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'choir' is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nAnyone who arrives late should take ______ seat quietly.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Anyone' is singular. Use 'his or her.'",
    difficulty: "C",
  },
];

const psat89 = [
  {
    stem: `${FORMAT}\n\nThe soccer team celebrated ______ first championship in over a decade.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'team' is singular. Use 'its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nEach of the kittens found ______ own favorite spot to nap.`,
    options: ["its", "their", "his or her", "there"],
    correct: 0,
    explanation: "'Each' is singular; for animals, 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe staff handed in ______ time sheets on Friday afternoon.`,
    options: ["their", "its", "there", "it's"],
    correct: 0,
    explanation: "'Staff' used here refers to multiple individuals — 'their' works. (In strict SAT collective usage, 'its' is also sometimes accepted, but 'their' is correct for 'staff members hand in their own timesheets.')",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNeither of the brothers brought ______ bike to the park.`,
    options: ["his", "their", "its", "his or her"],
    correct: 0,
    explanation: "'Neither' is singular; both are brothers, so 'his.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe class turned in ______ final projects on Monday.`,
    options: ["their", "its", "his or her", "there"],
    correct: 0,
    explanation: "Though 'class' can be collective, here 'the class' refers to the students handing in their own projects — 'their' is expected.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe drivers returned ______ rental cars before boarding the plane.`,
    options: ["their", "its", "his or her", "there"],
    correct: 0,
    explanation: "'Drivers' is plural. Use 'their.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nWhen Elena spoke with the counselor, ______ talked about summer plans.`,
    options: ["the two of them", "she", "they", "it"],
    correct: 0,
    explanation: "'She' would be ambiguous. 'The two of them' is unambiguous.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nEvery one of the runners finished ______ race in under an hour.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Every one' is singular. Use 'his or her.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe museum displayed ______ newest exhibit in the front hall.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "'Museum' is a singular noun. Use 'its.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe guests placed ______ coats in the closet by the entrance.`,
    options: ["their", "its", "his or her", "there"],
    correct: 0,
    explanation: "'Guests' is plural. Use 'their.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nAfter the coach spoke with the referee, ______ returned to the sideline.`,
    options: ["the coach", "he", "they", "one"],
    correct: 0,
    explanation: "'He' would be ambiguous. Naming 'the coach' removes the ambiguity.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEach of the sculptures has ______ own unique story behind it.`,
    options: ["its", "their", "his or her", "there"],
    correct: 0,
    explanation: "'Each' is singular; for sculptures, 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe government released ______ monthly economic report on Tuesday.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'government' is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNone of the students forgot ______ assigned reading over the weekend.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'None' with 'assigned reading' (one per student) → singular 'his or her.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nWhen chefs prepare for a big dinner, ______ often work in teams to save time.`,
    options: ["they", "he or she", "it", "one"],
    correct: 0,
    explanation: "'Chefs' is plural. Use 'they.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe audience applauded as the speaker finished ______ remarks.`,
    options: ["his", "their", "its", "there"],
    correct: 0,
    explanation: "The antecedent is 'the speaker' — singular. In this sentence the speaker is referred to as male by convention; 'his' fits.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nBoth of the teachers brought ______ lesson plans to the meeting.`,
    options: ["their", "its", "his or her", "there"],
    correct: 0,
    explanation: "'Both' is plural. Use 'their.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNo one on the field trip lost ______ water bottle.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'No one' is singular. Use 'his or her.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe dance troupe premiered ______ new routine last Saturday.`,
    options: ["its", "their", "there", "it's"],
    correct: 0,
    explanation: "Collective noun 'troupe' is singular. Use 'its.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nAnyone who wants extra help should bring ______ questions to the review session.`,
    options: ["his or her", "their", "its", "there"],
    correct: 0,
    explanation: "'Anyone' is singular. Use 'his or her.'",
    difficulty: "C",
  },
];

export default {
  skill: "pronoun_clarity",
  skillLabel: "Pronoun clarity and agreement",
  domain: "Standard English Conventions",
  section: "rw",
  batches: {
    "sat-rw": sat,
    "nmsqt-rw": nmsqt,
    "psat89-rw": psat89,
  },
};
