// Subject-verb agreement — 60 questions (20 per test type)

const FORMAT = "Which choice completes the text so that it conforms to the conventions of Standard English?";

const sat = [
  {
    stem: `${FORMAT}\n\nThe variety of birds that visit the backyard feeder each morning ______ a source of delight for Ms. Park.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Strip out the prepositional phrase 'of birds that visit the backyard feeder each morning'; the subject is singular 'variety.' Use singular 'is.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nNeither the coach nor the players ______ aware of the last-minute schedule change.`,
    options: ["were", "was", "is", "has been"],
    correct: 0,
    explanation: "With 'or'/'nor' compound subjects, match the verb to the CLOSER subject: 'players' (plural), so 'were.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEach of the applicants ______ required to submit two letters of recommendation.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "'Each' is singular, so 'is.' 'Of the applicants' is a prepositional phrase that doesn't change the subject.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe committee ______ reviewing the new proposal this afternoon.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Collective nouns like 'committee' are singular on the SAT when the group acts as a unit. Use 'is.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThere ______ several reasons to reconsider the original plan.`,
    options: ["are", "is", "has been", "was"],
    correct: 0,
    explanation: "In 'there is/are' inversions, the real subject follows the verb. 'Reasons' is plural, so 'are.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe list of items that students need to bring on the field trip ______ posted on the classroom bulletin board.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Subject: 'list' (singular). Strip out 'of items that students need to bring on the field trip.' Singular 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEvery one of the exhibits at the new gallery ______ been designed to appeal to children.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "'Every one' is singular (like 'each'). The prepositional phrase 'of the exhibits' doesn't change that. Use 'has.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNeither of the candidates ______ able to attend tonight's debate.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "'Neither' (like 'either,' 'each') is singular. Use 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe athletes, along with their coach, ______ traveling to the championship on Saturday.`,
    options: ["are", "is", "was", "has been"],
    correct: 0,
    explanation: "'Along with' is a prepositional phrase, not a compound subject. The real subject is 'athletes' (plural), so 'are.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nMathematics ______ one of the oldest and most widely studied subjects in the world.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "'Mathematics' ends in -s but is singular. Use 'is.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe number of students enrolled in after-school programs ______ risen sharply over the past five years.`,
    options: ["has", "have", "are", "were"],
    correct: 0,
    explanation: "'The number' is singular. ('A number of' would be plural, but 'the number' is not.) Use 'has.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nA number of volunteers ______ signed up to help with the river cleanup.`,
    options: ["have", "has", "is", "was"],
    correct: 0,
    explanation: "'A number of' is plural — it means 'several.' Use 'have.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe scientific community ______ divided on whether the new theory should be accepted.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Collective noun 'community' acting as a unit is singular. Use 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEither of those two dates ______ fine with the organizer.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "'Either' is singular even though 'of those two dates' is plural. Use 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe box of books and supplies that the principal ordered ______ arriving tomorrow.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Subject: 'box' (singular). Everything between is modifiers. Use 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe data from the most recent experiments ______ consistent with the predictions of the theory.`,
    options: ["are", "is", "was", "has been"],
    correct: 0,
    explanation: "On the SAT, 'data' is treated as plural. Use 'are.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nHere ______ the final report and the supporting appendices that you requested.`,
    options: ["are", "is", "was", "has been"],
    correct: 0,
    explanation: "Inverted order: the real subject is the compound 'the final report and the supporting appendices' — plural. Use 'are.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nEach of the exhibits ______ a separate label and audio track.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "'Each' is singular. Use 'has.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe news from the front lines ______ reassuring to the families at home.`,
    options: ["was", "were", "are", "have been"],
    correct: 0,
    explanation: "'News' is singular even though it ends in -s. Use 'was.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nMy favorite kind of cookies ______ baked by my grandmother every Christmas.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Subject: 'kind' (singular). 'Of cookies' is a prepositional phrase. Use 'is.'",
    difficulty: "M",
  },
];

const nmsqt = [
  {
    stem: `${FORMAT}\n\nThe stack of old magazines on the top shelf ______ been there for years.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "Subject: 'stack' (singular). Use 'has.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nNeither the director nor the producers ______ available to comment on the new release.`,
    options: ["were", "was", "is", "has been"],
    correct: 0,
    explanation: "'Or'/'nor' takes the closer subject: 'producers' (plural), so 'were.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEach of the volunteers ______ assigned a specific station at the event.`,
    options: ["was", "were", "are", "have been"],
    correct: 0,
    explanation: "'Each' is singular. Use 'was.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe jury ______ reached a unanimous verdict after three hours of deliberation.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "Collective noun 'jury' acting as a unit is singular. Use 'has.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThere ______ two paths leading from the trailhead to the lake.`,
    options: ["are", "is", "was", "has been"],
    correct: 0,
    explanation: "Real subject 'paths' (plural). Use 'are.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nA collection of rare butterflies from the Amazon rainforest ______ displayed in the museum's main hall.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Subject: 'collection' (singular). Use 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEvery one of the instruments in the orchestra ______ been carefully tuned before the concert.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "'Every one' is singular. Use 'has.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNeither of the proposals ______ been approved by the board.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "'Neither' is singular. Use 'has.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe teacher, as well as her students, ______ planning to attend the science fair.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "'As well as' is a prepositional phrase, not a conjunction. The real subject is 'teacher' (singular). Use 'is.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nPhysics ______ often considered one of the most difficult high school subjects.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "'Physics' ends in -s but is singular. Use 'is.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe number of rare species in the park ______ declined over the past decade.`,
    options: ["has", "have", "is", "are"],
    correct: 0,
    explanation: "'The number' is singular. Use 'has.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nA number of residents ______ complained about the new parking rules.`,
    options: ["have", "has", "is", "was"],
    correct: 0,
    explanation: "'A number of' is plural. Use 'have.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe audience ______ applauding enthusiastically as the curtain fell.`,
    options: ["was", "were", "are", "have been"],
    correct: 0,
    explanation: "Collective noun 'audience' is singular. Use 'was.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEither of the two bus routes ______ take you to the airport.`,
    options: ["will", "was", "have", "are"],
    correct: 0,
    explanation: "'Either' is singular. Use singular verb 'will.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe carton of eggs that we bought yesterday ______ on the top shelf of the refrigerator.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Subject: 'carton' (singular). Use 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe statistics in the recent report ______ difficult to interpret without more context.`,
    options: ["are", "is", "was", "has been"],
    correct: 0,
    explanation: "In this sense, 'statistics' refers to multiple data points — plural. Use 'are.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nHere ______ the two reports you asked about.`,
    options: ["are", "is", "was", "has been"],
    correct: 0,
    explanation: "Inverted order: the real subject is 'the two reports' (plural). Use 'are.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nEach of the swimmers ______ a personal best time in the relay.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "'Each' is singular. Use 'has.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe news about the merger ______ surprising to most of the company's employees.`,
    options: ["was", "were", "are", "have been"],
    correct: 0,
    explanation: "'News' is singular. Use 'was.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThis style of shoes ______ becoming popular among teenagers again.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Subject: 'style' (singular). Use 'is.'",
    difficulty: "M",
  },
];

const psat89 = [
  {
    stem: `${FORMAT}\n\nThe bowl of fresh strawberries ______ on the kitchen counter.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Subject: 'bowl' (singular). Use 'is.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nNeither the manager nor the employees ______ aware of the new policy.`,
    options: ["were", "was", "is", "has been"],
    correct: 0,
    explanation: "Compound subject with 'nor' takes the closer subject: 'employees' (plural). Use 'were.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEach of the puppies ______ a different colored collar.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "'Each' is singular. Use 'has.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe team ______ practicing every afternoon this week.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Collective noun 'team' is singular. Use 'is.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThere ______ four books on the desk that still need to be returned.`,
    options: ["are", "is", "was", "has been"],
    correct: 0,
    explanation: "Subject: 'books' (plural). Use 'are.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe bag of apples that Mrs. Lopez bought ______ sitting on the kitchen table.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Subject: 'bag' (singular). Use 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEvery one of the violinists ______ practiced this piece for weeks.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "'Every one' is singular. Use 'has.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nNeither of the answers ______ correct.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "'Neither' is singular. Use 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe doctor, along with the nurses, ______ reviewing the patient's chart.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "'Along with' is a prepositional phrase. Real subject: 'doctor' (singular). Use 'is.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nEconomics ______ a subject that many students find challenging.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "'Economics' is singular. Use 'is.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe number of errors on the test ______ decreased significantly.`,
    options: ["has", "have", "is", "are"],
    correct: 0,
    explanation: "'The number' is singular. Use 'has.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nA number of hikers ______ taken the longer route to the summit.`,
    options: ["have", "has", "is", "was"],
    correct: 0,
    explanation: "'A number of' is plural. Use 'have.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe crowd ______ cheering as the home team scored.`,
    options: ["was", "were", "are", "have been"],
    correct: 0,
    explanation: "Collective noun 'crowd' is singular. Use 'was.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nEither of these two shirts ______ suitable for the interview.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "'Either' is singular. Use 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe jar of cookies on the top shelf ______ almost empty.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Subject: 'jar' (singular). Use 'is.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe athletics department ______ announced the schedule for spring tryouts.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "'Athletics department' is a collective noun acting as a unit — singular. Use 'has.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nHere ______ the two sandwiches you ordered.`,
    options: ["are", "is", "was", "has been"],
    correct: 0,
    explanation: "Real subject 'sandwiches' (plural). Use 'are.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nEach of the singers ______ a solo part in the concert.`,
    options: ["has", "have", "were", "are"],
    correct: 0,
    explanation: "'Each' is singular. Use 'has.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe news from the coaches ______ encouraging to the players.`,
    options: ["was", "were", "are", "have been"],
    correct: 0,
    explanation: "'News' is singular. Use 'was.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThis type of flowers ______ easy to grow in any garden.`,
    options: ["is", "are", "were", "have been"],
    correct: 0,
    explanation: "Subject: 'type' (singular). Use 'is.'",
    difficulty: "M",
  },
];

export default {
  skill: "subject_verb_agreement",
  skillLabel: "Subject-verb agreement",
  domain: "Standard English Conventions",
  section: "rw",
  batches: {
    "sat-rw": sat,
    "nmsqt-rw": nmsqt,
    "psat89-rw": psat89,
  },
};
