// Text structure — 60 questions (20 per test type)
// Each question describes a passage and asks the student to label its overall
// structure. Objectively correct answers: for each described passage, only
// one option correctly names both the moves AND the order.

const sat = [
  {
    stem: "A passage begins by describing daily life in a coastal village in the 1950s, then explains how offshore drilling in the 1970s transformed the local economy, and finally describes the village as it is today. Which choice best describes the passage's overall structure?",
    options: [
      "It describes an earlier state, then the cause of a change, and finally the current state.",
      "It compares two different villages.",
      "It presents a problem and proposes a solution.",
      "It defines a term and then lists examples.",
    ],
    correct: 0,
    explanation: "Three moves in time order — past, cause of change, present.",
    difficulty: "F",
  },
  {
    stem: "A passage argues that urban parks improve residents' mental health, citing a 2018 longitudinal study, then anticipates the objection that correlation isn't causation, then responds by pointing to randomized trials. Which choice best describes the structure?",
    options: [
      "A claim is made, evidence is given, an objection is raised, and then the objection is addressed.",
      "Two competing theories are compared.",
      "The passage defines a key term and lists its properties.",
      "The passage describes a sequence of historical events.",
    ],
    correct: 0,
    explanation: "Claim → support → counter → response. Only the correct option names all four moves in the right order.",
    difficulty: "M",
  },
  {
    stem: "A passage opens by noting that coral reefs have declined globally. It identifies pollution, warming waters, and overfishing as the main causes. It ends by describing several ongoing restoration projects. Which choice best describes the structure?",
    options: [
      "Problem, causes of the problem, and responses to the problem.",
      "Compare and contrast of two ecosystems.",
      "Historical narrative of a single species.",
      "Definition followed by examples.",
    ],
    correct: 0,
    explanation: "The three moves are problem → causes → response.",
    difficulty: "M",
  },
  {
    stem: "A passage describes bees as thriving in 1950s meadows, explains how pesticide use starting in the 1990s caused sharp population drops, and closes with current conservation efforts. Which best describes the structure?",
    options: [
      "An earlier state, the cause of a decline, and the current response.",
      "Two species are compared.",
      "A definition is given, then examples.",
      "A claim is made and then rebutted.",
    ],
    correct: 0,
    explanation: "Three sequential moves that trace a decline and response.",
    difficulty: "M",
  },
  {
    stem: "A passage describes how electric cars have become popular and then contrasts them with gas-powered cars on cost, range, and environmental impact. Which choice best describes the structure?",
    options: [
      "It introduces one thing and then compares it with another.",
      "It identifies a problem and proposes a single solution.",
      "It lists the steps of a process in order.",
      "It makes a claim and then defends it with evidence.",
    ],
    correct: 0,
    explanation: "Introduction of electric cars, followed by a point-by-point compare/contrast with gas cars.",
    difficulty: "M",
  },
  {
    stem: "A passage opens with a narrator describing her grandmother's bakery, then flashes back to the grandmother's childhood, then returns to the narrator's present-day visit. Which best describes the structure?",
    options: [
      "A present scene, then a flashback, then a return to the present.",
      "Cause followed by effect.",
      "A claim followed by counterarguments.",
      "Two characters compared side by side.",
    ],
    correct: 0,
    explanation: "The narrative moves from present to past and back again — a frame structure.",
    difficulty: "M",
  },
  {
    stem: "A passage defines 'keystone species,' lists four examples, and explains why the concept matters for conservation policy. Which choice best describes the structure?",
    options: [
      "A term is defined, examples are given, and implications are drawn.",
      "Two opposing theories are weighed against each other.",
      "A problem is stated and a solution is proposed.",
      "Events are narrated in chronological order.",
    ],
    correct: 0,
    explanation: "Definition → examples → implications.",
    difficulty: "M",
  },
  {
    stem: "A passage opens with a surprising finding from a recent experiment. It then explains the experimental setup, details the results, and concludes by suggesting what the finding means for the field. Which best describes the structure?",
    options: [
      "It hooks the reader with a result, then explains how the result was obtained and what it means.",
      "It compares two competing experiments.",
      "It narrates events in chronological order from earliest to latest.",
      "It presents a problem and proposes a solution.",
    ],
    correct: 0,
    explanation: "Hook with result → method → interpretation.",
    difficulty: "M",
  },
  {
    stem: "A passage describes a rare genetic disorder, explains how researchers identified the responsible gene in 2011, and concludes with a discussion of emerging gene-therapy treatments. Which best describes the structure?",
    options: [
      "A condition is described, the discovery of its cause is explained, and current treatments are reviewed.",
      "Two diseases are compared.",
      "A historical narrative of one scientist's career.",
      "A persuasive argument for increased funding.",
    ],
    correct: 0,
    explanation: "Description → discovery → treatment review.",
    difficulty: "M",
  },
  {
    stem: "A passage begins by asserting that early childhood education pays for itself in the long run. It then cites three studies, and ends by acknowledging that the evidence is strongest in dense urban settings. Which best describes the structure?",
    options: [
      "A claim, supporting evidence, and a qualification of the claim.",
      "A problem and its solution.",
      "A chronological narrative.",
      "A compare and contrast of two policies.",
    ],
    correct: 0,
    explanation: "Claim → support → qualification.",
    difficulty: "M",
  },
  {
    stem: "A passage outlines the steps by which lightning forms: charge buildup, leader formation, return stroke, and thunder. Which best describes the structure?",
    options: [
      "A process is described step by step in the order the steps occur.",
      "A problem is defined and a solution is offered.",
      "Two related phenomena are compared.",
      "A claim is made and supported with evidence.",
    ],
    correct: 0,
    explanation: "Sequential process description.",
    difficulty: "F",
  },
  {
    stem: "A passage describes two competing theories about how the Moon formed, presents evidence for and against each, and concludes by saying that the 'giant impact' theory is currently favored. Which best describes the structure?",
    options: [
      "Two theories are presented, weighed, and one is identified as the current best.",
      "A single process is described in chronological order.",
      "A definition is given, then examples.",
      "A problem is stated and a single solution is proposed.",
    ],
    correct: 0,
    explanation: "Compare two theories → weigh evidence → conclusion.",
    difficulty: "M",
  },
  {
    stem: "A passage opens with a puzzling observation about migrating birds, then describes three hypotheses researchers have proposed, and ends by noting which hypothesis currently has the most support. Which best describes the structure?",
    options: [
      "An observation is introduced, multiple explanations are proposed, and one is favored.",
      "A definition is given and examples are listed.",
      "A problem is stated and a single solution is proposed.",
      "A chronological narrative of a single researcher's work.",
    ],
    correct: 0,
    explanation: "Observation → hypotheses → favored explanation.",
    difficulty: "M",
  },
  {
    stem: "A passage narrates a morning in a farmer's life: waking before dawn, checking the herd, repairing a fence, and loading vegetables for market. Which best describes the structure?",
    options: [
      "A day's routine is narrated in chronological order.",
      "A claim is made and defended.",
      "Two farms are compared.",
      "A problem is introduced and analyzed.",
    ],
    correct: 0,
    explanation: "Events in chronological sequence.",
    difficulty: "F",
  },
  {
    stem: "A passage describes how a historical treaty failed, then explains three reasons it failed, then draws a lesson for modern diplomacy. Which best describes the structure?",
    options: [
      "A past event is described, its causes are analyzed, and present-day lessons are drawn.",
      "Two treaties are compared side by side.",
      "A term is defined and examples given.",
      "A process is described step by step.",
    ],
    correct: 0,
    explanation: "Event → causes → lessons.",
    difficulty: "M",
  },
  {
    stem: "A passage first argues that standardized tests measure test-taking skill more than subject knowledge, then presents data supporting that claim, then addresses the objection that tests still correlate with college success. Which best describes the structure?",
    options: [
      "A claim is made, supported with data, and an objection is addressed.",
      "Two competing tests are compared.",
      "A problem is described and a solution is proposed.",
      "A process is outlined step by step.",
    ],
    correct: 0,
    explanation: "Claim → support → counter-address.",
    difficulty: "M",
  },
  {
    stem: "A passage defines 'metacognition,' gives a classroom example, explains its importance to learning, and suggests a simple technique teachers can use. Which best describes the structure?",
    options: [
      "A term is defined, illustrated, justified, and then applied.",
      "Two teaching methods are compared.",
      "A historical narrative of educational reform.",
      "A problem is posed and a series of solutions is debated.",
    ],
    correct: 0,
    explanation: "Definition → example → justification → application.",
    difficulty: "C",
  },
  {
    stem: "A passage begins by describing the current state of plastic pollution in oceans, then presents three technologies being developed to clean it up, and concludes by noting which is most promising. Which best describes the structure?",
    options: [
      "A problem is described, several solutions are presented, and one is identified as most promising.",
      "A definition is followed by examples.",
      "A chronological narrative of a single cleanup project.",
      "Two oceans are compared.",
    ],
    correct: 0,
    explanation: "Problem → solutions → best solution.",
    difficulty: "C",
  },
  {
    stem: "A passage opens with a character entering an unfamiliar city, describes her reactions to the unfamiliar streets, and ends with her realizing that the city reminds her of her childhood home. Which best describes the structure?",
    options: [
      "A character moves from disorientation to recognition.",
      "Two cities are compared.",
      "A historical event is narrated.",
      "A claim is made and defended.",
    ],
    correct: 0,
    explanation: "Arrival → disorientation → recognition.",
    difficulty: "C",
  },
  {
    stem: "A passage opens by saying that popular wisdom holds a certain claim to be true, then presents recent research challenging the claim, and ends by saying the older view is likely wrong. Which best describes the structure?",
    options: [
      "A common belief is stated, challenged with evidence, and concluded to be incorrect.",
      "Two equally supported views are compared.",
      "A definition is given followed by examples.",
      "A sequence of events is narrated in chronological order.",
    ],
    correct: 0,
    explanation: "Popular view → challenge → correction.",
    difficulty: "C",
  },
];

const nmsqt = [
  {
    stem: "A passage describes how a town's main industry collapsed, explains the economic and social consequences, and ends by describing a new industry that has begun to replace it. Which choice best describes the structure?",
    options: [
      "A change is described, its consequences are explained, and a new development is introduced.",
      "Two industries are compared point by point.",
      "A definition is given followed by examples.",
      "A claim is made and supported with data.",
    ],
    correct: 0,
    explanation: "Change → consequences → new development.",
    difficulty: "M",
  },
  {
    stem: "A passage asserts that reading fiction improves empathy, cites a 2019 study, then acknowledges that the effect depends on how deeply readers engage. Which best describes the structure?",
    options: [
      "A claim, evidence, and a qualification.",
      "A chronological narrative.",
      "A problem and a solution.",
      "A compare and contrast of two genres.",
    ],
    correct: 0,
    explanation: "Claim → support → qualification.",
    difficulty: "M",
  },
  {
    stem: "A passage describes the life cycle of a butterfly from egg to larva to pupa to adult. Which best describes the structure?",
    options: [
      "It describes a biological process in chronological order.",
      "It compares two related species.",
      "It presents a problem and offers a solution.",
      "It makes a claim and defends it.",
    ],
    correct: 0,
    explanation: "Sequential process description.",
    difficulty: "F",
  },
  {
    stem: "A passage describes a busy urban intersection during rush hour, then flashes back to the same intersection a century earlier, then returns to the present. Which best describes the structure?",
    options: [
      "Present scene, historical flashback, return to the present.",
      "Cause followed by effect.",
      "A claim and its supporting evidence.",
      "Two intersections compared.",
    ],
    correct: 0,
    explanation: "Frame structure: present → past → present.",
    difficulty: "M",
  },
  {
    stem: "A passage compares two approaches to treating anxiety — medication and therapy — outlining the strengths and weaknesses of each. Which best describes the structure?",
    options: [
      "Two approaches are weighed against each other.",
      "A chronological narrative of one patient.",
      "A term is defined and examples follow.",
      "A single claim is made and defended.",
    ],
    correct: 0,
    explanation: "Compare/contrast of two treatments.",
    difficulty: "F",
  },
  {
    stem: "A passage describes rising sea levels as a threat, identifies greenhouse-gas emissions as the cause, and concludes with policy proposals. Which best describes the structure?",
    options: [
      "Problem, cause, proposed responses.",
      "A historical narrative.",
      "A definition followed by examples.",
      "A compare and contrast of two coastlines.",
    ],
    correct: 0,
    explanation: "Problem → cause → response.",
    difficulty: "M",
  },
  {
    stem: "A passage defines 'ecological niche,' gives three examples, and explains why the concept matters to biologists. Which best describes the structure?",
    options: [
      "A term is defined, illustrated, and its significance is explained.",
      "Two competing theories are contrasted.",
      "A problem is stated and a single solution is proposed.",
      "Events are narrated in order.",
    ],
    correct: 0,
    explanation: "Definition → examples → significance.",
    difficulty: "M",
  },
  {
    stem: "A passage opens with a surprising experimental result, walks the reader through the method and setup, presents the data, and concludes by interpreting the significance. Which best describes the structure?",
    options: [
      "It presents a result first, then explains the method, data, and meaning.",
      "It narrates a researcher's life chronologically.",
      "It compares two experiments.",
      "It presents a problem and proposes a solution.",
    ],
    correct: 0,
    explanation: "Finding-first structure.",
    difficulty: "M",
  },
  {
    stem: "A passage describes how a particular disease was first recognized, how its cause was identified in the 1950s, and how modern treatments have improved survival rates. Which best describes the structure?",
    options: [
      "A disease is described, its cause is identified, and treatment advances are reviewed.",
      "A single scientist's career is narrated.",
      "Two diseases are compared.",
      "A persuasive argument about policy.",
    ],
    correct: 0,
    explanation: "Description → cause → treatment.",
    difficulty: "M",
  },
  {
    stem: "A passage first argues that remote work is reshaping cities, then cites commuting data from three metro areas, and ends by suggesting that the effect is strongest in areas with good transit. Which best describes the structure?",
    options: [
      "A claim, supporting data, and a qualification.",
      "A problem and a proposed solution.",
      "Two cities compared.",
      "A chronological narrative.",
    ],
    correct: 0,
    explanation: "Claim → data → qualification.",
    difficulty: "M",
  },
  {
    stem: "A passage narrates the steps involved in brewing coffee: grinding beans, heating water, pouring, and steeping. Which best describes the structure?",
    options: [
      "A process is described step by step.",
      "Two brewing methods are compared.",
      "A problem is posed and a solution proposed.",
      "A claim is made and defended.",
    ],
    correct: 0,
    explanation: "Process in order.",
    difficulty: "F",
  },
  {
    stem: "A passage describes two hypotheses for what happened to the Anasazi civilization, weighs the archaeological evidence, and suggests that neither is fully satisfactory. Which best describes the structure?",
    options: [
      "Two hypotheses are weighed against each other and both are judged insufficient.",
      "A process is described in chronological order.",
      "A definition is given and examples follow.",
      "A problem is described and a single solution is proposed.",
    ],
    correct: 0,
    explanation: "Two hypotheses → weighing → both insufficient.",
    difficulty: "C",
  },
  {
    stem: "A passage presents a puzzling historical question, reviews three competing explanations, and argues that the simplest is most persuasive. Which best describes the structure?",
    options: [
      "A question is raised, explanations are surveyed, and one is favored.",
      "A chronological narrative.",
      "A definition and examples.",
      "A problem and a single solution.",
    ],
    correct: 0,
    explanation: "Question → survey → preferred answer.",
    difficulty: "M",
  },
  {
    stem: "A passage describes the morning routine of a firefighter, from waking up to responding to a call. Which best describes the structure?",
    options: [
      "A day's routine is narrated chronologically.",
      "Two firefighters are compared.",
      "A claim is made and defended.",
      "A problem is posed and solved.",
    ],
    correct: 0,
    explanation: "Chronological narrative.",
    difficulty: "F",
  },
  {
    stem: "A passage describes a failed space mission, identifies the engineering flaws that caused the failure, and discusses lessons for future missions. Which best describes the structure?",
    options: [
      "A failure is described, its causes are analyzed, and lessons are drawn.",
      "Two missions are compared.",
      "A definition is followed by examples.",
      "A process is outlined step by step.",
    ],
    correct: 0,
    explanation: "Failure → causes → lessons.",
    difficulty: "M",
  },
  {
    stem: "A passage first claims that screen time harms teen sleep, cites two studies, then addresses the objection that correlation isn't causation by pointing to experimental evidence. Which best describes the structure?",
    options: [
      "A claim is supported with evidence, and an objection is then addressed.",
      "Two media forms are compared.",
      "A problem is posed and a solution proposed.",
      "A process is described step by step.",
    ],
    correct: 0,
    explanation: "Claim → evidence → counter-address.",
    difficulty: "M",
  },
  {
    stem: "A passage defines 'heuristic,' gives a classroom example, explains its benefits and limits, and finally suggests when heuristics should and shouldn't be used. Which best describes the structure?",
    options: [
      "A term is defined, illustrated, evaluated, and given usage guidance.",
      "A historical narrative about psychology.",
      "Two psychological theories are contrasted.",
      "A problem is described with one clear solution.",
    ],
    correct: 0,
    explanation: "Definition → example → evaluation → guidance.",
    difficulty: "C",
  },
  {
    stem: "A passage describes the global water crisis, outlines four possible solutions, and ranks them by practicality. Which best describes the structure?",
    options: [
      "A problem is described, several solutions are offered, and they are ranked.",
      "A definition is followed by examples.",
      "A chronological narrative of one researcher.",
      "Two regions are compared.",
    ],
    correct: 0,
    explanation: "Problem → solutions → ranking.",
    difficulty: "C",
  },
  {
    stem: "A passage opens with a character arriving at a crowded train station, describes her growing anxiety in the crowd, and ends with her boarding her train and feeling calm. Which best describes the structure?",
    options: [
      "A character moves from anxiety to resolution across a brief narrative.",
      "Two characters are compared.",
      "A claim is made and defended.",
      "A process is described step by step.",
    ],
    correct: 0,
    explanation: "Arrival → anxiety → resolution.",
    difficulty: "C",
  },
  {
    stem: "A passage opens by saying a widely accepted belief about sleep needs is outdated, cites recent sleep research, and concludes that the accepted belief should be revised. Which best describes the structure?",
    options: [
      "An accepted belief is challenged with evidence and judged incorrect.",
      "Two theories are compared.",
      "A definition is given with examples.",
      "A process is described in order.",
    ],
    correct: 0,
    explanation: "Accepted belief → challenge → correction.",
    difficulty: "C",
  },
];

const psat89 = [
  {
    stem: "A passage describes a small fishing village in the 1960s, explains how the construction of a nearby highway in the 1980s changed its economy, and ends by showing the village today. Which choice best describes the structure?",
    options: [
      "An earlier state, a cause of change, and the current state.",
      "Two villages are compared.",
      "A problem is posed and solved.",
      "A definition is followed by examples.",
    ],
    correct: 0,
    explanation: "Past → cause → present.",
    difficulty: "M",
  },
  {
    stem: "A passage argues that walking improves memory, cites a 2020 study, and acknowledges that the improvement depends on how often a person walks. Which best describes the structure?",
    options: [
      "A claim, evidence, and a qualification.",
      "A problem and its solution.",
      "A chronological narrative.",
      "Two activities compared.",
    ],
    correct: 0,
    explanation: "Claim → support → qualification.",
    difficulty: "M",
  },
  {
    stem: "A passage describes how a frog develops from egg to tadpole to adult. Which best describes the structure?",
    options: [
      "A process is described in chronological order.",
      "Two species are compared.",
      "A problem and a solution are presented.",
      "A claim and its defense.",
    ],
    correct: 0,
    explanation: "Sequential process description.",
    difficulty: "F",
  },
  {
    stem: "A passage describes a character riding the subway home, flashes back to her difficult day at work, and ends with her arriving home and resolving to do better tomorrow. Which best describes the structure?",
    options: [
      "Present moment, flashback, return to the present with a resolution.",
      "A claim and its support.",
      "A problem and a solution.",
      "Two characters compared.",
    ],
    correct: 0,
    explanation: "Present → flashback → present.",
    difficulty: "M",
  },
  {
    stem: "A passage compares two methods of teaching math — direct instruction and inquiry-based learning — by discussing strengths and weaknesses of each. Which best describes the structure?",
    options: [
      "Two methods are compared on their strengths and weaknesses.",
      "A chronological narrative.",
      "A definition followed by examples.",
      "A single claim is made and defended.",
    ],
    correct: 0,
    explanation: "Compare/contrast.",
    difficulty: "F",
  },
  {
    stem: "A passage describes food waste as a major problem, identifies overproduction and poor storage as the main causes, and proposes community composting and better packaging as solutions. Which best describes the structure?",
    options: [
      "Problem, causes, proposed responses.",
      "A historical narrative.",
      "A definition and examples.",
      "A compare and contrast of two foods.",
    ],
    correct: 0,
    explanation: "Problem → causes → responses.",
    difficulty: "M",
  },
  {
    stem: "A passage defines 'biodiversity,' gives three examples of biodiverse ecosystems, and explains why the concept matters to conservation. Which best describes the structure?",
    options: [
      "A term is defined, illustrated, and its significance is explained.",
      "Two ecosystems are compared.",
      "A problem is posed and solved.",
      "A process is described in order.",
    ],
    correct: 0,
    explanation: "Definition → examples → significance.",
    difficulty: "M",
  },
  {
    stem: "A passage opens with a striking result from a nutrition study, explains the study's design, reports the data, and interprets the findings. Which best describes the structure?",
    options: [
      "It begins with a result, then explains how the result was obtained and what it means.",
      "It narrates a researcher's life.",
      "It compares two studies.",
      "It presents a problem and a solution.",
    ],
    correct: 0,
    explanation: "Finding-first structure.",
    difficulty: "M",
  },
  {
    stem: "A passage describes the discovery of a new kind of jellyfish, explains the circumstances of its discovery, and ends with questions researchers still want to answer. Which best describes the structure?",
    options: [
      "A discovery is described, its context is given, and open questions are listed.",
      "Two species are compared.",
      "A problem and a solution are presented.",
      "A claim is made and defended.",
    ],
    correct: 0,
    explanation: "Discovery → context → open questions.",
    difficulty: "M",
  },
  {
    stem: "A passage argues that after-school clubs improve grades, cites two studies, and notes that the effect is strongest for students who attend regularly. Which best describes the structure?",
    options: [
      "A claim, supporting evidence, and a qualification.",
      "A problem and its cause.",
      "Two clubs compared.",
      "A chronological narrative.",
    ],
    correct: 0,
    explanation: "Claim → evidence → qualification.",
    difficulty: "M",
  },
  {
    stem: "A passage describes the steps needed to plant a garden: preparing soil, spacing the seeds, watering, and weeding. Which best describes the structure?",
    options: [
      "A process is described in order.",
      "Two gardens are compared.",
      "A problem and a solution are presented.",
      "A claim is made and defended.",
    ],
    correct: 0,
    explanation: "Process description.",
    difficulty: "F",
  },
  {
    stem: "A passage describes two theories of why a certain island bird went extinct, weighs the evidence for each, and concludes that habitat loss is the most likely cause. Which best describes the structure?",
    options: [
      "Two theories are weighed and one is favored.",
      "A chronological narrative.",
      "A definition with examples.",
      "A problem and a solution.",
    ],
    correct: 0,
    explanation: "Two theories → weighing → favored one.",
    difficulty: "M",
  },
  {
    stem: "A passage presents a puzzling historical question, reviews three possible answers, and argues that the most recent is best supported. Which best describes the structure?",
    options: [
      "A question, multiple answers, and a favored answer.",
      "A definition with examples.",
      "A compare and contrast of two documents.",
      "A chronological narrative.",
    ],
    correct: 0,
    explanation: "Question → options → favored option.",
    difficulty: "M",
  },
  {
    stem: "A passage narrates the morning of a newspaper reporter from waking up to filing a story. Which best describes the structure?",
    options: [
      "A morning is narrated in chronological order.",
      "A claim is made and defended.",
      "Two reporters are compared.",
      "A problem is posed and solved.",
    ],
    correct: 0,
    explanation: "Chronological narrative.",
    difficulty: "F",
  },
  {
    stem: "A passage describes a dam that failed, identifies design flaws that led to the failure, and discusses what engineers now do differently. Which best describes the structure?",
    options: [
      "A failure is described, its causes are analyzed, and present-day practices are drawn from the lessons.",
      "Two dams are compared.",
      "A process is described in order.",
      "A definition is given with examples.",
    ],
    correct: 0,
    explanation: "Failure → causes → lessons.",
    difficulty: "M",
  },
  {
    stem: "A passage first claims that homework harms sleep, cites three studies, and then responds to the objection that homework prepares students for college. Which best describes the structure?",
    options: [
      "A claim is supported with evidence, and an objection is then addressed.",
      "A definition and examples.",
      "A compare and contrast of two schools.",
      "A process described in order.",
    ],
    correct: 0,
    explanation: "Claim → evidence → counter-address.",
    difficulty: "M",
  },
  {
    stem: "A passage defines 'placebo effect,' gives a medical example, explains why it matters in clinical trials, and suggests how researchers control for it. Which best describes the structure?",
    options: [
      "A term is defined, illustrated, explained in importance, and then its handling described.",
      "Two medications are compared.",
      "A historical narrative.",
      "A problem and a single solution.",
    ],
    correct: 0,
    explanation: "Definition → example → importance → handling.",
    difficulty: "C",
  },
  {
    stem: "A passage describes traffic congestion in a big city, lists three proposed solutions (toll lanes, mass transit, remote work), and ranks them by feasibility. Which best describes the structure?",
    options: [
      "A problem is described, solutions are offered, and they are ranked.",
      "A definition is followed by examples.",
      "A chronological narrative.",
      "Two cities are compared.",
    ],
    correct: 0,
    explanation: "Problem → solutions → ranking.",
    difficulty: "C",
  },
  {
    stem: "A passage opens with a character walking into an empty theater, describes her growing unease, and ends with her discovering that the theater was closed for renovation. Which best describes the structure?",
    options: [
      "A character's experience is traced from unease to explanation.",
      "A claim is made and defended.",
      "Two theaters are compared.",
      "A process is described in order.",
    ],
    correct: 0,
    explanation: "Unease → explanation.",
    difficulty: "C",
  },
  {
    stem: "A passage begins by noting that many people believe eight glasses of water a day is necessary, cites recent research disputing that belief, and concludes that the claim is overstated. Which best describes the structure?",
    options: [
      "A common belief is challenged with evidence and judged incorrect.",
      "Two studies are compared.",
      "A definition is given with examples.",
      "A chronological narrative.",
    ],
    correct: 0,
    explanation: "Common belief → challenge → correction.",
    difficulty: "C",
  },
];

export default {
  skill: "text_structure",
  skillLabel: "Text structure",
  domain: "Information & Ideas",
  section: "rw",
  batches: {
    "sat-rw": sat,
    "nmsqt-rw": nmsqt,
    "psat89-rw": psat89,
  },
};
