// Unit circle and radians — 60 questions (20 per test type)

const sat = [
  {
    stem: "How many radians are equal to $180$ degrees?",
    options: ["$\\pi$", "$2\\pi$", "$\\frac{\\pi}{2}$", "$180\\pi$"],
    correct: 0,
    explanation: "$180° \\cdot \\frac{\\pi}{180} = \\pi$ radians.",
    difficulty: "F",
  },
  {
    stem: "Convert $60°$ to radians.",
    options: ["$\\frac{\\pi}{3}$", "$\\frac{\\pi}{6}$", "$\\frac{\\pi}{2}$", "$60\\pi$"],
    correct: 0,
    explanation: "$60 \\cdot \\frac{\\pi}{180} = \\frac{\\pi}{3}$.",
    difficulty: "F",
  },
  {
    stem: "Convert $\\frac{3\\pi}{2}$ radians to degrees.",
    options: ["$270°$", "$90°$", "$180°$", "$360°$"],
    correct: 0,
    explanation: "$\\frac{3\\pi}{2} \\cdot \\frac{180}{\\pi} = 270°$.",
    difficulty: "F",
  },
  {
    stem: "On the unit circle, what are the coordinates of the point at angle $0$ radians?",
    options: ["$(1, 0)$", "$(0, 1)$", "$(-1, 0)$", "$(0, 0)$"],
    correct: 0,
    explanation: "At $\\theta = 0$, $\\cos 0 = 1$ and $\\sin 0 = 0$. The point is $(1, 0)$.",
    difficulty: "F",
  },
  {
    stem: "What is the exact value of $\\sin\\!\\left(\\frac{\\pi}{2}\\right)$?",
    options: ["$1$", "$0$", "$-1$", "$\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\sin(\\pi/2) = \\sin(90°) = 1$.",
    difficulty: "F",
  },
  {
    stem: "What is $\\cos(\\pi)$?",
    options: ["$-1$", "$1$", "$0$", "$\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\cos(\\pi) = \\cos(180°) = -1$.",
    difficulty: "F",
  },
  {
    stem: "What is the exact value of $\\sin\\!\\left(\\frac{\\pi}{6}\\right)$?",
    options: ["$\\frac{1}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{2}}{2}$", "$1$"],
    correct: 0,
    explanation: "$\\sin(30°) = 1/2$.",
    difficulty: "M",
  },
  {
    stem: "What is the exact value of $\\cos\\!\\left(\\frac{\\pi}{4}\\right)$?",
    options: ["$\\frac{\\sqrt{2}}{2}$", "$\\frac{1}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$1$"],
    correct: 0,
    explanation: "$\\cos(45°) = \\sqrt{2}/2$.",
    difficulty: "M",
  },
  {
    stem: "What is $\\tan\\!\\left(\\frac{\\pi}{4}\\right)$?",
    options: ["$1$", "$\\frac{\\sqrt{2}}{2}$", "$0$", "$\\sqrt{3}$"],
    correct: 0,
    explanation: "$\\tan(45°) = \\sin(45°)/\\cos(45°) = 1$.",
    difficulty: "M",
  },
  {
    stem: "In which quadrant is the angle $\\frac{5\\pi}{4}$?",
    options: ["Quadrant III", "Quadrant I", "Quadrant II", "Quadrant IV"],
    correct: 0,
    explanation: "$\\frac{5\\pi}{4}$ corresponds to $225°$, which lies in Quadrant III.",
    difficulty: "M",
  },
  {
    stem: "Evaluate $\\cos\\!\\left(\\frac{2\\pi}{3}\\right)$.",
    options: ["$-\\frac{1}{2}$", "$\\frac{1}{2}$", "$-\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{3}}{2}$"],
    correct: 0,
    explanation: "$\\frac{2\\pi}{3} = 120°$ in Q2. Reference angle $\\pi/3$ gives $\\cos = 1/2$; Q2 cosine is negative, so $-1/2$.",
    difficulty: "M",
  },
  {
    stem: "Evaluate $\\sin\\!\\left(\\frac{7\\pi}{6}\\right)$.",
    options: ["$-\\frac{1}{2}$", "$\\frac{1}{2}$", "$-\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{3}}{2}$"],
    correct: 0,
    explanation: "$\\frac{7\\pi}{6} = 210°$ in Q3. Reference angle $\\pi/6$ gives $\\sin = 1/2$; Q3 sine is negative, so $-1/2$.",
    difficulty: "M",
  },
  {
    stem: "Convert $225°$ to radians.",
    options: ["$\\frac{5\\pi}{4}$", "$\\frac{3\\pi}{4}$", "$\\frac{7\\pi}{4}$", "$\\frac{4\\pi}{5}$"],
    correct: 0,
    explanation: "$225 \\cdot \\frac{\\pi}{180} = \\frac{225\\pi}{180} = \\frac{5\\pi}{4}$.",
    difficulty: "M",
  },
  {
    stem: "Convert $\\frac{7\\pi}{6}$ radians to degrees.",
    options: ["$210°$", "$105°$", "$150°$", "$420°$"],
    correct: 0,
    explanation: "$\\frac{7\\pi}{6} \\cdot \\frac{180}{\\pi} = \\frac{7 \\cdot 180}{6} = 210°$.",
    difficulty: "M",
  },
  {
    stem: "On the unit circle, the point $P = \\left(\\frac{\\sqrt{3}}{2}, \\frac{1}{2}\\right)$ corresponds to which angle (in radians)?",
    options: ["$\\frac{\\pi}{6}$", "$\\frac{\\pi}{3}$", "$\\frac{\\pi}{4}$", "$\\frac{5\\pi}{6}$"],
    correct: 0,
    explanation: "$\\cos\\theta = \\sqrt{3}/2$ and $\\sin\\theta = 1/2$ at $\\theta = \\pi/6$ (that is, $30°$).",
    difficulty: "M",
  },
  {
    stem: "What is $\\sin\\!\\left(\\frac{\\pi}{3}\\right)$?",
    options: ["$\\frac{\\sqrt{3}}{2}$", "$\\frac{1}{2}$", "$\\frac{\\sqrt{2}}{2}$", "$1$"],
    correct: 0,
    explanation: "$\\sin(60°) = \\sqrt{3}/2$.",
    difficulty: "M",
  },
  {
    stem: "What is $\\cos\\!\\left(\\frac{\\pi}{3}\\right)$?",
    options: ["$\\frac{1}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{2}}{2}$", "$0$"],
    correct: 0,
    explanation: "$\\cos(60°) = 1/2$.",
    difficulty: "M",
  },
  {
    stem: "Evaluate $\\tan\\!\\left(\\frac{\\pi}{3}\\right)$.",
    options: ["$\\sqrt{3}$", "$\\frac{1}{\\sqrt{3}}$", "$1$", "$\\frac{\\sqrt{3}}{2}$"],
    correct: 0,
    explanation: "$\\tan(60°) = \\frac{\\sin 60°}{\\cos 60°} = \\frac{\\sqrt{3}/2}{1/2} = \\sqrt{3}$.",
    difficulty: "C",
  },
  {
    stem: "Evaluate $\\sin\\!\\left(\\frac{11\\pi}{6}\\right)$.",
    options: ["$-\\frac{1}{2}$", "$\\frac{1}{2}$", "$-\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{3}}{2}$"],
    correct: 0,
    explanation: "$\\frac{11\\pi}{6} = 330°$ in Q4. Reference angle $\\pi/6$; sine in Q4 is negative. Answer: $-1/2$.",
    difficulty: "C",
  },
  {
    stem: "The terminal side of an angle $\\theta$ lies on the unit circle at the point $\\left(-\\frac{\\sqrt{2}}{2}, \\frac{\\sqrt{2}}{2}\\right)$. What is the smallest positive value of $\\theta$ in radians?",
    options: ["$\\frac{3\\pi}{4}$", "$\\frac{\\pi}{4}$", "$\\frac{5\\pi}{4}$", "$\\frac{7\\pi}{4}$"],
    correct: 0,
    explanation: "Negative $x$, positive $y$ → Q2. Reference angle $\\pi/4$ (where $\\cos = \\sin = \\sqrt{2}/2$). In Q2: $\\pi - \\pi/4 = 3\\pi/4$.",
    difficulty: "C",
  },
];

const nmsqt = [
  {
    stem: "How many radians are in $360°$?",
    options: ["$2\\pi$", "$\\pi$", "$\\frac{\\pi}{2}$", "$360\\pi$"],
    correct: 0,
    explanation: "A full turn is $2\\pi$ radians.",
    difficulty: "F",
  },
  {
    stem: "Convert $30°$ to radians.",
    options: ["$\\frac{\\pi}{6}$", "$\\frac{\\pi}{3}$", "$\\frac{\\pi}{2}$", "$30\\pi$"],
    correct: 0,
    explanation: "$30 \\cdot \\frac{\\pi}{180} = \\frac{\\pi}{6}$.",
    difficulty: "F",
  },
  {
    stem: "Convert $\\frac{\\pi}{2}$ radians to degrees.",
    options: ["$90°$", "$45°$", "$180°$", "$270°$"],
    correct: 0,
    explanation: "$\\frac{\\pi}{2} \\cdot \\frac{180}{\\pi} = 90°$.",
    difficulty: "F",
  },
  {
    stem: "At $\\theta = \\frac{\\pi}{2}$ on the unit circle, what are the coordinates?",
    options: ["$(0, 1)$", "$(1, 0)$", "$(0, -1)$", "$(-1, 0)$"],
    correct: 0,
    explanation: "$\\cos(\\pi/2) = 0$ and $\\sin(\\pi/2) = 1$.",
    difficulty: "F",
  },
  {
    stem: "What is $\\cos(0)$?",
    options: ["$1$", "$0$", "$-1$", "$\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\cos 0° = 1$.",
    difficulty: "F",
  },
  {
    stem: "What is $\\sin(\\pi)$?",
    options: ["$0$", "$1$", "$-1$", "$\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\sin(180°) = 0$.",
    difficulty: "F",
  },
  {
    stem: "What is $\\cos\\!\\left(\\frac{\\pi}{6}\\right)$?",
    options: ["$\\frac{\\sqrt{3}}{2}$", "$\\frac{1}{2}$", "$\\frac{\\sqrt{2}}{2}$", "$1$"],
    correct: 0,
    explanation: "$\\cos(30°) = \\sqrt{3}/2$.",
    difficulty: "M",
  },
  {
    stem: "What is $\\sin\\!\\left(\\frac{\\pi}{4}\\right)$?",
    options: ["$\\frac{\\sqrt{2}}{2}$", "$\\frac{1}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$1$"],
    correct: 0,
    explanation: "$\\sin(45°) = \\sqrt{2}/2$.",
    difficulty: "M",
  },
  {
    stem: "What is $\\tan(0)$?",
    options: ["$0$", "$1$", "$\\text{undefined}$", "$-1$"],
    correct: 0,
    explanation: "$\\tan 0 = \\sin 0 / \\cos 0 = 0/1 = 0$.",
    difficulty: "M",
  },
  {
    stem: "In which quadrant is the angle $\\frac{3\\pi}{4}$?",
    options: ["Quadrant II", "Quadrant I", "Quadrant III", "Quadrant IV"],
    correct: 0,
    explanation: "$\\frac{3\\pi}{4} = 135°$, which lies in Q2.",
    difficulty: "M",
  },
  {
    stem: "Evaluate $\\sin\\!\\left(\\frac{5\\pi}{6}\\right)$.",
    options: ["$\\frac{1}{2}$", "$-\\frac{1}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$-\\frac{\\sqrt{3}}{2}$"],
    correct: 0,
    explanation: "$\\frac{5\\pi}{6} = 150°$ in Q2. Reference angle $\\pi/6$; sine in Q2 is positive. $\\sin(\\pi/6) = 1/2$.",
    difficulty: "M",
  },
  {
    stem: "Evaluate $\\cos\\!\\left(\\frac{4\\pi}{3}\\right)$.",
    options: ["$-\\frac{1}{2}$", "$\\frac{1}{2}$", "$-\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{3}}{2}$"],
    correct: 0,
    explanation: "$\\frac{4\\pi}{3} = 240°$ in Q3. Reference angle $\\pi/3$; cosine in Q3 is negative. $-1/2$.",
    difficulty: "M",
  },
  {
    stem: "Convert $150°$ to radians.",
    options: ["$\\frac{5\\pi}{6}$", "$\\frac{2\\pi}{3}$", "$\\frac{3\\pi}{4}$", "$\\frac{\\pi}{6}$"],
    correct: 0,
    explanation: "$150 \\cdot \\frac{\\pi}{180} = \\frac{5\\pi}{6}$.",
    difficulty: "M",
  },
  {
    stem: "Convert $\\frac{5\\pi}{3}$ radians to degrees.",
    options: ["$300°$", "$150°$", "$240°$", "$360°$"],
    correct: 0,
    explanation: "$\\frac{5\\pi}{3} \\cdot \\frac{180}{\\pi} = 300°$.",
    difficulty: "M",
  },
  {
    stem: "On the unit circle, the point $\\left(\\frac{1}{2}, \\frac{\\sqrt{3}}{2}\\right)$ corresponds to which angle in radians?",
    options: ["$\\frac{\\pi}{3}$", "$\\frac{\\pi}{6}$", "$\\frac{\\pi}{4}$", "$\\frac{2\\pi}{3}$"],
    correct: 0,
    explanation: "$\\cos\\theta = 1/2$ and $\\sin\\theta = \\sqrt{3}/2$ at $\\theta = \\pi/3$ (that is, $60°$).",
    difficulty: "M",
  },
  {
    stem: "What is $\\cos\\!\\left(\\frac{\\pi}{2}\\right)$?",
    options: ["$0$", "$1$", "$-1$", "$\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\cos(90°) = 0$.",
    difficulty: "F",
  },
  {
    stem: "What is $\\sin\\!\\left(\\frac{3\\pi}{2}\\right)$?",
    options: ["$-1$", "$0$", "$1$", "$-\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\sin(270°) = -1$.",
    difficulty: "M",
  },
  {
    stem: "Evaluate $\\cos\\!\\left(\\frac{11\\pi}{6}\\right)$.",
    options: ["$\\frac{\\sqrt{3}}{2}$", "$-\\frac{\\sqrt{3}}{2}$", "$\\frac{1}{2}$", "$-\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\frac{11\\pi}{6} = 330°$ in Q4. Reference angle $\\pi/6$; cosine in Q4 is positive. $\\sqrt{3}/2$.",
    difficulty: "C",
  },
  {
    stem: "Evaluate $\\tan\\!\\left(\\frac{\\pi}{6}\\right)$.",
    options: ["$\\frac{1}{\\sqrt{3}}$", "$\\sqrt{3}$", "$\\frac{\\sqrt{3}}{2}$", "$1$"],
    correct: 0,
    explanation: "$\\tan(30°) = \\sin 30° / \\cos 30° = (1/2) / (\\sqrt{3}/2) = 1/\\sqrt{3}$.",
    difficulty: "C",
  },
  {
    stem: "The terminal side of an angle $\\theta$ in standard position meets the unit circle at $\\left(-\\frac{1}{2}, -\\frac{\\sqrt{3}}{2}\\right)$. What is the smallest positive $\\theta$ in radians?",
    options: ["$\\frac{4\\pi}{3}$", "$\\frac{2\\pi}{3}$", "$\\frac{5\\pi}{3}$", "$\\frac{\\pi}{3}$"],
    correct: 0,
    explanation: "Both coordinates negative → Q3. Reference angle where $\\cos = 1/2$ and $\\sin = \\sqrt{3}/2$ is $\\pi/3$. In Q3: $\\pi + \\pi/3 = 4\\pi/3$.",
    difficulty: "C",
  },
];

const psat89 = [
  {
    stem: "How many radians are in $90$ degrees?",
    options: ["$\\frac{\\pi}{2}$", "$\\pi$", "$\\frac{\\pi}{4}$", "$90\\pi$"],
    correct: 0,
    explanation: "$90 \\cdot \\frac{\\pi}{180} = \\frac{\\pi}{2}$.",
    difficulty: "F",
  },
  {
    stem: "Convert $45°$ to radians.",
    options: ["$\\frac{\\pi}{4}$", "$\\frac{\\pi}{6}$", "$\\frac{\\pi}{3}$", "$45\\pi$"],
    correct: 0,
    explanation: "$45 \\cdot \\frac{\\pi}{180} = \\frac{\\pi}{4}$.",
    difficulty: "F",
  },
  {
    stem: "Convert $\\pi$ radians to degrees.",
    options: ["$180°$", "$90°$", "$360°$", "$270°$"],
    correct: 0,
    explanation: "$\\pi \\cdot \\frac{180}{\\pi} = 180°$.",
    difficulty: "F",
  },
  {
    stem: "At $\\theta = \\pi$ on the unit circle, what are the coordinates?",
    options: ["$(-1, 0)$", "$(0, -1)$", "$(1, 0)$", "$(0, 1)$"],
    correct: 0,
    explanation: "$\\cos \\pi = -1$, $\\sin \\pi = 0$.",
    difficulty: "F",
  },
  {
    stem: "What is $\\sin(0)$?",
    options: ["$0$", "$1$", "$-1$", "$\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\sin 0° = 0$.",
    difficulty: "F",
  },
  {
    stem: "What is $\\cos\\!\\left(\\frac{3\\pi}{2}\\right)$?",
    options: ["$0$", "$1$", "$-1$", "$\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\cos(270°) = 0$.",
    difficulty: "F",
  },
  {
    stem: "What is $\\tan\\!\\left(\\frac{\\pi}{4}\\right)$?",
    options: ["$1$", "$0$", "$\\sqrt{3}$", "$\\frac{\\sqrt{2}}{2}$"],
    correct: 0,
    explanation: "$\\tan(45°) = 1$.",
    difficulty: "M",
  },
  {
    stem: "What is $\\cos\\!\\left(\\frac{\\pi}{3}\\right)$?",
    options: ["$\\frac{1}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{2}}{2}$", "$0$"],
    correct: 0,
    explanation: "$\\cos(60°) = 1/2$.",
    difficulty: "M",
  },
  {
    stem: "What is $\\sin\\!\\left(\\frac{\\pi}{3}\\right)$?",
    options: ["$\\frac{\\sqrt{3}}{2}$", "$\\frac{1}{2}$", "$\\frac{\\sqrt{2}}{2}$", "$1$"],
    correct: 0,
    explanation: "$\\sin(60°) = \\sqrt{3}/2$.",
    difficulty: "M",
  },
  {
    stem: "In which quadrant is the angle $\\frac{7\\pi}{4}$?",
    options: ["Quadrant IV", "Quadrant I", "Quadrant II", "Quadrant III"],
    correct: 0,
    explanation: "$\\frac{7\\pi}{4} = 315°$, which lies in Q4.",
    difficulty: "M",
  },
  {
    stem: "Evaluate $\\cos\\!\\left(\\frac{5\\pi}{6}\\right)$.",
    options: ["$-\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$-\\frac{1}{2}$", "$\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\frac{5\\pi}{6} = 150°$ in Q2. Reference angle $\\pi/6$, so $\\cos = \\sqrt{3}/2$; Q2 cosine is negative. Answer: $-\\sqrt{3}/2$.",
    difficulty: "M",
  },
  {
    stem: "Evaluate $\\sin\\!\\left(\\frac{5\\pi}{4}\\right)$.",
    options: ["$-\\frac{\\sqrt{2}}{2}$", "$\\frac{\\sqrt{2}}{2}$", "$-\\frac{1}{2}$", "$\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\frac{5\\pi}{4} = 225°$ in Q3. Reference angle $\\pi/4$, so $\\sin = \\sqrt{2}/2$; Q3 sine is negative. $-\\sqrt{2}/2$.",
    difficulty: "M",
  },
  {
    stem: "Convert $120°$ to radians.",
    options: ["$\\frac{2\\pi}{3}$", "$\\frac{\\pi}{3}$", "$\\frac{5\\pi}{6}$", "$\\frac{3\\pi}{4}$"],
    correct: 0,
    explanation: "$120 \\cdot \\frac{\\pi}{180} = \\frac{2\\pi}{3}$.",
    difficulty: "M",
  },
  {
    stem: "Convert $\\frac{2\\pi}{3}$ radians to degrees.",
    options: ["$120°$", "$60°$", "$240°$", "$180°$"],
    correct: 0,
    explanation: "$\\frac{2\\pi}{3} \\cdot \\frac{180}{\\pi} = 120°$.",
    difficulty: "M",
  },
  {
    stem: "On the unit circle, the point $\\left(\\frac{\\sqrt{2}}{2}, \\frac{\\sqrt{2}}{2}\\right)$ corresponds to which angle in radians?",
    options: ["$\\frac{\\pi}{4}$", "$\\frac{\\pi}{2}$", "$\\frac{\\pi}{6}$", "$\\frac{3\\pi}{4}$"],
    correct: 0,
    explanation: "$\\cos = \\sin = \\sqrt{2}/2$ at $\\theta = \\pi/4$ ($45°$).",
    difficulty: "M",
  },
  {
    stem: "What is $\\sin\\!\\left(\\frac{\\pi}{6}\\right)$?",
    options: ["$\\frac{1}{2}$", "$\\frac{\\sqrt{3}}{2}$", "$\\frac{\\sqrt{2}}{2}$", "$1$"],
    correct: 0,
    explanation: "$\\sin(30°) = 1/2$.",
    difficulty: "F",
  },
  {
    stem: "What is $\\cos\\!\\left(2\\pi\\right)$?",
    options: ["$1$", "$0$", "$-1$", "$2$"],
    correct: 0,
    explanation: "$2\\pi$ is a full turn back to the start. $\\cos(2\\pi) = \\cos 0 = 1$.",
    difficulty: "M",
  },
  {
    stem: "Evaluate $\\sin\\!\\left(\\frac{2\\pi}{3}\\right)$.",
    options: ["$\\frac{\\sqrt{3}}{2}$", "$-\\frac{\\sqrt{3}}{2}$", "$\\frac{1}{2}$", "$-\\frac{1}{2}$"],
    correct: 0,
    explanation: "$\\frac{2\\pi}{3} = 120°$ in Q2. Reference angle $\\pi/3$, $\\sin = \\sqrt{3}/2$; Q2 sine is positive. $\\sqrt{3}/2$.",
    difficulty: "C",
  },
  {
    stem: "Evaluate $\\tan\\!\\left(\\frac{\\pi}{3}\\right)$.",
    options: ["$\\sqrt{3}$", "$\\frac{1}{\\sqrt{3}}$", "$1$", "$\\frac{\\sqrt{3}}{2}$"],
    correct: 0,
    explanation: "$\\tan(60°) = (\\sqrt{3}/2) / (1/2) = \\sqrt{3}$.",
    difficulty: "C",
  },
  {
    stem: "The terminal side of angle $\\theta$ in standard position meets the unit circle at $\\left(\\frac{1}{2}, -\\frac{\\sqrt{3}}{2}\\right)$. What is the smallest positive $\\theta$ in radians?",
    options: ["$\\frac{5\\pi}{3}$", "$\\frac{\\pi}{3}$", "$\\frac{2\\pi}{3}$", "$\\frac{4\\pi}{3}$"],
    correct: 0,
    explanation: "Positive $x$, negative $y$ → Q4. Reference angle $\\pi/3$. In Q4: $2\\pi - \\pi/3 = 5\\pi/3$.",
    difficulty: "C",
  },
];

export default {
  skill: "unit_circle",
  skillLabel: "Unit circle and radians",
  domain: "Geometry & Trig",
  section: "math",
  batches: {
    "sat-math": sat,
    "nmsqt-math": nmsqt,
    "psat89-math": psat89,
  },
};
