// Unit conversion — 60 questions (20 per test type)
// Difficulty: F=foundation, M=medium, C=challenging

const sat = [
  {
    stem: "A runner completes a race in $5$ minutes. How many seconds did it take?",
    options: ["$300$ seconds", "$30$ seconds", "$60$ seconds", "$3600$ seconds"],
    correct: 0,
    explanation: "One minute equals $60$ seconds, so $5 \\text{ min} \\times 60 = 300$ seconds.",
    difficulty: "F",
  },
  {
    stem: "A box weighs $8$ kilograms. What is its mass in grams?",
    options: ["$8000$ g", "$80$ g", "$800$ g", "$80000$ g"],
    correct: 0,
    explanation: "$1 \\text{ kg} = 1000 \\text{ g}$, so $8 \\text{ kg} = 8000 \\text{ g}$.",
    difficulty: "F",
  },
  {
    stem: "A bottle holds $3$ liters of water. How many milliliters is that?",
    options: ["$3000$ mL", "$30$ mL", "$300$ mL", "$30000$ mL"],
    correct: 0,
    explanation: "$1 \\text{ L} = 1000 \\text{ mL}$, so $3 \\text{ L} = 3000 \\text{ mL}$.",
    difficulty: "F",
  },
  {
    stem: "A path is $7$ feet long. How many inches is that?",
    options: ["$84$ inches", "$70$ inches", "$42$ inches", "$21$ inches"],
    correct: 0,
    explanation: "$1 \\text{ ft} = 12 \\text{ in}$, so $7 \\text{ ft} = 84$ inches.",
    difficulty: "F",
  },
  {
    stem: "A distance is $2$ miles. What is it in feet? (Use $1 \\text{ mi} = 5280 \\text{ ft}$.)",
    options: ["$10560$ ft", "$5280$ ft", "$2640$ ft", "$1760$ ft"],
    correct: 0,
    explanation: "$2 \\text{ mi} \\times 5280 \\text{ ft/mi} = 10560$ ft.",
    difficulty: "F",
  },
  {
    stem: "A car travels at $20$ meters per second. What is its speed in kilometers per hour?",
    options: ["$72$ km/hr", "$200$ km/hr", "$1200$ km/hr", "$36$ km/hr"],
    correct: 0,
    explanation: "Multiply by $3.6$: $20 \\cdot 3.6 = 72$ km/hr. This uses $\\frac{1 \\text{ km}}{1000 \\text{ m}} \\cdot \\frac{3600 \\text{ s}}{1 \\text{ hr}}$.",
    difficulty: "M",
  },
  {
    stem: "A factory produces $480$ parts per hour. How many parts does it produce per minute?",
    options: ["$8$ per minute", "$28800$ per minute", "$80$ per minute", "$48$ per minute"],
    correct: 0,
    explanation: "Divide by $60$: $480 \\div 60 = 8$ parts per minute.",
    difficulty: "M",
  },
  {
    stem: "A recipe calls for $4$ cups of flour. If $1 \\text{ cup} = 240 \\text{ mL}$, how many milliliters of flour does it need?",
    options: ["$960$ mL", "$240$ mL", "$1200$ mL", "$480$ mL"],
    correct: 0,
    explanation: "$4 \\text{ cups} \\times 240 \\text{ mL/cup} = 960$ mL.",
    difficulty: "M",
  },
  {
    stem: "A road crew paves $25$ yards of road each day. How many feet is that? (Use $1 \\text{ yd} = 3 \\text{ ft}$.)",
    options: ["$75$ ft", "$28$ ft", "$125$ ft", "$8$ ft"],
    correct: 0,
    explanation: "$25 \\text{ yd} \\times 3 \\text{ ft/yd} = 75$ ft.",
    difficulty: "M",
  },
  {
    stem: "A swimming pool holds $50$ gallons of water. Approximately how many liters is that? (Use $1 \\text{ gal} \\approx 3.785 \\text{ L}$.)",
    options: ["$189.25$ L", "$50$ L", "$13.21$ L", "$150$ L"],
    correct: 0,
    explanation: "$50 \\text{ gal} \\times 3.785 \\text{ L/gal} \\approx 189.25$ L.",
    difficulty: "M",
  },
  {
    stem: "A hiker walks $9$ kilometers. How many meters is that?",
    options: ["$9000$ m", "$90$ m", "$900$ m", "$90000$ m"],
    correct: 0,
    explanation: "$1 \\text{ km} = 1000 \\text{ m}$, so $9 \\text{ km} = 9000 \\text{ m}$.",
    difficulty: "F",
  },
  {
    stem: "An object has a mass of $4500$ grams. What is its mass in kilograms?",
    options: ["$4.5$ kg", "$45$ kg", "$0.45$ kg", "$450$ kg"],
    correct: 0,
    explanation: "Divide by $1000$: $4500 \\div 1000 = 4.5$ kg.",
    difficulty: "M",
  },
  {
    stem: "A jet flies at $900$ km/hr. What is its speed in m/s, rounded to the nearest whole number?",
    options: ["$250$ m/s", "$3240$ m/s", "$15$ m/s", "$2500$ m/s"],
    correct: 0,
    explanation: "Divide by $3.6$: $900 \\div 3.6 = 250$ m/s.",
    difficulty: "M",
  },
  {
    stem: "A car's fuel efficiency is $30$ miles per gallon. If it drives $180$ miles, how many gallons does it use?",
    options: ["$6$ gallons", "$5400$ gallons", "$210$ gallons", "$150$ gallons"],
    correct: 0,
    explanation: "Gallons used $= \\frac{180}{30} = 6$ gallons.",
    difficulty: "M",
  },
  {
    stem: "A pump fills a tank at $4$ liters per minute. How many liters does it pump in $2$ hours?",
    options: ["$480$ L", "$8$ L", "$120$ L", "$240$ L"],
    correct: 0,
    explanation: "$2$ hours $= 120$ minutes. $4 \\text{ L/min} \\times 120 \\text{ min} = 480$ L.",
    difficulty: "M",
  },
  {
    stem: "A worker earns $\\$18$ per hour. How much does she earn per minute, to the nearest cent?",
    options: ["$\\$0.30$ per minute", "$\\$18.00$ per minute", "$\\$1.08$ per minute", "$\\$3.00$ per minute"],
    correct: 0,
    explanation: "Divide by $60$: $18 \\div 60 = \\$0.30$ per minute.",
    difficulty: "C",
  },
  {
    stem: "A fabric is priced at $\\$24$ per yard. What is the price per foot? (Use $1 \\text{ yd} = 3 \\text{ ft}$.)",
    options: ["$\\$8$ per foot", "$\\$72$ per foot", "$\\$21$ per foot", "$\\$12$ per foot"],
    correct: 0,
    explanation: "Three feet per yard, so divide by $3$: $24 \\div 3 = \\$8$ per foot.",
    difficulty: "C",
  },
  {
    stem: "A chemist has $4500$ milligrams of a compound. How many grams is that?",
    options: ["$4.5$ g", "$450$ g", "$0.045$ g", "$45$ g"],
    correct: 0,
    explanation: "$1 \\text{ g} = 1000 \\text{ mg}$, so $4500 \\div 1000 = 4.5$ g.",
    difficulty: "F",
  },
  {
    stem: "A train covers $300$ miles in $5$ hours. What is its average speed in miles per hour?",
    options: ["$60$ mph", "$1500$ mph", "$305$ mph", "$55$ mph"],
    correct: 0,
    explanation: "Speed $= \\frac{\\text{distance}}{\\text{time}} = \\frac{300}{5} = 60$ mph.",
    difficulty: "F",
  },
  {
    stem: "A water tank leaks at $50$ milliliters per minute. How many liters does it lose in one hour?",
    options: ["$3$ L", "$0.3$ L", "$30$ L", "$300$ L"],
    correct: 0,
    explanation: "$50 \\text{ mL/min} \\times 60 \\text{ min} = 3000 \\text{ mL} = 3$ L.",
    difficulty: "M",
  },
];

const nmsqt = [
  {
    stem: "A clock chimes every $15$ seconds. How many times does it chime in $1$ minute?",
    options: ["$4$ times", "$15$ times", "$60$ times", "$45$ times"],
    correct: 0,
    explanation: "$60 \\div 15 = 4$ chimes per minute.",
    difficulty: "F",
  },
  {
    stem: "A baby weighs $3.2$ kilograms at birth. How many grams is that?",
    options: ["$3200$ g", "$32$ g", "$320$ g", "$320000$ g"],
    correct: 0,
    explanation: "$1 \\text{ kg} = 1000 \\text{ g}$, so $3.2 \\text{ kg} = 3200$ g.",
    difficulty: "F",
  },
  {
    stem: "A juice carton contains $1.5$ liters. How many milliliters is that?",
    options: ["$1500$ mL", "$15$ mL", "$150$ mL", "$15000$ mL"],
    correct: 0,
    explanation: "$1 \\text{ L} = 1000 \\text{ mL}$, so $1.5 \\text{ L} = 1500$ mL.",
    difficulty: "F",
  },
  {
    stem: "A desk is $48$ inches wide. How many feet is that?",
    options: ["$4$ ft", "$6$ ft", "$12$ ft", "$576$ ft"],
    correct: 0,
    explanation: "$1 \\text{ ft} = 12 \\text{ in}$, so $48 \\div 12 = 4$ ft.",
    difficulty: "F",
  },
  {
    stem: "A racecar completes $3$ laps on a $1.5$-mile track. How many feet did it travel? (Use $1 \\text{ mi} = 5280 \\text{ ft}$.)",
    options: ["$23760$ ft", "$7920$ ft", "$15840$ ft", "$5280$ ft"],
    correct: 0,
    explanation: "$3 \\times 1.5 = 4.5 \\text{ mi}$. Then $4.5 \\times 5280 = 23760$ ft.",
    difficulty: "M",
  },
  {
    stem: "A runner's pace is $4$ meters per second. What is her speed in kilometers per hour?",
    options: ["$14.4$ km/hr", "$240$ km/hr", "$40$ km/hr", "$0.24$ km/hr"],
    correct: 0,
    explanation: "Multiply by $3.6$: $4 \\cdot 3.6 = 14.4$ km/hr.",
    difficulty: "M",
  },
  {
    stem: "A bakery produces $720$ loaves per day. How many loaves per hour is that, on average?",
    options: ["$30$ per hour", "$17280$ per hour", "$43200$ per hour", "$12$ per hour"],
    correct: 0,
    explanation: "Divide by $24$ hours per day: $720 \\div 24 = 30$ per hour.",
    difficulty: "M",
  },
  {
    stem: "A recipe needs $6$ tablespoons of oil. If $1 \\text{ tbsp} = 15 \\text{ mL}$, how many milliliters is that?",
    options: ["$90$ mL", "$21$ mL", "$9$ mL", "$45$ mL"],
    correct: 0,
    explanation: "$6 \\times 15 = 90$ mL.",
    difficulty: "M",
  },
  {
    stem: "A soccer field is $110$ yards long. How many feet is that?",
    options: ["$330$ ft", "$113$ ft", "$220$ ft", "$36.7$ ft"],
    correct: 0,
    explanation: "$1 \\text{ yd} = 3 \\text{ ft}$, so $110 \\times 3 = 330$ ft.",
    difficulty: "F",
  },
  {
    stem: "A gas tank holds $15$ gallons. How many liters is that, to the nearest tenth? (Use $1 \\text{ gal} \\approx 3.785 \\text{ L}$.)",
    options: ["$56.8$ L", "$15$ L", "$4$ L", "$50.5$ L"],
    correct: 0,
    explanation: "$15 \\times 3.785 \\approx 56.78 \\approx 56.8$ L.",
    difficulty: "M",
  },
  {
    stem: "A drone flies $2.5$ kilometers. How many meters is that?",
    options: ["$2500$ m", "$250$ m", "$25000$ m", "$25$ m"],
    correct: 0,
    explanation: "$1 \\text{ km} = 1000 \\text{ m}$, so $2.5 \\text{ km} = 2500$ m.",
    difficulty: "F",
  },
  {
    stem: "A package weighs $1250$ grams. What is its mass in kilograms?",
    options: ["$1.25$ kg", "$125$ kg", "$0.125$ kg", "$12.5$ kg"],
    correct: 0,
    explanation: "Divide by $1000$: $1250 \\div 1000 = 1.25$ kg.",
    difficulty: "F",
  },
  {
    stem: "A cruise ship sails at $36$ km/hr. What is its speed in m/s?",
    options: ["$10$ m/s", "$129.6$ m/s", "$600$ m/s", "$100$ m/s"],
    correct: 0,
    explanation: "Divide by $3.6$: $36 \\div 3.6 = 10$ m/s.",
    difficulty: "M",
  },
  {
    stem: "A car has a fuel efficiency of $25$ miles per gallon. How many gallons does it use on a $200$-mile trip?",
    options: ["$8$ gallons", "$5000$ gallons", "$175$ gallons", "$225$ gallons"],
    correct: 0,
    explanation: "$\\frac{200}{25} = 8$ gallons.",
    difficulty: "M",
  },
  {
    stem: "A faucet drips $5$ milliliters every $2$ minutes. How many milliliters drip in $1$ hour?",
    options: ["$150$ mL", "$10$ mL", "$300$ mL", "$75$ mL"],
    correct: 0,
    explanation: "Rate is $5 \\div 2 = 2.5$ mL/min. Over $60$ min: $2.5 \\times 60 = 150$ mL.",
    difficulty: "C",
  },
  {
    stem: "A babysitter earns $\\$12$ per hour. How much does she earn in $15$ minutes?",
    options: ["$\\$3.00$", "$\\$0.20$", "$\\$180.00$", "$\\$1.80$"],
    correct: 0,
    explanation: "Per minute: $12 \\div 60 = \\$0.20$. For $15$ minutes: $15 \\times 0.20 = \\$3.00$.",
    difficulty: "C",
  },
  {
    stem: "Carpet costs $\\$18$ per square yard. How much does it cost per square foot? (Hint: $1 \\text{ sq yd} = 9 \\text{ sq ft}$.)",
    options: ["$\\$2$ per sq ft", "$\\$54$ per sq ft", "$\\$162$ per sq ft", "$\\$6$ per sq ft"],
    correct: 0,
    explanation: "Divide by $9$ square feet per square yard: $18 \\div 9 = \\$2$ per sq ft.",
    difficulty: "C",
  },
  {
    stem: "A syringe holds $0.8$ grams of medicine. How many milligrams is that?",
    options: ["$800$ mg", "$80$ mg", "$8$ mg", "$0.0008$ mg"],
    correct: 0,
    explanation: "$1 \\text{ g} = 1000 \\text{ mg}$, so $0.8 \\text{ g} = 800$ mg.",
    difficulty: "F",
  },
  {
    stem: "A cyclist rides $45$ miles in $3$ hours. What is her average speed in miles per hour?",
    options: ["$15$ mph", "$135$ mph", "$48$ mph", "$42$ mph"],
    correct: 0,
    explanation: "$\\frac{45}{3} = 15$ mph.",
    difficulty: "F",
  },
  {
    stem: "A water main leaks at $120$ milliliters per minute. How many liters does it lose in $24$ hours?",
    options: ["$172.8$ L", "$17.28$ L", "$2880$ L", "$7.2$ L"],
    correct: 0,
    explanation: "$120 \\text{ mL/min} \\times 60 \\text{ min/hr} \\times 24 \\text{ hr} = 172800 \\text{ mL} = 172.8$ L.",
    difficulty: "C",
  },
];

const psat89 = [
  {
    stem: "How many seconds are there in $4$ minutes?",
    options: ["$240$ seconds", "$40$ seconds", "$24$ seconds", "$400$ seconds"],
    correct: 0,
    explanation: "$4 \\times 60 = 240$ seconds.",
    difficulty: "F",
  },
  {
    stem: "A puppy weighs $6$ kilograms. How many grams is that?",
    options: ["$6000$ g", "$60$ g", "$600$ g", "$60000$ g"],
    correct: 0,
    explanation: "$1 \\text{ kg} = 1000 \\text{ g}$, so $6 \\text{ kg} = 6000$ g.",
    difficulty: "F",
  },
  {
    stem: "A thermos holds $2$ liters of soup. How many milliliters is that?",
    options: ["$2000$ mL", "$20$ mL", "$200$ mL", "$20000$ mL"],
    correct: 0,
    explanation: "$1 \\text{ L} = 1000 \\text{ mL}$, so $2 \\text{ L} = 2000$ mL.",
    difficulty: "F",
  },
  {
    stem: "A ladder is $5$ feet tall. How many inches is that?",
    options: ["$60$ inches", "$50$ inches", "$30$ inches", "$15$ inches"],
    correct: 0,
    explanation: "$1 \\text{ ft} = 12 \\text{ in}$, so $5 \\text{ ft} = 60$ in.",
    difficulty: "F",
  },
  {
    stem: "A distance is $4$ miles. How many feet is that? (Use $1 \\text{ mi} = 5280 \\text{ ft}$.)",
    options: ["$21120$ ft", "$10560$ ft", "$5280$ ft", "$2640$ ft"],
    correct: 0,
    explanation: "$4 \\times 5280 = 21120$ ft.",
    difficulty: "F",
  },
  {
    stem: "A motorcycle travels at $10$ meters per second. What is its speed in kilometers per hour?",
    options: ["$36$ km/hr", "$100$ km/hr", "$600$ km/hr", "$3$ km/hr"],
    correct: 0,
    explanation: "Multiply by $3.6$: $10 \\times 3.6 = 36$ km/hr.",
    difficulty: "M",
  },
  {
    stem: "A printer produces $180$ pages per hour. How many pages does it produce per minute?",
    options: ["$3$ per minute", "$10800$ per minute", "$30$ per minute", "$18$ per minute"],
    correct: 0,
    explanation: "Divide by $60$: $180 \\div 60 = 3$ per minute.",
    difficulty: "M",
  },
  {
    stem: "A cake recipe calls for $3$ cups of milk. If $1 \\text{ cup} = 240 \\text{ mL}$, how many milliliters of milk does it need?",
    options: ["$720$ mL", "$240$ mL", "$900$ mL", "$360$ mL"],
    correct: 0,
    explanation: "$3 \\times 240 = 720$ mL.",
    difficulty: "M",
  },
  {
    stem: "A gardener plants $15$ yards of hedges. How many feet is that?",
    options: ["$45$ ft", "$18$ ft", "$75$ ft", "$5$ ft"],
    correct: 0,
    explanation: "$1 \\text{ yd} = 3 \\text{ ft}$, so $15 \\times 3 = 45$ ft.",
    difficulty: "F",
  },
  {
    stem: "A fish tank holds $10$ gallons of water. About how many liters is that? (Use $1 \\text{ gal} \\approx 3.785 \\text{ L}$.)",
    options: ["$37.85$ L", "$10$ L", "$2.64$ L", "$30$ L"],
    correct: 0,
    explanation: "$10 \\times 3.785 = 37.85$ L.",
    difficulty: "M",
  },
  {
    stem: "A marathon course is $5$ kilometers long. How many meters is that?",
    options: ["$5000$ m", "$50$ m", "$500$ m", "$50000$ m"],
    correct: 0,
    explanation: "$1 \\text{ km} = 1000 \\text{ m}$, so $5 \\text{ km} = 5000$ m.",
    difficulty: "F",
  },
  {
    stem: "A letter weighs $3500$ grams. What is its mass in kilograms?",
    options: ["$3.5$ kg", "$35$ kg", "$0.35$ kg", "$350$ kg"],
    correct: 0,
    explanation: "Divide by $1000$: $3500 \\div 1000 = 3.5$ kg.",
    difficulty: "F",
  },
  {
    stem: "A plane flies at $540$ km/hr. What is its speed in m/s?",
    options: ["$150$ m/s", "$1944$ m/s", "$9$ m/s", "$1500$ m/s"],
    correct: 0,
    explanation: "Divide by $3.6$: $540 \\div 3.6 = 150$ m/s.",
    difficulty: "M",
  },
  {
    stem: "A car's fuel efficiency is $32$ miles per gallon. How many gallons does it use on a $160$-mile trip?",
    options: ["$5$ gallons", "$5120$ gallons", "$192$ gallons", "$128$ gallons"],
    correct: 0,
    explanation: "$\\frac{160}{32} = 5$ gallons.",
    difficulty: "M",
  },
  {
    stem: "A pump moves $3$ liters of water per minute. How many liters does it move in $2$ hours?",
    options: ["$360$ L", "$6$ L", "$90$ L", "$180$ L"],
    correct: 0,
    explanation: "$2$ hours is $120$ minutes. $3 \\times 120 = 360$ L.",
    difficulty: "M",
  },
  {
    stem: "A tutor earns $\\$15$ per hour. How much does she earn per minute, to the nearest cent?",
    options: ["$\\$0.25$ per minute", "$\\$15.00$ per minute", "$\\$0.90$ per minute", "$\\$2.50$ per minute"],
    correct: 0,
    explanation: "Divide by $60$: $15 \\div 60 = \\$0.25$ per minute.",
    difficulty: "C",
  },
  {
    stem: "Ribbon costs $\\$18$ per yard. What is the cost per foot? (Use $1 \\text{ yd} = 3 \\text{ ft}$.)",
    options: ["$\\$6$ per foot", "$\\$54$ per foot", "$\\$15$ per foot", "$\\$9$ per foot"],
    correct: 0,
    explanation: "Divide by $3$: $18 \\div 3 = \\$6$ per foot.",
    difficulty: "C",
  },
  {
    stem: "A vitamin supplement contains $2800$ milligrams per serving. How many grams is that?",
    options: ["$2.8$ g", "$280$ g", "$0.028$ g", "$28$ g"],
    correct: 0,
    explanation: "$1 \\text{ g} = 1000 \\text{ mg}$, so $2800 \\div 1000 = 2.8$ g.",
    difficulty: "F",
  },
  {
    stem: "A bus travels $200$ miles in $4$ hours. What is its average speed?",
    options: ["$50$ mph", "$800$ mph", "$204$ mph", "$46$ mph"],
    correct: 0,
    explanation: "$\\frac{200}{4} = 50$ mph.",
    difficulty: "F",
  },
  {
    stem: "A dripping faucet wastes $40$ milliliters per minute. How many liters does it waste in one hour?",
    options: ["$2.4$ L", "$0.24$ L", "$24$ L", "$240$ L"],
    correct: 0,
    explanation: "$40 \\text{ mL/min} \\times 60 \\text{ min} = 2400 \\text{ mL} = 2.4$ L.",
    difficulty: "M",
  },
];

export default {
  skill: "unit_conversion",
  skillLabel: "Unit conversion",
  domain: "Problem Solving & Data",
  section: "math",
  batches: {
    "sat-math": sat,
    "nmsqt-math": nmsqt,
    "psat89-math": psat89,
  },
};
