// Verb tense — 60 questions (20 per test type)

const FORMAT = "Which choice completes the text so that it conforms to the conventions of Standard English?";

const sat = [
  {
    stem: `${FORMAT}\n\nBy the time the storm reached the coast, the evacuation crews ______ all of the elderly residents from the seaside neighborhoods.`,
    options: ["had already moved", "have already moved", "were already moving", "already moved"],
    correct: 0,
    explanation: "Two past events: the evacuation happened BEFORE the storm arrived. Use past perfect 'had already moved' for the earlier action.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nArchaeologists excavating the site in 1987 discovered pottery fragments, tools, and what ______ to be a ceremonial altar.`,
    options: ["appeared", "appears", "will appear", "has appeared"],
    correct: 0,
    explanation: "The main clause is in past tense ('discovered'). Match with past tense 'appeared.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nSince 2018, the nonprofit ______ over ten thousand meals to families in need.`,
    options: ["has delivered", "delivered", "is delivering", "was delivering"],
    correct: 0,
    explanation: "'Since 2018' is a present-perfect signal. Use 'has delivered' for a past action continuing into the present.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nYesterday, the governor ______ a new environmental bill into law.`,
    options: ["signed", "has signed", "signs", "was signing"],
    correct: 0,
    explanation: "'Yesterday' is a specific past time. Use simple past 'signed,' not present perfect.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nWhen I arrived at the station, the train ______ already.`,
    options: ["had left", "has left", "left", "was leaving"],
    correct: 0,
    explanation: "Two past events: the train left BEFORE I arrived. Use past perfect for the earlier one.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe committee ______ for two hours before reaching a decision.`,
    options: ["had been meeting", "has been meeting", "met", "meets"],
    correct: 0,
    explanation: "The meeting occurred for a duration BEFORE a second past event (reaching the decision). Past perfect progressive 'had been meeting.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nCurrently, scientists ______ several new species in the rainforest every year.`,
    options: ["discover", "had discovered", "discovered", "will discover"],
    correct: 0,
    explanation: "'Currently' signals the present. Use simple present 'discover.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nShe ______ in Paris for three years before moving to Rome in 2015.`,
    options: ["had lived", "has lived", "lived", "lives"],
    correct: 0,
    explanation: "The living happened BEFORE the move to Rome. Past perfect 'had lived.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nWater ______ at 100 degrees Celsius at standard atmospheric pressure.`,
    options: ["boils", "boiled", "has boiled", "will boil"],
    correct: 0,
    explanation: "Scientific fact — use simple present 'boils.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe reporter asked several questions, and the mayor ______ each one carefully.`,
    options: ["answered", "answers", "has answered", "will answer"],
    correct: 0,
    explanation: "Main clause is past tense ('asked'). Use past 'answered.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nUntil last year, the library ______ closed on Sundays.`,
    options: ["had been", "has been", "is", "was being"],
    correct: 0,
    explanation: "'Until last year' signals a past state that ended at a specific past time. Past perfect 'had been' works here.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nNext summer, the family ______ to visit their relatives in Brazil.`,
    options: ["plans", "planned", "has planned", "is planned"],
    correct: 0,
    explanation: "'Next summer' signals a future plan stated in the present. Use 'plans.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe contract ______ by all parties last Monday.`,
    options: ["was signed", "is signed", "has been signed", "will be signed"],
    correct: 0,
    explanation: "'Last Monday' is a specific past time. Simple past passive 'was signed.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nFor the past decade, researchers ______ the long-term effects of the medication on older adults.`,
    options: ["have studied", "studied", "are studying", "had studied"],
    correct: 0,
    explanation: "'For the past decade' is a present-perfect signal — an action starting in the past and continuing to now. 'Have studied.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nBy the end of this year, the charity ______ all of its fundraising goals.`,
    options: ["will have met", "met", "has met", "had met"],
    correct: 0,
    explanation: "Future perfect: 'by the end of this year' signals a future time by which the action will be complete. 'Will have met.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nIn the 1960s, the company ______ its first international branch.`,
    options: ["opened", "has opened", "opens", "was opening"],
    correct: 0,
    explanation: "'In the 1960s' is a specific past time. Simple past 'opened.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nWe ______ to the movie tonight because the theater is hosting a special screening.`,
    options: ["are going", "had gone", "went", "have gone"],
    correct: 0,
    explanation: "Present progressive 'are going' for a planned future action.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe patient ______ in the hospital for three days when the test results finally came back.`,
    options: ["had been", "has been", "was", "is"],
    correct: 0,
    explanation: "Past perfect for the earlier duration: the patient had been in the hospital before the results came back.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nShakespeare ______ at least thirty-seven plays during his lifetime.`,
    options: ["wrote", "has written", "writes", "was writing"],
    correct: 0,
    explanation: "A completed action in a historically closed period. Simple past 'wrote.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nBefore the meeting started, the secretary ______ copies of the agenda.`,
    options: ["had distributed", "has distributed", "distributed", "distributes"],
    correct: 0,
    explanation: "The distribution occurred BEFORE the meeting started. Past perfect 'had distributed.'",
    difficulty: "M",
  },
];

const nmsqt = [
  {
    stem: `${FORMAT}\n\nBy the time the teacher returned from the hallway, the students ______ their homework onto the desk.`,
    options: ["had placed", "have placed", "place", "were placing"],
    correct: 0,
    explanation: "The placing happened BEFORE the teacher returned. Past perfect 'had placed.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe scientists who conducted the 2010 study ______ that ocean temperatures were rising faster than expected.`,
    options: ["concluded", "conclude", "have concluded", "will conclude"],
    correct: 0,
    explanation: "Main clause is past tense. Match with simple past 'concluded.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nSince the beginning of the season, the team ______ in seven of its ten games.`,
    options: ["has won", "won", "is winning", "was winning"],
    correct: 0,
    explanation: "'Since the beginning of the season' is a present-perfect signal. 'Has won.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nLast week, the mayor ______ a new plan for the downtown area.`,
    options: ["announced", "has announced", "announces", "was announcing"],
    correct: 0,
    explanation: "'Last week' is specific past time. Simple past 'announced.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nWhen the teacher walked into the classroom, the students ______ already ______ the worksheet.`,
    options: ["had / completed", "have / completed", "did / complete", "were / completing"],
    correct: 0,
    explanation: "Past perfect: the completion happened before the teacher entered. 'Had completed.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nShe ______ the piano for five years before her family moved.`,
    options: ["had been playing", "has been playing", "plays", "was playing"],
    correct: 0,
    explanation: "A duration in the past that ended at another past event. Past perfect progressive 'had been playing.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nEvery morning, my grandfather ______ a cup of black coffee before reading the newspaper.`,
    options: ["drinks", "drank", "is drinking", "has drunk"],
    correct: 0,
    explanation: "'Every morning' signals a habitual present action. Use simple present 'drinks.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe artist ______ in New Mexico for many years before her first exhibition opened in 2018.`,
    options: ["had worked", "has worked", "worked", "works"],
    correct: 0,
    explanation: "The working happened BEFORE the 2018 exhibition. Past perfect 'had worked.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nSound ______ through air at approximately 343 meters per second.`,
    options: ["travels", "traveled", "has traveled", "is traveling"],
    correct: 0,
    explanation: "General scientific fact. Simple present 'travels.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe witness described what she ______ during the incident.`,
    options: ["had seen", "has seen", "sees", "was seeing"],
    correct: 0,
    explanation: "The seeing happened BEFORE the describing. Past perfect 'had seen.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nUntil last semester, the math club ______ only on Fridays.`,
    options: ["had met", "has met", "meets", "is meeting"],
    correct: 0,
    explanation: "Past habit that ended at a specific past point. Past perfect 'had met.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nNext weekend, our family ______ to the state fair.`,
    options: ["is going", "went", "has gone", "had gone"],
    correct: 0,
    explanation: "Planned future → present progressive 'is going.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe package ______ yesterday by the delivery service.`,
    options: ["was delivered", "is delivered", "has been delivered", "will be delivered"],
    correct: 0,
    explanation: "'Yesterday' is specific past. Simple past passive 'was delivered.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nFor the past six months, our book club ______ novels by African writers.`,
    options: ["has read", "read", "reads", "is reading"],
    correct: 0,
    explanation: "'For the past six months' signals present perfect. 'Has read.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nBy this time next year, I ______ from college.`,
    options: ["will have graduated", "graduated", "have graduated", "had graduated"],
    correct: 0,
    explanation: "Future perfect: an action that will be complete by a future time. 'Will have graduated.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nIn 1969, astronauts ______ on the Moon for the first time.`,
    options: ["walked", "has walked", "walks", "were walking"],
    correct: 0,
    explanation: "'In 1969' is specific past. Simple past 'walked.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThey ______ to the concert tomorrow if the weather holds.`,
    options: ["are going", "went", "have gone", "had gone"],
    correct: 0,
    explanation: "Planned future → 'are going.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe chef ______ in three restaurants before opening her own bistro.`,
    options: ["had worked", "has worked", "works", "was working"],
    correct: 0,
    explanation: "The working happened BEFORE the opening. Past perfect.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nMark Twain ______ 'The Adventures of Huckleberry Finn' in 1884.`,
    options: ["published", "has published", "publishes", "was publishing"],
    correct: 0,
    explanation: "Specific historical date. Simple past 'published.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nBefore the guests arrived, the host ______ the table for dinner.`,
    options: ["had set", "has set", "set", "sets"],
    correct: 0,
    explanation: "The setting happened BEFORE the arrival. Past perfect 'had set.'",
    difficulty: "M",
  },
];

const psat89 = [
  {
    stem: `${FORMAT}\n\nBy the time her parents arrived, Emily ______ her homework.`,
    options: ["had finished", "has finished", "finished", "was finishing"],
    correct: 0,
    explanation: "The finishing happened before the arrival. Past perfect 'had finished.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nThe boy who won the race ______ proud of his achievement.`,
    options: ["was", "is", "has been", "will be"],
    correct: 0,
    explanation: "Main clause is past tense ('won'). Match with past 'was.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nSince last Monday, the students ______ their final projects.`,
    options: ["have been working on", "worked on", "are working on", "were working on"],
    correct: 0,
    explanation: "'Since last Monday' is a present-perfect signal for an ongoing action. 'Have been working on.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nLast Saturday, we ______ to the park for a picnic.`,
    options: ["went", "have gone", "go", "are going"],
    correct: 0,
    explanation: "'Last Saturday' is specific past. Simple past 'went.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nWhen the bell rang, most of the students ______ their lockers.`,
    options: ["had already closed", "have already closed", "closed", "are closing"],
    correct: 0,
    explanation: "The closing occurred before the bell rang. Past perfect.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nShe ______ soccer for three years before joining the varsity team.`,
    options: ["had been playing", "has been playing", "played", "plays"],
    correct: 0,
    explanation: "A past duration ending at a past event. Past perfect progressive.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nEvery Saturday, my brother ______ his guitar for an hour.`,
    options: ["practices", "practiced", "is practicing", "has practiced"],
    correct: 0,
    explanation: "'Every Saturday' = habit → simple present 'practices.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe librarian ______ at the same library for twenty years before retiring.`,
    options: ["had worked", "has worked", "worked", "works"],
    correct: 0,
    explanation: "The working happened before the retirement. Past perfect 'had worked.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nPlants ______ sunlight to make food through photosynthesis.`,
    options: ["need", "needed", "are needing", "have needed"],
    correct: 0,
    explanation: "General scientific fact. Simple present 'need.'",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe detective asked what the suspect ______ on the night in question.`,
    options: ["had done", "has done", "does", "is doing"],
    correct: 0,
    explanation: "The doing happened before the asking. Past perfect.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nUntil yesterday, the store ______ open on Sundays.`,
    options: ["had been", "has been", "is", "was being"],
    correct: 0,
    explanation: "Past state that ended at a specific past point. Past perfect 'had been.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nTomorrow evening, the class ______ a movie as part of the history lesson.`,
    options: ["is watching", "watched", "has watched", "had watched"],
    correct: 0,
    explanation: "Planned future → present progressive.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nThe award ______ to the student with the highest science grade last June.`,
    options: ["was given", "is given", "has been given", "will be given"],
    correct: 0,
    explanation: "'Last June' is specific past. Simple past passive.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nFor the past few weeks, our family ______ to adopt a dog.`,
    options: ["has been trying", "tried", "tries", "is trying"],
    correct: 0,
    explanation: "'For the past few weeks' is present perfect signal. 'Has been trying.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nBy next summer, Luis ______ enough money to buy a new bike.`,
    options: ["will have saved", "has saved", "saved", "had saved"],
    correct: 0,
    explanation: "Future perfect: 'by next summer.'",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nIn 1776, the founders ______ the Declaration of Independence.`,
    options: ["signed", "have signed", "sign", "were signing"],
    correct: 0,
    explanation: "Specific historical date → simple past.",
    difficulty: "F",
  },
  {
    stem: `${FORMAT}\n\nWe ______ to the beach this weekend because the weather is perfect.`,
    options: ["are going", "went", "have gone", "had gone"],
    correct: 0,
    explanation: "Planned future → present progressive.",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nShe ______ in two other cities before moving to Boston last year.`,
    options: ["had lived", "has lived", "lived", "lives"],
    correct: 0,
    explanation: "The living happened before the move. Past perfect.",
    difficulty: "C",
  },
  {
    stem: `${FORMAT}\n\nThe playwright August Wilson ______ the Pulitzer Prize twice during his career.`,
    options: ["won", "has won", "wins", "was winning"],
    correct: 0,
    explanation: "Completed life — simple past 'won.'",
    difficulty: "M",
  },
  {
    stem: `${FORMAT}\n\nBefore the movie began, the audience ______ to their seats.`,
    options: ["had returned", "has returned", "returned", "returns"],
    correct: 0,
    explanation: "Returning happened before the movie began. Past perfect.",
    difficulty: "M",
  },
];

export default {
  skill: "verb_tense",
  skillLabel: "Verb tense and consistency",
  domain: "Standard English Conventions",
  section: "rw",
  batches: {
    "sat-rw": sat,
    "nmsqt-rw": nmsqt,
    "psat89-rw": psat89,
  },
};
