"use client";

import { DiagnosticTest } from "@/components/test/diagnostic-test";
import type { Question } from "@/types/question";

const QUESTIONS: Question[] = [
  {
    id: "diag-psat89-math-1",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear equations in 1 variable",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If 3x + 7 = 22, what is the value of x?",
    options: ["3", "5", "7", "15"],
    correctAnswer: "B",
    explanation: "Subtract 7: 3x=15. Divide by 3: x=5. Check: 3(5)+7=22. ✓",
    explanations: { "A": "3(3)+7=16, not 22.", "B": "Subtract 7: 3x=15. Divide by 3: x=5. Check: 3(5)+7=22. ✓", "C": "3(7)+7=28, not 22.", "D": "15 is the value of 3x, not x." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-2",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear equations in 2 variables",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which equation represents the total cost C after m months?",
    passage: "A gym charges a $50 enrollment fee plus $30 per month.",
    options: ["C = 50m + 30", "C = 30m + 50", "C = 80m", "C = 50m − 30"],
    correctAnswer: "B",
    explanation: "$30 per month (30m) plus one-time $50 fee. ✓",
    explanations: { "A": "$50 is one-time, not monthly. This charges $50 each month.", "B": "$30 per month (30m) plus one-time $50 fee. ✓", "C": "80m assumes $80/month with no separation of costs.", "D": "Subtracting $30 doesn’t model any real cost." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-3",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the slope of the line y = −4x + 9?",
    options: ["−4", "4", "9", "−9"],
    correctAnswer: "A",
    explanation: "In y=mx+b, m is the slope. Here m=−4. ✓",
    explanations: { "A": "In y=mx+b, m is the slope. Here m=−4. ✓", "B": "4 drops the negative sign.", "C": "9 is the y-intercept (b), not the slope.", "D": "−9 isn’t related to slope or intercept here." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-4",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Systems of linear equations",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the value of x?",
    passage: `The system:
x + y = 8
x − y = 2`,
    options: ["", "", "", ""],
    correctAnswer: "5",
    explanation: "Add equations: 2x=10, x=5. Then y=3. Check: 5+3=8, 5−3=2. ✓",
    explanations: { "correct": "Add equations: 2x=10, x=5. Then y=3. Check: 5+3=8, 5−3=2. ✓" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-5",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear equations (word problems)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the total charge for 3 hours of work?",
    passage: "A plumber charges $40 for a house call plus $25 per hour of labor.",
    options: ["$65", "$75", "$115", "$120"],
    correctAnswer: "C",
    explanation: "40+25(3)=40+75=115. ✓",
    explanations: { "A": "40+25=65 only counts 1 hour.", "B": "25×3=75 forgets the house call fee.", "C": "40+25(3)=40+75=115. ✓", "D": "40×3=120 multiplies the wrong amount." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-6",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear inequalities",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: `Which inequality represents 'a number n is at least 12'?`,
    options: ["n > 12", "n < 12", "n ≥ 12", "n ≤ 12"],
    correctAnswer: "C",
    explanation: `'At least' means 12 or more: n ≥ 12. ✓`,
    explanations: { "A": `'Greater than' excludes 12 itself.`, "B": "Less than 12 is the opposite.", "C": `'At least' means 12 or more: n ≥ 12. ✓`, "D": `'At most' would be ≤, not 'at least.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-7",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Evaluating expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the value of 4(2x − 3) when x = 5?",
    options: ["17", "28", "32", "37"],
    correctAnswer: "B",
    explanation: "2(5)−3=7. 4(7)=28. ✓",
    explanations: { "A": "May have done 2(5)−3=7, then forgot to multiply by 4.", "B": "2(5)−3=7. 4(7)=28. ✓", "C": "4×2(5)=40, 40−3=37? Multiple errors.", "D": "4(2×5)−3=40−3=37 — didn’t distribute correctly." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-8",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Quadratic expressions (FOIL)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression is equivalent to (x + 3)(x + 5)?",
    options: ["x² + 8x + 15", "x² + 15x + 8", "x² + 8x + 8", "2x + 8"],
    correctAnswer: "A",
    explanation: "FOIL: x²+5x+3x+15 = x²+8x+15. ✓",
    explanations: { "A": "FOIL: x²+5x+3x+15 = x²+8x+15. ✓", "B": "Coefficients are swapped.", "C": "Constant should be 3×5=15, not 8.", "D": "Only added the x-terms, ignoring the x² and constant." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-9",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Solving quadratics",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What are the solutions of x² − 9 = 0?",
    options: ["x = 3 only", "x = −3 only", "x = 3 and x = −3", "x = 9 and x = −9"],
    correctAnswer: "C",
    explanation: "x²=9 gives x=±3. Or factor: (x+3)(x−3)=0. ✓",
    explanations: { "A": "Only one of two solutions.", "B": "Only one of two solutions.", "C": "x²=9 gives x=±3. Or factor: (x+3)(x−3)=0. ✓", "D": "9 and −9 are the values of x², not x." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-10",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Exponential concepts",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression gives the population after 9 hours?",
    passage: "A population of 500 bacteria doubles every 3 hours.",
    options: ["500 + 2(9)", "500 × 2³", "500 × 9²", "500 × 3²"],
    correctAnswer: "B",
    explanation: "9 hours ÷ 3 hours per doubling = 3 doublings. 500×2³=500×8=4000. ✓",
    explanations: { "A": "Linear model, not exponential.", "B": "9 hours ÷ 3 hours per doubling = 3 doublings. 500×2³=500×8=4000. ✓", "C": "Base should be 2 (doubling), not 9.", "D": "3²=9 doesn’t represent doubling." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-11",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Function evaluation",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If f(x) = 2x + 1, what is f(6)?",
    options: ["", "", "", ""],
    correctAnswer: "13",
    explanation: "f(6)=2(6)+1=12+1=13.",
    explanations: { "correct": "f(6)=2(6)+1=12+1=13." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-12",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Ratios and proportions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If you use 8 cups of flour, how many cups of sugar do you need?",
    passage: "A recipe calls for 2 cups of flour for every 3 cups of sugar.",
    options: ["9", "10", "12", "16"],
    correctAnswer: "C",
    explanation: "2/3=8/s. Cross multiply: 2s=24, s=12. ✓",
    explanations: { "A": "No clear mathematical path to 9.", "B": "8+2=10? Not a valid proportion approach.", "C": "2/3=8/s. Cross multiply: 2s=24, s=12. ✓", "D": "8×2=16 doubles the flour, not the ratio." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-13",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Percentages",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the sale price?",
    passage: "A shirt originally costs $40 and is on sale for 25% off.",
    options: ["$10", "$15", "$25", "$30"],
    correctAnswer: "D",
    explanation: "25% of 40=10. Sale price: 40−10=30. Or 40×0.75=30. ✓",
    explanations: { "A": "$10 is 25% of $40 — that’s the discount amount, not the price.", "B": "No clear path.", "C": "$25 is 40−25, subtracting the percentage as dollars.", "D": "25% of 40=10. Sale price: 40−10=30. Or 40×0.75=30. ✓" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-14",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Measures of center",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the mean of this data set?",
    passage: "A data set has values: 4, 7, 7, 9, 13.",
    options: ["", "", "", ""],
    correctAnswer: "8",
    explanation: "Sum=4+7+7+9+13=40. Mean=40/5=8.",
    explanations: { "correct": "Sum=4+7+7+9+13=40. Mean=40/5=8." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-15",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Data interpretation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What percentage of students chose Basketball?",
    passage: "A class survey asked 30 students about their favorite sport. The results: Basketball 12, Soccer 8, Baseball 6, Other 4.",
    options: ["12%", "25%", "30%", "40%"],
    correctAnswer: "D",
    explanation: "12/30=0.40=40%. ✓",
    explanations: { "A": "12 is the count, not the percentage.", "B": "25% would be 7.5 students.", "C": "30 is the total students, not a percentage.", "D": "12/30=0.40=40%. ✓" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-16",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Scatterplots",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which best describes the relationship?",
    passage: "A scatterplot shows the relationship between hours of study and test scores. The data points generally go upward from left to right.",
    options: ["Negative linear association", "Positive linear association", "No association", "Exponential association"],
    correctAnswer: "B",
    explanation: "Upward from left to right = as one variable increases, so does the other. Positive linear. ✓",
    explanations: { "A": "Negative means downward; the data goes upward.", "B": "Upward from left to right = as one variable increases, so does the other. Positive linear. ✓", "C": "A clear upward trend is an association.", "D": `The question says 'generally upward' which suggests linear, not curved.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-17",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Probability",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the probability of randomly drawing a red marble? (Enter as a decimal.)",
    passage: "A bag contains 5 red marbles, 3 blue, and 2 green.",
    options: ["", "", "", ""],
    correctAnswer: "0.5",
    explanation: "Total=5+3+2=10. P(red)=5/10=0.5.",
    explanations: { "correct": "Total=5+3+2=10. P(red)=5/10=0.5." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-18",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Geometry",
    skill: "Area",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A rectangle has length 12 cm and width 5 cm. What is its area?",
    options: ["17 cm²", "34 cm²", "60 cm²", "120 cm²"],
    correctAnswer: "C",
    explanation: "A=l×w=12×5=60. ✓",
    explanations: { "A": "12+5=17 is the semi-perimeter, not area.", "B": "2(12+5)=34 is the perimeter.", "C": "A=l×w=12×5=60. ✓", "D": "12×10=120? No mathematical basis." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-19",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Geometry",
    skill: "Angles",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Two angles are supplementary. One measures 65°. What is the other?",
    options: ["25°", "65°", "115°", "295°"],
    correctAnswer: "C",
    explanation: "Supplementary=180°. 180−65=115. ✓",
    explanations: { "A": "90−65=25 is the complement, not supplement.", "B": "65° would make them equal, not supplementary.", "C": "Supplementary=180°. 180−65=115. ✓", "D": "360−65=295 uses the wrong total." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-20",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Geometry",
    skill: "Pythagorean theorem",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "A right triangle has legs of length 6 and 8. What is the hypotenuse?",
    options: ["", "", "", ""],
    correctAnswer: "10",
    explanation: "c²=6²+8²=36+64=100. c=10. (Classic 6-8-10 triple.)",
    explanations: { "correct": "c²=6²+8²=36+64=100. c=10. (Classic 6-8-10 triple.)" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-21",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Geometry",
    skill: "Volume",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A cylinder has radius 3 cm and height 10 cm. What is its volume? (V = πr²h)",
    options: ["30π cm³", "60π cm³", "90π cm³", "900π cm³"],
    correctAnswer: "C",
    explanation: "V=π(3)²(10)=π(9)(10)=90π. ✓",
    explanations: { "A": "30=3×10, forgot to square the radius.", "B": "π(6)(10)? Used diameter instead of r².", "C": "V=π(3)²(10)=π(9)(10)=90π. ✓", "D": "(30)²π? Squared the wrong thing." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-22",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Geometry",
    skill: "Triangle angle sum",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "In a triangle, two angles measure 45° and 70°. What is the third angle?",
    options: ["25°", "45°", "65°", "115°"],
    correctAnswer: "C",
    explanation: "180−45−70=65. ✓",
    explanations: { "A": "180−(45+70)=65, not 25.", "B": "Not necessarily equal to one of the given angles.", "C": "180−45−70=65. ✓", "D": "45+70=115 is the sum of the given angles, not the missing one." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-23",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Linear equations in 1 variable",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If 4(x − 2) = 20, what is x?",
    options: ["3", "5", "7", "8"],
    correctAnswer: "C",
    explanation: "Divide by 4: x−2=5. Add 2: x=7. Check: 4(7−2)=4(5)=20. ✓",
    explanations: { "A": "4(3−2)=4, not 20.", "B": "4(5−2)=12, not 20.", "C": "Divide by 4: x−2=5. Add 2: x=7. Check: 4(7−2)=4(5)=20. ✓", "D": "4(8−2)=24, not 20." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-24",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Linear equations (word problems)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the cost for a 4-day rental with 150 miles?",
    passage: "A car rental costs $35 per day plus $0.20 per mile driven.",
    options: ["$140", "$155", "$170", "$200"],
    correctAnswer: "C",
    explanation: "35(4)+0.20(150)=140+30=170. ✓",
    explanations: { "A": "35×4=140 forgot the mileage.", "B": "Miscalculated mileage cost.", "C": "35(4)+0.20(150)=140+30=170. ✓", "D": "No clear mathematical path." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-25",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the y-intercept of the line 2x + y = 10? (Enter the y-value.)",
    options: ["", "", "", ""],
    correctAnswer: "10",
    explanation: "Set x=0: 2(0)+y=10, so y=10. The y-intercept is (0,10).",
    explanations: { "correct": "Set x=0: 2(0)+y=10, so y=10. The y-intercept is (0,10)." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-26",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Equivalent expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression is equivalent to 3(x + 4) − 2(x − 1)?",
    options: ["x + 10", "x + 14", "5x + 10", "x + 12"],
    correctAnswer: "B",
    explanation: "3x+12−2x+2=x+14. ✓",
    explanations: { "A": "Forgot to distribute −2 to −1: should be +2, giving +14.", "B": "3x+12−2x+2=x+14. ✓", "C": "Added 3+2=5 for the x coefficient instead of 3−2=1.", "D": "3(4)−2(1)=12−2=10? Partial distribution error." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-27",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Systems (word problems)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "At what time does Train B catch Train A?",
    passage: "Train A leaves at 8:00 AM going 60 mph. Train B leaves at 9:00 AM going 80 mph on the same route.",
    options: ["11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM"],
    correctAnswer: "B",
    explanation: "At 12 PM: A has gone 4h×60=240mi, B has gone 3h×80=240mi. Equal! ✓",
    explanations: { "A": "At 11 AM: A has gone 3h×60=180mi, B has gone 2h×80=160mi. Not caught up.", "B": "At 12 PM: A has gone 4h×60=240mi, B has gone 3h×80=240mi. Equal! ✓", "C": "B would be ahead by 1 PM.", "D": "Way past the meeting point." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-28",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Linear inequalities",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If 2x + 5 > 17, which values of x satisfy the inequality?",
    options: ["x > 6", "x > 11", "x > 8.5", "x < 6"],
    correctAnswer: "A",
    explanation: "Subtract 5: 2x>12. Divide by 2: x>6. ✓",
    explanations: { "A": "Subtract 5: 2x>12. Divide by 2: x>6. ✓", "B": "Only subtracted 5 from 17 without dividing.", "C": "(17−5)/2=6, not 8.5. Computation error.", "D": "Flipped the inequality direction without reason." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-29",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Linear equations (word problems)",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many texts were sent?",
    passage: "A phone plan costs $20/month plus $0.05 per text. Last month the bill was $27.50.",
    options: ["", "", "", ""],
    correctAnswer: "150",
    explanation: "20+0.05t=27.50. 0.05t=7.50. t=150.",
    explanations: { "correct": "20+0.05t=27.50. 0.05t=7.50. t=150." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-30",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Quadratic expressions (FOIL)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression is equivalent to (x − 4)(x + 6)?",
    options: ["x² + 2x − 24", "x² − 2x − 24", "x² + 10x − 24", "x² − 24"],
    correctAnswer: "A",
    explanation: "x²+6x−4x−24=x²+2x−24. ✓",
    explanations: { "A": "x²+6x−4x−24=x²+2x−24. ✓", "B": "Middle term: 6x+(−4x)=+2x, not −2x.", "C": "Added magnitudes: 6+4=10 instead of 6−4=2.", "D": "Forgot the middle terms entirely." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-31",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Function evaluation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If g(x) = x² − 3x, what is g(−2)?",
    options: ["−10", "−2", "2", "10"],
    correctAnswer: "D",
    explanation: "g(−2)=(−2)²−3(−2)=4+6=10. ✓",
    explanations: { "A": "(−2)²=+4, not −4.", "B": "Partial calculation error.", "C": "4−6=−2? But −3(−2)=+6.", "D": "g(−2)=(−2)²−3(−2)=4+6=10. ✓" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-32",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Solving quadratics",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the positive solution of x² = 49?",
    options: ["", "", "", ""],
    correctAnswer: "7",
    explanation: "x²=49 gives x=±7. The positive solution is 7.",
    explanations: { "correct": "x²=49 gives x=±7. The positive solution is 7." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-33",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Exponential growth",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression gives the account balance after t years?",
    passage: "A savings account earns 5% interest per year, compounded annually. The initial deposit is $200.",
    options: ["200 + 0.05t", "200(1.05)ᵗ", "200(0.05)ᵗ", "200(1.5)ᵗ"],
    correctAnswer: "B",
    explanation: "Compound: multiply by (1+rate) each year. 200(1.05)ᵗ. ✓",
    explanations: { "A": "Linear model — compound interest is exponential.", "B": "Compound: multiply by (1+rate) each year. 200(1.05)ᵗ. ✓", "C": "0.05 alone is the rate, not the growth factor.", "D": "1.5 means 50% growth, not 5%." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-34",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Ratios",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the ratio of pizza lovers to burger lovers?",
    passage: "A survey of 200 students found: 90 prefer pizza, 60 prefer burgers, 35 prefer tacos, 15 prefer salad.",
    options: ["2:3", "3:2", "9:4", "6:9"],
    correctAnswer: "B",
    explanation: "90:60=3:2. ✓",
    explanations: { "A": "60:90=2:3 is the inverse.", "B": "90:60=3:2. ✓", "C": "90:40 would be 9:4, but burgers=60.", "D": "6:9 simplifies to 2:3 — inverse again." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-35",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Measures of center",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the mode of this data set?",
    passage: "A data set: 3, 5, 5, 8, 8, 8, 10, 12. ",
    options: ["5", "7.375", "8", "10"],
    correctAnswer: "C",
    explanation: "Mode = most frequent value. 8 appears 3 times. ✓",
    explanations: { "A": "5 appears twice, but 8 appears three times.", "B": "7.375 is the mean, not the mode.", "C": "Mode = most frequent value. 8 appears 3 times. ✓", "D": "10 appears once." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-36",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Ratios and proportions",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the actual distance in miles?",
    passage: "A map has a scale where 1 inch = 15 miles. Two cities are 4.5 inches apart on the map.",
    options: ["", "", "", ""],
    correctAnswer: "67.5",
    explanation: "4.5×15=67.5 miles.",
    explanations: { "correct": "4.5×15=67.5 miles." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-37",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Percentages",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Is the final price equal to, higher than, or lower than the original?",
    passage: "A store raises prices by 10% and then offers a 10% discount on the new price.",
    options: ["Equal to the original", "Higher than the original", "Lower than the original", "Cannot be determined"],
    correctAnswer: "C",
    explanation: "Example: $100→+10%=$110→−10%=$99. Final=$99<$100. Always lower. ✓",
    explanations: { "A": "10% up then 10% down does NOT return to original because the bases are different.", "B": "The discount is on a higher base, but the net effect is a loss.", "C": "Example: $100→+10%=$110→−10%=$99. Final=$99<$100. Always lower. ✓", "D": "It can be determined — the result is always lower." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-38",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Study design",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What type of study is this?",
    passage: "A researcher wants to know if a new fertilizer helps plants grow taller. She grows 20 plants with fertilizer and 20 without, measuring height after 4 weeks.",
    options: ["Observational study", "Survey", "Experiment", "Census"],
    correctAnswer: "C",
    explanation: "Treatments (fertilizer/no fertilizer) were assigned to groups → experiment. ✓",
    explanations: { "A": "She actively applied a treatment, not just observed.", "B": "No questions were asked; growth was measured.", "C": "Treatments (fertilizer/no fertilizer) were assigned to groups → experiment. ✓", "D": "Census measures an entire population, not a sample." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-39",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry",
    skill: "Circles",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A circle has a diameter of 14 cm. What is its circumference? (C = πd)",
    options: ["7π cm", "14π cm", "49π cm", "196π cm"],
    correctAnswer: "B",
    explanation: "C=πd=14π≈43.98 cm. ✓",
    explanations: { "A": "7 is the radius, and C=πd, not πr.", "B": "C=πd=14π≈43.98 cm. ✓", "C": "49π=πr² is the area, not circumference.", "D": "196π=πd² — doesn’t correspond to any formula." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-40",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry",
    skill: "Volume",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "A rectangular box has length 6, width 4, and height 3. What is its volume?",
    options: ["", "", "", ""],
    correctAnswer: "72",
    explanation: "V=lwh=6×4×3=72.",
    explanations: { "correct": "V=lwh=6×4×3=72." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-41",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry",
    skill: "Parallel lines and angles",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Two parallel lines are cut by a transversal. One angle formed is 125°. What is the measure of its corresponding angle?",
    options: ["55°", "65°", "125°", "180°"],
    correctAnswer: "C",
    explanation: "Corresponding angles formed by parallel lines and a transversal are equal: 125°. ✓",
    explanations: { "A": "180−125=55 is the supplementary angle, not corresponding.", "B": "No geometric basis.", "C": "Corresponding angles formed by parallel lines and a transversal are equal: 125°. ✓", "D": "180° is a straight angle, not an angle measure here." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-42",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry",
    skill: "Pythagorean theorem",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A right triangle has a hypotenuse of 13 and one leg of 5. What is the other leg?",
    options: ["8", "10", "12", "18"],
    correctAnswer: "C",
    explanation: "a²+5²=13². a²+25=169. a²=144. a=12. (5-12-13 triple.) ✓",
    explanations: { "A": "13−5=8 just subtracts — not how Pythagorean theorem works.", "B": "No triple matches.", "C": "a²+5²=13². a²+25=169. a²=144. a=12. (5-12-13 triple.) ✓", "D": "5+13=18 just adds — not valid." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-43",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry",
    skill: "Area",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A square has a perimeter of 36 inches. What is its area?",
    options: ["9 in²", "36 in²", "81 in²", "144 in²"],
    correctAnswer: "C",
    explanation: "Side=36/4=9. Area=9²=81. ✓",
    explanations: { "A": "Side=36/4=9, but 9 is the side length, not the area.", "B": "36 is the perimeter, not area.", "C": "Side=36/4=9. Area=9²=81. ✓", "D": "36×4=144 multiplies perimeter by sides." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-psat89-math-44",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry",
    skill: "Area",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A triangle has a base of 10 cm and a height of 7 cm. What is its area?",
    options: ["17 cm²", "35 cm²", "70 cm²", "140 cm²"],
    correctAnswer: "B",
    explanation: "A=½(10)(7)=35. ✓",
    explanations: { "A": "10+7=17 is the sum, not area.", "B": "A=½(10)(7)=35. ✓", "C": "10×7=70 forgot the ½.", "D": "No mathematical basis." },
    tags: ["diagnostic"],
  }
];

export default function PSAT89MathDiagnostic() {
  return (
    <DiagnosticTest
      testType="psat89"
      section="math"
      title="PSAT 8/9 Math Diagnostic"
      timeMinutes={35}
      domains={["Algebra", "Advanced Math", "Problem-Solving & Data Analysis", "Geometry"]}
      questions={QUESTIONS}
    />
  );
}


