import type { Question } from "@/types/question";

export const QUESTIONS: Question[] = [
  {
    id: "diag-nmsqt-math-1",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear equations in 1 variable",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If 5x − 3 = 2x + 12, what is the value of x?",
    options: ["3", "5", "9", "15"],
    correctAnswer: "B",
    explanation: "Subtract 2x: 3x−3=12. Add 3: 3x=15. x=5. Check: 5(5)−3=22, 2(5)+12=22. ✓",
    explanations: { "A": "If x=3: 5(3)−3=12, but 2(3)+12=18. Not equal.", "B": "Subtract 2x: 3x−3=12. Add 3: 3x=15. x=5. Check: 5(5)−3=22, 2(5)+12=22. ✓", "C": "Comes from adding 12+15=27, then dividing by 3 without proper setup.", "D": "15 is the value of 3x, not x." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-2",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear equations (word problems)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How many tickets must be sold for the venue to break even (P = 0)?",
    passage: "A concert venue charges $12 per ticket and has fixed operating costs of $2,400. The venue’s profit P (in dollars) from selling t tickets is P = 12t − 2400.",
    options: ["100", "150", "200", "288"],
    correctAnswer: "C",
    explanation: "12t−2400=0 → 12t=2400 → t=200. Check: 12(200)−2400=0. ✓",
    explanations: { "A": "12(100)−2400 = −1200. Still a loss.", "B": "12(150)−2400 = −600. Still a loss.", "C": "12t−2400=0 → 12t=2400 → t=200. Check: 12(200)−2400=0. ✓", "D": "2400/12 ≠ 288; likely a division error." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-3",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The line y = −(2/3)x + 4 has a y-intercept at which point?",
    options: ["(0, −2/3)", "(4, 0)", "(0, 4)", "(−2/3, 0)"],
    correctAnswer: "C",
    explanation: "In y=mx+b, b=4 is the y-intercept. The point is (0,4). ✓",
    explanations: { "A": "−2/3 is the slope, not the y-intercept.", "B": "(4,0) would be the x-intercept.", "C": "In y=mx+b, b=4 is the y-intercept. The point is (0,4). ✓", "D": "The slope in coordinate form, not meaningful as an intercept." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-4",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Systems of linear equations",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the value of x?",
    passage: `The system of equations is:
3x + y = 10
x − y = 2`,
    options: ["", "", "", ""],
    correctAnswer: "3",
    explanation: "Add equations: (3x+y)+(x−y)=10+2 → 4x=12 → x=3. Check: y=10−3(3)=1. And 3−1=2. ✓",
    explanations: { "correct": "Add equations: (3x+y)+(x−y)=10+2 → 4x=12 → x=3. Check: y=10−3(3)=1. And 3−1=2. ✓" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-5",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Equivalent expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which of the following is equivalent to 3(2x + 5) − 4(x − 1)?",
    options: ["2x + 11", "2x + 19", "10x + 11", "2x + 4"],
    correctAnswer: "B",
    explanation: "6x+15−4x+4 = 2x+19. ✓",
    explanations: { "A": "Forgot to distribute −4 to the −1: −4(−1)=+4, not 0.", "B": "6x+15−4x+4 = 2x+19. ✓", "C": "Added coefficients: 6+4=10 instead of 6−4=2.", "D": "Only distributed the 3, not the −4." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-6",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Systems of equations (word problems)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "After how many miles do both services cost the same?",
    passage: "A taxi charges $3.50 plus $0.75 per mile. A rideshare charges $1.00 plus $1.25 per mile.",
    options: ["3", "4", "5", "6"],
    correctAnswer: "C",
    explanation: "3.50+0.75m = 1.00+1.25m → 2.50=0.50m → m=5. Both=$7.25. ✓",
    explanations: { "A": "Taxi=3.50+2.25=5.75, Ride=1+3.75=4.75. Not equal.", "B": "Taxi=6.50, Ride=6.00. Not equal.", "C": "3.50+0.75m = 1.00+1.25m → 2.50=0.50m → m=5. Both=$7.25. ✓", "D": "Taxi=8.00, Ride=8.50. Not equal." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-7",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Function notation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If f(x) = 3x − 2, what is the value of f(4) − f(1)?",
    options: ["3", "7", "9", "12"],
    correctAnswer: "C",
    explanation: "f(4)=3(4)−2=10. f(1)=3(1)−2=1. 10−1=9. ✓",
    explanations: { "A": "3 is the slope/rate of change per unit, but we need f(4)−f(1) over 3 units.", "B": "f(4)=10, f(1)=1. 10−1=9, not 7.", "C": "f(4)=3(4)−2=10. f(1)=3(1)−2=1. 10−1=9. ✓", "D": "12=3×4, but that ignores the constant and subtraction." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-8",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Equivalent expressions (FOIL)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression is equivalent to (x + 4)(x − 7)?",
    options: ["x² − 3x − 28", "x² + 3x − 28", "x² − 28", "x² − 11x − 28"],
    correctAnswer: "A",
    explanation: "FOIL: x²−7x+4x−28 = x²−3x−28. ✓",
    explanations: { "A": "FOIL: x²−7x+4x−28 = x²−3x−28. ✓", "B": "Sign error on middle term: −7x+4x=−3x, not +3x.", "C": "Forgot the middle terms entirely.", "D": "Added magnitudes: −7x−4x=−11x. Should be −7x+4x." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-9",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Quadratic equations (factoring)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What are the solutions of x² − x − 12 = 0?",
    options: ["x = 3 and x = −4", "x = −3 and x = 4", "x = 6 and x = −2", "x = −6 and x = 2"],
    correctAnswer: "B",
    explanation: "Need two numbers that multiply to −12 and add to −1: −4 and +3? No: (−3)(4)=−12, −3+4=+1. Hmm. Actually (x+3)(x−4)=x²−x−12. So x=−3 or x=4. ✓",
    explanations: { "A": "(x−3)(x+4) = x²+x−12. Middle term is +x, not −x.", "B": "Need two numbers that multiply to −12 and add to −1: −4 and +3? No: (−3)(4)=−12, −3+4=+1. Hmm. Actually (x+3)(x−4)=x²−x−12. So x=−3 or x=4. ✓", "C": "(−2)(6)=−12 but −2+6=4≠−1.", "D": "(−6)(2)=−12 but −6+2=−4≠−1." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-10",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Solving quadratics",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If (x − 2)² = 36, what is the positive value of x?",
    options: ["", "", "", ""],
    correctAnswer: "8",
    explanation: "Take square root: x−2=±6. So x=8 or x=−4. Positive value is 8.",
    explanations: { "correct": "Take square root: x−2=±6. So x=8 or x=−4. Positive value is 8." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-11",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Quadratic functions (vertex form)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The function g(x) = −(x − 3)² + 5 has a maximum value. What is this maximum?",
    options: ["−3", "3", "5", "8"],
    correctAnswer: "C",
    explanation: "In vertex form a(x−h)²+k, the vertex is (3,5). Since a<0, it opens down and max=k=5. ✓",
    explanations: { "A": "−3 would flip the sign of the h-value; not the maximum.", "B": "3 is the x-coordinate of the vertex, not the maximum value.", "C": "In vertex form a(x−h)²+k, the vertex is (3,5). Since a<0, it opens down and max=k=5. ✓", "D": "3+5=8 is not how vertex form works." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-12",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Exponential functions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which function models the car’s value V after t years?",
    passage: "A car purchased for $22,000 depreciates by 15% per year.",
    options: ["V(t) = 22000(0.15)ᵗ", "V(t) = 22000(0.85)ᵗ", "V(t) = 22000(1.15)ᵗ", "V(t) = 22000 − 0.15t"],
    correctAnswer: "B",
    explanation: "Depreciates 15% means retains 85%=0.85 each year. V=22000(0.85)ᵗ. ✓",
    explanations: { "A": "0.15 is the rate of loss, not the retention factor. Value would vanish almost immediately.", "B": "Depreciates 15% means retains 85%=0.85 each year. V=22000(0.85)ᵗ. ✓", "C": "1.15 means 15% growth, not depreciation.", "D": "Linear model, not exponential. Cars depreciate by a percentage, not a fixed dollar amount." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-13",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Polynomial evaluation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If p(x) = 2x³ − 3x² + x − 5, what is p(−1)?",
    options: ["−11", "−9", "−1", "1"],
    correctAnswer: "A",
    explanation: "p(−1)=2(−1)³−3(−1)²+(−1)−5 = 2(−1)−3(1)+(−1)−5 = −2−3−1−5 = −11. ✓",
    explanations: { "A": "p(−1)=2(−1)³−3(−1)²+(−1)−5 = 2(−1)−3(1)+(−1)−5 = −2−3−1−5 = −11. ✓", "B": "Sign error on one term.", "C": "Likely forgot the constant −5.", "D": "Multiple sign errors." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-14",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Percentages (sequential)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the final sale price?",
    passage: "A store marks up wholesale prices by 40%, then offers a 20% sale discount on the marked-up price. The wholesale cost of a jacket is $60.",
    options: ["$67.20", "$72.00", "$76.80", "$84.00"],
    correctAnswer: "A",
    explanation: "Markup: 60×1.40=$84. Discount: 84×0.80=$67.20. ✓",
    explanations: { "A": "Markup: 60×1.40=$84. Discount: 84×0.80=$67.20. ✓", "B": "60×1.20=$72 — only applied the 20% difference (40−20), which is wrong.", "C": "60+(40%×60)−(20%×60) = 60+24−12=$72? No, this doesn’t match either.", "D": "$84 is the marked-up price before the discount." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-15",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Two-way tables / Venn diagrams",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What fraction of students who play sports are NOT in band?",
    passage: "A survey of 150 students found: 80 play sports, 60 are in band, and 25 do both.",
    options: ["11/16", "55/150", "25/80", "5/16"],
    correctAnswer: "A",
    explanation: "Sports players not in band: 80−25=55. Fraction of sports players: 55/80=11/16. ✓",
    explanations: { "A": "Sports players not in band: 80−25=55. Fraction of sports players: 55/80=11/16. ✓", "B": "55/150 is the fraction of ALL students, not of sports players.", "C": "25/80 is the fraction who ARE in band, the opposite of what’s asked.", "D": "5/16=25/80 simplified — same as C, the wrong condition." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-16",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Ratios and proportions",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many cups of sugar?",
    passage: "A recipe calls for flour and sugar in a ratio of 3:2. If you use 4.5 cups of flour, how many cups of sugar do you need?",
    options: ["", "", "", ""],
    correctAnswer: "3",
    explanation: "flour/sugar = 3/2. So 4.5/s = 3/2. Cross multiply: 3s=9 → s=3.",
    explanations: { "correct": "flour/sugar = 3/2. So 4.5/s = 3/2. Cross multiply: 3s=9 → s=3." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-17",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Scatterplots and r²",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which is the best interpretation of r² = 0.72?",
    passage: "A scatterplot of study hours vs. test scores for 20 students has a line of best fit with equation ŷ = 5.2x + 48 and r² = 0.72.",
    options: ["72% of students scored above average.", "For each additional study hour, scores increase by 72%.", "Approximately 72% of the variation in test scores is explained by study hours.", "The correlation between study hours and scores is 0.72."],
    correctAnswer: "C",
    explanation: "r² = coefficient of determination: proportion of variation in y explained by x. ✓",
    explanations: { "A": "r² doesn’t describe what percentage of students achieved a certain score.", "B": "5.2 is the rate of change per hour, not 72%.", "C": "r² = coefficient of determination: proportion of variation in y explained by x. ✓", "D": "r=√0.72≈0.85, not 0.72. r² and r are different." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-18",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Study design",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which best describes this study design?",
    passage: "A researcher wants to determine whether a new teaching method improves test scores. She randomly assigns 30 students to the new method and 30 to the traditional method.",
    options: ["Observational study, because the researcher recorded existing conditions.", "Survey, because data was collected from participants.", "Experiment, because treatments were randomly assigned to groups.", "Census, because all students in the class participated."],
    correctAnswer: "C",
    explanation: "Random assignment of treatments = experiment. Allows causal inference. ✓",
    explanations: { "A": "Not observational — the researcher actively assigned treatments.", "B": "Surveys collect self-reported opinions, not measured outcomes.", "C": "Random assignment of treatments = experiment. Allows causal inference. ✓", "D": "A census measures every member of a population; this is a sample." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-19",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Volume (cone)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A right circular cone has radius 5 cm and height 12 cm. What is the volume?",
    options: ["60π cm³", "100π cm³", "300π cm³", "100 cm³"],
    correctAnswer: "B",
    explanation: "V=(1/3)πr²h = (1/3)π(25)(12) = (1/3)(300π) = 100π. ✓",
    explanations: { "A": "60π = (1/3)π(5)(12) — used r instead of r².", "B": "V=(1/3)πr²h = (1/3)π(25)(12) = (1/3)(300π) = 100π. ✓", "C": "300π = πr²h — forgot the 1/3 factor.", "D": "Dropped the π." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-20",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Pythagorean theorem",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "In a right triangle, one leg is 8 and the hypotenuse is 17. What is the length of the other leg?",
    options: ["", "", "", ""],
    correctAnswer: "15",
    explanation: "a²+b²=c². 8²+b²=17². 64+b²=289. b²=225. b=15. (This is the 8-15-17 triple.)",
    explanations: { "correct": "a²+b²=c². 8²+b²=17². 64+b²=289. b²=225. b=15. (This is the 8-15-17 triple.)" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-21",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Trigonometric ratios",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is cos(D)?",
    passage: "In right triangle DEF, angle F=90°, DE=13, DF=5, and EF=12.",
    options: ["5/13", "12/13", "5/12", "12/5"],
    correctAnswer: "A",
    explanation: "cos(D) = adjacent/hypotenuse = DF/DE = 5/13. ✓",
    explanations: { "A": "cos(D) = adjacent/hypotenuse = DF/DE = 5/13. ✓", "B": "12/13 = sin(D) = opposite/hypotenuse.", "C": "5/12 = cos(D)/sin(D) inverted? Actually this is adjacent/opposite.", "D": "12/5 = tan(D) = opposite/adjacent." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-22",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Circle equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A circle has the equation (x + 1)² + (y − 4)² = 16. What are the center and radius?",
    options: ["Center (−1, 4), radius 4", "Center (1, −4), radius 4", "Center (−1, 4), radius 16", "Center (1, −4), radius 16"],
    correctAnswer: "A",
    explanation: "Standard form (x−h)²+(y−k)²=r². Here h=−1, k=4, r²=16 so r=4. ✓",
    explanations: { "A": "Standard form (x−h)²+(y−k)²=r². Here h=−1, k=4, r²=16 so r=4. ✓", "B": "Signs reversed: (x+1) means h=−1, not +1.", "C": "16 is r², not r. Must take the square root.", "D": "Both errors: wrong signs and unsquared radius." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-23",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Linear equations with fractions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The equation (2/3)x − 5 = (1/2)x + 1 has what solution for x?",
    options: ["18", "24", "36", "48"],
    correctAnswer: "C",
    explanation: "Multiply by 6: 4x−30=3x+6. Subtract 3x: x−30=6. Add 30: x=36. Check: (2/3)(36)−5=24−5=19, (1/2)(36)+1=18+1=19. ✓",
    explanations: { "A": "Likely only partially cleared fractions.", "B": "Arithmetic error in clearing denominators.", "C": "Multiply by 6: 4x−30=3x+6. Subtract 3x: x−30=6. Add 30: x=36. Check: (2/3)(36)−5=24−5=19, (1/2)(36)+1=18+1=19. ✓", "D": "Multiplied by 12 instead of 6, doubling the answer." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-24",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Special solutions (identity equations)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "For what value of k does the equation k(x + 3) = 4x + 12 have infinitely many solutions?",
    options: ["1", "3", "4", "12"],
    correctAnswer: "C",
    explanation: "4(x+3)=4x+12, identical to the right side. Infinitely many solutions. ✓",
    explanations: { "A": "1(x+3)=x+3 ≠ 4x+12 for all x.", "B": "3(x+3)=3x+9 ≠ 4x+12 for all x.", "C": "4(x+3)=4x+12, identical to the right side. Infinitely many solutions. ✓", "D": "12(x+3)=12x+36 ≠ 4x+12 for all x." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-25",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Systems (word problems)",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many texts per month make both plans equal in cost?",
    passage: "Plan A costs $45/month plus $0.10 per text. Plan B costs $25/month plus $0.30 per text.",
    options: ["", "", "", ""],
    correctAnswer: "100",
    explanation: "45+0.10t = 25+0.30t → 20=0.20t → t=100.",
    explanations: { "correct": "45+0.10t = 25+0.30t → 20=0.20t → t=100." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-26",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Absolute value equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If |3x − 6| = 12, what is the sum of all possible values of x?",
    options: ["4", "6", "8", "10"],
    correctAnswer: "A",
    explanation: "Case 1: 3x−6=12 → x=6. Case 2: 3x−6=−12 → x=−2. Sum: 6+(−2)=4. ✓",
    explanations: { "A": "Case 1: 3x−6=12 → x=6. Case 2: 3x−6=−12 → x=−2. Sum: 6+(−2)=4. ✓", "B": "6 is just one solution.", "C": "Doubled one solution: 2×4=8? No mathematical basis.", "D": "6+(−4)? Solving error in Case 2." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-27",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Perpendicular lines",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Line p is perpendicular to y = (3/4)x − 2. What is the slope of line p?",
    options: ["−3/4", "3/4", "4/3", "−4/3"],
    correctAnswer: "D",
    explanation: "Perpendicular slopes are negative reciprocals: −1/(3/4) = −4/3. ✓",
    explanations: { "A": "Negative but not reciprocal.", "B": "Same slope means parallel.", "C": "Reciprocal but not negated.", "D": "Perpendicular slopes are negative reciprocals: −1/(3/4) = −4/3. ✓" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-28",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Mixture problems",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How many mL of the 30% solution are used?",
    passage: "A pharmacist mixes a 10% saline solution with a 30% saline solution to create 500 mL of a 22% solution.",
    options: ["200", "250", "300", "350"],
    correctAnswer: "C",
    explanation: "Let x=mL of 30%. Then 500−x=mL of 10%. 0.10(500−x)+0.30x=0.22(500). 50−0.10x+0.30x=110. 0.20x=60. x=300. ✓",
    explanations: { "A": "0.10(300)+0.30(200)=30+60=90. 90/500=18%, too low.", "B": "0.10(250)+0.30(250)=25+75=100. 100/500=20%, too low.", "C": "Let x=mL of 30%. Then 500−x=mL of 10%. 0.10(500−x)+0.30x=0.22(500). 50−0.10x+0.30x=110. 0.20x=60. x=300. ✓", "D": "0.10(150)+0.30(350)=15+105=120. 120/500=24%, too high." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-29",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Systems of equations",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If 2x + 3y = 18 and x − y = 1, what is the value of y?",
    options: ["", "", "", ""],
    correctAnswer: "3.2",
    explanation: "From eq2: x=y+1. Substitute: 2(y+1)+3y=18 → 2y+2+3y=18 → 5y=16 → y=3.2.",
    explanations: { "correct": "From eq2: x=y+1. Substitute: 2(y+1)+3y=18 → 2y+2+3y=18 → 5y=16 → y=3.2." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-30",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Rational expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression is equivalent to (x² − 9) / (x + 3)?",
    options: ["x − 3", "x + 3", "x² − 3", "x − 9"],
    correctAnswer: "A",
    explanation: "x²−9 = (x+3)(x−3). Divide by (x+3): x−3. ✓",
    explanations: { "A": "x²−9 = (x+3)(x−3). Divide by (x+3): x−3. ✓", "B": "Would mean (x+3)² = x²−9, which is false.", "C": "Can’t simplify by just removing the denominator’s constant.", "D": "Subtracted 9 from x² without factoring." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-31",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Equivalent forms of quadratics",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The function h(x) = (x + 2)² − 9 can be rewritten as h(x) = (x + a)(x + b). What is a + b?",
    options: ["−1", "1", "4", "5"],
    correctAnswer: "C",
    explanation: "a+b=4 since (x+5)(x−1) has 5+(−1)=4. ✓",
    explanations: { "A": "Expand: (x+2)²−9 = x²+4x+4−9 = x²+4x−5. Factor: need two numbers that multiply to −5 and add to 4: that’s 5 and −1. So (x+5)(x−1). a+b=5+(−1)=4. Wait, let me recheck.", "B": "Actually: x²+4x−5 = (x+5)(x−1). So a=5, b=−1 (or vice versa). a+b=5+(−1)=4. Hmm, that’s C, not B. Let me re-examine. The sum of roots is −b/a = −4. The product of roots is −5. Factored form: (x+5)(x−1). The values in (x+a)(x+b) give a=5, b=−1, so a+b=4.", "C": "a+b=4 since (x+5)(x−1) has 5+(−1)=4. ✓", "D": "5 is just one of the values." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-32",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Composition of functions",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If f(x) = x² + 1 and g(x) = 3x − 2, what is f(g(1))?",
    options: ["", "", "", ""],
    correctAnswer: "2",
    explanation: "g(1)=3(1)−2=1. f(1)=1²+1=2.",
    explanations: { "correct": "g(1)=3(1)−2=1. f(1)=1²+1=2." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-33",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Radicals",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the simplified form of √(72x⁶)?",
    options: ["6x³√2", "36x³√2", "6x³", "8x³√9"],
    correctAnswer: "A",
    explanation: "√(72x⁶) = √(36·2·x⁶) = 6x³√2. ✓",
    explanations: { "A": "√(72x⁶) = √(36·2·x⁶) = 6x³√2. ✓", "B": "Squared the 6 unnecessarily.", "C": "Dropped the √2 factor.", "D": "Incorrect factorization of 72." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-34",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Exponential growth interpretation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which function models the population P after t hours?",
    passage: "A population of 800 bacteria triples every 4 hours.",
    options: ["P(t) = 800(3)ᵗ⁄⁴", "P(t) = 800(3)⁴ᵗ", "P(t) = 800(4)ᵗ⁄³", "P(t) = 800 + 3t"],
    correctAnswer: "A",
    explanation: "Triples every 4 hours: growth factor 3 per 4-hour period. t/4 periods in t hours. ✓",
    explanations: { "A": "Triples every 4 hours: growth factor 3 per 4-hour period. t/4 periods in t hours. ✓", "B": "3⁴ᵗ triples every 1/4 hour, way too fast.", "C": "Uses base 4, period 3 — swapped values.", "D": "Linear model, not exponential." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-35",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Polynomial factoring",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The polynomial p(x) = x³ − 4x² + x + 6 has x = 2 as a root. Which is a complete factorization?",
    options: ["(x − 2)(x² − 2x − 3)", "(x − 2)(x² + 2x − 3)", "(x + 2)(x² − 2x − 3)", "(x − 2)(x² − 2x + 3)"],
    correctAnswer: "A",
    explanation: "Divide p(x) by (x−2): x³−4x²+x+6 ÷ (x−2) = x²−2x−3. Check: (x−2)(x²−2x−3) = x³−2x²−3x−2x²+4x+6 = x³−4x²+x+6. ✓",
    explanations: { "A": "Divide p(x) by (x−2): x³−4x²+x+6 ÷ (x−2) = x²−2x−3. Check: (x−2)(x²−2x−3) = x³−2x²−3x−2x²+4x+6 = x³−4x²+x+6. ✓", "B": "(x−2)(x²+2x−3) = x³−8x+6? Doesn’t match.", "C": "x=2 is a root, so factor is (x−2), not (x+2).", "D": "x²−2x+3 has no real roots; check: discriminant=4−12<0." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-36",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Completing the square",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If x² + 10x + c is a perfect square trinomial, what is the value of c?",
    options: ["", "", "", ""],
    correctAnswer: "25",
    explanation: "Perfect square: x²+10x+c = (x+k)² means 2k=10, so k=5 and c=k²=25.",
    explanations: { "correct": "Perfect square: x²+10x+c = (x+k)² means 2k=10, so k=5 and c=k²=25." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-37",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Margin of error / confidence intervals",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which is the best interpretation?",
    passage: "A poll of 500 likely voters found 54% support Candidate A. The margin of error is ±4 percentage points at the 95% confidence level.",
    options: ["Exactly 54% of all voters support Candidate A.", "Between 50% and 58% of the sample supports Candidate A.", "It is plausible that between 50% and 58% of all likely voters support Candidate A.", "95% of voters have made up their minds."],
    correctAnswer: "C",
    explanation: "95% CI: 54%±4% = [50%,58%]. We’re 95% confident the population proportion falls here. ✓",
    explanations: { "A": "54% is the sample statistic, not the exact population value.", "B": "We know the sample result is 54%. The interval is about the population.", "C": "95% CI: 54%±4% = [50%,58%]. We’re 95% confident the population proportion falls here. ✓", "D": "95% is the confidence level, not the percentage of decided voters." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-38",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Probability",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the probability of drawing a blue marble? (Enter as a decimal.)",
    passage: "A bag contains 6 red, 4 blue, and 10 green marbles. One marble is drawn at random.",
    options: ["", "", "", ""],
    correctAnswer: "0.2",
    explanation: "Total: 6+4+10=20. P(blue)=4/20=1/5=0.2.",
    explanations: { "correct": "Total: 6+4+10=20. P(blue)=4/20=1/5=0.2." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-39",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Measures of center and spread",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which measure of center is most affected by the outlier (42)?",
    passage: "A data set has values: 3, 5, 7, 7, 8, 10, 12, 15, 42.",
    options: ["Median", "Mode", "Mean", "Range"],
    correctAnswer: "C",
    explanation: "Mean is pulled up by extreme values. Without 42: mean≈8.4. With 42: mean≈12.1. Biggest shift. ✓",
    explanations: { "A": "Median (middle value)=8 with or without the outlier’s exact value.", "B": "Mode=7 regardless of outliers.", "C": "Mean is pulled up by extreme values. Without 42: mean≈8.4. With 42: mean≈12.1. Biggest shift. ✓", "D": "Range is a measure of spread, not center. (And yes, range is also affected by outliers, but the question asks about center.)" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-40",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Similar figures (area ratios)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Two similar triangles have corresponding sides in the ratio 2:5. If the smaller triangle has area 12 cm², what is the area of the larger?",
    options: ["30 cm²", "48 cm²", "75 cm²", "120 cm²"],
    correctAnswer: "C",
    explanation: "Area ratio=(2/5)²=4/25. So 12/A=4/25 → A=12×25/4=75. ✓",
    explanations: { "A": "Multiplied by 5/2=2.5. Area scales by the square of the ratio, not the ratio itself.", "B": "Multiplied by 4=2². Numerator squared instead of ratio.", "C": "Area ratio=(2/5)²=4/25. So 12/A=4/25 → A=12×25/4=75. ✓", "D": "Multiplied by 10 (2×5). No mathematical basis." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-41",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Arc length",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "In a circle with radius 10, a central angle measures 144°. What is the arc length? (Give answer in terms of π, as a number times π, e.g. enter 8 if the answer is 8π.)",
    options: ["", "", "", ""],
    correctAnswer: "8",
    explanation: "Arc=(144/360)×2π(10) = (2/5)(20π) = 8π.",
    explanations: { "correct": "Arc=(144/360)×2π(10) = (2/5)(20π) = 8π." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-42",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Distance formula",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "In the xy-plane, what is the distance between points A(−1, 3) and B(5, 11)?",
    options: ["8", "10", "12", "14"],
    correctAnswer: "B",
    explanation: "d=√((5−(−1))²+(11−3)²) = √(36+64) = √100 = 10. ✓",
    explanations: { "A": "8 is the y-difference: 11−3.", "B": "d=√((5−(−1))²+(11−3)²) = √(36+64) = √100 = 10. ✓", "C": "No basis.", "D": "6+8=14 sums the legs instead of using Pythagorean theorem." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-43",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Sector area",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A sector of a circle has radius 9 and central angle 80°. What is the area of the sector?",
    options: ["18π", "16π", "20π", "12π"],
    correctAnswer: "A",
    explanation: "A=(80/360)πr² = (2/9)π(81) = 18π. ✓",
    explanations: { "A": "A=(80/360)πr² = (2/9)π(81) = 18π. ✓", "B": "Arithmetic error in simplification.", "C": "Used (80/360)×π(100) — wrong radius.", "D": "Used (80/360)×2π(9) which is arc length, not area." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-math-44",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Circle equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "In the xy-plane, which is the equation of a circle centered at (3, −5) with radius 6?",
    options: ["(x − 3)² + (y + 5)² = 6", "(x + 3)² + (y − 5)² = 36", "(x − 3)² + (y + 5)² = 36", "(x − 3)² + (y − 5)² = 36"],
    correctAnswer: "C",
    explanation: "(x−3)²+(y−(−5))²=6² → (x−3)²+(y+5)²=36. ✓",
    explanations: { "A": "Correct center but r²=36, not 6.", "B": "Signs reversed: (x+3) gives center x=−3.", "C": "(x−3)²+(y−(−5))²=6² → (x−3)²+(y+5)²=36. ✓", "D": "(y−5) gives center y=5, not −5." },
    tags: ["diagnostic"],
  }
];
