import type { Question } from "@/types/question";

export const QUESTIONS: Question[] = [
  {
    id: "diag-nmsqt-rw-1",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The architect’s newest building design was praised for its _______ approach, combining traditional materials like stone and wood with cutting-edge solar panel technology in a way that felt natural rather than forced.",
    options: ["controversial", "hybrid", "antiquated", "impractical"],
    correctAnswer: "B",
    explanation: `'Hybrid' means combining two different elements — matches 'combining traditional materials with cutting-edge technology.' ✓`,
    explanations: { "A": "Nothing suggests the approach was controversial or disputed.", "B": `'Hybrid' means combining two different elements — matches 'combining traditional materials with cutting-edge technology.' ✓`, "C": `'Antiquated' means outdated, contradicting the use of cutting-edge technology.`, "D": `The approach 'felt natural,' so it wasn’t impractical.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-2",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "After months of failed experiments, the research team’s breakthrough discovery seemed almost _______, arriving suddenly after a routine calibration of their equipment revealed an unexpected pattern in the data.",
    options: ["inevitable", "serendipitous", "insignificant", "predictable"],
    correctAnswer: "B",
    explanation: `'Serendipitous' means occurring by lucky chance — an unexpected pattern during routine work fits perfectly. ✓`,
    explanations: { "A": `'Inevitable' means bound to happen, but a routine calibration revealing unexpected data is chance, not certainty.`, "B": `'Serendipitous' means occurring by lucky chance — an unexpected pattern during routine work fits perfectly. ✓`, "C": `It was a 'breakthrough,' so not insignificant.`, "D": `An 'unexpected pattern' is by definition not predictable.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-3",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The documentary filmmaker chose to _______ the complex history of the civil rights movement into a single two-hour film, a decision that some critics felt sacrificed important nuance for accessibility.",
    options: ["expand", "condense", "fabricate", "broadcast"],
    correctAnswer: "B",
    explanation: `'Condense' means to compress or shorten — fitting a complex topic into two hours requires condensing. ✓`,
    explanations: { "A": `'Expand' contradicts fitting complex history into a single short film.`, "B": `'Condense' means to compress or shorten — fitting a complex topic into two hours requires condensing. ✓`, "C": `'Fabricate' means to invent falsely, not what the filmmaker did.`, "D": `'Broadcast' means to transmit, not to compress content.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-4",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Unlike her predecessor, who governed through rigid adherence to party platforms, the new mayor adopted a more _______ approach, adjusting her policies in response to changing community needs and emerging data.",
    options: ["dogmatic", "secretive", "pragmatic", "reckless"],
    correctAnswer: "C",
    explanation: `'Pragmatic' means practical and adaptive — matches 'adjusting policies in response to data and needs.' ✓`,
    explanations: { "A": `'Dogmatic' means rigidly following doctrine — that describes the predecessor, not the new mayor.`, "B": "Nothing suggests secrecy; she responded to community needs openly.", "C": `'Pragmatic' means practical and adaptive — matches 'adjusting policies in response to data and needs.' ✓`, "D": "Adjusting to data and community input is thoughtful, not reckless." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-5",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The novelist’s early works were characterized by spare, minimalist prose, but her later novels revealed a marked shift toward _______ description, with passages that lingered on sensory details and elaborate metaphors.",
    options: ["ambiguous", "clinical", "ornate", "repetitive"],
    correctAnswer: "C",
    explanation: `'Ornate' means elaborately decorated — directly contrasts with 'spare, minimalist' and matches 'sensory details and elaborate metaphors.' ✓`,
    explanations: { "A": `'Ambiguous' means unclear — the descriptions are elaborate, not vague.`, "B": `'Clinical' means detached and analytical, which contradicts 'sensory details and elaborate metaphors.'`, "C": `'Ornate' means elaborately decorated — directly contrasts with 'spare, minimalist' and matches 'sensory details and elaborate metaphors.' ✓`, "D": "Nothing suggests the descriptions were repetitive." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-6",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The city council’s decision to allow commercial development along the riverfront was met with _______ from environmental groups, who argued that construction would destroy critical wetland habitats and pollute the waterway.",
    options: ["indifference", "endorsement", "opposition", "confusion"],
    correctAnswer: "C",
    explanation: `Groups argued construction would 'destroy habitats and pollute' — clear opposition. ✓`,
    explanations: { "A": "Environmental groups actively argued against it — not indifferent.", "B": "They opposed the development, not endorsed it.", "C": `Groups argued construction would 'destroy habitats and pollute' — clear opposition. ✓`, "D": "Their position was clearly stated, not confused." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-7",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the overall structure of the text?",
    passage: `Honeybees communicate the location of food sources through a behavior known as the 'waggle dance.' When a forager bee returns to the hive, it performs a figure-eight movement on the honeycomb surface. The angle of the central waggle run relative to vertical indicates the direction of the food source relative to the sun, while the duration of the waggle indicates distance. The longer the waggle, the farther the food.`,
    options: ["It proposes a hypothesis about bee behavior and then tests it.", "It introduces a phenomenon and then explains the specific mechanics of how it works.", "It compares honeybee communication to human language systems.", "It argues that the waggle dance is the most sophisticated form of animal communication."],
    correctAnswer: "B",
    explanation: "Introduces the phenomenon (waggle dance) then explains mechanics (angle=direction, duration=distance). ✓",
    explanations: { "A": "No hypothesis is proposed or tested — the passage describes known behavior.", "B": "Introduces the phenomenon (waggle dance) then explains mechanics (angle=direction, duration=distance). ✓", "C": "No comparison to human language is made.", "D": "No argument about sophistication relative to other animals." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-8",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Cross-Text Connections",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Based on the texts, how would Cole (Text 2) most likely respond to Park’s proposal in Text 1?",
    passage: "<strong>Text 1</strong><br>Nutritionist Dr. Sarah Park argues that school lunch programs should eliminate all processed foods and serve only whole, organic meals. Research consistently shows that children who eat whole foods perform better academically and have fewer behavioral issues.<br><br><strong>Text 2</strong><br>School administrator James Cole acknowledges the health benefits of whole foods but notes that organic school meals cost roughly three times more per student than current programs. For districts already struggling to fund basic educational needs, he argues, the cost difference makes a full organic mandate unrealistic without significant new funding.",
    options: ["By arguing that processed foods are actually healthier than organic foods.", "By acknowledging the health benefits but arguing that implementation costs make a full mandate impractical without additional funding.", "By claiming that academic performance is unrelated to diet.", "By proposing that schools eliminate lunch programs entirely."],
    correctAnswer: "B",
    explanation: `Cole agrees on health benefits but raises practical cost concerns — 'three times more' without 'significant new funding.' ✓`,
    explanations: { "A": `Cole 'acknowledges the health benefits,' so he wouldn’t claim processed foods are healthier.`, "B": `Cole agrees on health benefits but raises practical cost concerns — 'three times more' without 'significant new funding.' ✓`, "C": "Cole acknowledges the research on health benefits, not disputes it.", "D": "Nothing suggests eliminating lunch programs." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-9",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best states the main idea of the text?",
    passage: "The tiny island nation of Bhutan measures its success not by gross domestic product but by Gross National Happiness (GNH). Introduced in 1972 by King Jigme Singye Wangchuck, GNH evaluates the population’s well-being across nine domains including psychological health, cultural resilience, ecological diversity, and living standards. Government policies must pass a GNH impact assessment before implementation, and Bhutan has used this framework to justify decisions that might seem economically irrational, such as banning plastic bags and keeping over 70% of the country forested.",
    options: ["Bhutan’s economy is weaker than other nations because it prioritizes happiness over growth.", "Bhutan uses a unique well-being metric that evaluates national success across multiple dimensions beyond economic output.", "King Jigme Singye Wangchuck was the most popular leader in Bhutanese history.", "Environmental policies like banning plastic bags have made Bhutan the happiest country in the world."],
    correctAnswer: "B",
    explanation: "The passage introduces GNH as an alternative to GDP, covering nine domains beyond economics. ✓",
    explanations: { "A": "The passage doesn’t say Bhutan’s economy is weaker — it describes a different measurement approach.", "B": "The passage introduces GNH as an alternative to GDP, covering nine domains beyond economics. ✓", "C": "The king is mentioned as introducing GNH, not described as most popular.", "D": "The passage doesn’t claim Bhutan is the happiest country." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-10",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "According to the text, what factors contributed to good dental health in Pompeii?",
    passage: "Archaeologists studying ancient Pompeii have discovered that many of the city’s residents had surprisingly good dental health. Analysis of skeletal remains reveals few cavities despite the absence of toothbrushes or modern dental care. Researchers attribute this to the Pompeiian diet, which was high in fiber and low in sugar. The volcanic soil around Mount Vesuvius also enriched local water supplies with fluoride, which strengthens tooth enamel.",
    options: ["Advanced dental tools and frequent visits to physicians.", "A high-fiber, low-sugar diet and naturally fluoridated water from volcanic soil.", "The hot climate, which killed bacteria in the mouth.", "Strict hygiene laws enforced by city officials."],
    correctAnswer: "B",
    explanation: `Directly stated: diet 'high in fiber and low in sugar' plus volcanic soil adding fluoride to water. ✓`,
    explanations: { "A": `The passage says 'absence of toothbrushes or modern dental care.'`, "B": `Directly stated: diet 'high in fiber and low in sugar' plus volcanic soil adding fluoride to water. ✓`, "C": "Climate is never mentioned.", "D": "No laws or officials are discussed." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-11",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The text primarily emphasizes which idea about language extinction?",
    passage: "Language extinction is accelerating worldwide. Of the roughly 7,000 languages currently spoken, linguists estimate that one goes silent every two weeks. Most at risk are indigenous languages spoken by fewer than 1,000 people, particularly in regions where economic pressures push younger generations toward dominant languages like English, Mandarin, or Spanish. When a language dies, it takes with it unique knowledge systems, oral histories, and ways of understanding the natural world that cannot be fully captured in translation.",
    options: ["English, Mandarin, and Spanish are the only languages that will survive.", "Language loss is happening rapidly and carries significant cultural consequences beyond mere communication.", "Younger generations should be required by law to learn their indigenous languages.", "Linguists have the tools to prevent all language extinction if given proper funding."],
    correctAnswer: "B",
    explanation: `'One goes silent every two weeks' (rapid) plus 'unique knowledge systems, oral histories' lost (cultural consequences). ✓`,
    explanations: { "A": `The passage says these are 'dominant' languages, not the only survivors.`, "B": `'One goes silent every two weeks' (rapid) plus 'unique knowledge systems, oral histories' lost (cultural consequences). ✓`, "C": "No legal requirements are discussed or proposed.", "D": "No claim about prevention capabilities." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-12",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding, if true, would most directly support Csikszentmihalyi’s claim about when flow occurs?",
    passage: `Psychologist Mihaly Csikszentmihalyi developed the concept of 'flow' — a mental state of complete absorption in an activity where a person loses track of time and feels deeply engaged. Csikszentmihalyi argued that flow occurs when the difficulty of a task closely matches a person’s skill level: too easy, and boredom results; too hard, and anxiety takes over.`,
    options: ["People who meditate regularly report feeling calmer throughout the day.", "A study found that chess players experienced the deepest engagement when playing opponents of similar skill, rather than much stronger or weaker ones.", "Most people prefer watching television to engaging in creative hobbies.", "Athletes who train more hours per week earn higher salaries."],
    correctAnswer: "B",
    explanation: "Matched opponents = difficulty matching skill. Deepest engagement = flow. Directly supports the claim. ✓",
    explanations: { "A": "Meditation and calm aren’t about the task-difficulty/skill-level match.", "B": "Matched opponents = difficulty matching skill. Deepest engagement = flow. Directly supports the claim. ✓", "C": "TV preference doesn’t address the difficulty/skill match.", "D": "Training hours and salary don’t relate to the flow experience." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-13",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the evidence Thompson uses?",
    passage: "Urban ecologist Dr. Maya Thompson argues that cities can support surprising biodiversity when green spaces are intentionally designed to mimic natural habitats rather than maintained as manicured lawns. Her research in Chicago found that parks with native prairie plantings supported four times more pollinator species than parks with traditional landscaping.",
    options: ["A nationwide survey of urban park visitors’ preferences.", "A comparison within one city showing that habitat-mimicking parks supported more pollinators than traditional parks.", "An experiment testing whether adding bird feeders increases biodiversity.", "Historical records of species populations in Chicago before urbanization."],
    correctAnswer: "B",
    explanation: `'Research in Chicago' comparing native prairie plantings (4x more pollinators) to traditional landscaping — comparison within one city. ✓`,
    explanations: { "A": "No survey of visitors is mentioned.", "B": `'Research in Chicago' comparing native prairie plantings (4x more pollinators) to traditional landscaping — comparison within one city. ✓`, "C": "No experiment with bird feeders.", "D": "No historical records discussed." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-14",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to support the claim that teachers prefer hands-on formats over lecture-based ones?",
    passage: "A school district surveyed teachers about their preferred professional development formats.",
    options: ["Online webinars were preferred by 15% of teachers, while in-person lectures were preferred by 20%.", "Hands-on workshops were preferred by 42% of teachers, more than double the 20% who preferred in-person lectures.", "The survey included responses from teachers at 12 schools across the district.", "Peer observation was the least preferred format at 8%."],
    correctAnswer: "B",
    explanation: "Directly compares hands-on (42%) to lecture (20%), showing hands-on preferred by more than double. ✓",
    explanations: { "A": "Compares two formats that could both be lecture-based.", "B": "Directly compares hands-on (42%) to lecture (20%), showing hands-on preferred by more than double. ✓", "C": "Sample description doesn’t support a preference claim.", "D": "Peer observation being least preferred doesn’t address the hands-on vs. lecture comparison." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-15",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to describe a trend in teenage screen time?",
    passage: "Researchers tracked the average daily screen time of teenagers across three years.",
    options: ["In 2021, social media accounted for 95 minutes of daily screen time.", "Video streaming remained the largest category of screen time across all three years, growing from 110 to 135 minutes daily.", "Educational screen time decreased from 55 to 35 minutes between 2021 and 2023.", "Total daily screen time increased from 300 to 350 minutes between 2021 and 2023."],
    correctAnswer: "D",
    explanation: "Total screen time increase across three years describes the broadest trend. ✓",
    explanations: { "A": "A single data point doesn’t describe a trend.", "B": "True but only describes one category, not the overall trend.", "C": "True but describes only one category.", "D": "Total screen time increase across three years describes the broadest trend. ✓" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-16",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: `In the 1960s, mathematician Edward Lorenz discovered that tiny rounding differences in weather simulation inputs — as small as 0.000127 — could produce dramatically different long-range forecasts. This finding, later popularized as the 'butterfly effect,' demonstrated that weather systems are so sensitive to initial conditions that perfect long-range prediction may be fundamentally impossible. ________`,
    options: ["This is why modern weather forecasts remain highly accurate only for about 7 to 10 days, despite enormous advances in computing power and data collection.", "As a result, meteorologists have abandoned all attempts to predict weather.", "Lorenz’s discovery proved that weather is completely random and follows no patterns.", "Modern computers are now powerful enough to overcome this limitation entirely."],
    correctAnswer: "A",
    explanation: "If perfect long-range prediction is fundamentally impossible, accuracy would be limited to shorter periods even with better technology. ✓",
    explanations: { "A": "If perfect long-range prediction is fundamentally impossible, accuracy would be limited to shorter periods even with better technology. ✓", "B": "Meteorologists still forecast; they just accept limits.", "C": "Weather follows patterns (physics) but is sensitive to initial conditions — not random.", "D": `Contradicts 'fundamentally impossible' — it’s a mathematical limit, not a computing one.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-17",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The giant panda was once classified as a member of the raccoon family due to certain physical similarities, including a similar body shape and a shared taste for bamboo. _______, genetic analysis conducted in the 1980s conclusively placed pandas within the bear family, Ursidae.",
    options: ["Similarly", "However", "Therefore", "For instance"],
    correctAnswer: "B",
    explanation: `Shifting from 'classified as raccoon family' to 'conclusively placed in bear family' — a clear contrast. ✓`,
    explanations: { "A": "The genetic finding contradicts the earlier classification, not supports it.", "B": `Shifting from 'classified as raccoon family' to 'conclusively placed in bear family' — a clear contrast. ✓`, "C": "The genetic finding doesn’t follow logically from the raccoon classification.", "D": "The genetic analysis isn’t an example of the raccoon classification." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-18",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The city of Amsterdam has invested heavily in cycling infrastructure, with over 500 kilometers of dedicated bike lanes and 800,000 bicycles for a population of 900,000. _______, roughly 63% of Amsterdam residents use their bikes daily for commuting, shopping, and socializing.",
    options: ["Nevertheless", "In contrast", "As a result", "Surprisingly"],
    correctAnswer: "C",
    explanation: "Infrastructure investment leads to high usage — a cause-and-effect relationship. ✓",
    explanations: { "A": `'Nevertheless' implies contrast, but high usage follows logically from heavy investment.`, "B": "No contrasting subject is introduced.", "C": "Infrastructure investment leads to high usage — a cause-and-effect relationship. ✓", "D": "High usage after heavy investment isn’t surprising; it’s expected." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-19",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The Mediterranean monk seal is one of the world’s most endangered marine mammals, with fewer than 700 individuals remaining. Conservation efforts in Greece and Turkey have shown promising results, with some local populations stabilizing. _______, researchers warn that climate change, ocean pollution, and habitat loss continue to threaten the species’ long-term survival.",
    options: ["In addition", "For example", "Even so", "In other words"],
    correctAnswer: "C",
    explanation: `'Even so' acknowledges the positive trend while introducing an important caveat. ✓`,
    explanations: { "A": "The warning doesn’t simply add to the positive news — it qualifies it.", "B": "The warning isn’t an example of stabilizing populations.", "C": `'Even so' acknowledges the positive trend while introducing an important caveat. ✓`, "D": "The warning restates nothing — it introduces new cautionary information." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-20",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the benefits of bilingualism and wants to emphasize cognitive advantages.",
    options: ["Approximately 43% of the world’s population is bilingual or multilingual.", "Studies show that bilingual individuals switch between tasks more efficiently and show delayed onset of dementia symptoms by an average of 4-5 years compared to monolinguals.", "Many countries require students to study a second language in school.", "Bilingualism can sometimes cause temporary difficulty in word retrieval."],
    correctAnswer: "B",
    explanation: "Task switching efficiency and delayed dementia — both are cognitive advantages. ✓",
    explanations: { "A": "A statistic about prevalence, not cognitive benefits.", "B": "Task switching efficiency and delayed dementia — both are cognitive advantages. ✓", "C": "Educational policy, not a cognitive benefit.", "D": "This is a disadvantage, not a benefit." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-21",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the history of the printing press and wants to emphasize its revolutionary impact on access to knowledge.",
    options: ["Johannes Gutenberg invented the movable type printing press around 1440 in Mainz, Germany.", "Before the printing press, a single book could take months to copy by hand, making books so expensive that only the wealthiest institutions could afford libraries; Gutenberg’s invention reduced book production time by over 90%, making written knowledge accessible to a vastly wider audience for the first time.", "The printing press used individual metal letter molds that could be rearranged and reused.", "China had developed woodblock printing several centuries before Gutenberg."],
    correctAnswer: "B",
    explanation: "Shows the before (expensive, slow) and after (90% faster, wider access) — directly emphasizes revolutionary impact on knowledge access. ✓",
    explanations: { "A": "Factual but doesn’t emphasize the revolutionary impact on access.", "B": "Shows the before (expensive, slow) and after (90% faster, wider access) — directly emphasizes revolutionary impact on knowledge access. ✓", "C": "Technical detail about the mechanism, not impact on access.", "D": "Historical context about China, not Gutenberg’s impact." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-22",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about coral reef conservation and wants to highlight a specific successful intervention.",
    options: ["Coral reefs support approximately 25% of all marine species.", "Coral bleaching occurs when water temperatures rise above normal levels.", "In Bonaire, a marine park program that restricted fishing and anchoring has helped local reefs recover, with coral cover increasing from 15% to 40% over a 15-year period.", "Scientists estimate that 50% of the world’s coral reefs have been lost since 1950."],
    correctAnswer: "C",
    explanation: "Names a specific place (Bonaire), intervention (restrictions), and measurable result (15% to 40%). ✓",
    explanations: { "A": "General importance of reefs, not a specific intervention.", "B": "Cause of bleaching, not a successful intervention.", "C": "Names a specific place (Bonaire), intervention (restrictions), and measurable result (15% to 40%). ✓", "D": "Global decline statistic — the opposite of a success story." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-23",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The Great Wall of China, which stretches over 13,000 _______ was built over many centuries by multiple dynasties to protect against invasions from the north.",
    options: ["miles,", "miles;", "miles", "miles—"],
    correctAnswer: "A",
    explanation: `A comma closes the nonrestrictive clause 'which stretches over 13,000 miles' before the main clause continues. ✓`,
    explanations: { "A": `A comma closes the nonrestrictive clause 'which stretches over 13,000 miles' before the main clause continues. ✓`, "B": "A semicolon joins independent clauses — but the portion before is not independent (it’s a nonrestrictive clause modifier).", "C": "No punctuation creates a run-on between the relative clause and the main clause.", "D": "A dash could work in informal writing but a comma is standard for closing a nonrestrictive clause." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-24",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The library’s new digital archive contains over 50,000 historical _______ it is free to access for all registered patrons.",
    options: ["documents,", "documents;", "documents and", "documents"],
    correctAnswer: "B",
    explanation: "Semicolon correctly joins two related independent clauses. ✓",
    explanations: { "A": "Comma splice — two independent clauses cannot be joined by a comma alone.", "B": "Semicolon correctly joins two related independent clauses. ✓", "C": `Needs a comma before 'and' to properly join independent clauses.`, "D": "Run-on sentence." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-25",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Although the experiment yielded promising initial _______ the team decided to replicate the study with a larger sample size before publishing their findings.",
    options: ["results;", "results", "results,", "results—"],
    correctAnswer: "C",
    explanation: `Comma correctly separates the introductory 'Although' clause from the main clause. ✓`,
    explanations: { "A": "A semicolon can’t separate a dependent clause from the main clause.", "B": "No punctuation between a subordinate clause and main clause creates a run-on.", "C": `Comma correctly separates the introductory 'Although' clause from the main clause. ✓`, "D": "A dash disrupts the natural subordinate-to-main flow." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-26",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The group of students _______ already submitted their final projects by the time the professor extended the deadline.",
    options: ["have", "has", "had", "having"],
    correctAnswer: "C",
    explanation: `'Had submitted' is past perfect, correctly showing the submission happened before the deadline extension. ✓`,
    explanations: { "A": `'Have' is present tense and doesn’t work with the past context ('extended').`, "B": `'Has' is present tense; both actions are in the past.`, "C": `'Had submitted' is past perfect, correctly showing the submission happened before the deadline extension. ✓`, "D": `'Having' without a helper verb creates a fragment.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-27",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Each of the volunteers _______ required to complete a background check before working with children at the community center.",
    options: ["are", "is", "were", "have been"],
    correctAnswer: "B",
    explanation: `'Each' always takes a singular verb regardless of the prepositional phrase 'of the volunteers.' ✓`,
    explanations: { "A": `'Each' is singular; 'are' is plural.`, "B": `'Each' always takes a singular verb regardless of the prepositional phrase 'of the volunteers.' ✓`, "C": `'Were' is plural past tense — doesn’t agree with singular 'each.'`, "D": `'Have been' is plural, disagreeing with 'each.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-28",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The composer’s latest symphony was a deliberate _______ of classical conventions: where audiences expected harmonic resolution, she introduced dissonance; where tradition demanded a triumphant finale, she ended in quiet ambiguity.",
    options: ["celebration", "subversion", "imitation", "simplification"],
    correctAnswer: "B",
    explanation: `'Subversion' means deliberately undermining or overturning — she replaced expected elements with their opposites. ✓`,
    explanations: { "A": "She introduced the opposite of expectations — not a celebration of convention.", "B": `'Subversion' means deliberately undermining or overturning — she replaced expected elements with their opposites. ✓`, "C": "She did the opposite of convention, not imitated it.", "D": "Replacing resolution with dissonance isn’t simplification." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-29",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "While many economists argue that automation will eventually generate new categories of employment, labor historian Sarah Chen contends that this optimism ignores the _______ nature of current technological displacement — entire sectors can be transformed within years, not the generations that previous economic transitions required.",
    options: ["gradual", "beneficial", "unprecedented", "negligible"],
    correctAnswer: "C",
    explanation: `'Unprecedented' means never before experienced — the speed of displacement (years vs. generations) is historically unique. ✓`,
    explanations: { "A": `'Gradual' contradicts 'within years' — the point is that displacement is fast.`, "B": "Chen is arguing against optimism, not supporting it.", "C": `'Unprecedented' means never before experienced — the speed of displacement (years vs. generations) is historically unique. ✓`, "D": `'Negligible' means too small to matter, contradicting 'entire sectors transformed.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-30",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The philosopher argued that genuine moral courage is not the absence of fear but rather the willingness to act _______ it, choosing what is right even when doing so carries personal risk.",
    options: ["without", "despite", "because of", "before"],
    correctAnswer: "B",
    explanation: `'Despite' means in spite of — acting even though fear exists. ✓`,
    explanations: { "A": `The passage says courage is 'not the absence of fear' — so fear is present, not absent.`, "B": `'Despite' means in spite of — acting even though fear exists. ✓`, "C": "Acting because of fear would be panic, not courage.", "D": `'Before' doesn’t capture the relationship between fear and action described.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-31",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Critics praised the museum’s new exhibit for its _______ approach to presenting colonial history, giving equal weight to the perspectives of colonizers and colonized peoples rather than privileging one narrative over the other.",
    options: ["biased", "comprehensive", "equitable", "traditional"],
    correctAnswer: "C",
    explanation: `'Equitable' means fair and balanced — matches 'giving equal weight' to both perspectives. ✓`,
    explanations: { "A": `'Biased' contradicts 'equal weight' to both perspectives.`, "B": `'Comprehensive' means thorough but doesn’t specifically address the balance between perspectives.`, "C": `'Equitable' means fair and balanced — matches 'giving equal weight' to both perspectives. ✓`, "D": `A 'traditional' approach would likely privilege the colonizer’s perspective.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-32",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The startup’s initial product launch was widely regarded as a failure, but CEO Maria Santos viewed the setback as _______, using customer feedback from the failed launch to redesign the product into what would eventually become the company’s most profitable offering.",
    options: ["catastrophic", "irrelevant", "instructive", "inevitable"],
    correctAnswer: "C",
    explanation: `'Instructive' means providing useful information — the failure taught her how to improve. ✓`,
    explanations: { "A": "She used it productively, not as a catastrophe.", "B": "If she used the feedback, it wasn’t irrelevant.", "C": `'Instructive' means providing useful information — the failure taught her how to improve. ✓`, "D": `'Inevitable' doesn’t capture the idea of learning from failure.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-33",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: `Which choice best describes the function of the phrase 'a geological blink'?`,
    passage: "In 2018, an international team of researchers drilled into the Chicxulub crater off Mexico’s Yucatán Peninsula — the impact site of the asteroid that caused the mass extinction of dinosaurs 66 million years ago. Core samples revealed that within hours of impact, the crater had been colonized by microorganisms. Within 30,000 years — a geological blink — a thriving ecosystem had established itself in what had been, moments before, a zone of total destruction.",
    options: ["It provides a technical definition of a unit of geological time.", "It uses figurative language to emphasize how quickly the ecosystem recovered relative to geological timescales.", "It argues that 30,000 years is an insignificant period.", "It compares the Chicxulub event to other asteroid impacts."],
    correctAnswer: "B",
    explanation: `Comparing 30,000 years to a 'blink' emphasizes speed in geological context. ✓`,
    explanations: { "A": `'A geological blink' isn’t a technical definition — it’s a metaphor.`, "B": `Comparing 30,000 years to a 'blink' emphasizes speed in geological context. ✓`, "C": `30,000 years matters in the passage; 'blink' shows it’s fast for geology, not insignificant.`, "D": "No comparison to other impacts." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-34",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding, if true, would most directly support Ariely’s claim about predictable irrationality?",
    passage: `Behavioral economist Dan Ariely argues that people are 'predictably irrational' — that human decision-making consistently deviates from purely rational models in specific, systematic ways. For instance, people tend to overvalue things they already own (the endowment effect) and are more motivated by potential losses than equivalent gains (loss aversion).`,
    options: ["A study found that people consistently rejected offers to sell items they owned for twice the market price, even when they had purchased those items at market price just hours earlier.", "Most consumers read product reviews before making purchases.", "People with higher incomes make different spending choices than those with lower incomes.", "A survey found that 60% of people consider themselves good decision-makers."],
    correctAnswer: "A",
    explanation: "Refusing to sell for double what you paid demonstrates the endowment effect — overvaluing what you own. Systematic and irrational. ✓",
    explanations: { "A": "Refusing to sell for double what you paid demonstrates the endowment effect — overvaluing what you own. Systematic and irrational. ✓", "B": "Reading reviews is rational behavior.", "C": "Income-based differences are expected, not irrational.", "D": "Self-perception doesn’t demonstrate actual irrationality." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-35",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly weaken Ballard’s argument for leaving wrecks undisturbed?",
    passage: "Marine archaeologist Robert Ballard, who discovered the wreck of the Titanic in 1985, has argued that deep-sea shipwrecks should be treated as underwater museums rather than salvage sites. He contends that removing artifacts from wrecks destroys the archaeological context that gives them meaning and that wrecks are better preserved in the cold, oxygen-poor environment of the deep sea than in surface museums.",
    options: ["A study showing that deep-sea corrosion is accelerating due to ocean acidification, causing wreck sites to deteriorate faster than previously expected.", "The discovery of a new deep-sea shipwreck in the Mediterranean.", "A survey showing that most people have never visited an underwater museum.", "Evidence that Robert Ballard profited from the Titanic discovery."],
    correctAnswer: "A",
    explanation: `If wrecks are deteriorating in situ, Ballard’s claim that they’re 'better preserved' in the deep sea is undermined. ✓`,
    explanations: { "A": `If wrecks are deteriorating in situ, Ballard’s claim that they’re 'better preserved' in the deep sea is undermined. ✓`, "B": "A new discovery doesn’t address whether wrecks should be disturbed.", "C": "Visitor numbers don’t address preservation arguments.", "D": "Personal motives don’t address the substance of the argument." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-36",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to support the claim that the engagement program improved satisfaction with parks and recreation services specifically?",
    passage: "A city tracked resident satisfaction with public services over five years after implementing a new community engagement program.",
    options: ["Overall satisfaction increased from 62% to 73% between 2019 and 2023.", "Parks and recreation satisfaction showed the largest increase of any category, rising from 55% to 78% over the five-year period.", "Public safety satisfaction remained relatively stable, changing only from 71% to 74%.", "Road maintenance satisfaction decreased from 58% to 52%."],
    correctAnswer: "B",
    explanation: "Specifically shows parks and recreation had the largest gain (55% to 78% = 23 points), directly supporting the claim. ✓",
    explanations: { "A": "Overall satisfaction doesn’t isolate parks and recreation.", "B": "Specifically shows parks and recreation had the largest gain (55% to 78% = 23 points), directly supporting the claim. ✓", "C": "Public safety stability doesn’t address parks.", "D": "Road maintenance declining contradicts the general claim but doesn’t address parks." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-37",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "Researchers studying elephant communication have discovered that elephants produce infrasound — vocalizations below the range of human hearing — that can travel through the ground for distances of up to 20 miles. Other elephants detect these vibrations through sensitive nerve endings in their feet. This seismic communication system appears to function independently of the elephants’ more familiar trumpet calls. ________",
    options: ["Elephants, therefore, are the only animals that communicate using sound.", "This discovery suggests that elephants possess a dual communication system, using both airborne and ground-based signals to stay connected across vast distances.", "Scientists have concluded that elephant trumpet calls serve no communicative purpose.", "Infrasound is too quiet for elephants to detect reliably."],
    correctAnswer: "B",
    explanation: `Infrasound through ground + trumpet calls through air = dual system, functioning 'independently.' ✓`,
    explanations: { "A": "Many animals use sound; the passage doesn’t claim exclusivity.", "B": `Infrasound through ground + trumpet calls through air = dual system, functioning 'independently.' ✓`, "C": `The passage says infrasound works 'independently of' trumpet calls, implying both are used.`, "D": `Contradicts 'detect these vibrations through sensitive nerve endings.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-38",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "In the 1950s, psychologist Solomon Asch conducted experiments in which participants were shown lines of clearly different lengths and asked which matched a reference line. When confederates in the room unanimously gave an obviously wrong answer, roughly 75% of participants conformed to the incorrect consensus at least once. ________",
    options: ["This demonstrates that most people have poor eyesight.", "The findings suggest that social pressure can override individuals’ own perceptual judgments, even when the correct answer is unambiguous.", "Asch concluded that participants actually believed the confederates’ answers were correct.", "The study proved that group decision-making always produces wrong answers."],
    correctAnswer: "B",
    explanation: "Participants knew the right answer (clear differences) but conformed anyway — social pressure overriding perception. ✓",
    explanations: { "A": `The lines were 'clearly different' and the answer 'obviously wrong' — eyesight isn’t the issue.`, "B": "Participants knew the right answer (clear differences) but conformed anyway — social pressure overriding perception. ✓", "C": "Conformity doesn’t mean they believed the wrong answer; they went along despite knowing better.", "D": `'Always' is too absolute; 75% conformed 'at least once,' not always.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-39",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The Japanese art of kintsugi involves repairing broken pottery with gold-infused lacquer, making the cracks visible rather than hiding them. Far from diminishing the object’s value, this technique often makes repaired pieces more prized than undamaged ones. _______, kintsugi has become a popular metaphor in psychology for the idea that overcoming adversity can make a person stronger and more beautiful.",
    options: ["In contrast", "Accordingly", "Nevertheless", "By extension"],
    correctAnswer: "D",
    explanation: `'By extension' — the physical concept extends metaphorically to psychology. ✓`,
    explanations: { "A": "The metaphor extends the concept, not contrasts it.", "B": `'Accordingly' implies the metaphor is a direct result, but it’s an extension of the idea.`, "C": "No contradiction between valuing repairs and using it as a metaphor.", "D": `'By extension' — the physical concept extends metaphorically to psychology. ✓` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-40",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Sleep researcher Matthew Walker has demonstrated that even moderate sleep deprivation — getting six hours instead of eight — measurably impairs cognitive function, emotional regulation, and immune response. _______, Walker notes that sleep-deprived individuals consistently overestimate their own performance, believing they are functioning normally when objective tests show significant decline.",
    options: ["On the other hand", "Compounding the problem", "In summary", "By contrast"],
    correctAnswer: "B",
    explanation: "Overestimating performance while impaired adds to (compounds) the problem of sleep deprivation. ✓",
    explanations: { "A": "The second point doesn’t contradict the first.", "B": "Overestimating performance while impaired adds to (compounds) the problem of sleep deprivation. ✓", "C": "The passage isn’t summarizing; it’s adding a new dimension.", "D": "Both points describe problems with sleep deprivation, not contrasts." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-41",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Ancient Roman concrete structures like the Pantheon have endured for nearly 2,000 years, while many modern concrete buildings begin deteriorating within decades. _______, researchers have discovered that Roman concrete contained volcanic ash, which reacts with seawater to form mineral crystals that actually strengthen the material over time.",
    options: ["Regardless", "Investigating this discrepancy", "As a result", "In other words"],
    correctAnswer: "B",
    explanation: "Scientists investigated why Roman concrete lasts longer and found the answer. ✓",
    explanations: { "A": "The research isn’t dismissing the discrepancy.", "B": "Scientists investigated why Roman concrete lasts longer and found the answer. ✓", "C": "The discovery isn’t a result of the durability; it’s an explanation for it.", "D": "The volcanic ash finding is new information, not a restatement." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-42",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about electric vehicles and wants to address a common concern about charging infrastructure.",
    options: ["Electric vehicles produce zero tailpipe emissions.", "Tesla was founded in 2003 by a group of engineers in Silicon Valley.", "While range anxiety remains a barrier to EV adoption, the U.S. now has over 160,000 public charging stations — triple the number available in 2020 — with the federal government funding an additional 500,000 by 2030.", "Lithium-ion batteries are the most common type used in electric vehicles."],
    correctAnswer: "C",
    explanation: "Acknowledges the concern (range anxiety) and responds with concrete data (160K stations, tripling, 500K target). ✓",
    explanations: { "A": "Emissions don’t address charging infrastructure concerns.", "B": "Company history is unrelated to infrastructure.", "C": "Acknowledges the concern (range anxiety) and responds with concrete data (160K stations, tripling, 500K target). ✓", "D": "Battery type doesn’t address charging access." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-43",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the history of women in computing and wants to highlight an often-overlooked contribution.",
    options: ["The first electronic computer, ENIAC, was completed in 1945.", "Ada Lovelace is widely considered the first computer programmer.", "Though rarely credited in their time, the six women who programmed ENIAC — Kay McNulty, Betty Jennings, Betty Snyder, Marlyn Meltzer, Fran Bilas, and Ruth Lichterman — invented many of the fundamental programming techniques still used today, yet their names went unrecognized for decades.", "Computer science enrollment among women peaked in 1984 at 37%."],
    correctAnswer: "C",
    explanation: `Names the women, describes their contributions, and emphasizes their lack of recognition — 'often-overlooked.' ✓`,
    explanations: { "A": "Technical fact about ENIAC, not about overlooked contributions.", "B": "Lovelace is widely known, not overlooked.", "C": `Names the women, describes their contributions, and emphasizes their lack of recognition — 'often-overlooked.' ✓`, "D": "Enrollment statistics aren’t about a specific overlooked contribution." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-44",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about urban heat islands for an environmental science class and wants to propose a specific solution.",
    options: ["Urban areas can be up to 7°F hotter than surrounding rural areas.", "Heat-related illness is a leading cause of weather-related deaths in the United States.", "Cities could significantly reduce heat island effects by replacing dark asphalt with reflective ‘cool pavements,’ which studies show can lower local surface temperatures by up to 30°F and reduce energy costs for nearby buildings by 10-15%.", "Climate change is expected to increase the frequency and intensity of heat waves."],
    correctAnswer: "C",
    explanation: "Names a specific solution (cool pavements) with quantified benefits (30°F reduction, 10-15% energy savings). ✓",
    explanations: { "A": "Describes the problem, not a solution.", "B": "Health impact, not a solution.", "C": "Names a specific solution (cool pavements) with quantified benefits (30°F reduction, 10-15% energy savings). ✓", "D": "Future projections, not a solution." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-45",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The astronomer presented three key _______ the expansion rate of the universe is accelerating, dark energy comprises approximately 68% of the cosmos, and our current models cannot fully explain either phenomenon.",
    options: ["findings,", "findings:", "findings;", "findings—"],
    correctAnswer: "B",
    explanation: "A colon correctly introduces the list of three findings. ✓",
    explanations: { "A": "A comma doesn’t properly introduce a list of three items.", "B": "A colon correctly introduces the list of three findings. ✓", "C": "A semicolon joins clauses, not a noun and a list.", "D": "A dash could work informally but a colon is standard for introducing enumerated items." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-46",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The restaurant earned praise for its innovative _______ however, some diners felt that the portion sizes did not justify the high prices.",
    options: ["menu,", "menu;", "menu", "menu, and"],
    correctAnswer: "B",
    explanation: `A semicolon before 'however' correctly separates two independent clauses. ✓`,
    explanations: { "A": `A comma before 'however' connecting independent clauses creates a comma splice.`, "B": `A semicolon before 'however' correctly separates two independent clauses. ✓`, "C": `No punctuation before 'however' creates a run-on.`, "D": `'And however' is not standard usage.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-47",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "While the initial results were _______ the research team remained cautious about drawing broad conclusions from such a limited data set.",
    options: ["encouraging;", "encouraging", "encouraging,", "encouraging—"],
    correctAnswer: "C",
    explanation: `A comma correctly separates the introductory 'While' clause from the main clause. ✓`,
    explanations: { "A": "A semicolon can’t separate a dependent clause from the main clause.", "B": "No punctuation creates a run-on.", "C": `A comma correctly separates the introductory 'While' clause from the main clause. ✓`, "D": "A dash disrupts the natural subordinate-to-main flow." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-48",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The orchestra’s rendition of Beethoven’s Fifth Symphony, which _______ over 200 years after its premiere, continues to move audiences with its dramatic intensity.",
    options: ["is performed", "are performed", "performing", "were performed"],
    correctAnswer: "A",
    explanation: `Subject is 'rendition' (singular). 'Is performed' agrees and fits present context. ✓`,
    explanations: { "A": `Subject is 'rendition' (singular). 'Is performed' agrees and fits present context. ✓`, "B": `'Are' is plural, doesn’t agree with singular 'rendition.'`, "C": `'Performing' without a helper verb creates a fragment.`, "D": `'Were' is past plural — wrong number and tense.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-49",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The committee, together with several outside _______ currently reviewing the grant applications for the upcoming fiscal year.",
    options: ["consultants, are", "consultants, is", "consultants are", "consultants is"],
    correctAnswer: "B",
    explanation: `Comma closes the parenthetical; 'is' agrees with singular 'committee.' ✓`,
    explanations: { "A": `'Together with' is parenthetical and doesn’t change the subject. 'Committee' is singular.`, "B": `Comma closes the parenthetical; 'is' agrees with singular 'committee.' ✓`, "C": "Missing closing comma for parenthetical phrase.", "D": "Missing comma; confusing structure." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-50",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "By the time the documentary _______ in theaters, the controversy it depicted had already been resolved through a landmark court ruling.",
    options: ["opens", "opened", "will open", "had opened"],
    correctAnswer: "B",
    explanation: `Simple past 'opened' matches the past narrative. The controversy 'had been resolved' (past perfect) before the release (simple past). ✓`,
    explanations: { "A": `Present tense doesn’t match the past-tense context ('had already been resolved').`, "B": `Simple past 'opened' matches the past narrative. The controversy 'had been resolved' (past perfect) before the release (simple past). ✓`, "C": "Future tense contradicts the past context.", "D": `'Had opened' would mean the opening happened before the resolution, but the resolution happened first.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-51",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The author, _______ previous novel had spent 47 weeks on the bestseller list, faced enormous pressure to produce an equally successful follow-up.",
    options: ["who’s", "whom", "whose", "which"],
    correctAnswer: "C",
    explanation: `'Whose' is possessive — 'whose previous novel' correctly shows the author owns the novel. ✓`,
    explanations: { "A": `'Who’s' means 'who is' — doesn’t fit ('who is previous novel').`, "B": `'Whom' is an object pronoun; here we need a possessive for 'novel.'`, "C": `'Whose' is possessive — 'whose previous novel' correctly shows the author owns the novel. ✓`, "D": `'Which' doesn’t show possession of the novel.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-52",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Neither the coach nor the players _______ satisfied with the team’s performance in the first half, leading to a dramatic change in strategy after halftime.",
    options: ["was", "were", "is", "has been"],
    correctAnswer: "B",
    explanation: `'Players' (plural, nearest to verb) takes 'were.' ✓`,
    explanations: { "A": `With 'neither...nor,' the verb agrees with the nearer subject: 'players' is plural, so 'was' is incorrect.`, "B": `'Players' (plural, nearest to verb) takes 'were.' ✓`, "C": `'Is' is singular present — wrong number and tense.`, "D": `'Has been' is singular, disagreeing with 'players.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-53",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The students who _______ in the summer research program presented their findings at the annual science symposium in September.",
    options: ["participate", "participating", "had participated", "participates"],
    correctAnswer: "C",
    explanation: `'Had participated' (past perfect) correctly shows participation happened before they presented. ✓`,
    explanations: { "A": `Present tense doesn’t match the past-tense 'presented.'`, "B": `'Participating' isn’t a finite verb — creates a fragment.`, "C": `'Had participated' (past perfect) correctly shows participation happened before they presented. ✓`, "D": "Singular and present tense — wrong on both counts." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-nmsqt-rw-54",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The hiking trail, which winds through dense forest for several miles before _______ at a scenic overlook, is one of the most popular routes in the state park.",
    options: ["it terminates", "terminated", "terminating", "having terminated"],
    correctAnswer: "C",
    explanation: `'Terminating' is a gerund matching the structure 'before [verb]-ing' — parallel to the ongoing description. ✓`,
    explanations: { "A": `'It terminates' introduces a new clause, but 'before' needs a parallel gerund to match 'winds.'`, "B": `'Terminated' is past tense, breaking parallel structure with the present-tense narrative.`, "C": `'Terminating' is a gerund matching the structure 'before [verb]-ing' — parallel to the ongoing description. ✓`, "D": `'Having terminated' implies the termination is complete before the winding, which is illogical.` },
    tags: ["diagnostic"],
  }
];
