import type { Question } from "@/types/question";

export const RW_QUESTIONS: Question[] = [
  {
    id: "pt-sat-rw-1",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The playwright’s dialogue was praised for its _______ quality, capturing the rhythms and vocabulary of everyday speech so faithfully that audiences felt they were overhearing real conversations rather than watching a performance.",
    options: ["stilted", "verisimilitude", "verbose", "antiquated"],
    correctAnswer: "B",
    explanation: `'Verisimilitude' means the appearance of being true or real — dialogue that feels like real conversation. ✓`,
    explanations: { "A": `'Stilted' means stiff and unnatural — the opposite of what’s described.`, "B": `'Verisimilitude' means the appearance of being true or real — dialogue that feels like real conversation. ✓`, "C": `'Verbose' means wordy, not necessarily realistic.`, "D": `'Antiquated' means old-fashioned, which contradicts the natural quality.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-2",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Although the initial experiments seemed to _______ the researcher’s hypothesis, she remained cautious, recognizing that a larger sample size and replication by independent laboratories would be needed before she could claim definitive support.",
    options: ["refute", "ignore", "corroborate", "complicate"],
    correctAnswer: "C",
    explanation: `'Corroborate' means to confirm or support — results seemed to support her, but she wanted more evidence. ✓`,
    explanations: { "A": "She wouldn’t remain cautious about claiming support if results refuted her hypothesis.", "B": `Results can’t 'ignore' a hypothesis.`, "C": `'Corroborate' means to confirm or support — results seemed to support her, but she wanted more evidence. ✓`, "D": `Results that complicate wouldn’t 'seem to' support.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-3",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The diplomat’s statement was deliberately _______, using language vague enough to satisfy multiple factions without committing to any specific course of action.",
    options: ["incendiary", "equivocal", "forthright", "prescient"],
    correctAnswer: "B",
    explanation: `'Equivocal' means deliberately ambiguous — matches 'vague enough to satisfy multiple factions.' ✓`,
    explanations: { "A": `'Incendiary' means provocative — contradicts satisfying multiple factions.`, "B": `'Equivocal' means deliberately ambiguous — matches 'vague enough to satisfy multiple factions.' ✓`, "C": `'Forthright' means direct and honest — the opposite of vague.`, "D": `'Prescient' means foreseeing the future, unrelated to vagueness.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-4",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The archaeological site had been _______ by decades of unregulated construction, with bulldozers destroying irreplaceable artifacts that could have revealed details about the region’s earliest inhabitants.",
    options: ["preserved", "excavated", "compromised", "celebrated"],
    correctAnswer: "C",
    explanation: `'Compromised' means damaged or weakened — unregulated construction destroyed the site. ✓`,
    explanations: { "A": "Bulldozers destroying artifacts is the opposite of preservation.", "B": "Excavation implies careful, intentional work — not bulldozers.", "C": `'Compromised' means damaged or weakened — unregulated construction destroyed the site. ✓`, "D": "Destruction isn’t celebration." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-5",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The novelist’s later works displayed a growing _______ with mortality, as characters increasingly confronted questions about legacy, meaning, and the passage of time.",
    options: ["indifference to", "preoccupation with", "confusion about", "hostility toward"],
    correctAnswer: "B",
    explanation: `'Preoccupation' means an absorbing concern — characters increasingly focused on these themes. ✓`,
    explanations: { "A": `A 'growing' engagement with mortality suggests deepening interest, not indifference.`, "B": `'Preoccupation' means an absorbing concern — characters increasingly focused on these themes. ✓`, "C": "The works display focused exploration, not confusion.", "D": "Exploring mortality through characters isn’t hostile." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-6",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the function of the last sentence?",
    passage: "Recent studies have challenged the long-held assumption that the Clovis people were the first humans to inhabit North America. Archaeological evidence from sites in Texas, Oregon, and Chile now suggests human presence at least 2,000 years before the Clovis culture emerged. However, the dating methods used at some of these sites have been questioned by researchers who argue that contamination could make samples appear older than they actually are.",
    options: ["It provides additional evidence supporting pre-Clovis habitation.", "It introduces a methodological concern that qualifies the new evidence.", "It proves that the Clovis-first theory is correct.", "It describes how contamination occurs in archaeological sites."],
    correctAnswer: "B",
    explanation: `'Dating methods questioned' and 'contamination' qualify the preceding evidence by noting potential flaws. ✓`,
    explanations: { "A": "The last sentence raises doubts, not support.", "B": `'Dating methods questioned' and 'contamination' qualify the preceding evidence by noting potential flaws. ✓`, "C": "It doesn’t prove the original theory, just raises questions about the new one.", "D": "It mentions contamination as a concern but doesn’t describe the process." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-7",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Cross-Text Connections",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Based on the texts, how would Zukin most likely characterize Florida’s argument?",
    passage: `<strong>Text 1</strong><br>Sociologist Richard Florida argues that the 'creative class' — artists, designers, tech workers — drives urban economic growth. Cities that attract creative professionals, he claims, experience higher property values, more job creation, and greater innovation.<br><br><strong>Text 2</strong><br>Urban researcher Sharon Zukin counters that Florida’s framework ignores displacement: as creative professionals raise property values, longtime residents and small businesses are priced out. The economic growth Florida celebrates, Zukin argues, primarily benefits newcomers while destroying the very communities that made neighborhoods attractive in the first place.`,
    options: ["As fundamentally wrong about which industries drive economic growth.", "As accurately identifying a pattern but failing to account for its harmful consequences for existing residents.", "As irrelevant to modern urban planning.", "As applicable only to small cities."],
    correctAnswer: "B",
    explanation: "Zukin accepts the growth pattern but shows it displaces residents, a harm Florida overlooks. ✓",
    explanations: { "A": "Zukin doesn’t dispute that creative workers drive growth — she challenges the outcome.", "B": "Zukin accepts the growth pattern but shows it displaces residents, a harm Florida overlooks. ✓", "C": "Zukin engages with it directly, so it’s clearly relevant.", "D": "No city-size limitation is mentioned." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-8",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best states the main idea of the text?",
    passage: "Researchers at Stanford University have developed a thin, flexible material that can cool buildings without electricity. The material works by reflecting sunlight and simultaneously emitting thermal radiation at a specific wavelength that passes directly through the atmosphere into outer space. In tests, surfaces covered with the material remained up to 5°C cooler than the surrounding air, even under direct sunlight — a result that could dramatically reduce air conditioning costs in hot climates.",
    options: ["Stanford researchers have invented a new type of air conditioner.", "A new passive cooling material can reduce building temperatures without energy consumption by reflecting sunlight and radiating heat into space.", "Thermal radiation always travels through the atmosphere into space.", "Air conditioning costs are the largest expense for buildings in hot climates."],
    correctAnswer: "B",
    explanation: "Captures the innovation (passive material), mechanism (reflect + radiate), and benefit (no energy). ✓",
    explanations: { "A": "It’s a material, not an air conditioner; it uses no electricity.", "B": "Captures the innovation (passive material), mechanism (reflect + radiate), and benefit (no energy). ✓", "C": "Only at specific wavelengths, and this isn’t the main idea.", "D": "Cost is mentioned as a benefit but not stated as the largest expense." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-9",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "According to the text, what is the significance of the Yellowstone wolf reintroduction?",
    passage: `The concept of 'rewilding' — reintroducing predators and other keystone species to ecosystems from which they’ve been removed — has gained traction among conservationists. The most cited example is Yellowstone National Park, where the reintroduction of wolves in 1995 triggered cascading ecological effects: elk herds changed their grazing patterns, allowing streamside vegetation to recover, which in turn stabilized riverbanks and increased biodiversity in riparian zones.`,
    options: ["It proved that wolves are the most important predator in all ecosystems.", "It demonstrated that a single species reintroduction can trigger widespread beneficial changes across an ecosystem.", "It showed that elk populations should be eliminated from national parks.", "It was the first time wolves had ever lived in Yellowstone."],
    correctAnswer: "B",
    explanation: "Wolves changed elk behavior, recovering vegetation, stabilizing riverbanks, increasing biodiversity — cascading effects from one reintroduction. ✓",
    explanations: { "A": `'Most important in all ecosystems' overstates the specific example.`, "B": "Wolves changed elk behavior, recovering vegetation, stabilizing riverbanks, increasing biodiversity — cascading effects from one reintroduction. ✓", "C": "Elk changed behavior; they weren’t eliminated.", "D": "They were reintroduced, implying they had lived there before." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-10",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding, if true, would most directly support Eagleman’s claim?",
    passage: "Neuroscientist David Eagleman argues that human perception of time is not fixed but varies systematically with emotional state and attention. He proposes that the brain’s internal clock speeds up during moments of fear or novelty, creating denser memories that are later interpreted as longer durations.",
    options: ["People who meditate report feeling calmer during stressful events.", "Participants in a study consistently estimated that a 30-second interval during a frightening experience lasted over a minute, while identical intervals during routine activities were estimated accurately.", "Brain scans show increased activity in the visual cortex during sleep.", "Older adults report that years seem to pass more quickly than in childhood."],
    correctAnswer: "B",
    explanation: "Overestimating time during fear (vs accurate during routine) directly supports the claim that emotional state alters time perception. ✓",
    explanations: { "A": "Feeling calmer is about emotional state, not time perception.", "B": "Overestimating time during fear (vs accurate during routine) directly supports the claim that emotional state alters time perception. ✓", "C": "Visual cortex during sleep is unrelated to time perception.", "D": "While relevant to time perception, this addresses aging, not the fear/novelty mechanism Eagleman describes." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-11",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly weaken Morrison’s argument?",
    passage: `Literary scholar Toni Morrison argued that canonical American literature is shaped by an unacknowledged 'Africanist presence' — that Black characters and racial dynamics, even when seemingly peripheral, are central to the meaning of works by white authors. She contended that understanding this dynamic is essential to a full reading of American fiction.`,
    options: ["A comprehensive analysis of 200 canonical American novels found that fewer than 5% contain any Black characters or references to race, and their themes operate independently of racial dynamics.", "Morrison’s own novels have won numerous literary awards.", "Some American novels address class inequality rather than race.", "Several white authors have acknowledged being influenced by Black literary traditions."],
    correctAnswer: "A",
    explanation: "If most canonical works lack racial content and function without it, the claim that an Africanist presence shapes the canon is weakened. ✓",
    explanations: { "A": "If most canonical works lack racial content and function without it, the claim that an Africanist presence shapes the canon is weakened. ✓", "B": "Morrison’s own success doesn’t address her argument about other authors.", "C": "Addressing class doesn’t disprove the presence of racial dynamics.", "D": "This actually supports, not weakens, the connection." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-12",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to support the claim that green space benefits are not equally distributed across income levels?",
    passage: "Researchers studied the relationship between green space access and mental health outcomes across neighborhoods of varying income levels.",
    options: ["High-income neighborhoods have an average of 12.4 acres of green space per 1,000 residents.", "Low-income neighborhoods have 2.1 acres of green space per 1,000 residents compared to 12.4 acres in high-income neighborhoods, and report depression rates three times higher, suggesting that unequal access to green space may contribute to mental health disparities.", "All three income levels showed some correlation between green space and mental health.", "Middle-income neighborhoods had 6.8 acres of green space per 1,000 residents."],
    correctAnswer: "B",
    explanation: "Compares both green space (2.1 vs 12.4) and health outcomes (3x depression) across income levels. ✓",
    explanations: { "A": "Single data point, no comparison.", "B": "Compares both green space (2.1 vs 12.4) and health outcomes (3x depression) across income levels. ✓", "C": "Too vague; doesn’t address unequal distribution.", "D": "Single data point." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-13",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to describe the impact of advising type on graduation rates?",
    passage: "A university tracked graduation rates by the type of advising students received during their first year.",
    options: ["Students who received proactive advising had a 6-year graduation rate of 82%.", "Students with proactive advising graduated at a rate of 82%, compared to 71% for on-demand advising and 58% for no advising, suggesting that structured early intervention improves long-term completion.", "No-advising students had the lowest graduation rate.", "The university offers three types of advising services."],
    correctAnswer: "B",
    explanation: "All three groups compared, with clear pattern showing advising impact. ✓",
    explanations: { "A": "Single point, no comparison.", "B": "All three groups compared, with clear pattern showing advising impact. ✓", "C": "True but doesn’t quantify the differences.", "D": "Describes offerings, not outcomes." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-14",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "Economists studying the gig economy have found that while platform workers (rideshare drivers, freelance designers, delivery couriers) report higher satisfaction with scheduling flexibility than traditional employees, they also report significantly higher rates of financial anxiety, with 68% unable to cover an unexpected $400 expense. ________",
    options: ["This suggests that gig work has eliminated financial insecurity for most workers.", "The findings indicate that the autonomy benefits of gig work may come at the cost of financial stability, creating a trade-off that workers navigate without institutional safety nets.", "Therefore, all workers should transition to gig employment immediately.", "This proves that traditional employment offers no advantages over gig work."],
    correctAnswer: "B",
    explanation: "Higher satisfaction but higher financial anxiety = autonomy vs. stability trade-off. ✓",
    explanations: { "A": "68% unable to cover $400 is the opposite of eliminating insecurity.", "B": "Higher satisfaction but higher financial anxiety = autonomy vs. stability trade-off. ✓", "C": "The data shows significant downsides to gig work.", "D": "Traditional workers reported less financial anxiety." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-15",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The Viking settlement at L’Anse aux Meadows in Newfoundland, discovered in 1960, provided the first definitive evidence that Norse explorers reached North America around 1000 CE. _______, the site raised as many questions as it answered, since no other confirmed Viking settlements have been found on the continent despite extensive archaeological searches.",
    options: ["As a result", "Paradoxically", "Similarly", "In other words"],
    correctAnswer: "B",
    explanation: "Definitive evidence that also raises more questions is paradoxical. ✓",
    explanations: { "A": "The questions aren’t a result of the confirmation — they’re an unexpected addition.", "B": "Definitive evidence that also raises more questions is paradoxical. ✓", "C": "The second idea contrasts, not parallels.", "D": "The questions aren’t a restatement." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-16",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Ocean acidification threatens marine organisms that build calcium carbonate shells, including oysters, clams, and certain plankton species. As pH levels drop, these organisms expend more energy maintaining their shells and less on growth and reproduction. _______, species that don’t rely on calcium carbonate, such as jellyfish, may actually thrive in more acidic conditions, potentially restructuring entire marine food webs.",
    options: ["Furthermore", "Conversely", "Therefore", "Similarly"],
    correctAnswer: "B",
    explanation: "Shell-builders struggle while non-shell species thrive — a clear contrast. ✓",
    explanations: { "A": "The jellyfish point contrasts with shell-builders, not extends it.", "B": "Shell-builders struggle while non-shell species thrive — a clear contrast. ✓", "C": "Jellyfish thriving isn’t a consequence of shell-builders struggling.", "D": "Thriving is opposite to struggling, not similar." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-17",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Architect Zaha Hadid’s designs were initially dismissed by critics as unbuildable fantasies. Her sweeping curves and fluid forms seemed to defy engineering constraints. _______, advances in computational design and construction technology gradually caught up to her vision, and her buildings — once theoretical — became celebrated landmarks worldwide.",
    options: ["In addition", "Nevertheless", "For instance", "Over time"],
    correctAnswer: "D",
    explanation: `'Over time' signals the gradual shift from 'unbuildable' to 'celebrated landmarks.' ✓`,
    explanations: { "A": `'In addition' adds; the shift is temporal.`, "B": `'Nevertheless' implies defiance, but the change is gradual progress.`, "C": "The buildings aren’t an example of dismissal.", "D": `'Over time' signals the gradual shift from 'unbuildable' to 'celebrated landmarks.' ✓` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-18",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about microplastics in the food chain and wants to convey the scale of the problem.",
    options: ["Microplastics are defined as plastic fragments smaller than 5 millimeters.", "Scientists first began studying microplastics in the early 2000s.", "A recent study found that the average person ingests approximately 5 grams of microplastic per week — roughly the weight of a credit card — through contaminated water, seafood, and even table salt.", "Several countries have banned microbeads in cosmetic products."],
    correctAnswer: "C",
    explanation: "5 grams weekly, credit card comparison, multiple sources — makes the scale tangible and alarming. ✓",
    explanations: { "A": "Definition doesn’t convey scale.", "B": "History of study doesn’t convey current scale.", "C": "5 grams weekly, credit card comparison, multiple sources — makes the scale tangible and alarming. ✓", "D": "Policy response, not scale of the problem." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-19",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the James Webb Space Telescope and wants to emphasize its improvement over previous technology.",
    options: ["The James Webb Space Telescope was launched on December 25, 2021.", "The telescope orbits the Sun at a point called L2, about 1.5 million kilometers from Earth.", "With a primary mirror 6.5 meters wide — nearly three times the diameter of Hubble’s — and infrared sensors 100 times more sensitive, the James Webb Space Telescope can detect light from galaxies that formed just 200 million years after the Big Bang, far beyond Hubble’s reach.", "NASA, ESA, and CSA collaborated on the telescope’s development."],
    correctAnswer: "C",
    explanation: "Direct comparisons to Hubble (3x mirror, 100x sensitivity) plus new capability (200M years after Big Bang). ✓",
    explanations: { "A": "Launch date, not improvement.", "B": "Orbit location, not capability comparison.", "C": "Direct comparisons to Hubble (3x mirror, 100x sensitivity) plus new capability (200M years after Big Bang). ✓", "D": "Collaboration, not improvement." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-20",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the decline of local journalism and wants to highlight real-world consequences.",
    options: ["About 2,500 newspapers have closed in the U.S. since 2005.", "Local news is primarily funded through advertising revenue.", "Communities that lost their local newspaper experienced a 5–11% increase in municipal borrowing costs and a measurable rise in political corruption, suggesting that local journalism serves as a critical accountability mechanism whose absence has tangible civic consequences.", "Some former journalists have transitioned to careers in public relations."],
    correctAnswer: "C",
    explanation: "Borrowing costs + corruption + accountability framing = real-world consequences. ✓",
    explanations: { "A": "Scale of closures, but not consequences.", "B": "Funding model, not consequences.", "C": "Borrowing costs + corruption + accountability framing = real-world consequences. ✓", "D": "Career transitions, not civic impact." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-21",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The biochemist’s research focused on three key _______ protein folding mechanisms, enzyme catalysis, and cell membrane permeability.",
    options: ["areas,", "areas:", "areas;", "areas"],
    correctAnswer: "B",
    explanation: "A colon correctly introduces the list of three areas. ✓",
    explanations: { "A": "A comma doesn’t properly introduce an enumerated list.", "B": "A colon correctly introduces the list of three areas. ✓", "C": "A semicolon doesn’t introduce lists.", "D": "No punctuation creates a run-on." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-22",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The restoration of the 17th-century painting, which had taken conservators nearly three _______ revealed previously hidden details in the background landscape.",
    options: ["years", "years;", "years,", "years."],
    correctAnswer: "C",
    explanation: `Comma closes the nonrestrictive clause 'which had taken...years' before the main verb 'revealed.' ✓`,
    explanations: { "A": "No punctuation to close the nonrestrictive clause.", "B": "Semicolon can’t close a relative clause.", "C": `Comma closes the nonrestrictive clause 'which had taken...years' before the main verb 'revealed.' ✓`, "D": "Period creates a fragment." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-23",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The conductor raised her baton and the orchestra fell _______ not a single musician moved until the downbeat signaled the opening chord.",
    options: ["silent", "silent,", "silent;", "silent."],
    correctAnswer: "C",
    explanation: "Semicolon correctly joins two related independent clauses. ✓",
    explanations: { "A": "Run-on sentence.", "B": "Comma splice between two independent clauses.", "C": "Semicolon correctly joins two related independent clauses. ✓", "D": "Could work but fragments the closely connected ideas." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-24",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The collection of rare manuscripts, along with several first-edition _______ currently on loan to the university library for a special exhibition.",
    options: ["novels, are", "novels, is", "novels are", "novels is"],
    correctAnswer: "B",
    explanation: `'Collection' is singular; 'along with' is parenthetical. Comma closes it; 'is' agrees. ✓`,
    explanations: { "A": `Subject is 'collection' (singular); 'are' is plural.`, "B": `'Collection' is singular; 'along with' is parenthetical. Comma closes it; 'is' agrees. ✓`, "C": "Missing comma to close the parenthetical.", "D": "Missing comma; confusing structure." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-25",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "By the time the delegation _______ the agreement, negotiators from both countries had spent over fourteen months working through the details.",
    options: ["will sign", "signs", "signed", "had signed"],
    correctAnswer: "C",
    explanation: `Simple past 'signed' works with 'had spent' (past perfect) — spending happened before signing. ✓`,
    explanations: { "A": "Future tense contradicts past context.", "B": "Present tense doesn’t match past narrative.", "C": `Simple past 'signed' works with 'had spent' (past perfect) — spending happened before signing. ✓`, "D": "Both in past perfect is incorrect; one must be simple past." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-26",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The historian _______ groundbreaking research on medieval trade routes has been cited in over 300 academic publications devoted the final chapter to unanswered questions.",
    options: ["who’s", "whom", "whose", "which"],
    correctAnswer: "C",
    explanation: `'Whose' shows possession of the research. ✓`,
    explanations: { "A": `'Who’s' = 'who is' — doesn’t fit before 'research.'`, "B": `'Whom' is an object pronoun, not possessive.`, "C": `'Whose' shows possession of the research. ✓`, "D": `'Which' can’t modify a person.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-27",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The pharmaceutical company announced that the clinical trial, _______ had enrolled over 5,000 participants across twelve countries, would release preliminary results by the end of the quarter.",
    options: ["that", "which", "who", "whom"],
    correctAnswer: "B",
    explanation: `'Which' introduces nonrestrictive clauses set off by commas. ✓`,
    explanations: { "A": `'That' introduces restrictive clauses; the comma before it indicates nonrestrictive.`, "B": `'Which' introduces nonrestrictive clauses set off by commas. ✓`, "C": `'Who' refers to people, not a trial.`, "D": `'Whom' refers to people.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-28",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The philosopher’s argument was _______ in its logic yet unsettling in its implications, leaving readers simultaneously convinced by the reasoning and disturbed by where it led.",
    options: ["flawed", "impeccable", "irrelevant", "pedestrian"],
    correctAnswer: "B",
    explanation: `'Impeccable' means faultless — the logic convinced readers even as the implications disturbed them. ✓`,
    explanations: { "A": `Readers were 'convinced,' so the logic wasn’t flawed.`, "B": `'Impeccable' means faultless — the logic convinced readers even as the implications disturbed them. ✓`, "C": "Irrelevant logic wouldn’t convince anyone.", "D": `'Pedestrian' means dull, contradicting the unsettling impact.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-29",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The architect’s proposal was met with _______ from the preservation society, whose members viewed the modern glass addition to the historic courthouse as an aesthetic affront that would irreparably alter the building’s character.",
    options: ["approbation", "ambivalence", "opprobrium", "elation"],
    correctAnswer: "C",
    explanation: `'Opprobrium' means harsh criticism or disapproval — matches 'affront' and 'irreparably alter.' ✓`,
    explanations: { "A": `'Approbation' means approval, which contradicts 'aesthetic affront.'`, "B": `'Ambivalence' means mixed feelings, but their reaction is clearly negative.`, "C": `'Opprobrium' means harsh criticism or disapproval — matches 'affront' and 'irreparably alter.' ✓`, "D": `'Elation' means joy, the opposite of their reaction.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-30",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Rather than seeking to _______ the existing theory, the researchers positioned their findings as a refinement — an important correction that strengthened the framework’s overall explanatory power while addressing a specific weakness.",
    options: ["supplant", "validate", "ignore", "plagiarize"],
    correctAnswer: "A",
    explanation: `'Supplant' means to replace entirely. They sought refinement, not replacement. ✓ (The sentence says 'rather than seeking to supplant')`,
    explanations: { "A": `'Supplant' means to replace entirely. They sought refinement, not replacement. ✓ (The sentence says 'rather than seeking to supplant')`, "B": "They did partially validate by strengthening the framework, so this doesn’t work as the thing they avoided.", "C": "They engaged with the theory, not ignored it.", "D": `'Plagiarize' means to copy, irrelevant here.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-31",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The CEO’s public apology was criticized as _______, with analysts noting that it acknowledged no specific wrongdoing and committed to no concrete changes — performative contrition designed to manage public relations rather than address genuine accountability.",
    options: ["heartfelt", "perfunctory", "unprecedented", "provocative"],
    correctAnswer: "B",
    explanation: `'Perfunctory' means carried out with minimal effort or reflection — no specifics, no commitments. ✓`,
    explanations: { "A": `'Heartfelt' contradicts 'performative contrition.'`, "B": `'Perfunctory' means carried out with minimal effort or reflection — no specifics, no commitments. ✓`, "C": `'Unprecedented' means never done before, not relevant.`, "D": `'Provocative' means stimulating reaction, not matching the hollow quality described.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-32",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The documentary filmmaker’s approach was deliberately _______, eschewing narration and expert commentary in favor of long, unedited sequences that allowed subjects to reveal their own stories at their own pace.",
    options: ["polemical", "observational", "sensationalist", "didactic"],
    correctAnswer: "B",
    explanation: `'Observational' means watching without interfering — no narration, unedited, subjects tell own stories. ✓`,
    explanations: { "A": `'Polemical' means aggressively argumentative — contradicts the hands-off approach.`, "B": `'Observational' means watching without interfering — no narration, unedited, subjects tell own stories. ✓`, "C": `'Sensationalist' means seeking shocking reactions, opposite of patient observation.`, "D": `'Didactic' means instructive/preachy — no expert commentary rules this out.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-33",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the overall structure of the text?",
    passage: "Historians have long debated whether the Scientific Revolution of the 16th and 17th centuries represented a genuine rupture with medieval thought or a gradual evolution from it. Proponents of the discontinuity thesis point to radical new methodologies — controlled experimentation, mathematical modeling — that had no clear medieval precedent. Their opponents, however, note that many supposedly revolutionary figures, including Newton himself, were deeply engaged with alchemical and theological traditions that stretched back centuries.",
    options: ["It presents one side of a debate and argues for that position.", "It introduces a historiographical debate and presents evidence supporting both sides.", "It chronologically traces the development of the Scientific Revolution.", "It refutes the idea that the Scientific Revolution was significant."],
    correctAnswer: "B",
    explanation: "The debate is introduced, then discontinuity thesis evidence, then continuity thesis evidence. ✓",
    explanations: { "A": "Both sides are presented, neither is favored.", "B": "The debate is introduced, then discontinuity thesis evidence, then continuity thesis evidence. ✓", "C": "No chronological narrative is provided.", "D": "Significance isn’t questioned." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-34",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly support Boroditsky’s broader claim?",
    passage: `Cognitive scientist Lera Boroditsky argues that the language a person speaks fundamentally shapes how they perceive reality. In one experiment, she found that speakers of Kuuk Thaayorre, an Aboriginal Australian language that uses cardinal directions instead of relative terms like 'left' and 'right,' maintained an extraordinary sense of orientation even in unfamiliar environments.`,
    options: ["Children learn language faster when exposed to it from birth.", "Russian speakers, whose language has separate words for light blue and dark blue, were faster at distinguishing between these shades than English speakers, who use a single word for both.", "Bilingual individuals earn higher salaries on average.", "Some languages have more words for snow than others."],
    correctAnswer: "B",
    explanation: "Different words for blue → faster discrimination. Language shaping perception in a different domain. ✓",
    explanations: { "A": "Language acquisition speed doesn’t show perception differences.", "B": "Different words for blue → faster discrimination. Language shaping perception in a different domain. ✓", "C": "Economic outcomes, not perception.", "D": "Having more words doesn’t prove perception differs." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-35",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly weaken Chetty’s claim?",
    passage: "Economist Raj Chetty has argued that neighborhood environments during childhood have lasting effects on economic outcomes. His research tracked millions of children who moved to different neighborhoods and found that each additional year a child spent in a higher-opportunity neighborhood before age 23 increased their adult earnings.",
    options: ["A study found that children who moved to higher-opportunity neighborhoods showed no difference in adult earnings compared to siblings who remained in lower-opportunity areas, after controlling for family-level characteristics.", "Some high-income families live in lower-opportunity neighborhoods by choice.", "Chetty’s study used a very large dataset.", "Schools in higher-opportunity neighborhoods receive more funding."],
    correctAnswer: "A",
    explanation: "Same family, different neighborhoods, no difference — suggests family factors, not neighborhood, drive outcomes. ✓",
    explanations: { "A": "Same family, different neighborhoods, no difference — suggests family factors, not neighborhood, drive outcomes. ✓", "B": "Doesn’t address the causal claim about children.", "C": "Large datasets strengthen, not weaken, findings.", "D": "Funding differences might explain the mechanism but don’t weaken the claim." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-36",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to argue for dietary shifts as a climate strategy?",
    passage: "Researchers compared the carbon footprints of different protein sources per gram of protein produced.",
    options: ["Beef produces 50 kg CO₂ per 100g of protein.", "Replacing beef with legumes as a primary protein source could reduce protein-related carbon emissions by approximately 98%, from 50 kg to 0.8 kg CO₂ per 100g of protein, making dietary change one of the most impactful individual climate actions.", "Chicken produces less carbon than beef.", "Tofu is made from soybeans."],
    correctAnswer: "B",
    explanation: "Quantifies the specific reduction (50 to 0.8, ~98%) and frames it as actionable climate strategy. ✓",
    explanations: { "A": "Single data point.", "B": "Quantifies the specific reduction (50 to 0.8, ~98%) and frames it as actionable climate strategy. ✓", "C": "True but limited comparison.", "D": "Production info, not carbon data." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-37",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "In experiments on decision fatigue, researchers found that judges were significantly more likely to grant parole early in the morning and immediately after food breaks, with approval rates dropping steadily throughout each session. The pattern persisted regardless of crime severity, sentence length, or the prisoner’s demographic characteristics. ________",
    options: ["This suggests that judicial decisions may be influenced less by case merits than by the cognitive state of the decision-maker, raising questions about the consistency and fairness of the justice system.", "Therefore, all prisoners should be scheduled for morning hearings.", "The researchers concluded that judges are inherently biased against certain groups.", "This proves that the parole system should be entirely automated."],
    correctAnswer: "A",
    explanation: "Pattern independent of case factors, dependent on time/meals → cognitive state matters more than merits. ✓",
    explanations: { "A": "Pattern independent of case factors, dependent on time/meals → cognitive state matters more than merits. ✓", "B": "Practical suggestion but doesn’t address the systemic problem.", "C": "The pattern was independent of demographics — not about group bias.", "D": `'Proves' is too strong, and automation isn’t mentioned.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-38",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: `Mycologist Paul Stamets has documented that certain fungal networks in forest soils — sometimes called the 'wood wide web' — facilitate the transfer of nutrients between trees of different species. Mature Douglas firs, for example, have been shown to send carbon to struggling seedlings through shared mycorrhizal networks, even when the seedlings are of a completely different species. ________`,
    options: ["This interspecies resource sharing challenges the traditional ecological view of forests as collections of competing individuals, suggesting instead that cooperation is a fundamental feature of forest ecosystems.", "Douglas firs are the tallest trees in North America.", "Fungi are neither plants nor animals.", "This means forests don’t need any management or conservation efforts."],
    correctAnswer: "A",
    explanation: "Cross-species nutrient sharing contradicts pure competition models, suggesting cooperation. ✓",
    explanations: { "A": "Cross-species nutrient sharing contradicts pure competition models, suggesting cooperation. ✓", "B": "Height fact is irrelevant to the cooperation finding.", "C": "Taxonomy fact, not a logical conclusion.", "D": "Cooperation doesn’t eliminate the need for conservation." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-39",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The discovery of high-temperature superconductors in 1986 promised a revolution in energy transmission, potentially eliminating the 6% of electricity lost to resistance in conventional power lines. _______, nearly four decades later, practical high-temperature superconductors still require cooling to at least −135°C, making widespread deployment prohibitively expensive.",
    options: ["As expected", "Yet", "Similarly", "Therefore"],
    correctAnswer: "B",
    explanation: "Promise of revolution vs. still impractical — a contrast. ✓",
    explanations: { "A": "The gap between promise and reality is unexpected.", "B": "Promise of revolution vs. still impractical — a contrast. ✓", "C": "No parallel situation.", "D": "Impracticality isn’t a logical result of the promise." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-40",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The archaeological evidence suggests that ancient Polynesian navigators could cross thousands of miles of open ocean using only the stars, wave patterns, and migratory bird routes as guides. _______, modern experimental voyages using traditional navigation techniques have successfully replicated these journeys, with the Polynesian Voyaging Society’s Hōkūle’a completing a 40,000-mile circumnavigation without instruments.",
    options: ["Casting doubt on this", "Corroborating this", "Contradicting this", "Regardless of this"],
    correctAnswer: "B",
    explanation: "Successful modern replications confirm the ancient capability. ✓",
    explanations: { "A": "Modern voyages support the claim, not doubt it.", "B": "Successful modern replications confirm the ancient capability. ✓", "C": "The voyages align with, not contradict, the evidence.", "D": "The voyages are directly related to the claim." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-41",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Critics of standardized testing argue that test scores primarily reflect socioeconomic background rather than academic ability, pointing to the strong correlation between family income and SAT scores. _______, defenders note that the correlation doesn’t establish causation and that tests remain the single best predictor of first-year college GPA across demographic groups.",
    options: ["In support of this", "In response", "As a result", "For example"],
    correctAnswer: "B",
    explanation: "Defenders respond to the criticism with counterarguments. ✓",
    explanations: { "A": "Defenders oppose, not support, the critics.", "B": "Defenders respond to the criticism with counterarguments. ✓", "C": "The defense isn’t a result of the criticism in a causal sense.", "D": "The defense isn’t an example of the criticism." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-42",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about CRISPR gene editing and wants to address both its promise and its ethical concerns.",
    options: ["CRISPR was adapted from a bacterial immune defense system.", "While CRISPR has enabled breakthroughs like correcting sickle cell disease mutations in clinical trials, the technology’s ability to edit human embryos raises profound ethical questions about consent, equity of access, and the potential for heritable changes that would affect all future generations.", "Jennifer Doudna and Emmanuelle Charpentier won the 2020 Nobel Prize for CRISPR.", "Gene editing can be performed in laboratories."],
    correctAnswer: "B",
    explanation: "Promise (sickle cell correction) and ethics (embryos, consent, equity, heritable changes) in one sentence. ✓",
    explanations: { "A": "Origin story, neither promise nor ethics.", "B": "Promise (sickle cell correction) and ethics (embryos, consent, equity, heritable changes) in one sentence. ✓", "C": "Nobel Prize doesn’t address both dimensions.", "D": "Lab capability is too generic." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-43",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about algorithmic bias in hiring and wants to explain how it occurs.",
    options: ["Many companies now use AI to screen job applications.", "When hiring algorithms are trained on historical data that reflects past discrimination — such as datasets where men were disproportionately promoted — they learn to replicate those patterns, systematically disadvantaging qualified female and minority candidates without any explicit discriminatory programming.", "AI technology has advanced rapidly in the past decade.", "Some job seekers have complained about automated screening processes."],
    correctAnswer: "B",
    explanation: "Mechanism: historical data → learned patterns → systematic disadvantage, without explicit code. ✓",
    explanations: { "A": "States the practice but doesn’t explain bias.", "B": "Mechanism: historical data → learned patterns → systematic disadvantage, without explicit code. ✓", "C": "Advancement speed doesn’t explain bias.", "D": "Complaints, not mechanism." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-44",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about urban heat islands and wants to present a data-driven argument for green roofs.",
    options: ["Green roofs are roofs partially or completely covered with vegetation.", "Many cities experience temperatures 5–10°F higher than surrounding rural areas.", "Studies show that buildings with green roofs use 25% less energy for cooling, reduce local surface temperatures by up to 40°F compared to conventional roofs, and can retain 70% of rainfall — making them a cost-effective, multi-benefit strategy for combating urban heat.", "Some cities offer tax incentives for green building practices."],
    correctAnswer: "C",
    explanation: "Three quantified benefits (25% energy, 40°F cooler, 70% rainfall) + framing as cost-effective strategy. ✓",
    explanations: { "A": "Definition, not data-driven argument.", "B": "Problem without solution.", "C": "Three quantified benefits (25% energy, 40°F cooler, 70% rainfall) + framing as cost-effective strategy. ✓", "D": "Incentives, not data about effectiveness." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-45",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The neurosurgeon’s memoir, which spent fourteen weeks on the bestseller _______ offered a rare and intimate look at the emotional toll of making life-and-death decisions daily.",
    options: ["list", "list;", "list,", "list—"],
    correctAnswer: "C",
    explanation: `Comma closes 'which spent...list' before the main verb 'offered.' ✓`,
    explanations: { "A": "No punctuation to close the nonrestrictive clause.", "B": "Semicolon can’t close a relative clause.", "C": `Comma closes 'which spent...list' before the main verb 'offered.' ✓`, "D": "Dash is less standard for closing relative clauses." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-46",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The expedition team discovered the wreck at a depth of 3,800 _______ they immediately notified maritime authorities and began documenting the site with remotely operated vehicles.",
    options: ["meters,", "meters;", "meters", "meters and"],
    correctAnswer: "B",
    explanation: "Semicolon correctly joins two related independent clauses. ✓",
    explanations: { "A": "Comma splice between independent clauses.", "B": "Semicolon correctly joins two related independent clauses. ✓", "C": "Run-on.", "D": `'And' would need a comma before it.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-47",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Although the satellite data initially appeared to confirm the _______ closer analysis revealed a systematic calibration error that had inflated temperature readings by 0.3 degrees across the entire dataset.",
    options: ["hypothesis;", "hypothesis", "hypothesis,", "hypothesis—"],
    correctAnswer: "C",
    explanation: `Comma separates the 'Although' clause from the main clause. ✓`,
    explanations: { "A": "Semicolon can’t follow a subordinate clause.", "B": "No punctuation between clauses.", "C": `Comma separates the 'Although' clause from the main clause. ✓`, "D": "Dash disrupts the subordinate-to-main flow." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-48",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Neither the established theory nor the competing _______ adequately account for the anomalous data points observed in the most recent experiment.",
    options: ["hypothesis", "hypotheses", "hypothesis’s", "hypothesizing"],
    correctAnswer: "B",
    explanation: `'Hypotheses' (plural) nearest to verb; 'account' agrees with plural. ✓`,
    explanations: { "A": `Singular 'hypothesis' with 'neither...nor' takes verb agreeing with nearer noun; but 'account' (plural) requires plural nearest subject.`, "B": `'Hypotheses' (plural) nearest to verb; 'account' agrees with plural. ✓`, "C": "Possessive form doesn’t fit grammatically.", "D": "Gerund doesn’t fit as the second subject." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-49",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The committee’s decision _______ to fund the infrastructure project was influenced by a recent study showing that the bridge’s structural integrity had deteriorated significantly.",
    options: ["not", "—not", "not—", "—not—"],
    correctAnswer: "A",
    explanation: `'Decision not to fund' is the straightforward negative infinitive. ✓`,
    explanations: { "A": `'Decision not to fund' is the straightforward negative infinitive. ✓`, "B": `A dash before 'not' disrupts the phrase unnecessarily.`, "C": "Dash after creates an incomplete parenthetical.", "D": `Dashes around 'not' implies it’s an aside, but it’s essential to meaning.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-50",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Having completed the longitudinal study that _______ more than a decade of data collection, the research team published their findings in a leading journal.",
    options: ["requiring", "required", "has required", "would require"],
    correctAnswer: "B",
    explanation: `Simple past 'required' correctly describes the completed study. ✓`,
    explanations: { "A": `'Requiring' creates a dangling modifier.`, "B": `Simple past 'required' correctly describes the completed study. ✓`, "C": `'Has required' implies ongoing; the study is completed.`, "D": `'Would require' is conditional, not factual.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-51",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The violinist, _______ performance at Carnegie Hall had received a standing ovation, was invited to join the orchestra as its youngest-ever principal player.",
    options: ["who’s", "whose", "whom", "that"],
    correctAnswer: "B",
    explanation: `'Whose' possesses 'performance.' ✓`,
    explanations: { "A": `'Who’s' = 'who is,' not possessive.`, "B": `'Whose' possesses 'performance.' ✓`, "C": `'Whom' is an object pronoun.`, "D": `'That' doesn’t show possession.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-52",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Each of the five proposed amendments to the charter _______ been reviewed by the legal team and approved by a majority of board members before being submitted for a public vote.",
    options: ["have", "has", "are", "were"],
    correctAnswer: "B",
    explanation: `'Each' takes singular verb 'has.' ✓`,
    explanations: { "A": `'Each' is singular regardless of the prepositional phrase.`, "B": `'Each' takes singular verb 'has.' ✓`, "C": `'Are' is present and plural.`, "D": `'Were' is plural past.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-53",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The software engineers, frustrated by the persistent bug that _______ eluded their debugging efforts for weeks, decided to rebuild the module from scratch.",
    options: ["have", "has", "had", "having"],
    correctAnswer: "C",
    explanation: `'Had eluded' is past perfect, showing the bug evaded them before they decided to rebuild. ✓`,
    explanations: { "A": `'Have' is present; the narrative is past tense.`, "B": `'Has' is singular present.`, "C": `'Had eluded' is past perfect, showing the bug evaded them before they decided to rebuild. ✓`, "D": `'Having' without a helper verb is incomplete.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-rw-54",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The documentary explores the lives of three families in _______ daily routines reveal the hidden costs of living in a food desert.",
    options: ["which", "whom", "whose", "that"],
    correctAnswer: "C",
    explanation: `'Whose daily routines' shows the families possess the routines. ✓`,
    explanations: { "A": `'Which' doesn’t show possession of 'routines.'`, "B": `'Whom' is an object pronoun.`, "C": `'Whose daily routines' shows the families possess the routines. ✓`, "D": `'That' doesn’t show possession.` },
    tags: ["practice-test"],
  }
];

export const MATH_QUESTIONS: Question[] = [
  {
    id: "pt-sat-math-1",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If 7x − 4 = 3x + 16, what is the value of x?",
    options: ["3", "4", "5", "6"],
    correctAnswer: "C",
    explanation: "Subtract 3x: 4x−4=16. Add 4: 4x=20. x=5. Check: 7(5)−4=31, 3(5)+16=31. ✓",
    explanations: { "A": "7(3)−4=17, 3(3)+16=25. Not equal.", "B": "7(4)−4=24, 3(4)+16=28. Not equal.", "C": "Subtract 3x: 4x−4=16. Add 4: 4x=20. x=5. Check: 7(5)−4=31, 3(5)+16=31. ✓", "D": "7(6)−4=38, 3(6)+16=34. Not equal." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-2",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which function f(m) represents the total charge for m miles?",
    passage: "A delivery service charges a $6 base fee plus $2.50 per mile.",
    options: ["f(m)=6m+2.50", "f(m)=2.50m+6", "f(m)=8.50m", "f(m)=2.50m−6"],
    correctAnswer: "B",
    explanation: "$2.50/mile + $6 base. ✓",
    explanations: { "A": "Multiplies base fee by miles.", "B": "$2.50/mile + $6 base. ✓", "C": "Adds rates instead of separating fixed and variable.", "D": "Subtracts the base fee." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-3",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Systems of equations",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the value of y?",
    passage: `2x+3y=19
4x−y=3`,
    options: ["", "", "", ""],
    correctAnswer: "5",
    explanation: "From eq2: y=4x−3. Substitute: 2x+3(4x−3)=19→14x−9=19→14x=28→x=2. y=4(2)−3=5.",
    explanations: { "correct": "From eq2: y=4x−3. Substitute: 2x+3(4x−3)=19→14x−9=19→14x=28→x=2. y=4(2)−3=5." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-4",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear inequalities",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the minimum score she needs on the 7th quiz?",
    passage: "A student needs at least 560 points total across 7 quizzes to earn an A. After 6 quizzes, she has 475 points.",
    options: ["75", "80", "85", "90"],
    correctAnswer: "C",
    explanation: "560−475=85 minimum. ✓",
    explanations: { "A": "475+75=550<560.", "B": "475+80=555<560.", "C": "560−475=85 minimum. ✓", "D": "Higher than needed." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-5",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Equivalent expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression is equivalent to 5(2x−3)−3(x+4)?",
    options: ["7x−27", "7x−19", "7x−7", "13x−27"],
    correctAnswer: "A",
    explanation: "10x−15−3x−12=7x−27. ✓",
    explanations: { "A": "10x−15−3x−12=7x−27. ✓", "B": "Didn’t distribute −3 to +4 correctly.", "C": "Only subtracted one constant.", "D": "Added coefficients: 10+3=13." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-6",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Absolute value",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If |2x−5|=9, what is the sum of all possible values of x?",
    options: ["5", "7", "2", "14"],
    correctAnswer: "A",
    explanation: "Case 1: 2x−5=9→x=7. Case 2: 2x−5=−9→x=−2. Sum=7+(−2)=5. ✓",
    explanations: { "A": "Case 1: 2x−5=9→x=7. Case 2: 2x−5=−9→x=−2. Sum=7+(−2)=5. ✓", "B": "Only one solution.", "C": "Difference of solutions.", "D": "Sum using wrong values." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-7",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Function notation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is f(−1)?",
    passage: "f(x)=3x²−2x+1",
    options: ["2", "4", "6", "0"],
    correctAnswer: "C",
    explanation: "f(−1)=3(1)−(−2)+1=3+2+1=6. ✓",
    explanations: { "A": "Sign error.", "B": "Partial calculation.", "C": "f(−1)=3(1)−(−2)+1=3+2+1=6. ✓", "D": "Multiple errors." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-8",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Quadratic factoring",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which are the solutions of x²+2x−15=0?",
    options: ["x=3, x=−5", "x=−3, x=5", "x=3, x=5", "x=−3, x=−5"],
    correctAnswer: "A",
    explanation: "Factor: (x+5)(x−3)=0. x=−5 or x=3. Check: 9+6−15=0✓, 25−10−15=0✓. ✓",
    explanations: { "A": "Factor: (x+5)(x−3)=0. x=−5 or x=3. Check: 9+6−15=0✓, 25−10−15=0✓. ✓", "B": "Product=−15 but sum=2, not +2 for these values.", "C": "(3)(5)=15≠−15.", "D": "(−3)(−5)=15≠−15." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-9",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Vertex form",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The function g(x)=−2(x+1)²+8 has a maximum value. What is it?",
    options: ["−2", "1", "8", "6"],
    correctAnswer: "C",
    explanation: "In a(x−h)²+k with a<0, max=k=8. ✓",
    explanations: { "A": "−2 is the leading coefficient.", "B": "x=−1 is the vertex x-coordinate.", "C": "In a(x−h)²+k with a<0, max=k=8. ✓", "D": "No mathematical basis." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-10",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Exponent rules",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If 3ˣ⋅4²=3³⋅4ˣ, what is the value of x+y if x and y are the unknowns in 3ˣ and 4ʸ?",
    options: ["", "", "", ""],
    correctAnswer: "5",
    explanation: "Matching bases: 3ˣ=3³ so x=3, and 4²=4ʸ so y=2. x+y=5.",
    explanations: { "correct": "Matching bases: 3ˣ=3³ so x=3, and 4²=4ʸ so y=2. x+y=5." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-11",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Rational expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression is equivalent to (x²−16)/(x+4)?",
    options: ["x+4", "x−4", "x²−4", "x−4x"],
    correctAnswer: "B",
    explanation: "x²−16=(x+4)(x−4). Divide by (x+4): x−4. ✓",
    explanations: { "A": "(x+4)(x+4)=x²+8x+16≠x²−16.", "B": "x²−16=(x+4)(x−4). Divide by (x+4): x−4. ✓", "C": "Can’t simplify by removing just the constant.", "D": "Not a valid expression." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-12",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Exponential growth",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which function models the population P after t years?",
    passage: "A town’s population is 8,000 and grows 3% annually.",
    options: ["P=8000(0.03)ᵗ", "P=8000(1.03)ᵗ", "P=8000+0.03t", "P=8000(3)ᵗ"],
    correctAnswer: "B",
    explanation: "3% growth: multiply by 1.03 each year. ✓",
    explanations: { "A": "0.03 is the rate, not the growth factor.", "B": "3% growth: multiply by 1.03 each year. ✓", "C": "Linear model.", "D": "Base 3 means tripling, not 3%." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-13",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Polynomial operations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the value of (2x³−5x+1)−(x³+3x−7) when x=2?",
    options: ["0", "−4", "−2", "4"],
    correctAnswer: "A",
    explanation: "Simplify: x³−8x+8. At x=2: 8−16+8=0. ✓",
    explanations: { "A": "Simplify: x³−8x+8. At x=2: 8−16+8=0. ✓", "B": "Sign error.", "C": "Partial calculation.", "D": "Multiple errors." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-14",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Ratios",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How many cups are needed for 20 servings?",
    passage: "A recipe for 8 servings uses 3 cups of rice.",
    options: ["6.5", "7", "7.5", "8"],
    correctAnswer: "C",
    explanation: "3/8=x/20. x=60/8=7.5. ✓",
    explanations: { "A": "No clear path.", "B": "Rounded wrong.", "C": "3/8=x/20. x=60/8=7.5. ✓", "D": "No basis." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-15",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Percentages",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the final price?",
    passage: "A $800 laptop is discounted 20%, then taxed at 8%.",
    options: ["$633.60", "$691.20", "$704.00", "$576.00"],
    correctAnswer: "B",
    explanation: "800×0.80=640. 640×1.08=691.20. ✓",
    explanations: { "A": "Applied both as discounts.", "B": "800×0.80=640. 640×1.08=691.20. ✓", "C": "Wrong order of operations.", "D": "Applied 28% total discount." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-16",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Probability",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the probability of drawing a red marble? (Enter as a decimal.)",
    passage: "A jar has 6 red and 14 blue marbles.",
    options: ["", "", "", ""],
    correctAnswer: "0.3",
    explanation: "P(red)=6/20=0.3.",
    explanations: { "correct": "P(red)=6/20=0.3." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-17",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Line of best fit",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What does the slope 4.2 represent?",
    passage: "A scatterplot has line of best fit y=4.2x+15 with r²=0.85, where x is ad spend ($1000s) and y is revenue ($1000s).",
    options: ["For each additional $1,000 in ad spend, revenue increases by about $4,200.", "Revenue is always $4,200.", "85% of revenue comes from advertising.", "The y-intercept is 4.2."],
    correctAnswer: "A",
    explanation: "Slope=change in y per unit x. Both in thousands. ✓",
    explanations: { "A": "Slope=change in y per unit x. Both in thousands. ✓", "B": "Revenue varies.", "C": "r² is about variation explained.", "D": "y-intercept is 15." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-18",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Circle equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Circle equation (x−3)²+(y+2)²=49. What is the radius?",
    options: ["3", "7", "49", "25"],
    correctAnswer: "B",
    explanation: "r²=49, r=7. ✓",
    explanations: { "A": "3 is the center x-coordinate.", "B": "r²=49, r=7. ✓", "C": "49=r², not r.", "D": "No basis." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-19",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Pythagorean theorem",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "A ladder reaches 24 ft high with base 7 ft from the wall. How long is the ladder?",
    options: ["", "", "", ""],
    correctAnswer: "25",
    explanation: "c²=24²+7²=576+49=625. c=25.",
    explanations: { "correct": "c²=24²+7²=576+49=625. c=25." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-20",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Trig ratios",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is tan(P)?",
    passage: "Right triangle PQR: angle R=90°, PQ=10, QR=6, PR=8.",
    options: ["3/4", "4/3", "3/5", "4/5"],
    correctAnswer: "A",
    explanation: "tan(P)=opp/adj=QR/PR=6/8=3/4. ✓",
    explanations: { "A": "tan(P)=opp/adj=QR/PR=6/8=3/4. ✓", "B": "Inverse ratio.", "C": "sin(P).", "D": "cos(P)." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-21",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Volume",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Cylinder: diameter 10 cm, height 15 cm. Volume?",
    options: ["150π", "375π", "750π", "1500π"],
    correctAnswer: "B",
    explanation: "r=5. V=π(25)(15)=375π. ✓",
    explanations: { "A": "Used diameter as radius for πrh.", "B": "r=5. V=π(25)(15)=375π. ✓", "C": "No basis.", "D": "Used d as r: π(100)(15)." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-22",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Similar triangles",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Similar triangles with sides in ratio 3:7. Smaller perimeter=18. Larger perimeter?",
    options: ["42", "36", "54", "126"],
    correctAnswer: "A",
    explanation: "18×(7/3)=42. ✓",
    explanations: { "A": "18×(7/3)=42. ✓", "B": "Wrong ratio.", "C": "18×3.", "D": "18×7." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-23",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Equations with fractions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Solve: (3/4)x−2=(1/3)x+3",
    options: ["10", "12", "15", "20"],
    correctAnswer: "B",
    explanation: "Multiply by 12: 9x−24=4x+36. 5x=60. x=12. Check: 9−2=7, 4+3=7. ✓",
    explanations: { "A": "Check: (3/4)(10)−2=5.5, (1/3)(10)+3=6.33. Not equal.", "B": "Multiply by 12: 9x−24=4x+36. 5x=60. x=12. Check: 9−2=7, 4+3=7. ✓", "C": "Check: 11.25−2=9.25, 5+3=8. Not equal.", "D": "15−2=13, 20/3+3=9.67. Not equal." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-24",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Systems (no solution)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: `For which value of k does the system have no solution?
3x+ky=12
6x+8y=5`,
    options: ["2", "4", "6", "8"],
    correctAnswer: "B",
    explanation: "For no solution: 3/6=k/8 but 12/5≠3/6. So k/8=1/2, k=4. Slopes equal but y-intercepts differ. ✓",
    explanations: { "A": "3/6≠2/8.", "B": "For no solution: 3/6=k/8 but 12/5≠3/6. So k/8=1/2, k=4. Slopes equal but y-intercepts differ. ✓", "C": "3/6≠6/8.", "D": "3/6≠8/8." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-25",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Absolute value",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many solutions does |4x−10|=−2 have?",
    options: ["", "", "", ""],
    correctAnswer: "0",
    explanation: "Absolute value is always ≥0. It can never equal −2. Zero solutions.",
    explanations: { "correct": "Absolute value is always ≥0. It can never equal −2. Zero solutions." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-26",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Perpendicular lines",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Line ℓ has slope 5/3. What is the slope of a line perpendicular to ℓ?",
    options: ["5/3", "−5/3", "3/5", "−3/5"],
    correctAnswer: "D",
    explanation: "Perpendicular slope = negative reciprocal: −3/5. ✓",
    explanations: { "A": "Same slope is parallel.", "B": "Negative but not reciprocal.", "C": "Reciprocal but not negative.", "D": "Perpendicular slope = negative reciprocal: −3/5. ✓" },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-27",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Word problems",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How many mL of the 10% solution are needed?",
    passage: "A pharmacy mixes a 10% saline solution with a 40% saline solution to make 600 mL of 22% solution.",
    options: ["240", "300", "360", "420"],
    correctAnswer: "C",
    explanation: "0.10(360)+0.40(240)=36+96=132. 132/600=22%. ✓",
    explanations: { "A": "0.10(240)+0.40(360)=24+144=168. 168/600=28%. Too high.", "B": "0.10(300)+0.40(300)=30+120=150. 150/600=25%. Too high.", "C": "0.10(360)+0.40(240)=36+96=132. 132/600=22%. ✓", "D": "0.10(420)+0.40(180)=42+72=114. 114/600=19%. Too low." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-28",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Function operations",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is f(g(2))?",
    passage: "f(x)=2x+3, g(x)=x²−1",
    options: ["", "", "", ""],
    correctAnswer: "9",
    explanation: "g(2)=4−1=3. f(3)=6+3=9.",
    explanations: { "correct": "g(2)=4−1=3. f(3)=6+3=9." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-29",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Identity equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "For what value of k is 2(x+k)=2x+8 true for all values of x?",
    options: ["2", "4", "6", "8"],
    correctAnswer: "B",
    explanation: "2(x+4)=2x+8 for all x. ✓",
    explanations: { "A": "2(x+2)=2x+4≠2x+8.", "B": "2(x+4)=2x+8 for all x. ✓", "C": "2(x+6)=2x+12≠2x+8.", "D": "2(x+8)=2x+16≠2x+8." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-30",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Completing the square",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the vertex of y=x²−6x+5?",
    options: ["(3,−4)", "(−3,−4)", "(3,5)", "(6,5)"],
    correctAnswer: "A",
    explanation: "y=(x−3)²−9+5=(x−3)²−4. Vertex (3,−4). ✓",
    explanations: { "A": "y=(x−3)²−9+5=(x−3)²−4. Vertex (3,−4). ✓", "B": "Wrong sign on h.", "C": "Didn’t complete the square.", "D": "Used b instead of b/2." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-31",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Complex numbers",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is (3+2i)(1−i)?",
    options: ["5−i", "1−i", "3−2i", "5+i"],
    correctAnswer: "A",
    explanation: "3−3i+2i−2i²=3−i−2(−1)=3−i+2=5−i. ✓",
    explanations: { "A": "3−3i+2i−2i²=3−i−2(−1)=3−i+2=5−i. ✓", "B": "Forgot i²=−1.", "C": "Only multiplied first terms.", "D": "Sign error on i term." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-32",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Quadratic formula",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many real solutions does 2x²+3x+5=0 have?",
    options: ["", "", "", ""],
    correctAnswer: "0",
    explanation: "Discriminant: 9−40=−31<0. No real solutions.",
    explanations: { "correct": "Discriminant: 9−40=−31<0. No real solutions." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-33",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Exponential decay",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which function models its value V after t years?",
    passage: "A car worth $25,000 depreciates 18% per year.",
    options: ["V=25000(0.18)ᵗ", "V=25000(0.82)ᵗ", "V=25000−18t", "V=25000(1.18)ᵗ"],
    correctAnswer: "B",
    explanation: "Loses 18%, retains 82%: 25000(0.82)ᵗ. ✓",
    explanations: { "A": "0.18 is the rate, not the remaining fraction.", "B": "Loses 18%, retains 82%: 25000(0.82)ᵗ. ✓", "C": "Linear model.", "D": "1.18 is growth, not depreciation." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-34",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Polynomial division",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If x−2 is a factor of x³−5x²+8x−4, what is the quotient?",
    options: ["x²−3x+2", "x²−x+6", "x²−3x+6", "x²+3x−2"],
    correctAnswer: "A",
    explanation: "Synthetic division with 2: coefficients 1,−5,8,−4 yield quotient x²−3x+2 with remainder 0. Verify: (x−2)(x²−3x+2)=x³−5x²+8x−4. ✓",
    explanations: { "A": "Synthetic division with 2: coefficients 1,−5,8,−4 yield quotient x²−3x+2 with remainder 0. Verify: (x−2)(x²−3x+2)=x³−5x²+8x−4. ✓", "B": "(x−2)(x²−x+6)=x³−3x²+8x−12. Wrong polynomial.", "C": "(x−2)(x²−3x+6)=x³−5x²+12x−12. Wrong x coefficient.", "D": "Signs produce a different polynomial entirely." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-35",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Function transformations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If f(x)=x², which describes the graph of g(x)=−(x−4)²+3?",
    options: ["Shifted right 4, up 3, reflected over x-axis.", "Shifted left 4, down 3, reflected over y-axis.", "Shifted right 4, down 3.", "Shifted left 4, up 3, reflected over x-axis."],
    correctAnswer: "A",
    explanation: "(x−4): right 4. +3: up 3. Negative: reflect over x-axis. ✓",
    explanations: { "A": "(x−4): right 4. +3: up 3. Negative: reflect over x-axis. ✓", "B": "Wrong direction on all transformations.", "C": "Missing the reflection; down should be up.", "D": "Wrong horizontal direction." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-36",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Margin of error",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which statement is best supported?",
    passage: "A poll of 1,200 voters found 52% support Candidate A, with a margin of error of ±3%.",
    options: ["Candidate A will definitely win the election.", "The true support level is likely between 49% and 55%.", "Exactly 52% of all voters support Candidate A.", "The poll is unreliable because the margin of error is too large."],
    correctAnswer: "B",
    explanation: "52%±3% = 49% to 55% confidence interval. ✓",
    explanations: { "A": "49% is within range, so a loss is possible.", "B": "52%±3% = 49% to 55% confidence interval. ✓", "C": "52% is the estimate, not exact.", "D": "3% is a standard margin of error." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-37",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Study design",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What type of study is this?",
    passage: "Researchers randomly assigned 200 patients to receive either a new drug or a placebo and measured recovery times.",
    options: ["Observational study", "Survey", "Randomized controlled experiment", "Case study"],
    correctAnswer: "C",
    explanation: "Random assignment + treatment vs. control = RCT. ✓",
    explanations: { "A": "Treatments were assigned, not just observed.", "B": "No questions asked; recovery was measured.", "C": "Random assignment + treatment vs. control = RCT. ✓", "D": "Case studies examine individual cases." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-38",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Two-way tables",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many students do neither sports nor arts?",
    passage: "In a school of 400 students: 220 play sports, 150 are in arts, 50 do both.",
    options: ["", "", "", ""],
    correctAnswer: "80",
    explanation: "Sports only: 220−50=170. Arts only: 150−50=100. Both: 50. Total in at least one: 170+100+50=320. Neither: 400−320=80.",
    explanations: { "correct": "Sports only: 220−50=170. Arts only: 150−50=100. Both: 50. Total in at least one: 170+100+50=320. Neither: 400−320=80." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-39",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Arc length",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the arc length?",
    passage: "A circle has radius 12. A central angle measures 150°.",
    options: ["5π", "10π", "15π", "20π"],
    correctAnswer: "B",
    explanation: "Arc=(θ/360)(2πr)=(150/360)(24π)=(5/12)(24π)=10π. ✓",
    explanations: { "A": "Too small.", "B": "Arc=(θ/360)(2πr)=(150/360)(24π)=(5/12)(24π)=10π. ✓", "C": "Used radius instead of diameter.", "D": "Too large." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-40",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Sector area",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A sector has central angle 90° and radius 8. What is its area?",
    options: ["8π", "16π", "32π", "64π"],
    correctAnswer: "B",
    explanation: "A=(90/360)π(64)=(1/4)(64π)=16π. ✓",
    explanations: { "A": "Used πr instead of πr² with fraction.", "B": "A=(90/360)π(64)=(1/4)(64π)=16π. ✓", "C": "Used half instead of quarter.", "D": "Full circle area." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-41",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Distance formula",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the distance between points (1,3) and (7,11)?",
    options: ["", "", "", ""],
    correctAnswer: "10",
    explanation: "d=√((7−1)²+(11−3)²)=√(36+64)=√100=10.",
    explanations: { "correct": "d=√((7−1)²+(11−3)²)=√(36+64)=√100=10." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-42",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Completing square (circles)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the radius of the circle x²+y²−8x+6y=0?",
    options: ["3", "4", "5", "10"],
    correctAnswer: "C",
    explanation: "(x−4)²+(y+3)²=16+9=25. r=5. ✓",
    explanations: { "A": "Only half of the completing.", "B": "Just the x-component.", "C": "(x−4)²+(y+3)²=16+9=25. r=5. ✓", "D": "r²=25, not r=25." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-43",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Trig (sine rule concept)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "In right triangle DEF, angle F=90° and sin(D)=5/13. What is cos(D)?",
    options: ["5/12", "12/13", "5/13", "13/12"],
    correctAnswer: "B",
    explanation: "opp=5, hyp=13. adj=√(169−25)=12. cos(D)=12/13. ✓",
    explanations: { "A": "That’s tan(D).", "B": "opp=5, hyp=13. adj=√(169−25)=12. cos(D)=12/13. ✓", "C": "That’s sin(D) repeated.", "D": "Greater than 1, impossible for cosine." },
    tags: ["practice-test"],
  },
  {
    id: "pt-sat-math-44",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Congruence and proof",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If two triangles have three pairs of congruent sides (SSS), which statement must be true?",
    options: ["The triangles are similar but not necessarily congruent.", "The triangles are congruent.", "The triangles have the same perimeter but different shapes.", "Nothing can be concluded."],
    correctAnswer: "B",
    explanation: "SSS (Side-Side-Side) is a triangle congruence theorem. ✓",
    explanations: { "A": "SSS guarantees congruence, not just similarity.", "B": "SSS (Side-Side-Side) is a triangle congruence theorem. ✓", "C": "Congruent triangles have identical shapes.", "D": "SSS is conclusive." },
    tags: ["practice-test"],
  }
];
