import type { Question } from "@/types/question";

export const QUESTIONS: Question[] = [
  {
    id: "diag-sat-rw-1",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "In her analysis of Renaissance painting techniques, art historian Maria Voss argues that Caravaggio’s use of chiaroscuro was not merely decorative but fundamentally _______ the viewer’s emotional response to sacred subjects, transforming passive observation into visceral engagement.",
    options: ["distorted", "mediated", "eliminated", "documented"],
    correctAnswer: "B",
    explanation: `'Mediated' means shaped or served as intermediary — the technique shaped the viewer’s emotional engagement. ✓`,
    explanations: { "A": `'Distorted' implies corruption, contradicting the positive framing.`, "B": `'Mediated' means shaped or served as intermediary — the technique shaped the viewer’s emotional engagement. ✓`, "C": `'Eliminated' contradicts the passage (technique intensified, not removed engagement).`, "D": `'Documented' means recorded — a technique doesn’t record a response, it creates one.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-2",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Despite the governor’s confident public statements, internal memoranda reveal that her administration viewed the proposed infrastructure bill with considerable _______, uncertain whether its projected economic benefits would materialize within the promised timeline.",
    options: ["enthusiasm", "indifference", "skepticism", "hostility"],
    correctAnswer: "C",
    explanation: `'Skepticism' means doubt — matches 'uncertain whether benefits would materialize.' ✓`,
    explanations: { "A": `Contradicts 'uncertain whether benefits would materialize.'`, "B": `'Indifference' suggests they didn’t care, but they were actively uncertain.`, "C": `'Skepticism' means doubt — matches 'uncertain whether benefits would materialize.' ✓`, "D": "Too strong; the passage indicates doubt, not active opposition." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-3",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Genomic studies of ancient wheat varieties have revealed that early agricultural communities did not simply select for larger grain size, as previously assumed. Instead, the process of domestication was remarkably _______, involving incremental genetic changes across dozens of traits over thousands of years.",
    options: ["deliberate", "gradual", "chaotic", "instantaneous"],
    correctAnswer: "B",
    explanation: `Matches 'incremental genetic changes over thousands of years.' ✓`,
    explanations: { "A": "Implies intentional planning, but the passage emphasizes natural incremental change.", "B": `Matches 'incremental genetic changes over thousands of years.' ✓`, "C": "Implies disorder, but the process was systematic if slow.", "D": `Directly contradicts 'thousands of years.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-4",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Philosopher Martha Nussbaum contends that a society’s commitment to justice cannot be measured solely by its legal codes. Rather, she argues, true justice requires the cultivation of empathy — the capacity to _______ the lived experiences of those whose circumstances differ profoundly from one’s own.",
    options: ["dismiss", "replicate", "apprehend", "publicize"],
    correctAnswer: "C",
    explanation: `'Apprehend' means to grasp or understand — captures the cognitive act of understanding others’ experiences. ✓`,
    explanations: { "A": "Contradicts the passage’s emphasis on empathy.", "B": "Too literal — empathy involves understanding, not duplicating experience.", "C": `'Apprehend' means to grasp or understand — captures the cognitive act of understanding others’ experiences. ✓`, "D": "Making experiences widely known doesn’t relate to personal empathy." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-5",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The coral reef ecosystem, once thought to be resilient enough to recover from periodic bleaching events, now faces a convergence of stressors — rising ocean temperatures, acidification, and coastal pollution — that threaten to _______ its capacity for regeneration altogether.",
    options: ["enhance", "overwhelm", "measure", "isolate"],
    correctAnswer: "B",
    explanation: `'Overwhelm' means to overpower — combined stressors could defeat the reef’s recovery ability. ✓`,
    explanations: { "A": `Contradicts 'threaten' — stressors are harmful.`, "B": `'Overwhelm' means to overpower — combined stressors could defeat the reef’s recovery ability. ✓`, "C": "Stressors don’t measure capacity.", "D": `'Isolate' doesn’t convey defeating regenerative capacity.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-6",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "In her 1929 essay “A Room of One’s Own,” Virginia Woolf argues that the absence of women from the literary canon is not evidence of inferior talent but rather a consequence of systemic barriers — limited education, financial dependence, and social _______ — that prevented women from writing at all.",
    options: ["mobility", "constraints", "distinctions", "networks"],
    correctAnswer: "B",
    explanation: `'Constraints' means restrictions — completes the list of barriers. ✓`,
    explanations: { "A": "Social mobility refers to class movement, not a barrier parallel to limited education.", "B": `'Constraints' means restrictions — completes the list of barriers. ✓`, "C": "Means differences or honors, neither fits as a barrier.", "D": "Networks typically help rather than hinder." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-7",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the function of the underlined sentence in the text as a whole?",
    passage: "When the James Webb Space Telescope captured its first deep field image in July 2022, astronomers were startled: galaxies from the universe’s earliest epochs appeared far more structured and mature than existing models predicted. Some displayed well-defined spiral arms that, according to prevailing theories, should not have developed for billions of years after the Big Bang. <u>The finding didn’t invalidate the Big Bang model, but it exposed significant gaps in our understanding of how quickly cosmic structures can assemble.</u>",
    options: ["It introduces a new hypothesis that challenges the Big Bang model.", "It qualifies the significance of the finding by clarifying what it does and does not imply.", "It summarizes the conclusions of a specific research study.", "It provides technical details about how galaxies form spiral arms."],
    correctAnswer: "B",
    explanation: "The sentence limits the claim (doesn’t invalidate) while preserving importance (exposed gaps) — classic qualification. ✓",
    explanations: { "A": `The sentence explicitly says it 'didn’t invalidate the Big Bang model.'`, "B": "The sentence limits the claim (doesn’t invalidate) while preserving importance (exposed gaps) — classic qualification. ✓", "C": "It’s interpretive framing, not a study summary.", "D": "Nothing about the technical process of spiral arm formation." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-8",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Cross-Text Connections",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Based on the texts, how would Acemoglu (Text 2) most likely respond to Cowen’s argument in Text 1?",
    passage: "<strong>Text 1</strong><br>Economist Tyler Cowen argues that artificial intelligence will dramatically increase economic productivity, creating new categories of employment — much as the industrial revolution ultimately generated more jobs than it destroyed.<br><br><strong>Text 2</strong><br>Labor researcher Daron Acemoglu cautions that the comparison to the industrial revolution is misleading. The transition from agrarian to industrial economies occurred over generations. AI-driven automation, by contrast, could displace millions within a single decade, far outpacing the economy’s capacity to create replacement employment.",
    options: ["By agreeing AI will create new jobs but arguing those jobs will pay less.", "By challenging the historical analogy, arguing that the speed of AI displacement prevents the gradual adaptation that made past transitions manageable.", "By rejecting the premise that AI will increase economic productivity.", "By arguing the industrial revolution did not, in fact, create more jobs than it destroyed."],
    correctAnswer: "B",
    explanation: "Acemoglu challenges the comparison because timescales differ fundamentally: generations vs. a decade. ✓",
    explanations: { "A": "Text 2 doesn’t discuss wages — it focuses on speed.", "B": "Acemoglu challenges the comparison because timescales differ fundamentally: generations vs. a decade. ✓", "C": "Text 2 doesn’t dispute productivity gains.", "D": "Text 2 doesn’t challenge the historical claim — it says the comparison is misleading due to different conditions." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-9",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best states the main idea of the text?",
    passage: "In 2019, researchers at MIT developed an AI system called “halicin” that discovered a powerful new antibiotic compound. The system was trained on 2,335 molecules with known antibacterial properties, then set loose on a library of 6,000 compounds. Halicin identified a molecule originally investigated as a diabetes drug that proved remarkably effective against drug-resistant bacteria, including strains untreatable for decades.",
    options: ["Drug-resistant bacteria represent a growing threat that traditional research has failed to address.", "An AI system successfully identified an existing compound as a potent antibiotic, demonstrating machine learning’s potential in drug discovery.", "The diabetes drug that halicin identified had been overlooked by researchers for decades.", "MIT researchers trained an AI system on over 2,000 molecules to study antibacterial properties."],
    correctAnswer: "B",
    explanation: "Central narrative: AI found a powerful antibiotic among existing compounds. ✓",
    explanations: { "A": "The passage is about AI finding a solution, not describing the problem.", "B": "Central narrative: AI found a powerful antibiotic among existing compounds. ✓", "C": `The compound wasn’t 'overlooked' — it was studied for a different purpose.`, "D": "Training data is a supporting detail, not the main idea." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-10",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "According to the text, what is a key feature of the octopus’s nervous system?",
    passage: "The octopus possesses approximately 500 million neurons — comparable to a dog — but distributes them radically differently. Nearly two-thirds reside in its eight arms rather than its central brain. Each arm can independently taste, touch, and make basic movement decisions without consulting the brain. This decentralized nervous system allows remarkably complex behaviors — opening jars, navigating mazes — while the brain handles higher-order processing.",
    options: ["The octopus has more neurons than a dog.", "Most of its neurons are located in the arms, which can operate with some autonomy from the central brain.", "The octopus’s brain is too small to control all eight arms simultaneously.", "Each arm contains a separate brain that functions independently."],
    correctAnswer: "B",
    explanation: `'Nearly two-thirds' in the arms and each arm can 'independently' make decisions. ✓`,
    explanations: { "A": `The passage says 'comparable,' not more.`, "B": `'Nearly two-thirds' in the arms and each arm can 'independently' make decisions. ✓`, "C": `Doesn’t say the brain is 'too small' — describes architectural difference.`, "D": `The arms have neurons, not separate 'brains.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-11",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Based on the text, Gordon-Reed’s most significant contribution was:",
    passage: "Historian Annette Gordon-Reed’s work on Jefferson and the Hemings family fundamentally altered how scholars approach enslaved people in early America. Before Gordon-Reed, mainstream historiography tended to treat enslaved individuals as an undifferentiated mass — sources of labor, rarely as complex people with inner lives and agency. Gordon-Reed demonstrated that careful analysis of fragmentary evidence — account books, letters, travel records — could reconstruct enslaved individuals’ experiences with surprising specificity.",
    options: ["discovering previously unknown documents about the Hemings family.", "showing that fragmentary historical evidence could recover the individual experiences and perspectives of enslaved people.", "proving that Thomas Jefferson fathered children with Sally Hemings.", "criticizing historians for ignoring the institution of slavery."],
    correctAnswer: "B",
    explanation: "Central claim: fragmentary evidence could reconstruct experiences of enslaved individuals. ✓",
    explanations: { "A": "She analyzed existing evidence, didn’t discover new documents.", "B": "Central claim: fragmentary evidence could reconstruct experiences of enslaved individuals. ✓", "C": "Paternity isn’t mentioned — the focus is historiographical method.", "D": `Earlier scholarship treated enslaved people as 'undifferentiated,' not that it ignored slavery.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-12",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding, if true, would most directly support Earle’s characterization of the deep ocean as ‘least understood’?",
    passage: "Marine biologist Sylvia Earle has long argued that the deep ocean — below 200 meters — constitutes Earth’s largest and least understood ecosystem. Despite covering more than 65% of the planet’s surface, it has been less thoroughly mapped than Mars. Recent expeditions have discovered hydrothermal vent communities, extremophile organisms that derive energy from chemical reactions, and species so novel that biologists must create entirely new taxonomic categories.",
    options: ["Deep-sea mining companies have begun extracting minerals from hydrothermal vents.", "A 2023 survey estimated that over 80% of the deep ocean floor remains unmapped at high resolution.", "Researchers found that deep-sea temperatures are rising due to climate change.", "Several deep-ocean species have been successfully bred in captivity."],
    correctAnswer: "B",
    explanation: `80%+ unmapped directly supports 'least understood.' ✓`,
    explanations: { "A": "Mining doesn’t address understanding.", "B": `80%+ unmapped directly supports 'least understood.' ✓`, "C": "Temperature changes are a finding, not evidence of how little we know.", "D": "Breeding species doesn’t support the poorly-understood claim." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-13",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the evidence Desmond uses to support his broader argument?",
    passage: "Sociologist Matthew Desmond argues that eviction is not merely a consequence of poverty but a cause of it. When families are evicted, they lose homes, possessions, school stability, employment proximity, and credit standing — losses that compound over years. His Milwaukee research found that women in low-income Black neighborhoods were evicted at disproportionately high rates, suggesting eviction reinforces both racial and economic inequality.",
    options: ["National statistics showing poverty rates have increased over the past decade.", "Interviews with landlords explaining why they evict tenants.", "Data from a specific city showing that eviction disproportionately affects particular demographic groups.", "A comparison of eviction rates across different countries."],
    correctAnswer: "C",
    explanation: `'Research in Milwaukee' showing disproportionate rates for 'women in low-income Black neighborhoods' — city-specific demographic data. ✓`,
    explanations: { "A": "National poverty statistics aren’t mentioned.", "B": "Landlord interviews aren’t described.", "C": `'Research in Milwaukee' showing disproportionate rates for 'women in low-income Black neighborhoods' — city-specific demographic data. ✓`, "D": "No international comparison is mentioned." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-14",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to support the conclusion that vocal music impairs reading comprehension?",
    passage: "A research team studied the effect of background music on reading comprehension among college students. Participants were randomly assigned to silence, instrumental music, or music with lyrics.",
    options: ["Students in silence scored 82%, while instrumental students scored 79%.", "Students in the lyrics condition scored 68%, substantially lower than both silence (82%) and instrumental (79%).", "More students were assigned to the silence condition than to either music condition.", "The instrumental condition produced scores closer to silence than to the lyrics condition."],
    correctAnswer: "B",
    explanation: "Shows the lyrics condition scored substantially lower than both others — directly supports the claim. ✓",
    explanations: { "A": "Doesn’t involve the lyrics condition at all.", "B": "Shows the lyrics condition scored substantially lower than both others — directly supports the claim. ✓", "C": "Sample sizes don’t support a conclusion about musical effects.", "D": "Less direct than B — doesn’t show the lyrics condition’s actual deficit." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-15",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to illustrate a limitation of Dr. Chen’s conclusion that downtown relocation improves satisfaction?",
    passage: "Urban planner Dr. Lisa Chen studied commute times and employee satisfaction at companies relocating from suburban office parks to downtown urban cores, surveying 500 employees at four companies.",
    options: ["Company B reported a decrease in satisfaction from 72% to 65% after relocating downtown.", "Company A’s satisfaction increased from 68% to 84%, the largest gain.", "Average commute time decreased for three of the four companies.", "Company D had the highest pre-relocation satisfaction at 78%."],
    correctAnswer: "A",
    explanation: `A company’s satisfaction decreasing after relocation directly challenges a blanket 'improves' conclusion. ✓`,
    explanations: { "A": `A company’s satisfaction decreasing after relocation directly challenges a blanket 'improves' conclusion. ✓`, "B": "Supports rather than limits the conclusion.", "C": "Commute times aren’t directly about satisfaction.", "D": "Pre-relocation scores don’t address post-relocation effects." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-16",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "The boreal forest, stretching across Canada, Scandinavia, and Russia, stores approximately twice as much carbon as all tropical rainforests combined — most of it in permafrost and peat soils rather than living trees. As temperatures rise, permafrost is thawing at accelerating rates, releasing methane and CO₂ sequestered for millennia. ________",
    options: ["This means the boreal forest is more biodiverse than tropical rainforests.", "Consequently, tropical deforestation remains the most urgent driver of climate change.", "The boreal forest could therefore shift from being one of Earth’s largest carbon sinks to a significant source of greenhouse gas emissions.", "Scientists have recommended planting more trees in the boreal region to offset carbon release."],
    correctAnswer: "C",
    explanation: "Logical inference: if stored carbon is released, the forest shifts from sink to source. ✓",
    explanations: { "A": "Passage discusses carbon, not biodiversity.", "B": "Passage is about boreal becoming a problem, not about tropical deforestation.", "C": "Logical inference: if stored carbon is released, the forest shifts from sink to source. ✓", "D": "Carbon is in permafrost/peat, not trees — tree-planting wouldn’t help." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-17",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Japanese architect Tadao Ando is renowned for minimalist concrete structures emphasizing natural light. His Church of the Light in Osaka features a cruciform slit projecting a cross of sunlight into the dark interior. _______, Ando’s design philosophy draws heavily on traditional Japanese aesthetics, particularly the concept of <em>ma</em> — the meaningful use of empty space.",
    options: ["In contrast", "More broadly", "For example", "Nevertheless"],
    correctAnswer: "B",
    explanation: "Moves from specific example to broader philosophy. ✓",
    explanations: { "A": "No contrast — both are about Ando’s philosophy.", "B": "Moves from specific example to broader philosophy. ✓", "C": "The general statement isn’t an example of the church.", "D": "No contradiction between the example and the philosophy." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-18",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: `Psychologist Carol Dweck’s 'growth mindset' research has been enormously influential in education. Schools implemented growth mindset curricula, training teachers to praise effort over innate ability. _______, several large-scale replication studies found that interventions produce smaller effects than Dweck’s original research suggested, leading some to question whether the concept was oversimplified.`,
    options: ["Furthermore", "Similarly", "However", "In other words"],
    correctAnswer: "C",
    explanation: "Shifts from widespread adoption to challenging findings — a clear contrast. ✓",
    explanations: { "A": "Would add support, but the next sentence contradicts.", "B": "Indicates parallel information, but this is a contradiction.", "C": "Shifts from widespread adoption to challenging findings — a clear contrast. ✓", "D": "Replication findings are new information, not a restatement." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-19",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Voyager 1, launched in 1977, has traveled farther from Earth than any human-made object. In 2012, it crossed the heliopause — the boundary where the sun’s solar wind gives way to interstellar space. _______, Voyager 1 continues to transmit scientific data, though its signal now takes over 22 hours to reach us.",
    options: ["By contrast", "As of 2025", "Consequently", "On the other hand"],
    correctAnswer: "B",
    explanation: "Updates the reader on current status after the 2012 milestone. ✓",
    explanations: { "A": "No contrast between crossing the heliopause and transmitting.", "B": "Updates the reader on current status after the 2012 milestone. ✓", "C": "Transmitting data isn’t a consequence of crossing the heliopause.", "D": "No opposing perspective is introduced." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-20",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about urban green spaces and wants to emphasize the mental health benefits of urban parks specifically for city residents.",
    options: ["Urban parks provide habitat for wildlife and help manage stormwater runoff.", "A 2022 study in <em>The Lancet</em> found that city residents within 300 meters of a park reported 20% lower rates of anxiety and depression.", "Urban parks have been a feature of city planning since Olmsted designed Central Park in the 1850s.", "Access to green space varies significantly across socioeconomic lines."],
    correctAnswer: "B",
    explanation: "Directly links parks to mental health outcomes for city residents with specific data. ✓",
    explanations: { "A": "Ecological benefits, not mental health.", "B": "Directly links parks to mental health outcomes for city residents with specific data. ✓", "C": "Historical context, not mental health.", "D": "Access inequality, not health outcomes." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-21",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the 1918 influenza pandemic’s economic impact and wants to highlight a surprising long-term economic outcome.",
    options: ["The 1918 pandemic killed an estimated 50 to 100 million people worldwide.", "During the pandemic, many businesses closed and economic activity declined sharply.", "Counterintuitively, research by Correia, Luck, and Verner found that U.S. cities with longer, more aggressive public health interventions experienced stronger economic growth in the years that followed.", "The pandemic disproportionately affected young, working-age adults between 20 and 40."],
    correctAnswer: "C",
    explanation: "Stricter measures leading to better economic outcomes is counterintuitive. ✓",
    explanations: { "A": `Death toll is not a 'surprising economic outcome.'`, "B": "Business closures during a pandemic are expected, not surprising.", "C": "Stricter measures leading to better economic outcomes is counterintuitive. ✓", "D": "Demographic impact, not a long-term economic outcome." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-22",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about monarch butterfly migration and wants to convey the remarkable precision of the butterflies’ navigational abilities.",
    options: ["Monarch butterflies migrate up to 3,000 miles from Canada to Mexico each fall.", "Despite having brains smaller than a pinhead, monarch butterflies navigate to the same few hectares of oyamel fir forest year after year — a destination none has ever visited before, since the journey spans multiple generations.", "The oyamel fir forests provide the cool, humid conditions monarchs need to survive winter.", "Monarch populations have declined approximately 80% since the 1990s due to habitat loss."],
    correctAnswer: "B",
    explanation: "Emphasizes precision (same few hectares), improbability (tiny brain, never visited), and multi-generational mystery. ✓",
    explanations: { "A": "Conveys distance but not precision.", "B": "Emphasizes precision (same few hectares), improbability (tiny brain, never visited), and multi-generational mystery. ✓", "C": "Explains why they go there, not how precisely they navigate.", "D": "About population decline, not navigation." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-23",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The discovery of high-temperature superconductors in 1986 revolutionized materials science. Unlike conventional superconductors, which require cooling to near absolute _______ these new materials exhibited zero electrical resistance at temperatures achievable with liquid nitrogen.",
    options: ["zero,", "zero;", "zero", "zero—"],
    correctAnswer: "A",
    explanation: `A comma after 'zero' properly closes the nonrestrictive clause before the main clause continues. ✓`,
    explanations: { "A": `A comma after 'zero' properly closes the nonrestrictive clause before the main clause continues. ✓`, "B": "A semicolon joins independent clauses, but the introductory phrase is dependent.", "C": "No punctuation creates a run-on.", "D": "A dash could work for emphasis but a comma is standard here." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-24",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Choreographer Alvin Ailey founded the Alvin Ailey American Dance Theater in _______ the company has since performed for an estimated 25 million people across 71 countries.",
    options: ["1958,", "1958;", "1958 and", "1958"],
    correctAnswer: "B",
    explanation: "A semicolon correctly joins two related independent clauses. ✓",
    explanations: { "A": "A comma creates a comma splice between two independent clauses.", "B": "A semicolon correctly joins two related independent clauses. ✓", "C": `'And' without a preceding comma doesn’t properly join these independent clauses.`, "D": "No punctuation creates a run-on." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-25",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Renowned for their architectural precision, the dry-stone walls of the Yorkshire _______ are built entirely without mortar. Skilled wallers select each stone by hand, relying on gravity and friction alone.",
    options: ["Dales,", "Dales:", "Dales—", "Dales"],
    correctAnswer: "D",
    explanation: `No extra punctuation needed — 'walls of the Yorkshire Dales are built' is a complete sentence. ✓`,
    explanations: { "A": "A comma would incorrectly separate the subject from its verb.", "B": "A colon doesn’t belong between subject and verb.", "C": "A dash creates unnecessary interruption between subject and verb.", "D": `No extra punctuation needed — 'walls of the Yorkshire Dales are built' is a complete sentence. ✓` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-26",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Neither the director nor the lead _______ willing to compromise on the final scene, resulting in weeks of tense negotiations.",
    options: ["actors were", "actors was", "actor were", "actor was"],
    correctAnswer: "D",
    explanation: `'Neither...nor' — verb agrees with nearer subject: 'actor' (singular) takes 'was.' ✓`,
    explanations: { "A": `With 'neither...nor,' the verb agrees with the nearer subject. 'Actors' would be plural.`, "B": `'Actors was' is never correct.`, "C": "Singular subject with plural verb is incorrect.", "D": `'Neither...nor' — verb agrees with nearer subject: 'actor' (singular) takes 'was.' ✓` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-27",
    testType: "sat",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "By the time the rescue team arrived at the summit, the stranded climbers _______ without shelter for over sixteen hours in sub-zero temperatures.",
    options: ["waited", "had been waiting", "have waited", "are waiting"],
    correctAnswer: "B",
    explanation: "Past perfect progressive shows an action that started before and continued up to a past event, emphasizing duration. ✓",
    explanations: { "A": "Simple past doesn’t convey ongoing duration before the rescue.", "B": "Past perfect progressive shows an action that started before and continued up to a past event, emphasizing duration. ✓", "C": "Present perfect shifts to present relevance in an entirely past scenario.", "D": "Present progressive contradicts the past-tense narrative." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-28",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The philosopher Simone de Beauvoir maintained that freedom is not a static possession but a continuous project — something that must be actively _______ through engagement with the world, lest it calcify into mere complacency.",
    options: ["relinquished", "exercised", "concealed", "debated"],
    correctAnswer: "B",
    explanation: `'Exercised' means actively practiced — freedom must be practiced through engagement. ✓`,
    explanations: { "A": "Means given up — the opposite.", "B": `'Exercised' means actively practiced — freedom must be practiced through engagement. ✓`, "C": "Hidden doesn’t fit active engagement.", "D": "Too narrow — the passage is about living freedom, not discussing it." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-29",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Although the two species of finches appeared virtually identical to untrained observers, ornithologist Elena Vasquez demonstrated that subtle differences in beak curvature and song frequency were _______ enough to constitute distinct evolutionary lineages, doubling the known finch diversity of the Galápagos.",
    options: ["superficial", "negligible", "significant", "ambiguous"],
    correctAnswer: "C",
    explanation: `'Significant' — meaningful enough to establish distinct species. ✓`,
    explanations: { "A": `Contradicts 'constitute distinct lineages.'`, "B": "Contradicts doubling known diversity.", "C": `'Significant' — meaningful enough to establish distinct species. ✓`, "D": `Vasquez 'demonstrated' the differences, implying clarity.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-30",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "During the Harlem Renaissance, Langston Hughes drew upon jazz and blues rhythms to create a literary voice that was both formally _______ and deeply rooted in African American vernacular, challenging the assumption that artistic sophistication required adherence to European conventions.",
    options: ["conventional", "innovative", "obscure", "derivative"],
    correctAnswer: "B",
    explanation: `'Innovative' — new methods combining formal experimentation with vernacular. ✓`,
    explanations: { "A": "Hughes challenged European conventions, so his work wasn’t conventional.", "B": `'Innovative' — new methods combining formal experimentation with vernacular. ✓`, "C": "Contradicts emphasis on accessible vernacular.", "D": "Means copied from others — Hughes was original." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-31",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Nutritionist Dr. Amara Osei cautions that the proliferation of conflicting dietary studies has created a climate of public _______ in which consumers, overwhelmed by contradictory claims, increasingly distrust scientific nutrition research altogether.",
    options: ["curiosity", "expertise", "cynicism", "compliance"],
    correctAnswer: "C",
    explanation: `'Cynicism' means a distrustful, skeptical attitude — matches 'increasingly distrust.' ✓`,
    explanations: { "A": "Curiosity suggests interest, but the passage describes distrust.", "B": "The public isn’t gaining expertise.", "C": `'Cynicism' means a distrustful, skeptical attitude — matches 'increasingly distrust.' ✓`, "D": "Compliance means following rules — unrelated." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-32",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The newly discovered galaxy, observed as it appeared 400 million years after the Big Bang, displayed a chemical composition far more _______ than cosmological models predicted — containing heavy elements like iron and silicon thought to require billions of years of stellar nucleosynthesis.",
    options: ["primitive", "homogeneous", "mature", "volatile"],
    correctAnswer: "C",
    explanation: `'Mature' — more chemically developed than expected for its age. ✓`,
    explanations: { "A": `'Primitive' means undeveloped — but it had heavy elements indicating development.`, "B": `'Homogeneous' doesn’t capture the surprise of heavy elements.`, "C": `'Mature' — more chemically developed than expected for its age. ✓`, "D": `'Volatile' means unstable, unrelated to compositional richness.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-33",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the overall structure of the text?",
    passage: `In 1848, Seneca Falls, New York, hosted the first women’s rights convention. Elizabeth Cady Stanton drafted the Declaration of Sentiments, modeled after the Declaration of Independence, proclaiming 'all men and women are created equal.' The document demanded property rights, educational access, and — most controversially — voting rights. Frederick Douglass, the only African American attendee, gave a rousing speech in support of suffrage that helped narrowly pass the voting rights resolution.`,
    options: ["It presents a debate between two opposing viewpoints on women’s rights.", "It describes a historical event, outlines its central document, and highlights a pivotal moment in its proceedings.", "It compares the Declaration of Sentiments with the Declaration of Independence.", "It argues that Frederick Douglass was the most important figure at the convention."],
    correctAnswer: "B",
    explanation: "Moves from event → document → pivotal moment. ✓",
    explanations: { "A": "Doesn’t present opposing viewpoints.", "B": "Moves from event → document → pivotal moment. ✓", "C": "The comparison is one detail, not the overall structure.", "D": "Douglass contributed to a moment but isn’t argued to be the most important figure." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-34",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding, if true, would most directly support the critics’ concern about structural advantages?",
    passage: `Psychologist Angela Duckworth’s concept of 'grit' has been widely adopted in education. She argues grit better predicts success than IQ, citing studies showing grittier students earn higher GPAs. Critics contend that grit research conflates conscientiousness with resilience and may underemphasize the role of structural advantages like wealth and social networks.`,
    options: ["Students high on grit also scored high on conscientiousness measures.", "Among students with equal grit scores, those from higher-income families were twice as likely to complete degrees.", "Duckworth’s grit scale has been translated into 15 languages.", "Grit scores correlated more strongly with GPA than standardized tests did."],
    correctAnswer: "B",
    explanation: "If wealth predicts success even when grit is equal, structural advantages matter independently. ✓",
    explanations: { "A": "Supports the conflation concern but not the structural advantage concern.", "B": "If wealth predicts success even when grit is equal, structural advantages matter independently. ✓", "C": "Translation breadth doesn’t address substance.", "D": "Supports Duckworth, not the critics." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-35",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding, if true, would most directly support McWhorter’s claim?",
    passage: "Linguist John McWhorter argues that the loss of grammatical complexity in English — case endings, gender, subjunctive mood — is not cultural decline but a natural process in all widely spoken languages. As languages spread to larger populations with more non-native speakers, grammatical features that don’t carry essential meaning tend to erode.",
    options: ["Languages spoken by small, isolated communities tend to have significantly more complex grammatical systems than global languages do.", "English vocabulary has expanded dramatically over the past 500 years.", "Some grammatically complex languages, such as Finnish, have high literacy rates.", "The subjunctive mood is still used in formal English writing."],
    correctAnswer: "A",
    explanation: "If isolated languages are more complex and global ones simpler, this supports the spread-causes-simplification claim. ✓",
    explanations: { "A": "If isolated languages are more complex and global ones simpler, this supports the spread-causes-simplification claim. ✓", "B": "Vocabulary growth doesn’t address grammatical complexity.", "C": "High literacy in complex languages doesn’t disprove McWhorter’s pattern.", "D": "Residual subjunctive use doesn’t address the overall trend." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-36",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to support the claim that insufficient sleep is associated with lower academic performance?",
    passage: "Researchers examined the relationship between sleep duration and academic performance among 1,200 high school students across four schools.",
    options: ["Students sleeping 6-7 hours had a GPA of 3.1, while those sleeping 8+ hours had 3.0.", "The largest group of students (38%) reported sleeping 6-7 hours per night.", "Students sleeping fewer than 6 hours had a mean GPA of 2.4, compared to 3.4 for students sleeping 7-8 hours — a full grade point lower.", "The percentage sleeping 8+ hours was smaller than those sleeping under 6 hours."],
    correctAnswer: "C",
    explanation: "A full grade point difference directly shows insufficient sleep correlated with lower GPA. ✓",
    explanations: { "A": "Minimal difference that doesn’t clearly show insufficient sleep harming performance.", "B": "Describes distribution, not the relationship to performance.", "C": "A full grade point difference directly shows insufficient sleep correlated with lower GPA. ✓", "D": "Group sizes don’t address the sleep-performance relationship." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-37",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: `In laboratory experiments, ravens have demonstrated the ability to plan for future events — selecting and saving tools they’ll need for a task they won’t encounter until the following day. This capacity, once thought uniquely human, requires 'mental time travel': projecting oneself into a future situation and acting on that projection. ________`,
    options: ["This suggests that the cognitive foundations for future planning may have evolved independently in birds and mammals.", "Ravens are therefore the most intelligent species in the animal kingdom.", "Scientists remain uncertain whether ravens possess any cognitive abilities beyond basic tool use.", "These findings have led researchers to abandon the concept of mental time travel."],
    correctAnswer: "A",
    explanation: "Ravens (birds) and humans (mammals) diverged long ago, suggesting convergent evolution of this capacity. ✓",
    explanations: { "A": "Ravens (birds) and humans (mammals) diverged long ago, suggesting convergent evolution of this capacity. ✓", "B": `Doesn’t claim ravens are 'most intelligent' — only that they share one capacity.`, "C": "The passage describes sophisticated planning beyond basic tool use.", "D": "The findings support, not undermine, mental time travel." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-38",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "The Nazca Lines — enormous geoglyphs in the Peruvian desert (500 BCE–500 CE) — remained undetected until commercial airlines flew over the region in the 1920s. The lines, some over 1,000 feet long, depict animals and shapes visible only from the air. Despite decades of study, archaeologists haven’t reached consensus on their purpose, though most agree they held ceremonial or astronomical significance. ________",
    options: ["This uncertainty persists in part because the Nazca left no written records that might explain the lines’ intended function.", "The lines were therefore created for communicating with extraterrestrial beings.", "Commercial airlines should be prohibited from flying over the region.", "Modern technology has allowed archaeologists to determine the exact purpose of every geoglyph."],
    correctAnswer: "A",
    explanation: "Lack of written records logically explains persistent uncertainty about purpose. ✓",
    explanations: { "A": "Lack of written records logically explains persistent uncertainty about purpose. ✓", "B": "Not supported by anything in the passage.", "C": "A policy recommendation, not a logical inference.", "D": `Contradicts 'haven’t reached consensus.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-39",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The Mediterranean diet has been extensively studied for cardiovascular benefits. Populations in Greece, Italy, and Spain following traditional patterns show lower rates of heart disease. _______, the diet’s benefits may extend beyond heart health: recent studies have linked Mediterranean eating to reduced rates of cognitive decline and Alzheimer’s disease.",
    options: ["Regardless", "Moreover", "Instead", "By comparison"],
    correctAnswer: "B",
    explanation: "Adds additional information: cardiovascular AND cognitive benefits. ✓",
    explanations: { "A": "Dismisses what came before, but the passage builds on it.", "B": "Adds additional information: cardiovascular AND cognitive benefits. ✓", "C": "Implies replacement — cognitive benefits don’t replace cardiovascular ones.", "D": "Would introduce a different subject being compared." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-40",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Marie Curie’s discovery of radium in 1898 earned her worldwide fame and two Nobel Prizes. _______, the same radioactive materials that made her research groundbreaking also caused the leukemia that ended her life in 1934 — a tragic irony that underscores the risks early radiation researchers unknowingly accepted.",
    options: ["For instance", "Similarly", "Ironically", "In addition"],
    correctAnswer: "C",
    explanation: "The same materials brought fame and death — a reversal. ✓",
    explanations: { "A": "Not an example of fame — it’s about consequences.", "B": "Suggests a parallel, but the outcome (death) contrasts with the achievement.", "C": "The same materials brought fame and death — a reversal. ✓", "D": "This is a reversal, not an addition." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-41",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Helsinki’s public library system consistently ranks among the world’s most innovative. Its flagship, Oodi, includes 3D printers, recording studios, and a cinema alongside books. _______, Helsinki’s system lends not only books but also tools, sports equipment, instruments, and sewing machines — redefining what a modern library can be.",
    options: ["Nevertheless", "In fact", "Previously", "Conversely"],
    correctAnswer: "B",
    explanation: `'In fact' intensifies — the lending program goes even further than the building’s amenities. ✓`,
    explanations: { "A": "Implies contrast, but lending reinforces the innovation description.", "B": `'In fact' intensifies — the lending program goes even further than the building’s amenities. ✓`, "C": "Would indicate this happened before, but it’s current.", "D": "Implies opposition, but both sentences describe innovation." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-42",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about fast fashion’s environmental impact and wants to emphasize the scale of the waste problem.",
    options: ["The fast fashion industry has grown rapidly since the 1990s, driven by companies like Zara and H&M.", "The global fashion industry produces approximately 92 million tons of textile waste annually — the equivalent of one garbage truck of clothing landfilled or burned every second.", "Some fashion brands have introduced recycling programs to address sustainability concerns.", "Cotton production requires approximately 2,700 liters of water per T-shirt."],
    correctAnswer: "B",
    explanation: "Specific tonnage plus vivid comparison conveys scale. ✓",
    explanations: { "A": "Industry growth, not waste scale.", "B": "Specific tonnage plus vivid comparison conveys scale. ✓", "C": "Recycling programs are solutions, not the problem’s scale.", "D": "Water usage, not waste." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-43",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is profiling mathematician Maryam Mirzakhani and wants to convey both her mathematical contributions and her historical significance.",
    options: ["Maryam Mirzakhani was born in Tehran, Iran, in 1977 and earned her PhD from Harvard.", "The Fields Medal is considered the most prestigious award in mathematics.", "In 2014, Maryam Mirzakhani became the first woman and first Iranian to win the Fields Medal, recognized for groundbreaking work on the geometry of curved surfaces — discoveries that transformed understanding of abstract shapes.", "Mirzakhani passed away in 2017 at the age of 40."],
    correctAnswer: "C",
    explanation: "Both goals: historical significance (first woman/Iranian) and contributions (geometry of curved surfaces). ✓",
    explanations: { "A": "Biographical facts alone don’t convey contributions or significance.", "B": "Describes the award, not Mirzakhani.", "C": "Both goals: historical significance (first woman/Iranian) and contributions (geometry of curved surfaces). ✓", "D": "Doesn’t address either goal." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-44",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing a policy brief on renewable energy and wants to counter the argument that renewables are too expensive.",
    options: ["The first commercial solar panel was produced in 1954 by Bell Laboratories.", "Fossil fuel companies continue to receive billions in government subsidies worldwide.", "According to IRENA, solar electricity costs have fallen 89% since 2010, and new solar and wind are now cheaper than new coal or gas plants in most markets.", "Renewable energy sources include solar, wind, hydroelectric, and geothermal."],
    correctAnswer: "C",
    explanation: `Directly counters 'too expensive' with dramatic cost declines and current competitiveness. ✓`,
    explanations: { "A": "Historical facts don’t counter a cost argument.", "B": "Relevant but doesn’t directly show renewables are competitive on price.", "C": `Directly counters 'too expensive' with dramatic cost declines and current competitiveness. ✓`, "D": "Listing types doesn’t address cost." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-45",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The Rosetta Stone, carved in 196 BCE, contains the same decree in three _______ Egyptian hieroglyphics, Demotic script, and ancient Greek. Its 1799 discovery gave scholars the key to deciphering hieroglyphics.",
    options: ["scripts,", "scripts:", "scripts—", "scripts;"],
    correctAnswer: "B",
    explanation: `A colon correctly introduces the list that explains 'three scripts.' ✓`,
    explanations: { "A": "A comma doesn’t properly introduce this specifying list.", "B": `A colon correctly introduces the list that explains 'three scripts.' ✓`, "C": "A dash could work informally, but a colon is standard for list introduction.", "D": "A semicolon joins independent clauses, not a noun and its list." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-46",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The committee reviewed applications from over two hundred _______ only twelve candidates were invited to interview for the fellowship.",
    options: ["candidates,", "candidates but", "candidates, but", "candidates;"],
    correctAnswer: "C",
    explanation: `Comma + 'but' correctly joins two contrasting independent clauses. ✓`,
    explanations: { "A": "Comma splice between two independent clauses.", "B": "Conjunction without preceding comma when joining lengthy independent clauses.", "C": `Comma + 'but' correctly joins two contrasting independent clauses. ✓`, "D": `Grammatically correct but misses the explicit contrast 'but' provides.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-47",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Although the experiment produced statistically significant _______ the researchers cautioned that the sample size was too small to draw definitive conclusions.",
    options: ["results;", "results", "results,", "results—"],
    correctAnswer: "C",
    explanation: "Comma correctly separates the introductory subordinate clause from the main clause. ✓",
    explanations: { "A": "Semicolon can’t follow a dependent clause to join it to the main clause.", "B": "No punctuation creates a run-on.", "C": "Comma correctly separates the introductory subordinate clause from the main clause. ✓", "D": "A dash interrupts the natural subordinate-to-main flow." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-48",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The museum’s collection of Impressionist paintings, which _______ more than 300 works by Monet, Renoir, and Degas, attracts over a million visitors annually.",
    options: ["include", "includes", "are including", "have included"],
    correctAnswer: "B",
    explanation: `'Includes' agrees with singular 'collection.' ✓`,
    explanations: { "A": `Subject is 'collection' (singular), not 'paintings.'`, "B": `'Includes' agrees with singular 'collection.' ✓`, "C": "Plural and wrong tense for a permanent state.", "D": "Plural and unnecessary tense shift." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-49",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The archaeological team, along with several graduate _______ planning to excavate the burial site next summer.",
    options: ["students, are", "students, is", "students are", "students is"],
    correctAnswer: "B",
    explanation: `Comma closes the parenthetical; 'is' agrees with singular 'team.' ✓`,
    explanations: { "A": `'Along with' is parenthetical and doesn’t make the subject plural. Subject is 'team.'`, "B": `Comma closes the parenthetical; 'is' agrees with singular 'team.' ✓`, "C": "Missing closing comma for the parenthetical.", "D": "Missing comma and confusing agreement." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-50",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Each of the candidates _______ required to submit a portfolio demonstrating proficiency in at least three programming languages.",
    options: ["are", "is", "were being", "have been"],
    correctAnswer: "B",
    explanation: `'Each' is always singular regardless of the prepositional phrase. ✓`,
    explanations: { "A": `'Each' is singular; 'are' is plural.`, "B": `'Each' is always singular regardless of the prepositional phrase. ✓`, "C": "Plural and shifts to past progressive.", "D": `Plural, disagreeing with 'each.'` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-51",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Having _______ the summit after a grueling twelve-hour ascent, the mountaineers paused to photograph the panoramic view.",
    options: ["reaching", "reached", "been reaching", "to reach"],
    correctAnswer: "B",
    explanation: `'Having reached' — past participle with 'having' forms the correct perfect participial phrase. ✓`,
    explanations: { "A": `'Having reaching' is ungrammatical.`, "B": `'Having reached' — past participle with 'having' forms the correct perfect participial phrase. ✓`, "C": "Unnecessarily complex, implies ongoing rather than completed action.", "D": "Changes meaning to obligation." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-52",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The novelist, who spent a decade researching the historical period in _______ the story is set, drew extensively on letters, diaries, and court records.",
    options: ["that", "where", "when", "which"],
    correctAnswer: "D",
    explanation: `'In which' is the correct prepositional relative pronoun. ✓`,
    explanations: { "A": `'In that' is not standard for formal relative clauses about a period.`, "B": `'In where' is redundant — 'where' already implies 'in which.'`, "C": `'In when' is grammatically incorrect.`, "D": `'In which' is the correct prepositional relative pronoun. ✓` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-53",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The city council voted to allocate additional funding for public transportation, a decision that _______ to reduce congestion and improve air quality.",
    options: ["are expected", "is expected", "expecting", "were expected"],
    correctAnswer: "B",
    explanation: `'Is expected' agrees with singular 'decision.' ✓`,
    explanations: { "A": `Subject is 'decision' (singular), not 'city council.'`, "B": `'Is expected' agrees with singular 'decision.' ✓`, "C": "Creates a fragment.", "D": "Shifts to past tense unnecessarily." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-rw-54",
    testType: "sat",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The researchers found that participants who _______ the meditation program for eight consecutive weeks showed measurable improvements in attention span compared to the control group.",
    options: ["complete", "completing", "completed", "had been complete"],
    correctAnswer: "C",
    explanation: `'Completed' matches the past tense of the narrative. ✓`,
    explanations: { "A": `Present tense, inconsistent with past-tense 'found' and 'showed.'`, "B": "Participle, not a finite verb — creates a fragment.", "C": `'Completed' matches the past tense of the narrative. ✓`, "D": `Wrong form — 'complete' is an adjective here, not a verb.` },
    tags: ["diagnostic"],
  }
];
