import type { Question } from "@/types/question";

export const RW_QUESTIONS: Question[] = [
  {
    id: "pt-nmsqt-rw-1",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The historian’s account of the revolution was notably _______, presenting events from the perspectives of both the ruling class and the insurgents rather than favoring either side.",
    options: ["partisan", "dispassionate", "incomplete", "sensationalized"],
    correctAnswer: "B",
    explanation: `'Dispassionate' means unbiased and objective — matches presenting both sides. ✓`,
    explanations: { "A": `'Partisan' means biased — contradicts presenting both perspectives.`, "B": `'Dispassionate' means unbiased and objective — matches presenting both sides. ✓`, "C": "Presenting both sides makes it more complete, not incomplete.", "D": `'Sensationalized' means exaggerated for effect, not suggested by the balanced approach.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-2",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The composer’s final symphony was a marked _______ from her earlier minimalist works, incorporating dense orchestration, rapid tempo changes, and layered counterpoint that surprised critics who had expected consistency.",
    options: ["continuation", "departure", "imitation", "simplification"],
    correctAnswer: "B",
    explanation: `'Departure' means a break from previous style — minimalist to dense orchestration. ✓`,
    explanations: { "A": "Dense orchestration contrasts with minimalism — not a continuation.", "B": `'Departure' means a break from previous style — minimalist to dense orchestration. ✓`, "C": "She’s not imitating others; she’s changing her own style.", "D": "Dense orchestration is more complex, not simpler." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-3",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The software company released a _______ update to its operating system, fixing only a handful of minor bugs rather than introducing the major interface overhaul users had anticipated.",
    options: ["revolutionary", "comprehensive", "modest", "delayed"],
    correctAnswer: "C",
    explanation: `'Modest' means small in scale — a few minor fixes vs. a major overhaul. ✓`,
    explanations: { "A": "A few bug fixes is the opposite of revolutionary.", "B": "Comprehensive implies thoroughness, but only minor bugs were fixed.", "C": `'Modest' means small in scale — a few minor fixes vs. a major overhaul. ✓`, "D": "Timing isn’t the issue; scope is." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-4",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The new policy was intended to _______ tensions between the two departments, but its ambiguous language only created more confusion about responsibilities and reporting structures.",
    options: ["intensify", "document", "alleviate", "publicize"],
    correctAnswer: "C",
    explanation: `'Alleviate' means reduce — intended to reduce tensions but failed. ✓`,
    explanations: { "A": "If intended to help, not intensify.", "B": `Documenting tensions doesn’t fit 'but created more confusion.'`, "C": `'Alleviate' means reduce — intended to reduce tensions but failed. ✓`, "D": "Publicizing tensions doesn’t connect to the resulting confusion." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-5",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The archaeologist’s theory about the site’s original purpose remained _______, supported by circumstantial evidence but lacking the definitive proof that would convince skeptics in the field.",
    options: ["debunked", "verified", "speculative", "irrelevant"],
    correctAnswer: "C",
    explanation: `'Speculative' means based on incomplete evidence — circumstantial support without proof. ✓`,
    explanations: { "A": `'Debunked' means disproven, but it’s supported by some evidence.`, "B": `'Verified' means confirmed, but it lacks definitive proof.`, "C": `'Speculative' means based on incomplete evidence — circumstantial support without proof. ✓`, "D": `'Irrelevant' would mean no one cares about it.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-6",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the main purpose of the text?",
    passage: "The Venus flytrap is often portrayed as an aggressive predator, snapping shut on any insect that lands on its leaves. In reality, the plant’s trigger mechanism is remarkably selective: two of its sensory hairs must be touched within 20 seconds of each other to activate the trap, a safeguard that prevents the plant from wasting energy on raindrops, debris, or prey too small to provide meaningful nutrition.",
    options: ["To argue that Venus flytraps should be protected as an endangered species.", "To correct a common misconception about how Venus flytraps capture prey.", "To explain how to grow Venus flytraps at home.", "To compare Venus flytraps with other carnivorous plants."],
    correctAnswer: "B",
    explanation: `Opens with misconception ('aggressive... any insect'), then corrects it with the selective mechanism. ✓`,
    explanations: { "A": "Conservation isn’t mentioned.", "B": `Opens with misconception ('aggressive... any insect'), then corrects it with the selective mechanism. ✓`, "C": "No growing instructions.", "D": "No other plants are discussed." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-7",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Cross-Text Connections",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Based on the texts, how would Jackson most likely respond to Duckworth’s emphasis on grit?",
    passage: `<strong>Text 1</strong><br>Psychologist Angela Duckworth argues that 'grit' — sustained passion and perseverance toward long-term goals — is a stronger predictor of success than talent or IQ. Her research shows that grittier students earn higher grades and are more likely to graduate.<br><br><strong>Text 2</strong><br>Sociologist Michelle Jackson questions whether grit can be separated from the socioeconomic conditions that shape it. Children in stable, well-resourced environments, Jackson notes, find it far easier to develop perseverance than children dealing with food insecurity, housing instability, or family trauma. Praising grit, she argues, risks blaming individuals for structural disadvantages.`,
    options: ["She would argue that grit has no correlation with academic outcomes.", "She would contend that grit itself may be a product of privilege, making it an inadequate explanation for unequal outcomes.", "She would agree that grit matters but suggest it should be taught in schools.", "She would dismiss psychology as irrelevant to education research."],
    correctAnswer: "B",
    explanation: "Jackson argues grit depends on socioeconomic stability — it’s shaped by privilege, not purely individual. ✓",
    explanations: { "A": "Jackson doesn’t deny grit correlates; she questions its origin.", "B": "Jackson argues grit depends on socioeconomic stability — it’s shaped by privilege, not purely individual. ✓", "C": "Jackson’s concern is structural, not pedagogical.", "D": "She engages with the research, not dismisses the field." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-8",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Cross-Text Connections",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "On which point do Gehl and Cervero most clearly disagree?",
    passage: "<strong>Text 1</strong><br>Urban planner Jan Gehl advocates for pedestrian-centered city design, arguing that wider sidewalks, public plazas, and reduced car traffic improve quality of life, encourage social interaction, and reduce pollution.<br><br><strong>Text 2</strong><br>Transportation engineer Robert Cervero acknowledges the appeal of pedestrian zones but warns that restricting vehicle access in cities designed around cars can devastate local businesses. Without adequate public transit alternatives, he argues, pushing cars out simply pushes customers to suburban malls with free parking.",
    options: ["Whether pollution is a problem in cities.", "Whether reducing car access in cities reliably produces positive outcomes.", "Whether public plazas are aesthetically appealing.", "Whether suburban malls should be prohibited."],
    correctAnswer: "B",
    explanation: "Gehl says reducing cars improves quality of life; Cervero says it can devastate businesses without transit alternatives. ✓",
    explanations: { "A": "Cervero doesn’t discuss pollution.", "B": "Gehl says reducing cars improves quality of life; Cervero says it can devastate businesses without transit alternatives. ✓", "C": "Aesthetics aren’t debated.", "D": "Mall prohibition isn’t mentioned." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-9",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best states the main idea of the text?",
    passage: "The axolotl, a salamander native to lakes near Mexico City, possesses an extraordinary ability that has captivated scientists: it can regenerate entire limbs, portions of its heart, and even sections of its brain with virtually no scarring. Unlike most animals, which form scar tissue after injury, the axolotl’s cells revert to a stem-cell-like state and rebuild the damaged structure from scratch. Researchers hope that understanding this process could eventually lead to breakthroughs in human regenerative medicine.",
    options: ["The axolotl is an endangered species that needs conservation.", "The axolotl’s remarkable regenerative abilities make it a valuable subject for medical research.", "Scientists have already developed human treatments based on axolotl biology.", "All salamanders can regenerate lost body parts."],
    correctAnswer: "B",
    explanation: "Regeneration + captivated scientists + potential medical breakthroughs = main idea. ✓",
    explanations: { "A": "Endangered status isn’t discussed.", "B": "Regeneration + captivated scientists + potential medical breakthroughs = main idea. ✓", "C": `'Could eventually lead to' means treatments haven’t been developed yet.`, "D": "The text specifies the axolotl, not all salamanders." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-10",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "According to the text, what challenged the universal grammar hypothesis?",
    passage: "For decades, linguists assumed that all human languages share a universal grammar — a set of structural rules hardwired into the brain. Recent fieldwork in the Amazon and Papua New Guinea, however, has documented languages that lack features once considered universal, such as recursion (embedding one clause inside another). These findings have reignited debate about whether language is primarily a biological endowment or a cultural invention shaped by environment and social need.",
    options: ["Advances in brain imaging technology.", "The discovery of languages lacking features previously thought to be universal.", "The publication of Noam Chomsky’s linguistic theories.", "Evidence that children learn language at different rates."],
    correctAnswer: "B",
    explanation: "Languages in the Amazon/Papua New Guinea lacked recursion, a supposedly universal feature. ✓",
    explanations: { "A": "Brain imaging isn’t mentioned.", "B": "Languages in the Amazon/Papua New Guinea lacked recursion, a supposedly universal feature. ✓", "C": "Chomsky isn’t mentioned, and his work supports universal grammar.", "D": "Learning rates aren’t discussed." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-11",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly support Earle’s claim about the climate importance of deep-sea ecosystems?",
    passage: `Marine biologist Sylvia Earle argues that deep ocean ecosystems, despite being largely unexplored, are critical to global climate regulation. She points out that deep-sea organisms play a key role in the 'biological carbon pump,' transporting carbon from surface waters to the ocean floor where it remains sequestered for centuries.`,
    options: ["Deep-sea fish species have adapted to survive extreme pressure.", "A study found that disrupting deep-sea ecosystems reduced carbon sequestration rates by 40%, causing measurably higher atmospheric CO₂ concentrations in affected regions.", "The Mariana Trench is the deepest point in the ocean.", "Some deep-sea creatures are bioluminescent."],
    correctAnswer: "B",
    explanation: "Disrupting ecosystems → less carbon sequestration → more CO₂. Directly connects deep-sea health to climate. ✓",
    explanations: { "A": "Adaptation to pressure is about survival, not climate regulation.", "B": "Disrupting ecosystems → less carbon sequestration → more CO₂. Directly connects deep-sea health to climate. ✓", "C": "Depth fact, not about climate role.", "D": "Bioluminescence is unrelated to carbon cycling." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-12",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the type of argument Zinn makes?",
    passage: "Historian Howard Zinn argued that traditional American history textbooks present a misleadingly positive narrative by focusing on the perspectives of political leaders and wealthy elites while marginalizing the experiences of ordinary people, laborers, and minority groups.",
    options: ["A statistical analysis comparing textbook sales figures.", "A critique of whose perspectives are included in and excluded from mainstream historical narratives.", "A personal memoir about his experience as a student.", "A proposal for new government regulations on textbook publishers."],
    correctAnswer: "B",
    explanation: "Zinn’s argument is about inclusion and exclusion of perspectives in how history is told. ✓",
    explanations: { "A": "No statistics or sales data mentioned.", "B": "Zinn’s argument is about inclusion and exclusion of perspectives in how history is told. ✓", "C": "No personal memoir is referenced.", "D": "No regulatory proposals are made." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-13",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to support the claim that the four-day week improved employee wellbeing?",
    passage: "Researchers surveyed employees about workplace satisfaction before and after their company adopted a four-day work week.",
    options: ["Before the change, 45% of employees reported high stress.", `After adopting the four-day week, the percentage of employees reporting high stress dropped from 45% to 18%, while those rating their work-life balance as 'good' or 'excellent' rose from 38% to 71%, suggesting broad wellbeing improvements across multiple dimensions.`, "The company adopted the four-day week in January.", "Some employees preferred the traditional five-day schedule."],
    correctAnswer: "B",
    explanation: "Two metrics improving (stress: 45%→18%, work-life: 38%→71%) = multi-dimensional wellbeing improvement. ✓",
    explanations: { "A": "Single pre-change data point.", "B": "Two metrics improving (stress: 45%→18%, work-life: 38%→71%) = multi-dimensional wellbeing improvement. ✓", "C": "Timing, not outcomes.", "D": "Doesn’t use data to support the claim." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-14",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to describe the impact of infrastructure on cycling?",
    passage: "A city tracked bicycle commuting rates after installing protected bike lanes on major routes.",
    options: ["The downtown corridor had the highest cycling rate after installation.", "All three corridors with new protected lanes saw cycling rates at least double, with the university route experiencing a 180% increase, suggesting that dedicated infrastructure is a primary driver of cycling adoption rather than proximity to destinations alone.", "Protected bike lanes are painted green.", "Cycling rates were measured in peak-hour counts."],
    correctAnswer: "B",
    explanation: "Three corridors all doubled+ (especially 180% on university route), connecting infrastructure to adoption. ✓",
    explanations: { "A": "Single point, no comparison.", "B": "Three corridors all doubled+ (especially 180% on university route), connecting infrastructure to adoption. ✓", "C": "Lane color, not usage data.", "D": "Methodology, not findings." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-15",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "Psychologists studying nostalgia have found that, contrary to earlier assumptions that it was a form of unhealthy dwelling on the past, nostalgic reflection actually boosts mood, increases feelings of social connectedness, and enhances self-continuity — the sense that one’s identity is coherent across time. ________",
    options: ["Therefore, people should avoid thinking about the past entirely.", "These findings suggest that nostalgia may serve an important psychological function, helping individuals maintain emotional resilience and a stable sense of self.", "This proves that all forms of dwelling on the past are beneficial.", "Scientists have therefore stopped studying nostalgia."],
    correctAnswer: "B",
    explanation: "Mood boost + social connection + self-continuity = psychological function for resilience and identity. ✓",
    explanations: { "A": "The findings show nostalgia is positive, not that the past should be avoided.", "B": "Mood boost + social connection + self-continuity = psychological function for resilience and identity. ✓", "C": `'All forms' overgeneralizes; the study addresses nostalgia specifically.`, "D": "The findings would stimulate more research, not end it." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-16",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The Great Barrier Reef is often described as a single, continuous structure. _______, it is actually composed of nearly 3,000 individual reef systems and hundreds of islands stretching over 2,300 kilometers.",
    options: ["Similarly", "In fact", "As a result", "For example"],
    correctAnswer: "B",
    explanation: `'In fact' introduces a surprising clarification that corrects the common description. ✓`,
    explanations: { "A": "The second sentence corrects, not parallels.", "B": `'In fact' introduces a surprising clarification that corrects the common description. ✓`, "C": "The composition isn’t a result of the description.", "D": "The composition isn’t an example of being a single structure." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-17",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Early GPS systems could determine a user’s location to within about 10 meters. _______, modern systems enhanced with ground-based correction stations can achieve accuracy within a few centimeters, enabling applications from autonomous farming to millimeter-precise surveying.",
    options: ["Nevertheless", "In contrast", "Likewise", "By comparison"],
    correctAnswer: "D",
    explanation: `'By comparison' frames the modern systems alongside the earlier ones, highlighting the advancement. ✓`,
    explanations: { "A": "No obstacle is being overcome.", "B": `'In contrast' emphasizes opposition; this is a comparison showing improvement.`, "C": "The modern system is better, not similar.", "D": `'By comparison' frames the modern systems alongside the earlier ones, highlighting the advancement. ✓` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-18",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The novelist spent seven years researching the historical period before beginning to write. _______, the resulting book was praised for its extraordinary attention to period-accurate details, from the dialect spoken by characters to the specific foods available in 1840s Mississippi.",
    options: ["Nevertheless", "Otherwise", "Accordingly", "Instead"],
    correctAnswer: "C",
    explanation: `'Accordingly' means 'as a natural result' — research led to praised accuracy. ✓`,
    explanations: { "A": "The praise follows logically from the research; no contrast.", "B": `'Otherwise' implies an alternative scenario.`, "C": `'Accordingly' means 'as a natural result' — research led to praised accuracy. ✓`, "D": "No replacement is described." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-19",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about urban beekeeping and wants to address common safety concerns.",
    options: ["Urban beekeeping has grown 300% in the past decade.", "Bees produce honey through a process of nectar collection and evaporation.", "Despite fears about stings, urban honeybees are docile and rarely aggressive toward humans; studies in cities with active beekeeping programs report no increase in sting-related hospital visits, while pollination of nearby gardens improves crop yields by an average of 20%.", "Beekeepers must register their hives in most U.S. cities."],
    correctAnswer: "C",
    explanation: "Addresses sting fears directly (docile bees + no hospital increase) and adds a benefit (crop yields). ✓",
    explanations: { "A": "Growth trend, not safety.", "B": "Honey production process, not safety.", "C": "Addresses sting fears directly (docile bees + no hospital increase) and adds a benefit (crop yields). ✓", "D": "Regulation, not safety data." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-20",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the Dead Sea and wants to explain why its salinity is so extreme.",
    options: ["The Dead Sea is located between Israel and Jordan.", "Tourists visit the Dead Sea to float in its waters.", "The Dead Sea’s extreme salinity — nearly ten times that of the ocean — results from its position as a terminal lake with no outlet: water flows in from the Jordan River but can only leave through evaporation, concentrating dissolved minerals over thousands of years.", "The Dead Sea has been shrinking due to water diversion from the Jordan River."],
    correctAnswer: "C",
    explanation: "Terminal lake + no outlet + evaporation only + mineral concentration = full causal chain. ✓",
    explanations: { "A": "Geography, not explanation of salinity.", "B": "Tourism, not causation.", "C": "Terminal lake + no outlet + evaporation only + mineral concentration = full causal chain. ✓", "D": "Shrinkage is a separate issue." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-21",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the discovery of penicillin and wants to emphasize the role of chance.",
    options: ["Penicillin is an antibiotic that kills bacteria.", "Alexander Fleming discovered penicillin in 1928.", "Fleming’s discovery of penicillin began with an accident: returning from vacation, he noticed that a mold colony on a contaminated petri dish had killed the surrounding bacteria — a chance observation that, had he discarded the dish as planned, might never have launched the antibiotic revolution.", "Penicillin saved millions of lives during World War II."],
    correctAnswer: "C",
    explanation: "Accident + contaminated dish + almost discarded = chance was central. ✓",
    explanations: { "A": "Definition, not the story of chance.", "B": "Date without the chance element.", "C": "Accident + contaminated dish + almost discarded = chance was central. ✓", "D": "Impact, not the role of chance." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-22",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The architect designed three distinct _______ a library, a community center, and a museum, each reflecting a different aspect of the city’s cultural heritage.",
    options: ["structures", "structures;", "structures:", "structures,"],
    correctAnswer: "C",
    explanation: "Colon correctly introduces the enumerated list. ✓",
    explanations: { "A": "No punctuation before a list.", "B": "Semicolon doesn’t introduce lists.", "C": "Colon correctly introduces the enumerated list. ✓", "D": "Comma is too weak before a list with commas inside it." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-23",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Although the volcano had been dormant for over 600 _______ seismologists detected a sudden increase in underground tremors that suggested magma was moving toward the surface.",
    options: ["years;", "years", "years,", "years."],
    correctAnswer: "C",
    explanation: `Comma correctly follows the introductory 'Although' clause. ✓`,
    explanations: { "A": "Semicolon can’t follow a subordinate clause.", "B": `No punctuation between the 'Although' clause and main clause.`, "C": `Comma correctly follows the introductory 'Although' clause. ✓`, "D": "Period creates a fragment." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-24",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The cellist’s performance was technically _______ every note was precise, every tempo change seamless, and every dynamic shift perfectly controlled.",
    options: ["flawless;", "flawless,", "flawless", "flawless."],
    correctAnswer: "A",
    explanation: "Semicolon correctly joins two related independent clauses. ✓",
    explanations: { "A": "Semicolon correctly joins two related independent clauses. ✓", "B": "Comma splice between independent clauses.", "C": "Run-on sentence.", "D": "Could work but unnecessarily separates the closely connected idea." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-25",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The anthology of essays, which _______ perspectives from scholars across five continents, was praised for its inclusivity and breadth.",
    options: ["include", "includes", "are including", "have included"],
    correctAnswer: "B",
    explanation: `'Anthology' is singular; 'includes' agrees. ✓`,
    explanations: { "A": `Subject is 'anthology' (singular); 'include' is plural.`, "B": `'Anthology' is singular; 'includes' agrees. ✓`, "C": `'Are including' is plural progressive.`, "D": `'Have included' is plural present perfect.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-26",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "By the time the rescue team _______ the site, survivors had already been waiting for over 18 hours in deteriorating conditions.",
    options: ["will reach", "reaches", "reached", "had reached"],
    correctAnswer: "C",
    explanation: `Simple past 'reached' pairs with past perfect 'had been waiting.' ✓`,
    explanations: { "A": "Future tense contradicts past narrative.", "B": "Present tense doesn’t match.", "C": `Simple past 'reached' pairs with past perfect 'had been waiting.' ✓`, "D": "Both past perfect is incorrect." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-27",
    testType: "nmsqt",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The documentary, directed by a filmmaker _______ previous work had focused exclusively on wildlife, surprised audiences with its unflinching examination of urban poverty.",
    options: ["who’s", "whose", "whom", "which"],
    correctAnswer: "B",
    explanation: `'Whose' shows possession of 'previous work.' ✓`,
    explanations: { "A": `'Who’s'='who is' — doesn’t fit before 'previous work.'`, "B": `'Whose' shows possession of 'previous work.' ✓`, "C": "Object pronoun, not possessive.", "D": `'Which' doesn’t show possession.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-28",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The journalist’s reporting was characterized by its _______ attention to detail; she verified every claim through multiple independent sources and never published a story until she was certain of its accuracy.",
    options: ["scrupulous", "superficial", "sporadic", "reluctant"],
    correctAnswer: "A",
    explanation: `'Scrupulous' means extremely careful and thorough — matches verifying through multiple sources. ✓`,
    explanations: { "A": `'Scrupulous' means extremely careful and thorough — matches verifying through multiple sources. ✓`, "B": `'Superficial' means shallow, the opposite.`, "C": `'Sporadic' means irregular, not about care level.`, "D": `'Reluctant' means unwilling.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-29",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The governor’s proposed budget cuts provoked a _______ response from educators, who flooded the statehouse with calls, organized rallies, and threatened a statewide walkout if funding was reduced.",
    options: ["tepid", "measured", "vehement", "ambiguous"],
    correctAnswer: "C",
    explanation: `'Vehement' means showing strong feeling — matches the intense reaction. ✓`,
    explanations: { "A": `'Tepid' means lukewarm; calls, rallies, and walkout threats are intense.`, "B": `'Measured' means restrained; the response was forceful.`, "C": `'Vehement' means showing strong feeling — matches the intense reaction. ✓`, "D": `'Ambiguous' means unclear, but the response was decisively opposed.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-30",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The study’s findings were _______ by the scientific community, with multiple research groups publishing results that confirmed the original conclusions using different methodologies and populations.",
    options: ["challenged", "corroborated", "retracted", "overlooked"],
    correctAnswer: "B",
    explanation: `'Corroborated' means confirmed by independent evidence — different methods reaching same conclusions. ✓`,
    explanations: { "A": "Other groups confirmed, not challenged.", "B": `'Corroborated' means confirmed by independent evidence — different methods reaching same conclusions. ✓`, "C": `'Retracted' means withdrawn; the findings were supported.`, "D": `'Overlooked' means ignored; they received attention.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-31",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The artist’s early paintings were _______ renderings of landscapes — precise, photographic reproductions that showcased technical skill but, critics argued, lacked emotional depth or personal vision.",
    options: ["abstract", "faithful", "provocative", "whimsical"],
    correctAnswer: "B",
    explanation: `'Faithful' means accurately representing reality — photographic, precise. ✓`,
    explanations: { "A": `'Abstract' contradicts 'precise, photographic reproductions.'`, "B": `'Faithful' means accurately representing reality — photographic, precise. ✓`, "C": `'Provocative' means stimulating controversy, not suggested.`, "D": `'Whimsical' means playfully quaint, contradicting precise reproductions.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-32",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The committee’s report attempted to _______ the conflicting data by proposing a framework that explained how both sets of results could be accurate under different experimental conditions.",
    options: ["dismiss", "fabricate", "reconcile", "exaggerate"],
    correctAnswer: "C",
    explanation: `'Reconcile' means make compatible — explaining how conflicting data are both accurate. ✓`,
    explanations: { "A": "The report doesn’t dismiss data; it explains both sets.", "B": `'Fabricate' means make up, not relevant.`, "C": `'Reconcile' means make compatible — explaining how conflicting data are both accurate. ✓`, "D": `'Exaggerate' means overstate.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-33",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best describes the structure of the text?",
    passage: "Traditional economic models assume that people make rational decisions by weighing costs and benefits. Behavioral economist Richard Thaler demonstrated that this assumption fails to account for predictable irrationalities: people overvalue items they already own (the endowment effect), are disproportionately influenced by how choices are presented (framing effects), and consistently choose immediate small rewards over larger delayed ones (hyperbolic discounting).",
    options: ["It presents a traditional assumption and then provides evidence of systematic exceptions.", "It compares two competing economic theories.", "It argues that economic models should be abandoned entirely.", "It describes how Richard Thaler became an economist."],
    correctAnswer: "A",
    explanation: "Rational assumption → three named exceptions (endowment, framing, discounting). ✓",
    explanations: { "A": "Rational assumption → three named exceptions (endowment, framing, discounting). ✓", "B": "Only one alternative perspective is presented.", "C": "No call to abandon models.", "D": "No biographical information." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-34",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly support Wilson’s biophilia hypothesis?",
    passage: `Ecologist E.O. Wilson proposed that humans have an innate affiliation with other living organisms, a concept he called 'biophilia.' Wilson argued that this instinct developed because our ancestors who paid close attention to other species — whether as predators, prey, or food sources — had survival advantages.`,
    options: ["City parks are more expensive to maintain than parking lots.", "Studies show that hospital patients with windows facing greenery recover 20% faster than those facing brick walls, and infants as young as six months preferentially orient toward images of living things over inanimate objects.", "Some people are afraid of spiders.", "National parks receive millions of visitors annually."],
    correctAnswer: "B",
    explanation: "Faster recovery near nature + infant preference for living things = innate connection to other organisms. ✓",
    explanations: { "A": "Cost comparison, not evidence of innate affiliation.", "B": "Faster recovery near nature + infant preference for living things = innate connection to other organisms. ✓", "C": "Fear of spiders might relate but doesn’t demonstrate positive affiliation.", "D": "Park visits could be cultural, not innate." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-35",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly weaken Dweck’s claim?",
    passage: `Education researcher Carol Dweck argues that students with a 'growth mindset' — who believe ability can be developed through effort — outperform those with a 'fixed mindset,' who believe ability is innate and unchangeable.`,
    options: ["A meta-analysis of 40 studies found that mindset interventions had no statistically significant effect on academic performance, and that the correlation between self-reported mindset and achievement disappeared once socioeconomic factors were controlled.", "Some students enjoy school more than others.", "Dweck’s research has been widely cited.", "Teachers believe effort is important for student success."],
    correctAnswer: "A",
    explanation: "No effect from interventions + correlation disappears with SES controls = mindset may not cause performance differences. ✓",
    explanations: { "A": "No effect from interventions + correlation disappears with SES controls = mindset may not cause performance differences. ✓", "B": "Enjoyment is different from mindset effects on performance.", "C": "Citation frequency doesn’t address validity.", "D": "Teacher beliefs don’t test the student mindset claim." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-36",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to argue for passive solar design?",
    passage: "A research team compared energy efficiency of different building designs in the same climate zone.",
    options: ["Conventional buildings used 120 kWh/m²/year.", "Passive solar buildings consumed only 45 kWh/m²/year compared to 120 kWh/m²/year for conventional designs — a 62.5% reduction — while adding only 8% to construction costs, making them the most cost-effective efficiency strategy studied.", "Green roofs reduce energy use by some amount.", "All buildings require some energy."],
    correctAnswer: "B",
    explanation: "Quantifies energy savings (62.5%), notes modest cost increase (8%), and frames as most cost-effective. ✓",
    explanations: { "A": "Single data point.", "B": "Quantifies energy savings (62.5%), notes modest cost increase (8%), and frames as most cost-effective. ✓", "C": "Green roofs are separate from passive solar.", "D": "Trivially true." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-37",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "Researchers studying the placebo effect have found that it operates through measurable biological mechanisms: placebo painkillers trigger the release of endorphins, placebo anti-anxiety medications activate GABA receptors, and even placebo surgeries can produce genuine tissue healing. Perhaps most surprisingly, studies show that placebos retain their effectiveness even when patients are told they are receiving a placebo. ________",
    options: ["These findings suggest that the placebo effect is simply patients imagining they feel better.", "This body of evidence challenges the assumption that a treatment must contain an active ingredient to produce real physiological effects, pointing to the brain’s own healing mechanisms as a legitimate therapeutic pathway.", "Therefore, doctors should never prescribe real medications.", "The placebo effect only works for pain, not other conditions."],
    correctAnswer: "B",
    explanation: "Real biology from inactive substances challenges the active-ingredient assumption; brain’s own mechanisms. ✓",
    explanations: { "A": "Measurable biological mechanisms (endorphins, GABA, tissue healing) prove it’s not imaginary.", "B": "Real biology from inactive substances challenges the active-ingredient assumption; brain’s own mechanisms. ✓", "C": "Extreme conclusion not supported.", "D": "The passage shows effects across pain, anxiety, and surgery." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-38",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "The medieval Islamic world developed sophisticated hospitals (bimaristans) centuries before comparable institutions existed in Europe. These facilities separated patients by condition, maintained medical records, employed trained physicians, and even included gardens for convalescent patients. ________",
    options: ["The existence of these advanced medical institutions challenges Eurocentric narratives that position Western Europe as the sole cradle of institutional healthcare innovation.", "Medieval Europeans had no knowledge of medicine.", "Gardens are known to be therapeutic.", "All modern hospitals are based directly on bimaristan designs."],
    correctAnswer: "A",
    explanation: "Sophisticated non-European hospitals centuries earlier challenges the narrative of European-only innovation. ✓",
    explanations: { "A": "Sophisticated non-European hospitals centuries earlier challenges the narrative of European-only innovation. ✓", "B": `Too absolute — the passage says 'before comparable institutions,' not no knowledge at all.`, "C": "True but too narrow for a conclusion.", "D": `'All directly based on' is unsupported.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-39",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The city’s new congestion pricing program was designed to reduce traffic by charging drivers a fee to enter the downtown core during peak hours. Early data showed a 15% reduction in vehicle traffic. _______, transit ridership did not increase proportionally, suggesting that many former drivers were working from home or shifting their schedules rather than switching to public transportation.",
    options: ["Predictably", "However", "Therefore", "Similarly"],
    correctAnswer: "B",
    explanation: "Traffic dropped, but transit didn’t rise as expected — a contrast. ✓",
    explanations: { "A": "The transit ridership pattern was unexpected, not predicted.", "B": "Traffic dropped, but transit didn’t rise as expected — a contrast. ✓", "C": "Transit not rising isn’t a result of traffic dropping in a causal sense.", "D": "The patterns are different, not similar." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-40",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: `The philosopher argued that consciousness cannot be reduced to brain activity, pointing to the persistent 'explanatory gap' between subjective experience and neural processes. _______, neuroscientist Giulio Tononi has proposed Integrated Information Theory, which attempts to bridge precisely this gap by quantifying consciousness as a measurable property of complex systems.`,
    options: ["Confirming this view", "Challenging this position", "Ignoring this debate", "Regardless of these claims"],
    correctAnswer: "B",
    explanation: `A theory attempting to bridge the 'unbridgeable' gap directly challenges the philosopher’s argument. ✓`,
    explanations: { "A": "Tononi attempts to solve the gap the philosopher says can’t be solved — that’s a challenge.", "B": `A theory attempting to bridge the 'unbridgeable' gap directly challenges the philosopher’s argument. ✓`, "C": "Tononi engages directly with the gap.", "D": "His theory directly addresses the claims." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-41",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Blue-footed boobies perform elaborate courtship dances in which males lift their vivid blue feet one at a time in an exaggerated stepping motion. The brightness of the feet signals nutritional health and immune function. _______, females consistently prefer males with the most intensely colored feet, effectively selecting for genetic fitness through a visible proxy.",
    options: ["Despite this", "Consequently", "In contrast", "Alternatively"],
    correctAnswer: "B",
    explanation: "Because bright feet signal health, females prefer bright-footed males — cause and effect. ✓",
    explanations: { "A": "Female preference logically follows from the signal, no contrast.", "B": "Because bright feet signal health, females prefer bright-footed males — cause and effect. ✓", "C": "No contrast between the signal and the preference.", "D": "No alternative is presented." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-42",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the decline of monarch butterfly populations and wants to present a call to action.",
    options: ["Monarch butterflies migrate up to 3,000 miles annually.", "Monarchs are orange and black with white spots.", "With monarch populations declining 80% over two decades due primarily to herbicide-driven loss of milkweed — the only plant on which monarchs lay eggs — homeowners can make a meaningful difference by planting native milkweed varieties, creating stepping-stone habitats along the butterflies’ migration route.", "The monarch butterfly is the state insect of several U.S. states."],
    correctAnswer: "C",
    explanation: "Problem (80% decline + milkweed loss) + solution (plant milkweed) = call to action. ✓",
    explanations: { "A": "Migration fact, not call to action.", "B": "Description, not action.", "C": "Problem (80% decline + milkweed loss) + solution (plant milkweed) = call to action. ✓", "D": "State insect status, not action." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-43",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the Voyager 1 spacecraft and wants to emphasize its historic distance from Earth.",
    options: ["Voyager 1 was launched in 1977.", "Now more than 15 billion miles from Earth — so far that its radio signals, traveling at the speed of light, take over 22 hours to reach us — Voyager 1 remains the most distant human-made object in existence, still transmitting data from beyond the boundary of our solar system.", "Voyager 1 carries a golden record with sounds and images from Earth.", "NASA has launched many space probes over the decades."],
    correctAnswer: "B",
    explanation: "15 billion miles + 22-hour signal delay + most distant object + beyond solar system = multiple distance dimensions. ✓",
    explanations: { "A": "Launch year, not distance emphasis.", "B": "15 billion miles + 22-hour signal delay + most distant object + beyond solar system = multiple distance dimensions. ✓", "C": "The golden record is cultural, not about distance.", "D": "Too general." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-44",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the history of vaccination and wants to explain why herd immunity matters.",
    options: ["Edward Jenner developed the first vaccine in 1796.", "When a sufficient percentage of a population is vaccinated — typically 85–95% depending on the disease — the pathogen cannot find enough susceptible hosts to sustain transmission, indirectly protecting individuals who cannot be vaccinated due to age, allergies, or compromised immune systems.", "Vaccines contain weakened or inactive forms of pathogens.", "Some people choose not to vaccinate for personal reasons."],
    correctAnswer: "B",
    explanation: "Threshold (85–95%) + mechanism (can’t find hosts) + beneficiaries (can’t be vaccinated) = complete explanation. ✓",
    explanations: { "A": "History, not herd immunity mechanism.", "B": "Threshold (85–95%) + mechanism (can’t find hosts) + beneficiaries (can’t be vaccinated) = complete explanation. ✓", "C": "Vaccine composition, not herd immunity.", "D": "Vaccine hesitancy, not the mechanism." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-45",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The research station, perched on a volcanic ridge 4,200 meters above sea _______ provides astronomers with some of the clearest atmospheric conditions on Earth.",
    options: ["level", "level;", "level,", "level—"],
    correctAnswer: "C",
    explanation: `Comma closes the descriptive phrase before the verb 'provides.' ✓`,
    explanations: { "A": "No punctuation to close the appositive phrase.", "B": "Semicolon can’t close an appositive.", "C": `Comma closes the descriptive phrase before the verb 'provides.' ✓`, "D": "Dash is less standard here." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-46",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The expedition reached the summit at _______ the team immediately began documenting wind patterns and collecting ice core samples.",
    options: ["dawn,", "dawn;", "dawn", "dawn and"],
    correctAnswer: "B",
    explanation: "Semicolon correctly joins two independent clauses. ✓",
    explanations: { "A": "Comma splice.", "B": "Semicolon correctly joins two independent clauses. ✓", "C": "Run-on.", "D": `'And' would need a comma: 'dawn, and.'` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-47",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "While the northern hemisphere experiences winter due to its axial tilt away from the _______ the southern hemisphere simultaneously enjoys summer.",
    options: ["sun,", "sun;", "sun", "sun."],
    correctAnswer: "A",
    explanation: `Comma separates the 'While' clause from the main clause. ✓`,
    explanations: { "A": `Comma separates the 'While' clause from the main clause. ✓`, "B": "Semicolon can’t follow a subordinate clause.", "C": "No punctuation creates confusion.", "D": "Period creates a fragment." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-48",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Each of the proposed amendments _______ been thoroughly reviewed by the legal team before presentation to the board.",
    options: ["have", "has", "are", "were"],
    correctAnswer: "B",
    explanation: `'Each' + singular verb 'has.' ✓`,
    explanations: { "A": `'Each' is always singular.`, "B": `'Each' + singular verb 'has.' ✓`, "C": "Wrong form entirely.", "D": `'Were' is plural past.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-49",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The orchestra, along with the guest _______ scheduled to perform the Beethoven concerto at next Saturday’s gala event.",
    options: ["soloists, are", "soloists, is", "soloists are", "soloists is"],
    correctAnswer: "B",
    explanation: `'Orchestra' is singular; comma closes parenthetical; 'is' agrees. ✓`,
    explanations: { "A": `Subject is 'orchestra' (singular); 'along with' is parenthetical.`, "B": `'Orchestra' is singular; comma closes parenthetical; 'is' agrees. ✓`, "C": "Missing comma to close the parenthetical.", "D": "Missing comma." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-50",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Having _______ three bestselling novels before the age of thirty, the author was considered one of the most promising voices of her generation.",
    options: ["wrote", "written", "writing", "write"],
    correctAnswer: "B",
    explanation: `'Having written' is correct past participle after 'having.' ✓`,
    explanations: { "A": `'Having wrote' is nonstandard; past participle needed.`, "B": `'Having written' is correct past participle after 'having.' ✓`, "C": `'Having writing' is grammatically incorrect.`, "D": `'Having write' is grammatically incorrect.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-51",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The scientist _______ research on gravitational waves earned her the Nobel Prize published a new paper this morning on neutron star collisions.",
    options: ["who’s", "whose", "whom", "that"],
    correctAnswer: "B",
    explanation: `'Whose' shows possession of 'research.' ✓`,
    explanations: { "A": `'Who’s'='who is.'`, "B": `'Whose' shows possession of 'research.' ✓`, "C": "Object pronoun, not possessive.", "D": "Doesn’t show possession." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-52",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Neither the original data nor the subsequent _______ supports the hypothesis that the treatment reduces inflammation more effectively than the current standard of care.",
    options: ["replication", "replications", "replicating", "replicated"],
    correctAnswer: "A",
    explanation: `'Neither...nor' with singular nearest subject 'replication' takes singular 'supports.' ✓`,
    explanations: { "A": `'Neither...nor' with singular nearest subject 'replication' takes singular 'supports.' ✓`, "B": `'Replications' is plural; 'supports' is singular — agreement error.`, "C": "Gerund doesn’t fit as a noun subject here.", "D": "Past participle can’t serve as the subject." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-53",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The mural, which the artist _______ over the course of three months, depicts the neighborhood’s transformation from industrial district to cultural hub.",
    options: ["painting", "has painted", "painted", "paints"],
    correctAnswer: "C",
    explanation: `Simple past 'painted' describes the completed action. ✓`,
    explanations: { "A": "Participle can’t serve as the main verb of the clause.", "B": `Present perfect doesn’t fit the past narrative ('depicts' is descriptive present).`, "C": `Simple past 'painted' describes the completed action. ✓`, "D": "Present tense for a completed past action is incorrect." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-rw-54",
    testType: "nmsqt",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The refugees, many of _______ had traveled hundreds of miles on foot, were finally provided with temporary shelter and medical care.",
    options: ["which", "whom", "who", "that"],
    correctAnswer: "B",
    explanation: `'Whom' is the object of the preposition 'of.' ✓`,
    explanations: { "A": `'Which' refers to things, not people.`, "B": `'Whom' is the object of the preposition 'of.' ✓`, "C": `'Who' is subjective case; 'of' requires objective.`, "D": `'That' doesn’t work after a preposition with commas.` },
    tags: ["practice-test"],
  }
];

export const MATH_QUESTIONS: Question[] = [
  {
    id: "pt-nmsqt-math-1",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If 4x−7=2x+9, what is x?",
    options: ["1", "2", "8", "16"],
    correctAnswer: "C",
    explanation: "2x=16, x=8. Check: 25=25. ✓",
    explanations: { "A": "4(1)−7=−3≠11.", "B": "4(2)−7=1≠13.", "C": "2x=16, x=8. Check: 25=25. ✓", "D": "Too large." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-2",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which function represents the fare f for m miles?",
    passage: "A rideshare charges $3 base plus $1.80 per mile.",
    options: ["f(m)=3m+1.80", "f(m)=1.80m+3", "f(m)=4.80m", "f(m)=1.80m−3"],
    correctAnswer: "B",
    explanation: "$1.80/mile + $3 base. ✓",
    explanations: { "A": "$3 is fixed, not per mile.", "B": "$1.80/mile + $3 base. ✓", "C": "Adds rates.", "D": "Subtracts base." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-3",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Systems of equations",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the value of x?",
    passage: `3x+2y=20
x−y=1`,
    options: ["", "", "", ""],
    correctAnswer: "4.4",
    explanation: "From eq2: x=y+1. Sub: 3(y+1)+2y=20 → 5y=17 → y=3.4. x=4.4.",
    explanations: { "correct": "From eq2: x=y+1. Sub: 3(y+1)+2y=20 → 5y=17 → y=3.4. x=4.4." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-4",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Inequalities",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Maximum total hours he can park?",
    passage: "Parking: $5 first hour, $3 each additional hour. Tom has $20.",
    options: ["5", "6", "7", "8"],
    correctAnswer: "B",
    explanation: "5+3(5)=20. 6 total hours. ✓",
    explanations: { "A": "5+3(4)=17, can afford more.", "B": "5+3(5)=20. 6 total hours. ✓", "C": "5+3(6)=23>20.", "D": "Too many." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-5",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Equivalent expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression equals 2(3x−4)−(x+6)?",
    options: ["5x−14", "5x−2", "7x−14", "5x−10"],
    correctAnswer: "A",
    explanation: "6x−8−x−6=5x−14. ✓",
    explanations: { "A": "6x−8−x−6=5x−14. ✓", "B": "Didn’t distribute negative.", "C": "Added x coefficients wrong.", "D": "Wrong constant." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-6",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Slope",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Slope of a line through (2,5) and (6,13)?",
    options: ["1/2", "2", "4", "8"],
    correctAnswer: "B",
    explanation: "(13−5)/(6−2)=8/4=2. ✓",
    explanations: { "A": "Inverted.", "B": "(13−5)/(6−2)=8/4=2. ✓", "C": "Δx only.", "D": "Δy only." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-7",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Function notation",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is f(5)?",
    passage: "f(x)=x²−4x+3",
    options: ["", "", "", ""],
    correctAnswer: "8",
    explanation: "25−20+3=8.",
    explanations: { "correct": "25−20+3=8." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-8",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Factoring quadratics",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Solutions of x²−7x+12=0?",
    options: ["x=3, x=4", "x=−3, x=−4", "x=2, x=6", "x=−2, x=−6"],
    correctAnswer: "A",
    explanation: "(x−3)(x−4)=0. ✓",
    explanations: { "A": "(x−3)(x−4)=0. ✓", "B": "Product=12 but sum=−7.", "C": "Sum=8≠7.", "D": "Product=12 but sum wrong." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-9",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Vertex form",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Vertex of y=−(x−3)²+7?",
    options: ["(3,7)", "(−3,7)", "(3,−7)", "(−3,−7)"],
    correctAnswer: "A",
    explanation: "a(x−h)²+k → vertex=(3,7). ✓",
    explanations: { "A": "a(x−h)²+k → vertex=(3,7). ✓", "B": "Sign error on h.", "C": "Sign error on k.", "D": "Both wrong." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-10",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Exponent rules",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Simplify: (2x³)²",
    options: ["2x⁶", "4x⁶", "4x⁵", "2x⁵"],
    correctAnswer: "B",
    explanation: "(2)²(x³)²=4x⁶. ✓",
    explanations: { "A": "Must square 2 also.", "B": "(2)²(x³)²=4x⁶. ✓", "C": "Wrong exponent.", "D": "Neither correct." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-11",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Difference of squares",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is 51²−49²?",
    options: ["", "", "", ""],
    correctAnswer: "200",
    explanation: "(51+49)(51−49)=100×2=200.",
    explanations: { "correct": "(51+49)(51−49)=100×2=200." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-12",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Exponential growth",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Value after t years?",
    passage: "$5,000 earns 4% annually, compounded.",
    options: ["5000(1.04)ᵗ", "5000(0.04)ᵗ", "5000+200t", "5000(1.4)ᵗ"],
    correctAnswer: "A",
    explanation: "P(1+r)ᵗ=5000(1.04)ᵗ. ✓",
    explanations: { "A": "P(1+r)ᵗ=5000(1.04)ᵗ. ✓", "B": "Rate only.", "C": "Simple interest.", "D": "40% rate." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-13",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Function composition",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is g(f(4))?",
    passage: "f(x)=x+3, g(x)=2x−1",
    options: ["10", "13", "14", "11"],
    correctAnswer: "B",
    explanation: "f(4)=7. g(7)=13. ✓",
    explanations: { "A": "Wrong.", "B": "f(4)=7. g(7)=13. ✓", "C": "Wrong.", "D": "Wrong." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-14",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Radical expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression equals √50?",
    options: ["5√2", "25√2", "10√5", "2√25"],
    correctAnswer: "A",
    explanation: "√(25×2)=5√2. ✓",
    explanations: { "A": "√(25×2)=5√2. ✓", "B": "25√2≈35.4.", "C": "10√5≈22.4.", "D": "2(5)=10." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-15",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Percentages",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Retail price?",
    passage: "Store markup: 60% over $25 wholesale.",
    options: ["$35", "$40", "$45", "$85"],
    correctAnswer: "B",
    explanation: "25×1.60=40. ✓",
    explanations: { "A": "40% markup.", "B": "25×1.60=40. ✓", "C": "No basis.", "D": "Added 60." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-16",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Data interpretation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What percentage walk?",
    passage: "500 students surveyed on transportation.",
    options: ["12%", "15%", "18%", "20%"],
    correctAnswer: "C",
    explanation: "90/500=18%. ✓",
    explanations: { "A": "Bus count.", "B": "Not walking.", "C": "90/500=18%. ✓", "D": "Wrong count." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-17",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Median",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the median?",
    passage: "Data: 12, 15, 15, 18, 20, 22, 30",
    options: ["", "", "", ""],
    correctAnswer: "18",
    explanation: "7 values, 4th value=18.",
    explanations: { "correct": "7 values, 4th value=18." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-18",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Probability",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "P(king or queen)?",
    passage: "Standard 52-card deck.",
    options: ["1/13", "2/13", "4/52", "1/26"],
    correctAnswer: "B",
    explanation: "8/52=2/13. ✓",
    explanations: { "A": "Kings only.", "B": "8/52=2/13. ✓", "C": "Same as 1/13.", "D": "No basis." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-19",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Circle properties",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Circle with center (1,−5) passes through (1,−1). Radius?",
    options: ["3", "4", "5", "6"],
    correctAnswer: "B",
    explanation: "|−1−(−5)|=4. ✓",
    explanations: { "A": "Distance=4.", "B": "|−1−(−5)|=4. ✓", "C": "Too large.", "D": "Too large." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-20",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Trig ratios",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "cos(θ)=?",
    passage: "Right triangle: legs 5, 12; hypotenuse 13. θ opposite the 5.",
    options: ["5/13", "12/13", "5/12", "13/12"],
    correctAnswer: "B",
    explanation: "adj/hyp=12/13. ✓",
    explanations: { "A": "That’s sin(θ).", "B": "adj/hyp=12/13. ✓", "C": "That’s tan(θ).", "D": ">1, impossible." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-21",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Volume",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "Cone: radius 6, height 10. Volume as a multiple of π?",
    options: ["", "", "", ""],
    correctAnswer: "120",
    explanation: "(1/3)π(36)(10)=120π.",
    explanations: { "correct": "(1/3)π(36)(10)=120π." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-22",
    testType: "nmsqt",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Midpoint",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Midpoint of (−3,8) and (7,−2)?",
    options: ["(2,3)", "(5,5)", "(4,6)", "(2,5)"],
    correctAnswer: "A",
    explanation: "((−3+7)/2,(8−2)/2)=(2,3). ✓",
    explanations: { "A": "((−3+7)/2,(8−2)/2)=(2,3). ✓", "B": "No division.", "C": "Wrong.", "D": "y wrong." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-23",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Equations with fractions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Solve: (2/3)x+5=(5/6)x+2",
    options: ["−18", "6", "18", "−6"],
    correctAnswer: "C",
    explanation: "Multiply by 6: 4x+30=5x+12. x=18. Check: 17=17. ✓",
    explanations: { "A": "Sign error.", "B": "Too small.", "C": "Multiply by 6: 4x+30=5x+12. x=18. Check: 17=17. ✓", "D": "Wrong sign." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-24",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Perpendicular lines",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which line is perpendicular to y=−(2/5)x+3?",
    options: ["y=(2/5)x+1", "y=−(2/5)x−7", "y=(5/2)x−4", "y=−(5/2)x+6"],
    correctAnswer: "C",
    explanation: "Neg recip of −2/5 is 5/2. ✓",
    explanations: { "A": "Not negative reciprocal.", "B": "Parallel.", "C": "Neg recip of −2/5 is 5/2. ✓", "D": "Not correct reciprocal." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-25",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Absolute value",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many solutions does |3x+6|=0 have?",
    options: ["", "", "", ""],
    correctAnswer: "1",
    explanation: "Only 3x+6=0 → x=−2. One solution.",
    explanations: { "correct": "Only 3x+6=0 → x=−2. One solution." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-26",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Systems word problems",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How many adult tickets?",
    passage: "Adult tickets $12, child $7. 15 tickets total for $145.",
    options: ["6", "7", "8", "9"],
    correctAnswer: "C",
    explanation: "96+49=145. ✓",
    explanations: { "A": "72+63=135.", "B": "84+56=140.", "C": "96+49=145. ✓", "D": "108+42=150." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-27",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "No-solution systems",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which system has no solution?",
    options: ["y=2x+1, y=2x+5", "y=2x+1, y=−2x+5", "y=x+3, y=2x+3", "y=x, y=x"],
    correctAnswer: "A",
    explanation: "Same slope, different intercepts. Parallel. ✓",
    explanations: { "A": "Same slope, different intercepts. Parallel. ✓", "B": "Different slopes: one intersection.", "C": "Different slopes.", "D": "Identical: infinite solutions." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-28",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Function evaluation",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is g(1)?",
    passage: "g(x)=|2x−7|",
    options: ["", "", "", ""],
    correctAnswer: "5",
    explanation: "|2−7|=|−5|=5.",
    explanations: { "correct": "|2−7|=|−5|=5." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-29",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Completing the square",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Minimum value of y=x²+10x+21?",
    options: ["−4", "0", "4", "21"],
    correctAnswer: "A",
    explanation: "(x+5)²−25+21=(x+5)²−4. Min=−4. ✓",
    explanations: { "A": "(x+5)²−25+21=(x+5)²−4. Min=−4. ✓", "B": "y(0)=21.", "C": "Not vertex.", "D": "y-intercept." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-30",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Complex numbers",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "(4−i)(2+3i)=?",
    options: ["11+10i", "5+10i", "11+14i", "8+10i"],
    correctAnswer: "A",
    explanation: "8+12i−2i−3i²=8+10i+3=11+10i. ✓",
    explanations: { "A": "8+12i−2i−3i²=8+10i+3=11+10i. ✓", "B": "Forgot i²=−1.", "C": "Added wrong.", "D": "Missed i² term." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-31",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Discriminant",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "For x²−6x+9=0, how many distinct real solutions?",
    options: ["", "", "", ""],
    correctAnswer: "1",
    explanation: "b²−4ac=36−36=0. One repeated root (x=3).",
    explanations: { "correct": "b²−4ac=36−36=0. One repeated root (x=3)." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-32",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Factoring",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If (x−3) is a factor of x²−7x+12, what is the other factor?",
    options: ["(x−4)", "(x+4)", "(x−3)", "(x−6)"],
    correctAnswer: "A",
    explanation: "x²−7x+12=(x−3)(x−4). Product=12, sum=−7. ✓",
    explanations: { "A": "x²−7x+12=(x−3)(x−4). Product=12, sum=−7. ✓", "B": "(x−3)(x+4)=x²+x−12.", "C": "(x−3)²=x²−6x+9.", "D": "Wrong product." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-33",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Exponential decay",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Value after t years?",
    passage: "A car worth $20,000 depreciates 15% per year.",
    options: ["20000(0.15)ᵗ", "20000(0.85)ᵗ", "20000−300t", "20000(1.15)ᵗ"],
    correctAnswer: "B",
    explanation: "Retains 85%: 20000(0.85)ᵗ. ✓",
    explanations: { "A": "0.15 is the loss rate.", "B": "Retains 85%: 20000(0.85)ᵗ. ✓", "C": "Linear decay.", "D": "Growth, not depreciation." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-34",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Function transformations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If f(x)=x², how does g(x)=(x+2)²−5 compare?",
    options: ["Shifted left 2, down 5", "Shifted right 2, down 5", "Shifted left 2, up 5", "Shifted right 2, up 5"],
    correctAnswer: "A",
    explanation: "(x+2)=x−(−2): left 2. −5: down 5. ✓",
    explanations: { "A": "(x+2)=x−(−2): left 2. −5: down 5. ✓", "B": "(x+2) shifts left.", "C": "Down 5, not up.", "D": "Both wrong." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-35",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Polynomial evaluation",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is p(3)?",
    passage: "p(x)=x³−2x²+x−5",
    options: ["", "", "", ""],
    correctAnswer: "7",
    explanation: "p(3)=27−18+3−5=7.",
    explanations: { "correct": "p(3)=27−18+3−5=7." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-36",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Margin of error",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which is the best interpretation?",
    passage: "A poll of 800 likely voters: 48% favor Measure A, margin of error ±4%.",
    options: ["Exactly 48% of all voters favor it.", "Between 44% and 52% of voters likely favor it.", "The poll is unreliable.", "Measure A will definitely fail."],
    correctAnswer: "B",
    explanation: "48±4 = 44% to 52% confidence interval. ✓",
    explanations: { "A": "48% is an estimate, not exact.", "B": "48±4 = 44% to 52% confidence interval. ✓", "C": "±4% is normal.", "D": "52% is possible." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-37",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Study design",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Why can’t the school conclude tutoring caused higher scores?",
    passage: "A school compared test scores of students who chose to attend tutoring with those who did not.",
    options: ["The sample size was too small.", "Students self-selected into tutoring, so motivation or other factors may explain the difference.", "The tests were too easy.", "Tutoring is always ineffective."],
    correctAnswer: "B",
    explanation: "Self-selection bias: students who chose tutoring may be more motivated. Not random assignment. ✓",
    explanations: { "A": "Size isn’t the issue here.", "B": "Self-selection bias: students who chose tutoring may be more motivated. Not random assignment. ✓", "C": "Test difficulty isn’t mentioned.", "D": "Untrue and unsupported." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-38",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Two-way tables",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What percentage of ALL employees have benefits?",
    passage: "200 employees: 120 full-time, 80 part-time. Of full-time, 90 have benefits. Of part-time, 20 have benefits.",
    options: ["", "", "", ""],
    correctAnswer: "55",
    explanation: "90+20=110 with benefits. 110/200=0.55=55%.",
    explanations: { "correct": "90+20=110 with benefits. 110/200=0.55=55%." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-39",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Scatterplots",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What score does the model predict for 5 hours of study?",
    passage: "A scatterplot shows hours studied (x) vs. exam score (y). Line of best fit: y=8x+42.",
    options: ["72", "78", "82", "90"],
    correctAnswer: "C",
    explanation: "8(5)+42=40+42=82. ✓",
    explanations: { "A": "8(5)=40, not +32.", "B": "Close but wrong arithmetic.", "C": "8(5)+42=40+42=82. ✓", "D": "Too high." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-40",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Arc length",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Arc length?",
    passage: "Circle with radius 9. Central angle 120°.",
    options: ["3π", "6π", "9π", "12π"],
    correctAnswer: "B",
    explanation: "(120/360)(2π×9)=(1/3)(18π)=6π. ✓",
    explanations: { "A": "Too small.", "B": "(120/360)(2π×9)=(1/3)(18π)=6π. ✓", "C": "That’s half the circumference.", "D": "Too large." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-41",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Sector area",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Sector: central angle 60°, radius 12. Area?",
    options: ["12π", "24π", "36π", "144π"],
    correctAnswer: "B",
    explanation: "(60/360)π(144)=(1/6)(144π)=24π. ✓",
    explanations: { "A": "Too small.", "B": "(60/360)π(144)=(1/6)(144π)=24π. ✓", "C": "Quarter circle area.", "D": "Full circle." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-42",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Distance formula",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "Distance from (−2,3) to (4,11)?",
    options: ["", "", "", ""],
    correctAnswer: "10",
    explanation: "√((4−(−2))²+(11−3)²)=√(36+64)=√100=10.",
    explanations: { "correct": "√((4−(−2))²+(11−3)²)=√(36+64)=√100=10." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-43",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Circle from general form",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Radius of circle x²+y²+4x−10y=0?",
    options: ["√29", "29", "7", "5"],
    correctAnswer: "A",
    explanation: "(x+2)²+(y−5)²=4+25=29. r=√29. ✓",
    explanations: { "A": "(x+2)²+(y−5)²=4+25=29. r=√29. ✓", "B": "That’s r².", "C": "Not correct.", "D": "Too small." },
    tags: ["practice-test"],
  },
  {
    id: "pt-nmsqt-math-44",
    testType: "nmsqt",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Pythagorean theorem applied",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How high does the ladder reach?",
    passage: "A 15-foot ladder leans against a wall with its base 9 feet away.",
    options: ["6", "10", "12", "15"],
    correctAnswer: "C",
    explanation: "h²=15²−9²=225−81=144. h=12. ✓",
    explanations: { "A": "6²+9²=117≠225.", "B": "10²+9²=181≠225.", "C": "h²=15²−9²=225−81=144. h=12. ✓", "D": "That’s the ladder, not the height." },
    tags: ["practice-test"],
  }
];
