"use client";

import { PracticeTest } from "@/components/test/practice-test";
import type { Question } from "@/types/question";

const RW_QUESTIONS: Question[] = [
  {
    id: "pt-psat89-rw-1",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The new student was _______ at first, barely speaking in class, but by the end of the semester she had become one of the most active participants in group discussions.",
    options: ["reserved", "enthusiastic", "rude", "popular"],
    correctAnswer: "A",
    explanation: `'Reserved' means quiet and restrained — matches 'barely speaking.' ✓`,
    explanations: { "A": `'Reserved' means quiet and restrained — matches 'barely speaking.' ✓`, "B": "She became active later, not at first.", "C": "Being quiet isn’t the same as rude.", "D": "Popularity isn’t about speaking in class." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-2",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The science fair project was _______, presenting a creative hypothesis, well-designed experiments, and clear data analysis that impressed every judge.",
    options: ["ordinary", "incomplete", "impressive", "confusing"],
    correctAnswer: "C",
    explanation: `'Impressive' matches 'creative,' 'well-designed,' and 'impressed every judge.' ✓`,
    explanations: { "A": "Creative + well-designed + impressed judges ≠ ordinary.", "B": "It included hypothesis, experiments, and analysis — not incomplete.", "C": `'Impressive' matches 'creative,' 'well-designed,' and 'impressed every judge.' ✓`, "D": "Clear analysis isn’t confusing." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-3",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The trail was _______ after the rainstorm, with mud covering the path and fallen branches blocking the way, forcing hikers to turn back.",
    options: ["scenic", "impassable", "peaceful", "crowded"],
    correctAnswer: "B",
    explanation: `'Impassable' means impossible to travel through — mud, branches, hikers turned back. ✓`,
    explanations: { "A": "Mud and fallen branches don’t suggest scenic.", "B": `'Impassable' means impossible to travel through — mud, branches, hikers turned back. ✓`, "C": "The conditions described aren’t peaceful.", "D": "Crowded refers to people, not trail conditions." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-4",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "Rather than _______ the old community garden, the city council voted to restore it, adding new raised beds and a tool shed for neighborhood volunteers.",
    options: ["demolish", "expand", "ignore", "celebrate"],
    correctAnswer: "A",
    explanation: `'Rather than demolish' — they chose restoration instead of destruction. ✓`,
    explanations: { "A": `'Rather than demolish' — they chose restoration instead of destruction. ✓`, "B": `'Rather than expand' doesn’t contrast well with 'restore.'`, "C": "Ignoring isn’t a strong contrast to restoring.", "D": "Celebrating doesn’t set up the contrast." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-5",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The coach praised the team’s _______ during the final quarter, when they came back from a 15-point deficit to win the game in the last minute.",
    options: ["strategy", "uniforms", "resilience", "speed"],
    correctAnswer: "C",
    explanation: `'Resilience' means the ability to recover from difficulty — a 15-point comeback. ✓`,
    explanations: { "A": "Strategy is a plan, not the quality of bouncing back.", "B": "Uniforms are irrelevant to the comeback.", "C": `'Resilience' means the ability to recover from difficulty — a 15-point comeback. ✓`, "D": "Speed alone doesn’t capture the comeback quality." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-6",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the main purpose of the text?",
    passage: `Honeybees communicate the location of food sources through a behavior called the 'waggle dance.' When a forager bee returns to the hive after finding flowers, it performs a figure-eight pattern on the honeycomb. The angle of the dance relative to the sun indicates the direction of the food, while the duration of the waggle portion tells other bees how far away it is.`,
    options: ["To argue that bees are smarter than other insects.", "To explain how honeybees use dance to share information about food locations.", "To describe the nutritional needs of honeybees.", "To compare different types of bees."],
    correctAnswer: "B",
    explanation: "The entire text describes how the waggle dance communicates direction and distance of food. ✓",
    explanations: { "A": "No comparison to other insects.", "B": "The entire text describes how the waggle dance communicates direction and distance of food. ✓", "C": "Nutrition isn’t discussed.", "D": "Only honeybees are mentioned." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-7",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Craft and Structure",
    skill: "Cross-Text Connections",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "On which point do Rivera and Patel disagree?",
    passage: `<strong>Text 1</strong><br>School counselor Ms. Rivera believes homework is essential for building study habits: 'Students who practice material at home develop discipline and retain information better. Thirty minutes of homework per night is a reasonable expectation.'<br><br><strong>Text 2</strong><br>Pediatrician Dr. Patel argues that excessive homework harms children’s wellbeing: 'After a full school day, kids need time to play, rest, and spend time with family. Research shows that for elementary students, homework has no measurable academic benefit.'`,
    options: ["Whether schools should exist.", "Whether homework provides meaningful benefits that justify the time it requires.", "Whether teachers work hard.", "Whether children should learn to read."],
    correctAnswer: "B",
    explanation: "Rivera says homework builds habits; Patel says it harms wellbeing without academic benefit. ✓",
    explanations: { "A": "Both support schooling.", "B": "Rivera says homework builds habits; Patel says it harms wellbeing without academic benefit. ✓", "C": "Teacher effort isn’t discussed.", "D": "Reading isn’t the topic." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-8",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best states the main idea of the text?",
    passage: "The octopus is one of the most intelligent invertebrates in the ocean. Scientists have observed octopuses unscrewing jar lids to reach food inside, navigating complex mazes, and even using coconut shells as portable shelters. Unlike most animals, each of the octopus’s eight arms has its own cluster of neurons, allowing the arms to taste, touch, and even make simple decisions independently of the brain.",
    options: ["Octopuses are dangerous predators.", "Octopuses demonstrate remarkable intelligence through problem-solving abilities and a uniquely distributed nervous system.", "All sea creatures are intelligent.", "Octopuses have eight arms."],
    correctAnswer: "B",
    explanation: "Problem-solving (jars, mazes, tools) + distributed neurons = intelligence and unique nervous system. ✓",
    explanations: { "A": "Intelligence, not danger, is the focus.", "B": "Problem-solving (jars, mazes, tools) + distributed neurons = intelligence and unique nervous system. ✓", "C": "Only octopuses are discussed.", "D": "True but a minor detail." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-9",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Central Ideas and Details",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "According to the text, what was a major effect of the Erie Canal?",
    passage: "When the Erie Canal opened in 1825, it transformed American commerce. The 363-mile waterway connected the Great Lakes to the Atlantic Ocean via the Hudson River, reducing the cost of shipping goods from Buffalo to New York City by about 95%. Towns along the canal, such as Rochester and Syracuse, grew rapidly as trade flowed through them.",
    options: ["It made shipping dramatically cheaper, spurring growth in towns along its route.", "It connected California to New York.", "It was the first road built in America.", "It was used primarily for passenger travel."],
    correctAnswer: "A",
    explanation: "95% cost reduction + town growth = dramatic economic impact. ✓",
    explanations: { "A": "95% cost reduction + town growth = dramatic economic impact. ✓", "B": "It connected the Great Lakes to the Atlantic, not California.", "C": "It was a canal, not a road.", "D": "Commerce and shipping are the focus, not passenger travel." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-10",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding, if true, would most directly support Dr. Patel’s claim?",
    passage: "Marine biologist Dr. Aisha Patel claims that sea turtle populations are recovering in areas with strong conservation programs.",
    options: ["Sea turtles are reptiles that breathe air.", "Beaches with volunteer nest-protection programs saw a 40% increase in hatchling survival rates over ten years, while unprotected beaches showed no change.", "Some tourists enjoy watching sea turtles.", "Sea turtles migrate long distances."],
    correctAnswer: "B",
    explanation: "Protected beaches: 40% increase. Unprotected: no change. Directly connects conservation to recovery. ✓",
    explanations: { "A": "Biology fact, not conservation evidence.", "B": "Protected beaches: 40% increase. Unprotected: no change. Directly connects conservation to recovery. ✓", "C": "Tourism interest doesn’t show recovery.", "D": "Migration doesn’t address conservation effectiveness." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-11",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly support this claim?",
    passage: "A teacher argues that reading fiction improves students’ ability to understand other people’s feelings and perspectives.",
    options: ["Students who read fiction regularly scored higher on tests measuring empathy and perspective-taking than students who read only nonfiction or did not read for pleasure.", "Fiction books are available in most school libraries.", "Some students prefer graphic novels to traditional books.", "Reading speed increases with practice."],
    correctAnswer: "A",
    explanation: "Fiction readers → higher empathy scores directly supports the claim. ✓",
    explanations: { "A": "Fiction readers → higher empathy scores directly supports the claim. ✓", "B": "Availability doesn’t show the effect.", "C": "Format preference doesn’t address empathy.", "D": "Speed isn’t about emotional understanding." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-12",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses data from the table to describe a trend?",
    passage: "A school tracked participation in after-school activities over three years.",
    options: ["In 2023, 180 students participated in sports.", "While sports participation remained steady at about 180 students across all three years, coding club enrollment surged from 25 to 95 students, making it the fastest-growing activity and suggesting increasing student interest in technology.", "The school offers after-school activities.", "Some students don’t participate in any activity."],
    correctAnswer: "B",
    explanation: "Compares sports (steady ~180) vs. coding (25→95, fastest growth) with interpretation. ✓",
    explanations: { "A": "Single data point.", "B": "Compares sports (steady ~180) vs. coding (25→95, fastest growth) with interpretation. ✓", "C": "Too vague.", "D": "Not supported by the data shown." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-13",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice best uses the table data to identify a seasonal pattern?",
    passage: "A pet store tracked monthly sales of different pet food types.",
    options: ["Dog food outsells cat food.", "Fish food sales doubled from 40 units in March to 80 units in June, likely reflecting the popularity of starting fish tanks in warmer months, while dog and cat food sales remained relatively stable across the same period.", "The store sells pet food.", "Cat food sales were 120 in March."],
    correctAnswer: "B",
    explanation: "Fish food seasonal doubling vs. stable dog/cat = clear seasonal pattern. ✓",
    explanations: { "A": "True but no seasonal pattern.", "B": "Fish food seasonal doubling vs. stable dog/cat = clear seasonal pattern. ✓", "C": "Too obvious.", "D": "Single data point." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-14",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "Scientists studying a remote island found that the local lizard population had developed significantly longer legs than the same species on the mainland. The island’s terrain is mostly rocky with wide gaps between boulders that lizards must jump across to find food and escape predators. ________",
    options: ["This suggests that the island’s terrain created a selective pressure favoring longer-legged individuals, who could jump farther and survive more successfully.", "Therefore, all lizards everywhere have long legs.", "This means the lizards were brought to the island by humans.", "Scientists concluded that the lizards don’t need legs."],
    correctAnswer: "A",
    explanation: "Rocky terrain + wide gaps + need to jump = selection for longer legs. ✓",
    explanations: { "A": "Rocky terrain + wide gaps + need to jump = selection for longer legs. ✓", "B": "Only island lizards; doesn’t apply everywhere.", "C": "No evidence of human introduction.", "D": "Contradicts the entire passage." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-15",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The school’s recycling program collected over 2,000 pounds of paper in its first year. _______, plastic recycling lagged behind, with students often throwing plastic bottles in regular trash cans despite clearly labeled recycling bins nearby.",
    options: ["Similarly", "However", "Therefore", "For example"],
    correctAnswer: "B",
    explanation: "Success in paper, but failure in plastic — a contrast. ✓",
    explanations: { "A": "Paper success vs. plastic failure is a contrast, not similarity.", "B": "Success in paper, but failure in plastic — a contrast. ✓", "C": "Plastic failure isn’t caused by paper success.", "D": "Plastic isn’t an example of the paper program." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-16",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "Cheetahs are the fastest land animals, reaching speeds of 70 mph. _______, they can only maintain this speed for about 30 seconds before overheating, which means they must catch prey quickly or abandon the chase.",
    options: ["In addition", "As a result", "On the other hand", "For instance"],
    correctAnswer: "C",
    explanation: "Fast, but only briefly — a counterpoint. ✓",
    explanations: { "A": "The time limit qualifies, not adds to, the speed.", "B": "The limit isn’t a result; it’s a counterbalance.", "C": "Fast, but only briefly — a counterpoint. ✓", "D": "Not an example of speed." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-17",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The school garden produced enough tomatoes to supply the cafeteria for three weeks. _______, the lettuce and peppers also thrived, contributing to a total harvest that exceeded the club’s expectations.",
    options: ["Nevertheless", "Moreover", "Instead", "Unfortunately"],
    correctAnswer: "B",
    explanation: "Tomatoes succeeded; lettuce and peppers also succeeded — additional positive information. ✓",
    explanations: { "A": "No contrast with something negative.", "B": "Tomatoes succeeded; lettuce and peppers also succeeded — additional positive information. ✓", "C": "Nothing is being replaced.", "D": "Thriving is positive, not unfortunate." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-18",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the benefits of school therapy dogs and wants to emphasize measurable outcomes.",
    options: ["Some schools have therapy dog programs.", "Therapy dogs are usually golden retrievers or Labrador retrievers.", "Schools with therapy dog programs reported a 22% decrease in student anxiety levels and a 15% reduction in office discipline referrals, with students in the program also showing improved attendance rates compared to the previous year.", "Students enjoy petting dogs."],
    correctAnswer: "C",
    explanation: "Three measurable outcomes: 22% anxiety drop, 15% fewer referrals, improved attendance. ✓",
    explanations: { "A": "Existence, not outcomes.", "B": "Breed info, not outcomes.", "C": "Three measurable outcomes: 22% anxiety drop, 15% fewer referrals, improved attendance. ✓", "D": "Enjoyment, not measurable outcomes." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-19",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about coral reefs and wants to convey their ecological importance.",
    options: ["Coral reefs are found in warm ocean waters.", "Although coral reefs cover less than 1% of the ocean floor, they support roughly 25% of all marine species, providing habitat, breeding grounds, and protection for thousands of fish, invertebrate, and plant species that depend on the reef structure for survival.", "Some coral is used in jewelry.", "Coral reefs are colorful."],
    correctAnswer: "B",
    explanation: "1% coverage supporting 25% of species = massive ecological importance. ✓",
    explanations: { "A": "Location, not importance.", "B": "1% coverage supporting 25% of species = massive ecological importance. ✓", "C": "Jewelry use, not ecology.", "D": "Appearance, not ecological role." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-20",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the history of the bicycle and wants to show how the design evolved.",
    options: ["Bicycles are a popular form of exercise.", `The bicycle has undergone dramatic design changes since the early 'penny-farthing' of the 1870s, which had an enormous front wheel and no chain: the introduction of equal-sized wheels and a chain drive in the 1880s — the 'safety bicycle' — made cycling accessible to ordinary people and launched a transportation revolution.`, "Many countries have bike lanes.", "Bicycles are environmentally friendly."],
    correctAnswer: "B",
    explanation: "Penny-farthing → safety bicycle = clear design evolution with impact. ✓",
    explanations: { "A": "Modern use, not design evolution.", "B": "Penny-farthing → safety bicycle = clear design evolution with impact. ✓", "C": "Infrastructure, not design history.", "D": "Environmental benefit, not evolution." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-21",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The bakery offers three types of _______ sourdough, whole wheat, and rye.",
    options: ["bread", "bread:", "bread,", "bread;"],
    correctAnswer: "B",
    explanation: "Colon introduces the enumerated list. ✓",
    explanations: { "A": "No punctuation before the list.", "B": "Colon introduces the enumerated list. ✓", "C": "Comma is too weak before a listed series.", "D": "Semicolon doesn’t introduce lists." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-22",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Although the movie received mostly negative _______ it earned over $200 million at the box office during its opening weekend.",
    options: ["reviews", "reviews;", "reviews,", "reviews."],
    correctAnswer: "C",
    explanation: `Comma after the introductory 'Although' clause. ✓`,
    explanations: { "A": `No punctuation after 'Although' clause.`, "B": "Semicolon can’t follow a subordinate clause.", "C": `Comma after the introductory 'Although' clause. ✓`, "D": "Period creates a fragment." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-23",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The concert was sold _______ not a single ticket remained by noon on the first day of sales.",
    options: ["out", "out,", "out;", "out."],
    correctAnswer: "C",
    explanation: "Semicolon joins two related independent clauses. ✓",
    explanations: { "A": "Run-on sentence.", "B": "Comma splice between independent clauses.", "C": "Semicolon joins two related independent clauses. ✓", "D": "Separates closely connected ideas." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-24",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The team of volunteers _______ working since early morning to clean up the park before the festival begins.",
    options: ["have been", "has been", "are", "were"],
    correctAnswer: "B",
    explanation: `'Team' is singular; 'has been' agrees. ✓`,
    explanations: { "A": `'Team' is singular collective noun.`, "B": `'Team' is singular; 'has been' agrees. ✓`, "C": `Wrong form with 'since early morning.'`, "D": `Past tense doesn’t match 'since early morning.'` },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-25",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Neither the coach nor the _______ happy with the referee’s call during the final play of the game.",
    options: ["players was", "players were", "player are", "players is"],
    correctAnswer: "B",
    explanation: `'Neither...nor' — verb agrees with nearer subject 'players' (plural). ✓`,
    explanations: { "A": `'Players' is plural; needs 'were.'`, "B": `'Neither...nor' — verb agrees with nearer subject 'players' (plural). ✓`, "C": `'Player' singular with 'are' disagrees.`, "D": `'Players' plural with 'is' disagrees.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-26",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The student _______ project won first place at the science fair was invited to present at the state competition.",
    options: ["who’s", "whose", "which", "whom"],
    correctAnswer: "B",
    explanation: `'Whose' shows possession of 'project.' ✓`,
    explanations: { "A": `'Who’s'='who is,' not possessive.`, "B": `'Whose' shows possession of 'project.' ✓`, "C": `'Which' doesn’t refer to a person.`, "D": `'Whom' is an object pronoun, not possessive.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-27",
    testType: "psat89",
    section: "rw",
    module: 1,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "After the bell _______ the students rushed to their lockers to grab their coats before heading to the buses.",
    options: ["rang,", "rung,", "ringed,", "rings,"],
    correctAnswer: "A",
    explanation: `Simple past of 'ring' is 'rang.' ✓`,
    explanations: { "A": `Simple past of 'ring' is 'rang.' ✓`, "B": `'Rung' is the past participle (needs 'had').`, "C": `'Ringed' means 'encircled,' different word.`, "D": "Present tense doesn’t match past narrative." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-28",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The mayor’s decision to build a skate park was _______, since a recent survey showed that 78% of residents supported the project and local businesses expected increased foot traffic.",
    options: ["unpopular", "well-founded", "surprising", "illegal"],
    correctAnswer: "B",
    explanation: "Survey data + business support = good reasoning behind the decision. ✓",
    explanations: { "A": "78% support = popular, not unpopular.", "B": "Survey data + business support = good reasoning behind the decision. ✓", "C": "With 78% support, it’s expected, not surprising.", "D": "Nothing illegal is mentioned." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-29",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The documentary’s portrayal of the endangered species was deliberately _______, using close-up footage of mothers caring for their young to make viewers feel a personal connection to the animals’ struggle for survival.",
    options: ["objective", "misleading", "emotionally engaging", "technical"],
    correctAnswer: "C",
    explanation: `'Emotionally engaging' — deliberate use of footage to create personal connection. ✓`,
    explanations: { "A": "Close-ups of mothers to create connection is emotional, not objective.", "B": "Showing real animal behavior isn’t misleading.", "C": `'Emotionally engaging' — deliberate use of footage to create personal connection. ✓`, "D": "Close-ups of family behavior isn’t technical." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-30",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The experiment produced _______ results: in some trials the chemical reaction occurred in seconds, while in others identical conditions yielded no reaction at all, leaving researchers unable to identify a pattern.",
    options: ["consistent", "predictable", "inconsistent", "expected"],
    correctAnswer: "C",
    explanation: `'Inconsistent' means varying without pattern — matches seconds vs. no reaction. ✓`,
    explanations: { "A": "Seconds vs. no reaction = opposite of consistent.", "B": "Unable to identify a pattern = unpredictable.", "C": `'Inconsistent' means varying without pattern — matches seconds vs. no reaction. ✓`, "D": "They couldn’t explain it, so it wasn’t expected." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-31",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The teacher _______ a classroom policy requiring students to put phones in a wall organizer at the start of each period, and within a week, both participation and test scores had improved noticeably.",
    options: ["considered", "rejected", "implemented", "delayed"],
    correctAnswer: "C",
    explanation: `'Implemented' means put into action — the policy was enacted and produced results. ✓`,
    explanations: { "A": `'Considered' means thought about; results wouldn’t follow from just thinking.`, "B": "If rejected, the policy wouldn’t produce results.", "C": `'Implemented' means put into action — the policy was enacted and produced results. ✓`, "D": "Delayed wouldn’t explain immediate improvement." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-32",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Words in Context",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical and precise word or phrase?",
    passage: "The museum exhibit was designed to be _______, with touchable replicas, audio descriptions, and wheelchair-accessible displays so visitors of all abilities could fully experience the collection.",
    options: ["exclusive", "accessible", "temporary", "expensive"],
    correctAnswer: "B",
    explanation: `'Accessible' means able to be used by everyone — multiple accommodations. ✓`,
    explanations: { "A": "Touchable + audio + wheelchair access = opposite of exclusive.", "B": `'Accessible' means able to be used by everyone — multiple accommodations. ✓`, "C": "Duration isn’t the point.", "D": "Cost isn’t discussed." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-33",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Craft and Structure",
    skill: "Text Structure and Purpose",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the main purpose of the text?",
    passage: "Many people believe that goldfish have a memory span of only three seconds. In fact, scientists have trained goldfish to navigate mazes, remember the location of food for months, and even respond to specific sounds. One study found that goldfish could be taught to push a lever to receive food and remembered the skill five months later.",
    options: ["To explain how to care for goldfish.", "To correct a popular misconception about goldfish memory with scientific evidence.", "To argue that goldfish are the smartest fish.", "To describe different types of pet fish."],
    correctAnswer: "B",
    explanation: "Opens with misconception (3-second memory), then presents contrary evidence (mazes, 5-month memory). ✓",
    explanations: { "A": "No care instructions.", "B": "Opens with misconception (3-second memory), then presents contrary evidence (mazes, 5-month memory). ✓", "C": "No comparison to other fish.", "D": "Only goldfish discussed." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-34",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly support this claim?",
    passage: "A nutritionist claims that eating breakfast improves academic performance in middle school students.",
    options: ["Most students prefer cereal to toast.", "A study comparing students who ate breakfast daily with those who skipped it found that breakfast eaters had 12% higher average test scores and were less likely to visit the nurse for headaches or fatigue during morning classes.", "Breakfast foods contain various vitamins.", "Some schools start before 8 AM."],
    correctAnswer: "B",
    explanation: "Direct comparison: breakfast eaters = higher scores + fewer health visits. ✓",
    explanations: { "A": "Food preference, not performance.", "B": "Direct comparison: breakfast eaters = higher scores + fewer health visits. ✓", "C": "Nutrition facts don’t prove performance gains.", "D": "Start time, not breakfast impact." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-35",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Textual)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which finding would most directly weaken this claim?",
    passage: "A city planner argues that adding more streetlights reduces crime in urban neighborhoods.",
    options: ["A study of 50 neighborhoods found no significant difference in crime rates between those that received new streetlights and those that did not, after controlling for other factors like police patrols and economic conditions.", "Streetlights use electricity.", "Some residents prefer darker streets for stargazing.", "LED lights are more efficient than older bulbs."],
    correctAnswer: "A",
    explanation: "No difference after controls directly undercuts the streetlight-crime link. ✓",
    explanations: { "A": "No difference after controls directly undercuts the streetlight-crime link. ✓", "B": "Energy use doesn’t address crime.", "C": "Personal preference, not crime data.", "D": "Efficiency, not crime." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-36",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Command of Evidence (Quantitative)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the table data to evaluate the program?",
    passage: "A school compared reading levels before and after implementing a daily 20-minute silent reading program.",
    options: ["Before the program, 35% read at grade level.", "After one year of daily silent reading, the percentage of students reading at or above grade level rose from 35% to 58%, with the biggest improvement among students who had been below grade level, 62% of whom advanced at least one level — suggesting the program especially benefits struggling readers.", "The program lasted 20 minutes per day.", "Some students already read above grade level."],
    correctAnswer: "B",
    explanation: "35%→58% overall + 62% of below-level improved = data-driven evaluation showing impact especially for struggling readers. ✓",
    explanations: { "A": "Single pre-program point.", "B": "35%→58% overall + 62% of below-level improved = data-driven evaluation showing impact especially for struggling readers. ✓", "C": "Duration, not outcome.", "D": "Doesn’t evaluate impact." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-37",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "When researchers played recordings of different bird calls in a forest, they noticed that small birds fell silent after hearing a hawk’s call but resumed singing within seconds of hearing a robin’s call. The small birds had no visual contact with any predator or other bird during the experiment. ________",
    options: ["This suggests that small birds can identify specific threats by sound alone, discriminating between dangerous and harmless species without visual confirmation.", "Therefore, all birds are afraid of hawks.", "This means birds cannot see very well.", "Researchers concluded that birds don’t like music."],
    correctAnswer: "A",
    explanation: "Different responses to hawk vs. robin sounds, with no visual cues = threat identification by sound. ✓",
    explanations: { "A": "Different responses to hawk vs. robin sounds, with no visual cues = threat identification by sound. ✓", "B": `'All birds' overgeneralizes.`, "C": "They had no visual contact by design; vision wasn’t tested.", "D": "Bird calls aren’t music in this context." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-38",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Information and Ideas",
    skill: "Inferences",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most logically completes the text?",
    passage: "A study of identical twins raised in different households found that both twins in each pair tended to choose similar careers, have similar hobbies, and even prefer similar foods — despite having no contact with each other during childhood. ________",
    options: ["These similarities suggest that genetics plays a significant role in shaping personality and preferences, even when environmental factors differ.", "This proves that environment has no effect on personality.", "Therefore, all siblings are identical.", "Researchers concluded that career choice is random."],
    correctAnswer: "A",
    explanation: "Same genes + different environments + similar outcomes = genetic influence. ✓",
    explanations: { "A": "Same genes + different environments + similar outcomes = genetic influence. ✓", "B": `'No effect' is too absolute; the passage shows strong genetic influence, not zero environmental influence.`, "C": "Only identical twins were studied.", "D": "Similar careers suggest non-random patterns." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-39",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The city planted 500 new trees along Main Street to improve air quality and provide shade. _______, the trees attracted birds and butterflies, creating a more vibrant ecosystem in the downtown area.",
    options: ["Unfortunately", "In addition", "However", "Instead"],
    correctAnswer: "B",
    explanation: "Wildlife is an additional benefit beyond air quality and shade. ✓",
    explanations: { "A": "Birds and butterflies are positive, not unfortunate.", "B": "Wildlife is an additional benefit beyond air quality and shade. ✓", "C": "No contrast here.", "D": "Nothing is being replaced." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-40",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The student council proposed extending lunch by 10 minutes. _______, the principal noted that a longer lunch would require shortening another class period, which teachers strongly opposed.",
    options: ["As a result", "In response", "Similarly", "For example"],
    correctAnswer: "B",
    explanation: "The principal is responding to the proposal with a concern. ✓",
    explanations: { "A": "The principal’s note isn’t a result of the proposal in a causal sense.", "B": "The principal is responding to the proposal with a concern. ✓", "C": "The principal’s concern contrasts, not parallels.", "D": "Not an example." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-41",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Transitions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text with the most logical transition?",
    passage: "The museum’s dinosaur exhibit attracts over 100,000 visitors annually. _______, the insect exhibit, despite containing some of the museum’s rarest specimens, draws fewer than 10,000 visitors per year.",
    options: ["Similarly", "Therefore", "By contrast", "In addition"],
    correctAnswer: "C",
    explanation: "100,000 vs. fewer than 10,000 — a clear contrast. ✓",
    explanations: { "A": "100,000 vs. 10,000 is a contrast, not similarity.", "B": "Low insect attendance isn’t caused by high dinosaur attendance.", "C": "100,000 vs. fewer than 10,000 — a clear contrast. ✓", "D": "The point is the difference, not adding information." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-42",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about school lunch waste and wants to propose a specific solution with evidence.",
    options: ["Schools serve lunch every day.", "Food waste is a problem in many schools.", `Schools that switched to 'offer vs. serve' policies — allowing students to choose which items they take — reduced plate waste by 30%, saving an average of $8,000 per school annually while ensuring students still received balanced nutrition options.`, "Some students bring lunch from home."],
    correctAnswer: "C",
    explanation: "Specific policy + 30% waste reduction + $8,000 savings + nutrition maintained = solution with evidence. ✓",
    explanations: { "A": "Background, not solution.", "B": "Problem statement without solution.", "C": "Specific policy + 30% waste reduction + $8,000 savings + nutrition maintained = solution with evidence. ✓", "D": "Irrelevant." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-43",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about service dogs and wants to highlight the training process.",
    options: ["Service dogs help people with disabilities.", "Training a service dog takes approximately two years and includes three phases: basic obedience as a puppy, specialized task training such as opening doors or alerting to seizures, and a final public-access certification ensuring the dog remains calm and focused in crowded, noisy environments.", "Some dogs are very friendly.", "Service dogs wear vests."],
    correctAnswer: "B",
    explanation: "Timeline (2 years) + 3 phases with details = comprehensive training description. ✓",
    explanations: { "A": "Function, not training.", "B": "Timeline (2 years) + 3 phases with details = comprehensive training description. ✓", "C": "Too vague.", "D": "Equipment, not training." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-44",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Expression of Ideas",
    skill: "Rhetorical Synthesis",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice most effectively uses the relevant information from the notes to accomplish this goal?",
    passage: "A student is writing about the water cycle and wants to explain why it matters for everyday life.",
    options: ["Water evaporates from oceans.", "The water cycle directly affects daily life: it determines rainfall patterns that farmers depend on for crops, replenishes the reservoirs and aquifers that supply drinking water to cities, and drives weather systems that influence everything from school closures to outdoor events.", "Water is made of hydrogen and oxygen.", "The water cycle is taught in science class."],
    correctAnswer: "B",
    explanation: "Farming + drinking water + weather/school closures = concrete everyday connections. ✓",
    explanations: { "A": "One step, not everyday relevance.", "B": "Farming + drinking water + weather/school closures = concrete everyday connections. ✓", "C": "Chemistry, not daily impact.", "D": "Meta-information." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-45",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The library, which was built in _______ houses over 50,000 books and serves as the town’s main gathering space for community events.",
    options: ["1952", "1952;", "1952,", "1952."],
    correctAnswer: "C",
    explanation: `Comma closes 'which was built in 1952' before the main verb 'houses.' ✓`,
    explanations: { "A": "No punctuation to close the nonrestrictive clause.", "B": "Semicolon can’t close a relative clause.", "C": `Comma closes 'which was built in 1952' before the main verb 'houses.' ✓`, "D": "Period creates a fragment." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-46",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The students finished their science _______ they immediately began preparing for the math exam scheduled for the following morning.",
    options: ["project", "project,", "project;", "project and"],
    correctAnswer: "C",
    explanation: "Semicolon joins two independent clauses. ✓",
    explanations: { "A": "Run-on.", "B": "Comma splice.", "C": "Semicolon joins two independent clauses. ✓", "D": `Needs a comma before 'and.'` },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-47",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Boundaries",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Because the power went out during the _______ the students had to finish their essays by hand using paper and pencils from the supply closet.",
    options: ["storm,", "storm;", "storm", "storm."],
    correctAnswer: "A",
    explanation: `Comma after the 'Because' clause. ✓`,
    explanations: { "A": `Comma after the 'Because' clause. ✓`, "B": "Semicolon can’t follow a subordinate clause.", "C": "No separation.", "D": "Fragment." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-48",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Every student in the eighth grade _______ required to complete 10 hours of community service before graduation.",
    options: ["are", "is", "were", "have been"],
    correctAnswer: "B",
    explanation: `'Every student' is singular; 'is' agrees. ✓`,
    explanations: { "A": `'Every' takes singular verb.`, "B": `'Every student' is singular; 'is' agrees. ✓`, "C": "Past tense doesn’t match present context.", "D": "Plural form." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-49",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The art teacher, along with two parent _______ setting up the gallery display for tonight’s open house.",
    options: ["volunteers, are", "volunteers, is", "volunteers are", "volunteers is"],
    correctAnswer: "B",
    explanation: `'Teacher' is singular; comma closes parenthetical; 'is' agrees. ✓`,
    explanations: { "A": `Subject is 'teacher' (singular); 'along with' is parenthetical.`, "B": `'Teacher' is singular; comma closes parenthetical; 'is' agrees. ✓`, "C": "Missing comma.", "D": "Missing comma." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-50",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The class had already _______ the chapter before the teacher assigned the review questions.",
    options: ["read", "readed", "reading", "reads"],
    correctAnswer: "A",
    explanation: `'Had read' is correct past perfect. ✓`,
    explanations: { "A": `'Had read' is correct past perfect. ✓`, "B": `'Readed' is not a word; 'read' is irregular.`, "C": `'Had reading' is incorrect.`, "D": `Present tense doesn’t match 'had.'` },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-51",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The band members practiced _______ instruments every day after school in preparation for the state competition.",
    options: ["they’re", "there", "their", "its"],
    correctAnswer: "C",
    explanation: `'Their' = possessive for plural 'members.' ✓`,
    explanations: { "A": `'They’re'='they are.'`, "B": `'There' indicates a place.`, "C": `'Their' = possessive for plural 'members.' ✓`, "D": `'Its' is singular.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-52",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "Maria, _______ always finishes her homework early, offered to help her classmates with the math assignment.",
    options: ["which", "whom", "who", "whose"],
    correctAnswer: "C",
    explanation: `'Who' is the subject of 'finishes.' ✓`,
    explanations: { "A": `'Which' doesn’t refer to people.`, "B": `'Whom' is an object pronoun; 'finishes' needs a subject.`, "C": `'Who' is the subject of 'finishes.' ✓`, "D": `'Whose' is possessive.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-53",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The experiment worked _______ than anyone expected, producing results that exceeded even the teacher’s most optimistic predictions.",
    options: ["more better", "better", "more good", "gooder"],
    correctAnswer: "B",
    explanation: `'Better' is the correct comparative form of 'good/well.' ✓`,
    explanations: { "A": "Double comparative.", "B": `'Better' is the correct comparative form of 'good/well.' ✓`, "C": `'More good' is nonstandard; use 'better.'`, "D": `'Gooder' is not a word.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-rw-54",
    testType: "psat89",
    section: "rw",
    module: 2,
    domain: "Standard English Conventions",
    skill: "Form, Structure, and Sense",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which choice completes the text so that it conforms to the conventions of Standard English?",
    passage: "The two dogs _______ in the backyard when the gate accidentally swung open.",
    options: ["was playing", "were playing", "is playing", "plays"],
    correctAnswer: "B",
    explanation: `'Dogs' is plural; 'were playing' agrees. ✓`,
    explanations: { "A": `'Dogs' is plural; 'was' is singular.`, "B": `'Dogs' is plural; 'were playing' agrees. ✓`, "C": "Singular present; should be plural past.", "D": "Simple present, wrong tense and number." },
    tags: ["practice-test"],
  }
];

const MATH_QUESTIONS: Question[] = [
  {
    id: "pt-psat89-math-1",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If 3x+7=22, what is x?",
    options: ["3", "5", "7", "10"],
    correctAnswer: "B",
    explanation: "3(5)+7=22. ✓",
    explanations: { "A": "3(3)+7=16≠22.", "B": "3(5)+7=22. ✓", "C": "3(7)+7=28.", "D": "3(10)+7=37." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-2",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Solve: 2(x+4)=18",
    options: ["3", "5", "7", "9"],
    correctAnswer: "B",
    explanation: "2(5+4)=2(9)=18. ✓",
    explanations: { "A": "2(7)=14≠18.", "B": "2(5+4)=2(9)=18. ✓", "C": "2(11)=22.", "D": "2(13)=26." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-3",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Slope and y-intercept",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the slope and y-intercept?",
    passage: "A line has equation y=3x−2.",
    options: ["Slope 3, y-intercept −2", "Slope −2, y-intercept 3", "Slope 3, y-intercept 2", "Slope −3, y-intercept −2"],
    correctAnswer: "A",
    explanation: "In y=mx+b, m=3 (slope) and b=−2 (y-intercept). ✓",
    explanations: { "A": "In y=mx+b, m=3 (slope) and b=−2 (y-intercept). ✓", "B": "Reversed slope and intercept.", "C": "y-intercept is −2, not +2.", "D": "Slope is positive 3." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-4",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Systems of equations",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the value of x?",
    passage: `x+y=10
x−y=4`,
    options: ["", "", "", ""],
    correctAnswer: "7",
    explanation: "Add equations: 2x=14, x=7. Then y=3.",
    explanations: { "correct": "Add equations: 2x=14, x=7. Then y=3." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-5",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Word problems",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression represents the total cost for m months?",
    passage: "A gym membership costs $25 per month plus a one-time $50 sign-up fee.",
    options: ["25m+50", "50m+25", "75m", "25+50m"],
    correctAnswer: "A",
    explanation: "$25/month × m months + $50 one-time. ✓",
    explanations: { "A": "$25/month × m months + $50 one-time. ✓", "B": "Reversed the rates.", "C": "Adds both as monthly.", "D": "Same as B, different format." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-6",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Inequalities",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If the final exam is worth e points, which inequality represents what she needs?",
    passage: "A student needs at least 80 points on the final exam to pass. She currently has 65 points from homework and quizzes.",
    options: ["65+e>80", "65+e≥80", "65−e≥80", "e≥80"],
    correctAnswer: "B",
    explanation: "Total (65+e) must be ≥80. ✓",
    explanations: { "A": "She needs at least 80, including equals.", "B": "Total (65+e) must be ≥80. ✓", "C": "Subtracting the exam makes no sense.", "D": "Ignores existing points." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-7",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Evaluating expressions",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If a=3 and b=−2, what is the value of 2a²−3b?",
    options: ["", "", "", ""],
    correctAnswer: "24",
    explanation: "2(9)−3(−2)=18+6=24.",
    explanations: { "correct": "2(9)−3(−2)=18+6=24." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-8",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "FOIL",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is (x+3)(x+5)?",
    options: ["x²+15", "x²+8x+15", "x²+5x+15", "2x+8"],
    correctAnswer: "B",
    explanation: "x²+5x+3x+15=x²+8x+15. ✓",
    explanations: { "A": "Missing middle term.", "B": "x²+5x+3x+15=x²+8x+15. ✓", "C": "3x+5x=8x, not 5x.", "D": "Completely wrong approach." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-9",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Solving quadratics",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What are the solutions of x²−25=0?",
    options: ["x=5 only", "x=−5 only", "x=5 or x=−5", "x=25 or x=−25"],
    correctAnswer: "C",
    explanation: "x²=25. x=±5. ✓",
    explanations: { "A": "Also −5 works.", "B": "Also 5 works.", "C": "x²=25. x=±5. ✓", "D": "Those would solve x²=625." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-10",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Function evaluation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is f(4)?",
    passage: "f(x)=2x+7",
    options: ["11", "14", "15", "16"],
    correctAnswer: "C",
    explanation: "2(4)+7=15. ✓",
    explanations: { "A": "2(4)=8, not 11.", "B": "2(4)=8, 8+7=15, not 14.", "C": "2(4)+7=15. ✓", "D": "Off by 1." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-11",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Exponents",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the result?",
    passage: "Simplify: 3²×3³",
    options: ["", "", "", ""],
    correctAnswer: "243",
    explanation: "3²×3³=3⁵=243.",
    explanations: { "correct": "3²×3³=3⁵=243." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-12",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Ratios",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How many cups are needed for 15 cookies?",
    passage: "A recipe for 6 cookies uses 2 cups of flour.",
    options: ["3", "4", "5", "6"],
    correctAnswer: "C",
    explanation: "2/6=x/15. x=30/6=5. ✓",
    explanations: { "A": "Too few.", "B": "4 cups would make 12 cookies.", "C": "2/6=x/15. x=30/6=5. ✓", "D": "6 cups would make 18 cookies." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-13",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Percentages",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the sale price?",
    passage: "A shirt originally costs $40 and is on sale for 25% off.",
    options: ["$10", "$15", "$25", "$30"],
    correctAnswer: "D",
    explanation: "40−40(0.25)=40−10=30. ✓",
    explanations: { "A": "$10 is the discount amount.", "B": "25% of 40 is 10, not 15.", "C": "$25 would be 37.5% off.", "D": "40−40(0.25)=40−10=30. ✓" },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-14",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Mean",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the mean (average) score?",
    passage: "Test scores: 82, 90, 76, 88, 94",
    options: ["82", "86", "88", "90"],
    correctAnswer: "B",
    explanation: "(82+90+76+88+94)/5=430/5=86. ✓",
    explanations: { "A": "That’s the first score.", "B": "(82+90+76+88+94)/5=430/5=86. ✓", "C": "That’s the median.", "D": "That’s the second score." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-15",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Probability",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the probability of drawing a blue marble? (Enter as a decimal.)",
    passage: "A bag contains 3 red, 5 blue, and 2 green marbles.",
    options: ["", "", "", ""],
    correctAnswer: "0.5",
    explanation: "5/(3+5+2)=5/10=0.5.",
    explanations: { "correct": "5/(3+5+2)=5/10=0.5." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-16",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Data interpretation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Based on the table, which subject is most popular?",
    passage: "A bar graph shows student favorite subjects.",
    options: ["Math", "Science", "English", "History"],
    correctAnswer: "B",
    explanation: "62 students — highest. ✓",
    explanations: { "A": "45 students.", "B": "62 students — highest. ✓", "C": "38 students.", "D": "30 students." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-17",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Scatterplots",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which statement best describes this association?",
    passage: "A scatterplot shows a strong positive association between hours of sleep and test scores.",
    options: ["More sleep causes higher test scores.", "As hours of sleep increase, test scores tend to increase.", "Sleep and test scores are unrelated.", "As hours of sleep increase, test scores decrease."],
    correctAnswer: "B",
    explanation: "Positive association: both increase together. ✓",
    explanations: { "A": "Association doesn’t prove causation.", "B": "Positive association: both increase together. ✓", "C": "They are associated.", "D": "That would be negative association." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-18",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Area",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A rectangle has length 12 cm and width 8 cm. What is its area?",
    options: ["20 cm²", "40 cm²", "80 cm²", "96 cm²"],
    correctAnswer: "D",
    explanation: "A=lw=12×8=96. ✓",
    explanations: { "A": "That’s half the perimeter.", "B": "Perimeter = 2(12+8)=40, not area.", "C": "Close but wrong.", "D": "A=lw=12×8=96. ✓" },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-19",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Pythagorean theorem",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "A right triangle has legs 3 and 4. What is the hypotenuse?",
    options: ["", "", "", ""],
    correctAnswer: "5",
    explanation: "c²=9+16=25. c=5.",
    explanations: { "correct": "c²=9+16=25. c=5." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-20",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Angles",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If one angle measures 115°, what is the other?",
    passage: "Two angles are supplementary.",
    options: ["25°", "55°", "65°", "75°"],
    correctAnswer: "C",
    explanation: "180−115=65. ✓",
    explanations: { "A": "That’s complementary.", "B": "Not supplementary.", "C": "180−115=65. ✓", "D": "Not correct." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-21",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Circumference",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A circle has diameter 14 cm. What is its circumference? (Use π≈3.14)",
    options: ["21.98 cm", "43.96 cm", "153.86 cm", "87.92 cm"],
    correctAnswer: "B",
    explanation: "C=πd=3.14×14=43.96. ✓",
    explanations: { "A": "That’s πd/2.", "B": "C=πd=3.14×14=43.96. ✓", "C": "That’s the area.", "D": "2×circumference." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-22",
    testType: "psat89",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Volume",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A rectangular box has length 5, width 3, and height 4. What is the volume?",
    options: ["12", "24", "60", "94"],
    correctAnswer: "C",
    explanation: "V=lwh=5×3×4=60. ✓",
    explanations: { "A": "Only two dimensions.", "B": "Only two dimensions.", "C": "V=lwh=5×3×4=60. ✓", "D": "That’s surface area." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-23",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Multi-step equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Solve: 4(x−3)+2=18",
    options: ["5", "6", "7", "8"],
    correctAnswer: "C",
    explanation: "4(7−3)+2=4(4)+2=18. ✓",
    explanations: { "A": "4(2)+2=10≠18.", "B": "4(3)+2=14≠18.", "C": "4(7−3)+2=4(4)+2=18. ✓", "D": "4(5)+2=22." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-24",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Equivalent expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression is equivalent to 3(x+4)−2(x−1)?",
    options: ["x+14", "x+10", "5x+10", "x+12"],
    correctAnswer: "A",
    explanation: "3x+12−2x+2=x+14. ✓",
    explanations: { "A": "3x+12−2x+2=x+14. ✓", "B": "Missed distributing negative to −1.", "C": "Added coefficients.", "D": "Only added one constant." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-25",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Systems word problems",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many apples did Jake buy?",
    passage: "A store sells apples for $2 each and bananas for $1 each. Jake bought 8 fruits for $11.",
    options: ["", "", "", ""],
    correctAnswer: "3",
    explanation: "a+b=8, 2a+b=11. Subtract: a=3. Then b=5. Check: 2(3)+1(5)=11. ✓",
    explanations: { "correct": "a+b=8, 2a+b=11. Subtract: a=3. Then b=5. Check: 2(3)+1(5)=11. ✓" },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-26",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Word problems",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "After how many hours (from when the 2nd train leaves) will the second train catch the first?",
    passage: "A train travels at 60 mph. A second train leaves the same station 1 hour later at 80 mph.",
    options: ["2", "3", "4", "5"],
    correctAnswer: "B",
    explanation: "Train 1: 60(4)=240mi. Train 2: 80(3)=240mi. Equal! ✓",
    explanations: { "A": "Train 1: 60(3)=180mi, Train 2: 80(2)=160mi. Not equal.", "B": "Train 1: 60(4)=240mi. Train 2: 80(3)=240mi. Equal! ✓", "C": "Train 1: 60(5)=300, Train 2: 80(4)=320.", "D": "Too long." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-27",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Function notation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is g(4)?",
    passage: "g(x)=x²−3x+2",
    options: ["2", "4", "6", "8"],
    correctAnswer: "C",
    explanation: "16−12+2=6. ✓",
    explanations: { "A": "16−12+2=6, not 2.", "B": "Partial calculation.", "C": "16−12+2=6. ✓", "D": "Too large." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-28",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Slope between points",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the slope of the line through these points?",
    passage: "Points: (1,3) and (5,11)",
    options: ["", "", "", ""],
    correctAnswer: "2",
    explanation: "(11−3)/(5−1)=8/4=2.",
    explanations: { "correct": "(11−3)/(5−1)=8/4=2." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-29",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Parallel lines",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which line is parallel to y=4x+1?",
    options: ["y=4x−3", "y=−4x+1", "y=(1/4)x+1", "y=x+4"],
    correctAnswer: "A",
    explanation: "Same slope (4), different intercept = parallel. ✓",
    explanations: { "A": "Same slope (4), different intercept = parallel. ✓", "B": "Slope −4 is different.", "C": "Slope 1/4 is different.", "D": "Slope 1 is different." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-30",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "FOIL with negatives",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is (x−3)(x+7)?",
    options: ["x²+4x−21", "x²−4x−21", "x²+4x+21", "x²−10x−21"],
    correctAnswer: "A",
    explanation: "x²+7x−3x−21=x²+4x−21. ✓",
    explanations: { "A": "x²+7x−3x−21=x²+4x−21. ✓", "B": "7x−3x=+4x, not −4x.", "C": "(−3)(7)=−21, not +21.", "D": "Middle term wrong." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-31",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Exponential growth",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How many bacteria after 5 hours?",
    passage: "A bacteria colony starts with 100 and doubles every hour.",
    options: ["500", "1,000", "1,600", "3,200"],
    correctAnswer: "D",
    explanation: "100×2⁵=100×32=3,200. ✓",
    explanations: { "A": "That’s linear (100×5).", "B": "Doubled twice (100→2→4→)... too few doublings.", "C": "After 4 doublings.", "D": "100×2⁵=100×32=3,200. ✓" },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-32",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Solving quadratics",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If x²−16=0, what is the positive value of x?",
    options: ["", "", "", ""],
    correctAnswer: "4",
    explanation: "x²=16. x=±4. Positive value: 4.",
    explanations: { "correct": "x²=16. x=±4. Positive value: 4." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-33",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Growth vs decay",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression represents its value after t years?",
    passage: "A phone costs $800 and loses 20% of its value each year.",
    options: ["800(0.20)ᵗ", "800(0.80)ᵗ", "800−160t", "800(1.20)ᵗ"],
    correctAnswer: "B",
    explanation: "Retains 80% each year: 800(0.80)ᵗ. ✓",
    explanations: { "A": "0.20 is the loss rate.", "B": "Retains 80% each year: 800(0.80)ᵗ. ✓", "C": "Linear, not exponential.", "D": "1.20 means gaining 20%." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-34",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Percent change",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What was the percent increase?",
    passage: "A store’s revenue increased from $20,000 to $25,000.",
    options: ["20%", "25%", "30%", "50%"],
    correctAnswer: "B",
    explanation: "(25000−20000)/20000=5000/20000=25%. ✓",
    explanations: { "A": "Increase is 5000. 5000/20000=0.25=25%, not 20%.", "B": "(25000−20000)/20000=5000/20000=25%. ✓", "C": "No basis.", "D": "5000/10000, wrong denominator." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-35",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Two-way tables",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How many like pizza but NOT tacos?",
    passage: "150 students surveyed: 90 like pizza, 40 like tacos, 20 like both.",
    options: ["50", "70", "90", "110"],
    correctAnswer: "B",
    explanation: "Pizza only: 90−20=70. ✓",
    explanations: { "A": "That’s too few.", "B": "Pizza only: 90−20=70. ✓", "C": "90 includes those who like both.", "D": "More than the pizza total." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-36",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Unit rates",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many miles per gallon?",
    passage: "A car travels 240 miles on 8 gallons of gas.",
    options: ["", "", "", ""],
    correctAnswer: "30",
    explanation: "240/8=30 mpg.",
    explanations: { "correct": "240/8=30 mpg." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-37",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Percent of a whole",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What percentage earned an A or B?",
    passage: "In a class of 30 students, 18 earned an A or B on the test.",
    options: ["40%", "50%", "60%", "70%"],
    correctAnswer: "C",
    explanation: "18/30=0.60=60%. ✓",
    explanations: { "A": "12/30=40%, that’s those who didn’t.", "B": "15/30=50%.", "C": "18/30=0.60=60%. ✓", "D": "21/30=70%." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-38",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Misleading statistics",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Why might the reported average be misleading?",
    passage: `A school reports that the 'average' student reads 5 books per month. The data shows: 25 students read 1−2 books, 3 students read 20+ books.`,
    options: ["The sample is too large.", "A few students who read many books pull the mean much higher than what is typical for most students.", "The school didn’t count graphic novels.", "Five books is a lot."],
    correctAnswer: "B",
    explanation: "3 students at 20+ skew the mean up; most read 1−2. Median would better represent the typical student. ✓",
    explanations: { "A": "Larger samples are generally better.", "B": "3 students at 20+ skew the mean up; most read 1−2. Median would better represent the typical student. ✓", "C": "Not mentioned as an issue.", "D": `Whether 5 is 'a lot' isn’t the statistical concern.` },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-39",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Triangle angle sum",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the third angle?",
    passage: "A triangle has angles of 45° and 65°.",
    options: ["60°", "70°", "80°", "90°"],
    correctAnswer: "B",
    explanation: "180−45−65=70. ✓",
    explanations: { "A": "45+65+60=170≠180.", "B": "180−45−65=70. ✓", "C": "45+65+80=190.", "D": "45+65+90=200." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-40",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Area of triangle",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A triangle has base 10 and height 6. Area?",
    options: ["16", "30", "60", "36"],
    correctAnswer: "B",
    explanation: "A=½(10)(6)=30. ✓",
    explanations: { "A": "Perimeter idea.", "B": "A=½(10)(6)=30. ✓", "C": "Forgot the ½.", "D": "No basis." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-41",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Pythagorean theorem",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "A right triangle has legs 8 and 15. What is the hypotenuse?",
    options: ["", "", "", ""],
    correctAnswer: "17",
    explanation: "c²=64+225=289. c=17.",
    explanations: { "correct": "c²=64+225=289. c=17." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-42",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Circle area",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A circular garden has radius 7 feet. What is its area? (Use π≈3.14)",
    options: ["21.98 sq ft", "43.96 sq ft", "153.86 sq ft", "307.72 sq ft"],
    correctAnswer: "C",
    explanation: "A=πr²=3.14(49)=153.86. ✓",
    explanations: { "A": "That’s πr.", "B": "That’s circumference.", "C": "A=πr²=3.14(49)=153.86. ✓", "D": "2πr², wrong formula." },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-43",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Cylinder volume",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the volume? (Use π≈3.14)",
    passage: "A cylindrical water tank has radius 3 feet and height 10 feet.",
    options: ["90 cu ft", "94.2 cu ft", "188.4 cu ft", "282.6 cu ft"],
    correctAnswer: "D",
    explanation: "V=πr²h=3.14(9)(10)=282.6. ✓",
    explanations: { "A": "Missing π.", "B": "Using diameter instead of radius.", "C": "Using r not r².", "D": "V=πr²h=3.14(9)(10)=282.6. ✓" },
    tags: ["practice-test"],
  },
  {
    id: "pt-psat89-math-44",
    testType: "psat89",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Coordinate geometry",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "In which quadrant is this point?",
    passage: "A point is at (−3,4).",
    options: ["Quadrant I", "Quadrant II", "Quadrant III", "Quadrant IV"],
    correctAnswer: "B",
    explanation: "QII: x negative, y positive. (−3,4) ✓",
    explanations: { "A": "QI: both positive.", "B": "QII: x negative, y positive. (−3,4) ✓", "C": "QIII: both negative.", "D": "QIV: x positive, y negative." },
    tags: ["practice-test"],
  }
];

export default function PSAT89PracticeTest() {
  return (
    <PracticeTest
      rwQuestions={RW_QUESTIONS}
      mathQuestions={MATH_QUESTIONS}
      testType="psat89"
      title="PSAT 8/9 Practice Test"
      rwTime={[32, 32]}
      mathTime={[35, 35]}
    />
  );
}


