"use client";

import { ModuleShell } from "@/components/course/module-shell";
import type { ModuleConfig } from "@/types/module";
import {
  TransitionTaxonomyVisual,
  RelationshipMethodVisual,
  SynthesisVisual,
} from "./lesson-visuals";

export default function NMSQTRWModule8() {
  return (
    <ModuleShell
      config={MODULE_CONFIG}
      visuals={{
        "transition-taxonomy": <TransitionTaxonomyVisual />,
        "relationship-method": <RelationshipMethodVisual />,
        "synthesis": <SynthesisVisual />,
      }}
      nextModuleHref="/courses/nmsqt-rw/9"
      nextModuleLabel="Module 9: Expression of Ideas"
    />
  );
}

const MODULE_CONFIG: ModuleConfig = {
  testType: "nmsqt",
  section: "rw",
  moduleNum: 8,
  title: "Transitions & Synthesis",
  subtitle:
    "Logical connections and rhetorical synthesis -- the Expression of Ideas domain.",
  accentColor: "#d4a017",
  screens: [
    { id: "welcome", label: "Welcome", icon: "wave" },
    { id: "warmup", label: "Warm-Up", icon: "brain" },
    { id: "lesson", label: "Lesson", icon: "book" },
    { id: "quiz", label: "Practice", icon: "target" },
    { id: "challenge", label: "Challenge", icon: "flame" },
    { id: "complete", label: "Complete", icon: "trophy" },
  ],

  warmup: [
    {
      source: "Module 4 -- Words in Context",
      stem: "The sculptor's work was defined by its _______ -- massive stone forms reduced to their simplest geometric shapes, with no ornament or surface detail.\n\nWhich word best completes the text?",
      choices: ["austerity", "complexity", "flamboyance", "fragility"],
      correct: 0,
      explanation: '"Simplest geometric shapes, no ornament" = stripped down. "Austerity" = severe simplicity.',
    },
    {
      source: "Module 7 -- Transitions",
      stem: "The coral reef had been severely damaged by bleaching. _______ marine biologists were surprised to find 60% had regenerated by 2024.\n\nWhich transition best completes the text?",
      choices: ["Similarly,", "For instance,", "Nevertheless,", "Therefore,"],
      correct: 2,
      explanation: 'Severe damage then surprising recovery. "Nevertheless" = despite that.',
    },
    {
      source: "Module 3 -- Boundaries",
      stem: "The committee voted to approve the proposal, which included new safety standards for all commercial _______ after two years of public consultation.\n\nWhich choice conforms to Standard English?",
      choices: ["buildings after", "buildings. After", "buildings; after", "buildings, after"],
      correct: 3,
      explanation: 'The "which" clause ends at "buildings." Comma + "after" begins a participial phrase.',
    },
    {
      source: "Module 5 -- Central Ideas",
      stem: "Research shows that children who learn to play chess before age 7 achieve grandmaster status at higher rates, but those children also practiced twice as many hours weekly. The study could not determine whether the advantage stemmed from early cognitive development or accumulated practice time.\n\nBased on the text, which inference is best supported?",
      choices: ["The age-related advantage may reflect practice hours rather than a developmental window.", "Chess should be taught in preschools.", "Starting chess early causes superior cognitive development.", "Players who start after 12 cannot achieve grandmaster status."],
      correct: 0,
      explanation: "The advantage MIGHT be practice hours, not age. (B) captures this uncertainty.",
    },
  ],

  lessons: [
    {
      id: "transition-taxonomy",
      title: "The Transition Taxonomy",
      subtitle: "Seven relationships, seven word families",
      visual: "transition-taxonomy",
      body: [
        "Transition questions (~$6$ per test) ask you to select the word or phrase that best connects two ideas. The key: identify the RELATIONSHIP between the sentences first, then find the transition that matches.",
        "The seven relationships: (1) Addition/Continuation: Furthermore, Moreover, Additionally, In addition. (2) Contrast: However, Nevertheless, Conversely, On the other hand. (3) Cause/Effect: Therefore, Consequently, As a result, Thus. (4) Example: For instance, For example, Specifically. (5) Comparison: Similarly, Likewise, In the same way. (6) Time/Sequence: Meanwhile, Subsequently, Then, Previously. (7) Surprise: Surprisingly, Unexpectedly, Remarkably.",
        "The #1 trap: using a contrast transition when the relationship is actually addition, or vice versa. Always check: do these two ideas agree or disagree?",
      ],
    },
    {
      id: "transition-method",
      title: "The Relationship-First Method",
      subtitle: "Don't read the choices first",
      visual: "relationship-method",
      body: [
        "Step 1: Read BOTH sentences (before and after the blank). Step 2: Determine the relationship WITHOUT looking at the choices. Step 3: THEN find the matching transition.",
        "This prevents the most common mistake: being drawn to a transition that 'sounds right' but misrepresents the relationship.",
        "Key signals: 'Despite,' 'although,' 'even though' = contrast is already built in. 'Because,' 'since,' 'given that' = cause is already built in. Don't double up!",
      ],
    },
    {
      id: "synthesis",
      title: "Rhetorical Synthesis",
      subtitle: "The most novel question type",
      visual: "synthesis",
      body: [
        "Synthesis questions (~$6$ per test) give you a set of bulleted research notes and ask you to select the answer that accomplishes a specific rhetorical goal.",
        "The key skill: read the GOAL first, then find the answer that uses the notes to accomplish that specific goal. Common goals: 'emphasize a contrast,' 'introduce a topic by highlighting its significance,' 'present a finding and its implication.'",
        "Strategy: (1) Read the goal carefully. (2) Identify which notes are relevant to that goal. (3) Find the answer that combines the relevant notes in a way that achieves the goal. Ignore notes that don't serve the goal.",
      ],
    },
  ],

  quiz: [
    {
      passage: "The orchestra's performance of Beethoven's Fifth was technically flawless. _______ critics felt it lacked the emotional intensity that distinguishes a good performance from a great one.",
      stem: "Which transition best completes the text?",
      choices: ["For instance,", "Accordingly,", "Nevertheless,", "Moreover,"],
      correct: 2,
      explanation: 'Technically flawless (positive) -> lacked emotion (negative despite the positive). "Nevertheless."',
      type: "Transitions",
      difficulty: "easy",
      domain: "Expression of Ideas",
      skill: "transitions",
    },
    {
      passage: "The painting's vivid reds and oranges immediately draw the viewer's eye to the foreground. _______ the muted blues and grays of the background create a sense of depth and distance.",
      stem: "Which transition best completes the text?",
      choices: ["For example,", "Therefore,", "Meanwhile,", "Similarly,"],
      correct: 2,
      explanation: 'Two simultaneous visual effects. "Meanwhile" = at the same time.',
      type: "Transitions",
      difficulty: "easy",
      domain: "Expression of Ideas",
      skill: "transitions",
    },
    {
      passage: "The city banned single-use plastic bags in 2020. _______ a follow-up study found that overall plastic waste had actually increased by 12%, driven by a surge in thicker 'reusable' bags that consumers discarded after one use.",
      stem: "Which transition best completes the text?",
      choices: ["Surprisingly,", "For instance,", "As a result,", "In addition,"],
      correct: 0,
      explanation: 'Ban expected to reduce waste -> waste actually increased. Unexpected. "Surprisingly."',
      type: "Transitions",
      difficulty: "medium",
      domain: "Expression of Ideas",
      skill: "transitions",
    },
    {
      passage: "The human gut contains approximately 100 trillion microorganisms. The gut microbiome influences digestion, immune function, and even mood. A 2024 meta-analysis linked low microbial diversity to higher rates of depression, obesity, and autoimmune disease. Factors reducing diversity include antibiotic overuse and processed food diets. Fecal transplantation has shown 90% success for treating C. difficile infections.",
      stem: "Which choice effectively presents the gut microbiome as a critical but underappreciated factor in overall health?",
      choices: ["The gut-brain axis connects intestinal microbes to neurological function.", "The human gut houses roughly 100 trillion microorganisms that influence far more than digestion: emerging research links microbial diversity to immune function, mood regulation, and resistance to conditions ranging from depression to autoimmune disease -- yet common modern habits like antibiotic overuse and processed diets are steadily depleting this hidden ecosystem.", "Factors reducing gut diversity include antibiotics and processed food.", "Fecal transplants successfully treat 90% of C. difficile infections."],
      correct: 1,
      explanation: 'Goal: critical + underappreciated. (B) establishes scope, the "hidden" framing, AND the modern threat.',
      type: "Synthesis",
      difficulty: "medium",
      domain: "Expression of Ideas",
      skill: "transitions",
    },
    {
      passage: "The platypus is one of only five egg-laying mammals. Male platypuses have venomous spurs. The platypus uses electroreception to detect prey underwater. The platypus genome contains genes from birds, reptiles, and mammals. Indigenous Australians have cultural stories about the platypus dating back thousands of years.",
      stem: "Which choice effectively presents the platypus as an animal that defies biological classification?",
      choices: ["The platypus defies easy classification: it lays eggs like a reptile, produces venom like a snake, detects prey through electroreception like a shark, and has a genome containing genes from birds, reptiles, and mammals.", "The platypus is one of only five species of monotremes.", "Male platypuses possess venomous spurs, making them one of the few venomous mammals.", "The platypus has been featured in Indigenous Australian cultural stories for thousands of years."],
      correct: 0,
      explanation: 'Goal: defies classification. (C) lists traits from multiple animal classes + mixed genome.',
      type: "Synthesis",
      difficulty: "medium",
      domain: "Expression of Ideas",
      skill: "transitions",
    },
    {
      passage: "The Svalbard Global Seed Vault, opened in 2008, stores over 1.1 million seed samples. It is located inside a mountain 1,300 km from the North Pole. The vault's permafrost keeps seeds frozen even without electricity. In 2015, seeds were withdrawn for the first time to replace collections destroyed by the Syrian civil war. The vault holds seeds from 6,000 plant species.",
      stem: "Which choice introduces the seed vault by emphasizing both its purpose and its real-world use?",
      choices: ["Opened in 2008, the vault stores over 1.1 million seed samples representing 6,000 plant species.", "The vault's permafrost ensures seeds remain frozen during power outages.", "The vault is located inside a mountain on a remote Norwegian island.", "The Svalbard Global Seed Vault -- a repository of over 1.1 million seed samples frozen inside an Arctic mountain -- proved its value in 2015, when seeds were withdrawn for the first time to replace collections destroyed by Syria's civil war."],
      correct: 3,
      explanation: "Goal: purpose + real-world use. (C) includes purpose (repository) AND real-world use (2015 Syria withdrawal).",
      type: "Synthesis",
      difficulty: "hard",
      domain: "Expression of Ideas",
      skill: "transitions",
    },
  ],

  challenge: [
    {
      passage: 'The word "sanction" can mean either "to approve" or "to penalize." When the United Nations announced it would sanction the regime, commentators initially _______ whether the organization intended to legitimize or punish the government.',
      stem: "Which word best completes the text?",
      choices: ["debated", "confirmed", "ignored", "resolved"],
      correct: 0,
      explanation: 'Ambiguity about meaning -> people questioned which sense was intended. "Debated."',
      difficulty: "hard",
      domain: "Expression of Ideas",
      skill: "transitions",
    },
    {
      passage: "Text 1: Neuroscientist Park argues that adolescent risk-taking is driven by an imbalance between a mature limbic system and an immature prefrontal cortex.\n\nText 2: Neuroscientist Alvarez agrees the brain regions Park identifies are relevant but argues that framing adolescence as a 'deficit' in prefrontal control is misleading. Alvarez contends that heightened risk-taking is an adaptive feature promoting exploration and social learning.",
      stem: "What is the fundamental nature of the disagreement?",
      choices: ["Whether the prefrontal cortex develops during adolescence.", "Whether adolescence is a real developmental stage.", "Whether adolescent risk-taking is a developmental flaw or an adaptive feature.", "Whether the limbic system is involved in risk-taking."],
      correct: 2,
      explanation: "Both agree on the brain regions. They disagree on INTERPRETATION: deficit vs. adaptive feature.",
      difficulty: "hard",
      domain: "Expression of Ideas",
      skill: "transitions",
    },
  ],

  takeaways: [
    "Every transition expresses one of six relationships: addition, contrast, cause/effect, example, sequence, summary.",
    "Always identify the relationship FIRST, then match the transition.",
    "'However' = unexpected contrast. 'Therefore' = logical result. 'For example' = specific instance. 'Moreover' = additional similar point.",
    "The hardest questions test distinctions within a category: 'however' vs. 'conversely' vs. 'nevertheless' vs. 'in contrast.'",
    "Target under 60 seconds per transition question on test day.",
  ],
};
