"use client";

import { DiagnosticTest } from "@/components/test/diagnostic-test";
import type { Question } from "@/types/question";

const QUESTIONS: Question[] = [
  {
    id: "diag-sat-math-1",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear equations in 1 variable",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If 3(2x − 4) = 18, what is the value of x?",
    options: ["3", "5", "7", "11"],
    correctAnswer: "B",
    explanation: "Distribute: 6x−12=18. Add 12: 6x=30. Divide: x=5. Check: 3(10−4)=3(6)=18. ✓",
    explanations: { "A": "If x=3: 3(6−4)=6, not 18.", "B": "Distribute: 6x−12=18. Add 12: 6x=30. Divide: x=5. Check: 3(10−4)=3(6)=18. ✓", "C": "Likely from dividing 18 by 3 and adding 4 without accounting for the coefficient of x.", "D": "Comes from adding 18+4=22, then ignoring the factor of 6." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-2",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear inequalities",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which inequality represents the number of hours h of labor the client can afford?",
    passage: "A landscaping company charges $75 for a consultation plus $40 per hour of labor. A client has a budget of $355 for a project.",
    options: ["75h + 40 ≤ 355", "40h + 75 ≤ 355", "40h + 75 ≥ 355", "75 + 40h > 355"],
    correctAnswer: "B",
    explanation: "Total cost = 75 + 40h. To stay within budget: 40h + 75 ≤ 355. Solving: 40h ≤ 280, h ≤ 7 hours. ✓",
    explanations: { "A": "This reverses the roles of 75 and 40. The $75 is a flat fee, not a per-hour rate.", "B": "Total cost = 75 + 40h. To stay within budget: 40h + 75 ≤ 355. Solving: 40h ≤ 280, h ≤ 7 hours. ✓", "C": "This says the cost must be at least $355 — the opposite of a budget constraint.", "D": "This says the cost must exceed the budget, which is the wrong direction." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-3",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Linear functions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Line ℓ passes through the points (−2, 5) and (4, −1). What is the slope of line ℓ?",
    options: ["−1", "−2/3", "2/3", "1"],
    correctAnswer: "A",
    explanation: "Slope = (y₂−y₁)/(x₂−x₁) = (−1−5)/(4−(−2)) = −6/6 = −1. ✓",
    explanations: { "A": "Slope = (y₂−y₁)/(x₂−x₁) = (−1−5)/(4−(−2)) = −6/6 = −1. ✓", "B": "This results from a sign error in the denominator: using 4−2=2 instead of 4−(−2)=6.", "C": "This flips the sign; the line clearly goes down from left to right.", "D": "Correct magnitude but wrong sign. The line decreases, so slope is negative." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-4",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Systems of linear equations",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the value of y?",
    passage: `The system of equations below has a solution (x, y).

2x + 3y = 19
4x − y = 3`,
    options: ["", "", "", ""],
    correctAnswer: "5",
    explanation: "From the second equation: y = 4x − 3. Substitute into the first: 2x + 3(4x − 3) = 19 → 2x + 12x − 9 = 19 → 14x = 28 → x = 2. Then y = 4(2) − 3 = 5.",
    explanations: { "correct": "From the second equation: y = 4x − 3. Substitute into the first: 2x + 3(4x − 3) = 19 → 2x + 12x − 9 = 19 → 14x = 28 → x = 2. Then y = 4(2) − 3 = 5." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-5",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Equivalent expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which of the following is equivalent to 2(3x − 1) − (x + 5)?",
    options: ["5x − 7", "5x + 3", "5x − 3", "7x − 7"],
    correctAnswer: "A",
    explanation: "Distribute: 6x − 2 − x − 5 = 5x − 7. ✓",
    explanations: { "A": "Distribute: 6x − 2 − x − 5 = 5x − 7. ✓", "B": "Sign error: forgot to distribute the negative to the +5, getting −2+5=3.", "C": "Only partially distributed the negative: got −2−(−5) instead of −2−5.", "D": "Added the x-coefficients as 6+1=7 instead of 6−1=5." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-6",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Systems of equations (word problems)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "For how many hours of rental will both shops charge the same amount?",
    passage: `The table shows the cost C (in dollars) of renting a kayak for h hours at two rental shops.

Shop A: C = 15h + 20
Shop B: C = 12h + 35`,
    options: ["3", "5", "7", "15"],
    correctAnswer: "B",
    explanation: "Set equal: 15h + 20 = 12h + 35 → 3h = 15 → h = 5. Check: A = 95, B = 95. ✓",
    explanations: { "A": "At h=3: Shop A = 65, Shop B = 71. Not equal.", "B": "Set equal: 15h + 20 = 12h + 35 → 3h = 15 → h = 5. Check: A = 95, B = 95. ✓", "C": "At h=7: Shop A = 125, Shop B = 119. Not equal.", "D": "15 is the value of 3h, not h." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-7",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Algebra",
    skill: "Function notation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If f(x) = 4x − 7, what is the value of f(−3)?",
    options: ["−19", "−5", "5", "19"],
    correctAnswer: "A",
    explanation: "f(−3) = 4(−3) − 7 = −12 − 7 = −19. ✓",
    explanations: { "A": "f(−3) = 4(−3) − 7 = −12 − 7 = −19. ✓", "B": "This comes from computing 4(−3) + 7 = −5 (wrong sign on 7).", "C": "Absolute value error: |−12−7| would be 19, not 5. This is 4(3)−7.", "D": "Used |4(−3)−7| = |−19| = 19, dropping the negative." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-8",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Equivalent expressions (factoring)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which of the following is equivalent to x² − 9?",
    options: ["(x − 3)²", "(x + 3)(x − 3)", "(x − 9)(x + 1)", "(x + 9)(x − 1)"],
    correctAnswer: "B",
    explanation: "Difference of squares: a²−b² = (a+b)(a−b). Here a=x, b=3. x²−9 = (x+3)(x−3). ✓",
    explanations: { "A": "(x−3)² = x²−6x+9, not x²−9. Missing the cross term.", "B": "Difference of squares: a²−b² = (a+b)(a−b). Here a=x, b=3. x²−9 = (x+3)(x−3). ✓", "C": "(x−9)(x+1) = x²−8x−9. Incorrect factoring.", "D": "(x+9)(x−1) = x²+8x−9. Also incorrect." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-9",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Quadratic equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What are the solutions of x² − 5x − 6 = 0?",
    options: ["x = −1 and x = 6", "x = 1 and x = −6", "x = −2 and x = 3", "x = 2 and x = −3"],
    correctAnswer: "A",
    explanation: "Factor: (x−6)(x+1) = 0. Two numbers that multiply to −6 and add to −5 are −6 and +1. So x=6 or x=−1. ✓",
    explanations: { "A": "Factor: (x−6)(x+1) = 0. Two numbers that multiply to −6 and add to −5 are −6 and +1. So x=6 or x=−1. ✓", "B": "Sign error in factoring. (x−1)(x+6) gives x²+5x−6, not x²−5x−6.", "C": "(x+2)(x−3) = x²−x−6. The middle term is wrong.", "D": `(x−2)(x+3) = x²+x−6. Also doesn't match.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-10",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Radical/rational equations",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If (x + 3)² = 49, what is the positive value of x?",
    options: ["", "", "", ""],
    correctAnswer: "4",
    explanation: "Take square root: x + 3 = ±7. So x = 4 or x = −10. The positive value is 4.",
    explanations: { "correct": "Take square root: x + 3 = ±7. So x = 4 or x = −10. The positive value is 4." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-11",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Quadratic functions (vertex)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The function g is defined by g(x) = 2x² − 8x + 6. What is the minimum value of g(x)?",
    options: ["−2", "−1", "0", "2"],
    correctAnswer: "A",
    explanation: "Complete the square: g(x) = 2(x²−4x) + 6 = 2(x²−4x+4−4) + 6 = 2(x−2)² − 8 + 6 = 2(x−2)² − 2. Minimum value is −2 when x=2. ✓",
    explanations: { "A": "Complete the square: g(x) = 2(x²−4x) + 6 = 2(x²−4x+4−4) + 6 = 2(x−2)² − 8 + 6 = 2(x−2)² − 2. Minimum value is −2 when x=2. ✓", "B": "Arithmetic error in completing the square.", "C": "This is g(1) = 2−8+6 = 0, but not the minimum.", "D": "This is g(0) = 6, also not the minimum." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-12",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Exponential functions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which function models the population P after t hours?",
    passage: "A population of bacteria doubles every 3 hours. At time t = 0, there are 500 bacteria.",
    options: ["P(t) = 500(2)^(t/3)", "P(t) = 500(2)^(3t)", "P(t) = 500(3)^(t/2)", "P(t) = 500 + 2t/3"],
    correctAnswer: "A",
    explanation: "Doubling every 3 hours means the growth factor is 2 per 3-hour period. In t hours there are t/3 periods, so P(t) = 500·2^(t/3). ✓",
    explanations: { "A": "Doubling every 3 hours means the growth factor is 2 per 3-hour period. In t hours there are t/3 periods, so P(t) = 500·2^(t/3). ✓", "B": "This doubles every 1/3 hour (20 min), far too fast.", "C": "Uses base 3 and period 2 — swapped values.", "D": `Linear model, not exponential. Bacteria don't grow at a constant rate.` },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-13",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Polynomial functions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If p(x) = x³ + 2x² − 5x − 6, which of the following is a factor of p(x)?",
    options: ["(x − 1)", "(x + 4)", "(x − 3)", "(x + 3)"],
    correctAnswer: "D",
    explanation: "p(−3) = −27+18+15−6 = 0. So (x+3) is a factor. ✓ The polynomial factors as (x+1)(x−2)(x+3).",
    explanations: { "A": "p(1) = 1+2−5−6 = −8 ≠ 0.", "B": "p(−4) = −64+32+20−6 = −18 ≠ 0.", "C": "p(3) = 27+18−15−6 = 24 ≠ 0.", "D": "p(−3) = −27+18+15−6 = 0. So (x+3) is a factor. ✓ The polynomial factors as (x+1)(x−2)(x+3)." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-14",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Advanced Math",
    skill: "Equivalent expressions",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If (2x + 5)(x − 3) = 2x² + bx − 15, what is the value of b?",
    options: ["", "", "", ""],
    correctAnswer: "-1",
    explanation: "Expand: (2x+5)(x−3) = 2x²−6x+5x−15 = 2x²−x−15. So b = −1.",
    explanations: { "correct": "Expand: (2x+5)(x−3) = 2x²−6x+5x−15 = 2x²−x−15. So b = −1." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-15",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Percentages",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the final sale price of the jacket?",
    passage: "A store marks up the wholesale price of a jacket by 60%, then offers a 25% discount on the marked-up price. The wholesale price is $80.",
    options: ["$92.00", "$96.00", "$100.80", "$108.00"],
    correctAnswer: "B",
    explanation: "Markup: 80 × 1.60 = $128. Discount: 128 × 0.75 = $96. ✓",
    explanations: { "A": `This comes from a 15% markup (60−25=35% error). Sequential percentages don't subtract.`, "B": "Markup: 80 × 1.60 = $128. Discount: 128 × 0.75 = $96. ✓", "C": "Computed 60% of 80 = 48, then subtracted 25% of 48 = 12, getting 80+48−12 = 116. Incorrect method.", "D": "Only applied the 60% markup on the original $80 minus 25% of $80: 128−20 = 108. Discount should apply to marked-up price." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-16",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Two-way tables / conditional probability",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What fraction of students who play a sport are also in a club?",
    passage: "A survey of 200 students found that 120 play a sport, 90 are in a club, and 40 do both.",
    options: ["1/5", "1/3", "2/9", "4/9"],
    correctAnswer: "B",
    explanation: "Of the 120 who play a sport, 40 are also in a club. 40/120 = 1/3. ✓",
    explanations: { "A": "40/200 = 1/5 is the fraction of ALL students who do both, not the conditional.", "B": "Of the 120 who play a sport, 40 are also in a club. 40/120 = 1/3. ✓", "C": "40/180 — incorrect denominator.", "D": "40/90 — this is the fraction of club members who also play a sport, which is the wrong condition." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-17",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Ratios and proportions",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many cups of sugar are needed?",
    passage: "A recipe calls for flour and sugar in a ratio of 5 : 2. If 3.5 cups of flour are used, how many cups of sugar are needed?",
    options: ["", "", "", ""],
    correctAnswer: "1.4",
    explanation: "flour/sugar = 5/2, so 3.5/sugar = 5/2. Cross multiply: 5 × sugar = 7 → sugar = 7/5 = 1.4 cups.",
    explanations: { "correct": "flour/sugar = 5/2, so 3.5/sugar = 5/2. Cross multiply: 5 × sugar = 7 → sugar = 7/5 = 1.4 cups." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-18",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Problem-Solving & Data Analysis",
    skill: "Scatterplots and regression",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which of the following is the best interpretation of r² = 0.81?",
    passage: "A researcher collected data on study hours and test scores for 15 students and found a linear regression model with r² = 0.81.",
    options: ["81% of students scored above average on the test.", "For every additional hour of study, the test score increases by 81%.", "Approximately 81% of the variation in test scores is explained by the number of study hours.", "The correlation between study hours and test scores is 0.81."],
    correctAnswer: "C",
    explanation: "r² is the coefficient of determination: the proportion of variation in the dependent variable explained by the independent variable. ✓",
    explanations: { "A": `r² doesn't describe what percentage of students achieved a certain score.`, "B": `r² isn't a rate of change — that's the slope of the regression line.`, "C": "r² is the coefficient of determination: the proportion of variation in the dependent variable explained by the independent variable. ✓", "D": "The correlation r = √0.81 = 0.9, not 0.81. r² and r are different values." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-19",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Circle equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A circle has the equation (x − 3)² + (y + 2)² = 25. What is the radius of the circle?",
    options: ["3", "5", "12.5", "25"],
    correctAnswer: "B",
    explanation: "The standard form is (x−h)²+(y−k)²=r². Here r²=25, so r=5. ✓",
    explanations: { "A": "3 is the x-coordinate of the center, not the radius.", "B": "The standard form is (x−h)²+(y−k)²=r². Here r²=25, so r=5. ✓", "C": "25/2 = 12.5 — no reason to divide by 2.", "D": "25 is r², not r. Must take the square root." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-20",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Right triangles / Pythagorean theorem",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "A right triangle has legs of length 9 and 12. What is the length of the hypotenuse?",
    options: ["", "", "", ""],
    correctAnswer: "15",
    explanation: "By the Pythagorean theorem: c² = 9² + 12² = 81 + 144 = 225. So c = 15. (This is a 3-4-5 triple scaled by 3.)",
    explanations: { "correct": "By the Pythagorean theorem: c² = 9² + 12² = 81 + 144 = 225. So c = 15. (This is a 3-4-5 triple scaled by 3.)" },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-21",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Trigonometric ratios",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is sin(A)?",
    passage: "In right triangle ABC, angle C = 90°, AC = 5, and BC = 12.",
    options: ["5/13", "12/13", "5/12", "12/5"],
    correctAnswer: "B",
    explanation: "First find AB (hypotenuse): √(25+144) = √169 = 13. sin(A) = opposite/hypotenuse = BC/AB = 12/13. ✓",
    explanations: { "A": "This is cos(A). sin(A) = opposite/hypotenuse, and the side opposite A is BC.", "B": "First find AB (hypotenuse): √(25+144) = √169 = 13. sin(A) = opposite/hypotenuse = BC/AB = 12/13. ✓", "C": "This is tan(A) with sides reversed: 5/12 = adjacent/opposite.", "D": "This is tan(A) = opposite/adjacent = 12/5." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-22",
    testType: "sat",
    section: "math",
    module: 1,
    domain: "Geometry & Trigonometry",
    skill: "Volume",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "What is the volume of the cylinder, in cubic centimeters?",
    passage: "A cylinder has a radius of 4 cm and a height of 10 cm.",
    options: ["40π", "80π", "160π", "640π"],
    correctAnswer: "C",
    explanation: "V = πr²h = π(16)(10) = 160π. ✓",
    explanations: { "A": "40π = π(4)(10), using V = πrh instead of πr²h.", "B": "80π = π(4)²(10)/2 — no reason to halve the volume.", "C": "V = πr²h = π(16)(10) = 160π. ✓", "D": "640π = π(4)³(10) — used r³ instead of r²." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-23",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Linear equations with fractions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The equation (3/4)x − (2/3) = (5/6)x + 1 has what solution for x?",
    options: ["−20", "−10", "10", "20"],
    correctAnswer: "A",
    explanation: "Multiply everything by 12: 9x − 8 = 10x + 12. Subtract 9x: −8 = x + 12. Subtract 12: x = −20. ✓",
    explanations: { "A": "Multiply everything by 12: 9x − 8 = 10x + 12. Subtract 9x: −8 = x + 12. Subtract 12: x = −20. ✓", "B": "Sign error or arithmetic mistake in clearing fractions.", "C": "Forgot to multiply the constant terms by 12.", "D": "Positive version — dropped a negative sign." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-24",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Special solutions (identity equations)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "For what value of a does the equation a(x + 2) = 3x + 6 have infinitely many solutions?",
    options: ["1", "2", "3", "6"],
    correctAnswer: "C",
    explanation: "3(x+2)=3x+6, which equals the right side for ALL x. Infinitely many solutions. ✓",
    explanations: { "A": "1(x+2)=x+2, but 3x+6 ≠ x+2 for all x.", "B": "2(x+2)=2x+4, but 3x+6 ≠ 2x+4 for all x.", "C": "3(x+2)=3x+6, which equals the right side for ALL x. Infinitely many solutions. ✓", "D": "6(x+2)=6x+12, not equal to 3x+6 for all x." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-25",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Systems of equations (word problems)",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "How many text messages per month make the two plans cost the same?",
    passage: "A phone plan costs $35 per month plus $0.05 per text message. Another plan costs $20 per month plus $0.15 per text message.",
    options: ["", "", "", ""],
    correctAnswer: "150",
    explanation: "Set equal: 35 + 0.05t = 20 + 0.15t → 15 = 0.10t → t = 150 messages.",
    explanations: { "correct": "Set equal: 35 + 0.05t = 20 + 0.15t → 15 = 0.10t → t = 150 messages." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-26",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Absolute value equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "If |2x − 7| = 11, what is the sum of all possible values of x?",
    options: ["3", "7", "9", "11"],
    correctAnswer: "B",
    explanation: "Case 1: 2x−7 = 11 → x = 9. Case 2: 2x−7 = −11 → x = −2. Sum: 9 + (−2) = 7. ✓",
    explanations: { "A": "One solution is x = −2 and the other is x = 9. Their sum is 7, not 3.", "B": "Case 1: 2x−7 = 11 → x = 9. Case 2: 2x−7 = −11 → x = −2. Sum: 9 + (−2) = 7. ✓", "C": "9 is just one of the two solutions.", "D": "11 is the value on the right side of the equation, not a sum of solutions." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-27",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Perpendicular lines",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Line m is perpendicular to the line y = (2/5)x + 3. What is the slope of line m?",
    options: ["−5/2", "−2/5", "2/5", "5/2"],
    correctAnswer: "A",
    explanation: "Perpendicular slopes are negative reciprocals. The negative reciprocal of 2/5 is −5/2. ✓",
    explanations: { "A": "Perpendicular slopes are negative reciprocals. The negative reciprocal of 2/5 is −5/2. ✓", "B": "This is just the negative, not the reciprocal.", "C": "Same slope means parallel, not perpendicular.", "D": "Reciprocal but not negated." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-28",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Mixture problems",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "How many liters of the 20% solution are used?",
    passage: "A chemist mixes a 20% acid solution with a 50% acid solution to create 30 liters of a 32% acid solution.",
    options: ["12", "15", "18", "24"],
    correctAnswer: "C",
    explanation: "Let x = liters of 20%. Then 30−x = liters of 50%. 0.20x + 0.50(30−x) = 0.32(30). 0.20x + 15 − 0.50x = 9.6. −0.30x = −5.4. x = 18. ✓",
    explanations: { "A": "If 12 L of 20%: 12(0.20)+18(0.50) = 2.4+9.0 = 11.4 → 38%, too high.", "B": "If 15 L of each: 15(0.20)+15(0.50) = 3+7.5 = 10.5 → 35%, too high.", "C": "Let x = liters of 20%. Then 30−x = liters of 50%. 0.20x + 0.50(30−x) = 0.32(30). 0.20x + 15 − 0.50x = 9.6. −0.30x = −5.4. x = 18. ✓", "D": "If 24 L of 20%: 24(0.20)+6(0.50) = 4.8+3.0 = 7.8 → 26%, too low." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-29",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Algebra",
    skill: "Systems of equations",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If 3x − 2y = 12 and x + 2y = 8, what is the value of 2x + y?",
    options: ["", "", "", ""],
    correctAnswer: "11.5",
    explanation: "Add the equations: (3x−2y)+(x+2y) = 12+8 → 4x = 20 → x = 5. Substitute into x+2y=8: 5+2y=8 → 2y=3 → y=1.5. Therefore 2x+y = 2(5)+1.5 = 11.5.",
    explanations: { "correct": "Add the equations: (3x−2y)+(x+2y) = 12+8 → 4x = 20 → x = 5. Substitute into x+2y=8: 5+2y=8 → 2y=3 → y=1.5. Therefore 2x+y = 2(5)+1.5 = 11.5." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-30",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Rational expressions",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which expression is equivalent to (x² − 4x + 4) / (x² − 4)?",
    options: ["(x − 2)/(x + 2)", "(x + 2)/(x − 2)", "1", "(x − 4)/(x − 4)"],
    correctAnswer: "A",
    explanation: "Numerator: x²−4x+4 = (x−2)². Denominator: x²−4 = (x−2)(x+2). Cancel one (x−2): (x−2)/(x+2). ✓",
    explanations: { "A": "Numerator: x²−4x+4 = (x−2)². Denominator: x²−4 = (x−2)(x+2). Cancel one (x−2): (x−2)/(x+2). ✓", "B": "This inverts the result. The (x−2) remains in the numerator.", "C": "The numerator and denominator are not equal expressions.", "D": "Neither the numerator nor denominator factors to (x−4)." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-31",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Vertex form of quadratics",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "The function h(x) = −2(x − 3)² + 8 has a maximum value. What is the x-coordinate of the vertex?",
    options: ["−3", "2", "3", "8"],
    correctAnswer: "C",
    explanation: "In h(x) = −2(x−3)²+8, the vertex is at (3, 8). The x-coordinate is 3. ✓",
    explanations: { "A": `The vertex form is a(x−h)²+k, so h=3, not −3. Don't negate the value inside.`, "B": "No basis for this value.", "C": "In h(x) = −2(x−3)²+8, the vertex is at (3, 8). The x-coordinate is 3. ✓", "D": "8 is the y-coordinate (maximum value), not the x-coordinate." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-32",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Composition of functions",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If f(x) = x² + 3x and g(x) = 2x − 1, what is f(g(2))?",
    options: ["", "", "", ""],
    correctAnswer: "18",
    explanation: "First: g(2) = 2(2)−1 = 3. Then: f(3) = 9+9 = 18.",
    explanations: { "correct": "First: g(2) = 2(2)−1 = 3. Then: f(3) = 9+9 = 18." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-33",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Radicals",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which of the following is equivalent to √(50x⁴)?",
    options: ["5x²√2", "25x²√2", "5x²", "25x²"],
    correctAnswer: "A",
    explanation: "√(50x⁴) = √(25·2·x⁴) = 5x²√2. ✓",
    explanations: { "A": "√(50x⁴) = √(25·2·x⁴) = 5x²√2. ✓", "B": "Incorrectly squared the 5: 5² = 25.", "C": "Dropped the √2 factor.", "D": "Both errors combined." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-34",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Exponential growth interpretation",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which of the following best describes the meaning of 1.08 in this context?",
    passage: "The value of a certain collectible is modeled by V(t) = 250(1.08)^t, where t is the number of years since purchase.",
    options: [`The collectible's value increases by $1.08 each year.`, `The collectible's value increases by 8% each year.`, "The collectible will be worth $1.08 after one year.", `The collectible's initial value was $1.08.`],
    correctAnswer: "B",
    explanation: "In V = 250(1.08)^t, the base 1.08 = 1 + 0.08, meaning 8% annual growth. ✓",
    explanations: { "A": "1.08 is a growth factor (multiplier), not a dollar amount. The increase is by 8%, not $1.08.", "B": "In V = 250(1.08)^t, the base 1.08 = 1 + 0.08, meaning 8% annual growth. ✓", "C": "V(1) = 250(1.08) = 270, not 1.08.", "D": "The initial value is 250 (when t=0)." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-35",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Complex numbers",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "For i = √(−1), what is the value of (3 + 2i)(3 − 2i)?",
    options: ["5", "9", "13", "9 − 4i²"],
    correctAnswer: "C",
    explanation: "(3+2i)(3−2i) = 9−4i² = 9−4(−1) = 9+4 = 13. This is a conjugate pair product. ✓",
    explanations: { "A": "5 = 9−4, but i² = −1, so −4i² = −4(−1) = +4, giving 9+4 = 13.", "B": "9 would be just 3², ignoring the imaginary terms entirely.", "C": "(3+2i)(3−2i) = 9−4i² = 9−4(−1) = 9+4 = 13. This is a conjugate pair product. ✓", "D": "This is technically an intermediate step, not simplified. Since i²=−1, this equals 9+4=13." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-36",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Advanced Math",
    skill: "Completing the square",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "If x² + bx + 9 is a perfect square trinomial with b > 0, what is the value of b?",
    options: ["", "", "", ""],
    correctAnswer: "6",
    explanation: "A perfect square trinomial x² + bx + 9 = (x + k)² means k² = 9 and 2k = b. So k = 3 (since b > 0) and b = 6.",
    explanations: { "correct": "A perfect square trinomial x² + bx + 9 = (x + k)² means k² = 9 and 2k = b. So k = 3 (since b > 0) and b = 6." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-37",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Confidence intervals / margin of error",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which of the following is the best interpretation of this result?",
    passage: "In a random sample of 400 voters, 52% said they support a proposed policy. The margin of error is ±4 percentage points at the 95% confidence level.",
    options: ["Exactly 52% of all voters support the policy.", "Between 48% and 56% of the sample supports the policy.", "It is plausible that between 48% and 56% of all voters support the policy.", "95% of all voters have an opinion about the policy."],
    correctAnswer: "C",
    explanation: `The 95% confidence interval is 52% ± 4% = [48%, 56%]. We're 95% confident the true population proportion falls in this range. ✓`,
    explanations: { "A": "52% is the sample statistic, not the exact population parameter.", "B": "We know the sample result is 52%. The interval is about the population, not the sample.", "C": `The 95% confidence interval is 52% ± 4% = [48%, 56%]. We're 95% confident the true population proportion falls in this range. ✓`, "D": "The 95% refers to confidence level, not the percentage of voters with opinions." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-38",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Study design",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "Which of the following best describes this study?",
    passage: "A researcher wants to determine whether a new fertilizer increases crop yield. She randomly assigns 50 plots to receive the new fertilizer and 50 plots to receive the standard fertilizer, then measures yield.",
    options: ["An observational study, because the researcher recorded existing conditions.", "A survey, because the researcher collected data from multiple plots.", "An experiment, because treatments were randomly assigned to groups.", "A census, because all plots in the field were included."],
    correctAnswer: "C",
    explanation: "Random assignment of treatments to experimental units = experiment. This allows causal inference. ✓",
    explanations: { "A": "This is not observational — the researcher actively assigned treatments.", "B": "Surveys collect self-reported data from people; this measures crop yield.", "C": "Random assignment of treatments to experimental units = experiment. This allows causal inference. ✓", "D": "A census measures every member of a population, not a sample of plots." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-39",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Problem-Solving & Data Analysis",
    skill: "Probability",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "What is the probability of selecting a blue marble? (Enter as a decimal.)",
    passage: "A jar contains 5 red, 8 blue, and 7 green marbles. One marble is selected at random.",
    options: ["", "", "", ""],
    correctAnswer: "0.4",
    explanation: "Total marbles: 5+8+7 = 20. P(blue) = 8/20 = 2/5 = 0.4.",
    explanations: { "correct": "Total marbles: 5+8+7 = 20. P(blue) = 8/20 = 2/5 = 0.4." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-40",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Volume (cone)",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "A cone has a radius of 6 cm and a height of 10 cm. What is the volume of the cone, in cubic centimeters?",
    options: ["60π", "120π", "180π", "360π"],
    correctAnswer: "B",
    explanation: "V = (1/3)πr²h = (1/3)π(36)(10) = 120π. ✓",
    explanations: { "A": "60π = (1/3)π(6)(10) — used r instead of r².", "B": "V = (1/3)πr²h = (1/3)π(36)(10) = 120π. ✓", "C": "180π = (1/2)πr²h — used 1/2 instead of 1/3.", "D": "360π = πr²h — forgot the 1/3 factor." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-41",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Distance formula",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "In a coordinate plane, segment AB has endpoints A(1, 3) and B(7, 11). What is the length of AB?",
    options: ["8", "10", "12", "14"],
    correctAnswer: "B",
    explanation: "d = √((7−1)²+(11−3)²) = √(36+64) = √100 = 10. ✓",
    explanations: { "A": "8 is the difference in y-coordinates (11−3), not the distance.", "B": "d = √((7−1)²+(11−3)²) = √(36+64) = √100 = 10. ✓", "C": `Added the differences: 6+8 = 14? No, that's D. 12 has no basis.`, "D": "6+8 = 14 is the sum of the legs, not the hypotenuse." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-42",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Similar figures (area ratios)",
    difficulty: "medium" as const,
    type: "spr" as const,
    stem: "Two similar triangles have corresponding sides in a ratio of 3:5. If the area of the smaller triangle is 27 cm², what is the area of the larger triangle, in cm²?",
    options: ["", "", "", ""],
    correctAnswer: "75",
    explanation: "Area ratio = (side ratio)² = (3/5)² = 9/25. So 27/A = 9/25 → A = 27 × 25/9 = 75 cm².",
    explanations: { "correct": "Area ratio = (side ratio)² = (3/5)² = 9/25. So 27/A = 9/25 → A = 27 × 25/9 = 75 cm²." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-43",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Arc length",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "In a circle with center O, a central angle measures 120°. If the radius is 9, what is the length of the arc intercepted by this angle?",
    options: ["3π", "6π", "9π", "12π"],
    correctAnswer: "B",
    explanation: "Arc length = (θ/360)×2πr = (120/360)×2π(9) = (1/3)(18π) = 6π. ✓",
    explanations: { "A": "3π uses the wrong fraction: (120/360)=1/3, and 1/3 of 2π(9) = 6π, not 3π.", "B": "Arc length = (θ/360)×2πr = (120/360)×2π(9) = (1/3)(18π) = 6π. ✓", "C": "9π = πr, which would be a semicircle arc (180°), not 120°.", "D": "12π uses 2/3 of the circumference, which is the major arc (240°), not the minor arc." },
    tags: ["diagnostic"],
  },
  {
    id: "diag-sat-math-44",
    testType: "sat",
    section: "math",
    module: 2,
    domain: "Geometry & Trigonometry",
    skill: "Circle equations",
    difficulty: "medium" as const,
    type: "mc" as const,
    stem: "In the xy-plane, what is the equation of a circle with center (−2, 5) and radius 7?",
    options: ["(x + 2)² + (y − 5)² = 7", "(x − 2)² + (y + 5)² = 49", "(x + 2)² + (y − 5)² = 49", "(x − 2)² + (y − 5)² = 49"],
    correctAnswer: "C",
    explanation: "(x−(−2))² + (y−5)² = 7² → (x+2)² + (y−5)² = 49. ✓",
    explanations: { "A": "Right center but forgot to square the radius: r²=49, not 7.", "B": "Signs wrong for center: (x−2) gives center x=2, not −2. (y+5) gives center y=−5.", "C": "(x−(−2))² + (y−5)² = 7² → (x+2)² + (y−5)² = 49. ✓", "D": "(x−2)² gives center x=2, not −2. Must use (x+2)² for center at x=−2." },
    tags: ["diagnostic"],
  }
];

export default function SATMathDiagnostic() {
  return (
    <DiagnosticTest
      testType="sat"
      section="math"
      title="SAT Math Diagnostic"
      timeMinutes={35}
      domains={["Algebra", "Advanced Math", "Problem-Solving & Data Analysis", "Geometry & Trigonometry"]}
      questions={QUESTIONS}
    />
  );
}


